Feature/m0078 ddg 331 footprint
MicroEJ/docs pull request #101
Opened 2020-10-22 15:05 UTC by apoudret

2020-10-22 16:01 UTC, stephanemainchain commented on Tutorials/tutorialFootprintGuidelines.rst
> +A ``<firmware>.map`` file is generated after linking the MicroEJ application with the BSP.
is generated by the C toolchain after..

2020-10-22 16:02 UTC, apoudret commented on Tutorials/tutorialJavaCodingRules.rst
> +Analyze and Improve the Quality of the Code of an Application
fixed

2020-10-22 16:02 UTC, apoudret commented on Tutorials/tutorialJavaCodingRules.rst
> +settings <https://repository.microej.com/packages/formatter/microej_formatter-13.xml>`__.
fixed

2020-10-22 16:02 UTC, apoudret commented on Tutorials/tutorialFootprintGuidelines.rst
> +Temporary Section
fixed

2020-10-22 16:02 UTC, apoudret commented on Tutorials/tutorialFootprintGuidelines.rst
> +To be added later:
fixed

2020-10-22 16:08 UTC, apoudret commented on Tutorials/tutorialFootprintGuidelines.rst
> +A ``<firmware>.map`` file is generated after linking the MicroEJ application with the BSP.
fixed

2020-10-22 16:08 UTC, apoudret commented on Tutorials/tutorialJavaCodingRules.rst
> +**Effective Java** book for more information.
fixed

2020-10-25 22:10 UTC, jcourcelmicroej commented on Tutorials/tutorialFootprintGuidelines.rst
> +1. Enable the stack overflow check in ``FreeRTOS.h``:
You can add a link here on FreeRTOS documentation: https://www.freertos.org/Stacks-and-stack-overflow-checking.html

2020-10-25 22:10 UTC, jcourcelmicroej commented on Tutorials/tutorialFootprintGuidelines.rst
> +	#define configCHECK_FOR_STACK_OVERFLOW 1
Add a note here, to justify why you choose to use `1` and not `2` for `configCHECK_FOR_STACK_OVERFLOW`.

2020-10-25 22:10 UTC, jcourcelmicroej commented on Tutorials/tutorialFootprintGuidelines.rst
> +- Configure the immortals heap to be as small as possible. The minimum value can be known by calling ``Immortals.freeMemory()`` after all immortals object have been created.
Do we expose our HeapProfiler on the web ? A good way to give an implementation of this polling mecanism

2020-10-25 22:10 UTC, jcourcelmicroej commented on Tutorials/tutorialFootprintGuidelines.rst
> +- Configure the maximum number of monitors. This number can be known accurately by counting the number of concurrent ``synchronized`` blocks. This can also be done empirically by starting with a low
The function `LLMJVM_dump()` can be called in the BSP or exposed using a SNI native to print information on stack block usage and others usefull information by Java threads. An exemple of this usage/result can be appreciated.

2020-10-25 22:10 UTC, jcourcelmicroej commented on Tutorials/tutorialFootprintGuidelines.rst
> +- Configure the images heap to be as small as possible. The optimal size can be computed empirically. It can also be known accurately by counting the size of every image which may be stored in the im
Is it possible to use a polling mecanism or an API to have the maximum MicroUI Images heap consumption for a run ?

2020-10-26 23:15 UTC, jerome-leroux requested changes

2020-10-26 23:15 UTC, jerome-leroux commented on Tutorials/tutorialFootprintGuidelines.rst
> +- Don't declare arrays in ``static final`` fields, use immutables instead.
```suggestion
- Don't declare arrays content in ``static final`` fields, use immutables instead.
```

2020-10-26 23:15 UTC, jerome-leroux commented on Tutorials/tutorialFootprintGuidelines.rst
> +- Avoid creating multiple threads, timers, or executors, share the instances instead when possible. Each thread requires to allocate dedicated VM stacks which take a lot of memory.
```suggestion
- Avoid creating multiple threads, timers, or executors, share the instances instead when possible. Each thread requires allocating dedicated VM stacks, which take a lot of memory.
```

2020-10-26 23:15 UTC, jerome-leroux commented on Tutorials/tutorialFootprintGuidelines.rst
> +- Avoid creating mutable images (``BufferedImage`` instances) to draw in them and render them later, render directly on the display. Mutable images require allocating a lot of memory from the images
```suggestion
- Avoid creating mutable images (``BufferedImage`` instances) to draw in them and render them later, render graphics directly on the display. Mutable images require allocating a lot of memory from the images heap.
```

2020-10-26 23:15 UTC, jerome-leroux commented on Tutorials/tutorialFootprintGuidelines.rst
> +- Check the size of the stack of each RTOS task. For example, 1.0KB may be enough for the MicroJVM task but it can be increased to allow deep native calls.
```suggestion
- Check the size of the stack of each RTOS task. For example, 1.5KB may be enough for the MicroJVM task, but it can be increased to allow deep native calls.
```

2020-10-26 23:15 UTC, jerome-leroux commented on Tutorials/tutorialFootprintGuidelines.rst
> +- Check the size of the heap allocated by the RTOS (for example ``configTOTAL_HEAP_SIZE`` for FreeRTOS).
```suggestion
- Check the size of the heap allocated by the RTOS (for example, ``configTOTAL_HEAP_SIZE`` for FreeRTOS).
```

2020-10-26 23:15 UTC, jerome-leroux commented on Tutorials/tutorialFootprintGuidelines.rst
> +If the size that you allocate for a given RTOS task is too low, a stack overflow will occur. To be aware of stack overflows, proceed with the following steps (for FreeRTOS):
```suggestion
If the size you allocate for a given RTOS task is too small, a stack overflow will occur. To be aware of stack overflows, proceed with the following steps when using FreeRTOS:
```

2020-10-26 23:15 UTC, jerome-leroux commented on Tutorials/tutorialFootprintGuidelines.rst
> +- Configure the immortals heap to be as small as possible. The minimum value can be known by calling ``Immortals.freeMemory()`` after all immortals object have been created.
```suggestion
- Configure the immortals heap to be as small as possible. The minimum value can be known by calling ``Immortals.freeMemory()`` after the creation of all the immortal objects.
```

2020-10-26 23:15 UTC, jerome-leroux commented on Tutorials/tutorialFootprintGuidelines.rst
> +- Configure the Java heap to fit the needs of the application. The maximum heap usage can be known by calling ``Runtime.freeMemory()`` after ``System.gc()`` at different moments in the lifecycle of t
```suggestion
- Configure the Java heap to fit the needs of the application. The maximum heap usage can be known by calling ``Runtime.freeMemory()`` after ``System.gc()`` at different moments in the application's lifecycle.
```

2020-10-26 23:15 UTC, jerome-leroux commented on Tutorials/tutorialFootprintGuidelines.rst
> +- Configure the maximum number of threads. This number can be known accurately by counting in the code how many ``Thread`` and ``Timer`` objects may run concurrently. Calling ``Thread.getAllStackTrac
```suggestion
- Configure the maximum number of threads. This number can be known accurately by counting in the code how many ``Thread`` and ``Timer`` objects may run concurrently. You can call ``Thread.getAllStackTraces()`` or ``Thread.activeCount()`` to know what threads are running at a given moment.
```

2020-10-27 08:35 UTC, apoudret commented on Tutorials/tutorialFootprintGuidelines.rst
> +- Check the size of the stack of each RTOS task. For example, 1.0KB may be enough for the MicroJVM task but it can be increased to allow deep native calls.
on my platform 1KB was enough. maybe you were calling more complex natives than me?

2020-10-27 08:54 UTC, apoudret commented on Tutorials/tutorialFootprintGuidelines.rst
> +- Check the size of the stack of each RTOS task. For example, 1.0KB may be enough for the MicroJVM task but it can be increased to allow deep native calls.
1.0KB was enough in my case

2020-10-27 09:19 UTC, apoudret commented on Tutorials/tutorialFootprintGuidelines.rst
> +Types, static fields, class names and strings are grouped into separate categories. Since they are packed into separate sections, they can not be distributed in the libraries in which they are used.
integrated and formulated differently:
The linker regroups all the strings in the same section. The same applies to the static fields, the types and the class names. Each of these sections is displayed in its own category.

2020-10-27 09:35 UTC, seonmej commented on Tutorials/tutorialFootprintGuidelines.rst
> +The following application code guidelines are recommended in order to minimize the size of the application:
And some of them are duplicated with the ones in coding rules.

2020-10-27 09:35 UTC, seonmej commented on Tutorials/tutorialFootprintGuidelines.rst
> +- Avoid using synchronization. A ``synchronized`` block takes a lot of extra code size, even though it is only a few characters of code.
Mhh ok, this issue is more general, it saves a bit of flash, a bit of runtime and a bit of maintenance.

2020-10-27 09:35 UTC, seonmej commented on Tutorials/tutorialFootprintGuidelines.rst
> +- Avoid using synchronization. A ``synchronized`` block takes a lot of extra code size, even though it is only a few characters of code.
Mhh ok, this issue is more general, it saves a bit of flash, a bit of runtime and a bit of maintenance.

2020-10-27 09:35 UTC, seonmej commented on Tutorials/tutorialFootprintGuidelines.rst
> +- Avoid using the string concatenation operator (``+``) when concatenating more than 2 objects into a single string, use ``StringBuilder`` instead. Multiple ``+`` take more code size than multiple ``
Are you sure of that? I think that the rule in the coding rules is more accurate:
`Use + operator for single line string concatenation, use a StringBuilder otherwise.`

2020-10-27 09:35 UTC, seonmej commented on Tutorials/tutorialFootprintGuidelines.rst
> +- Avoid accessing the same field multiple times in the same method, copy the value of the field into a local variable instead. Accessing fields leads o bigger code size and may induce synchronization
`leads of` (missing `f`)

2020-10-27 09:35 UTC, seonmej commented on Tutorials/tutorialFootprintGuidelines.rst
> +- Use an optimal compiler such as IAR rather than GCC.
Are you sure about that? Recently I heard that the same platform on GCC and IAR was quite equivalent (perf and size).

2020-10-27 09:35 UTC, seonmej commented on Tutorials/tutorialFootprintGuidelines.rst
> +- Use an optimal compiler such as IAR rather than GCC.
Are you sure about that? Recently I heard that the same platform on GCC and IAR was quite equivalent (perf and size).

2020-10-27 09:35 UTC, seonmej commented on Tutorials/tutorialFootprintGuidelines.rst
> +- Don't declare arrays in ``static final`` fields, use immutables instead.
Already in Java coding rules.

2020-10-27 09:35 UTC, seonmej commented on Tutorials/tutorialFootprintGuidelines.rst
> +- Configure the immortals heap to be as small as possible. The minimum value can be known by calling ``Immortals.freeMemory()`` after all immortals object have been created.
Yes I think we need to give a better way to find the pick of memory. Polling may not give the right value.
(In the UI, a pick is reached when creating a page while another one is still displayed, this time may be short and the polling may not run at this exact moment).

2020-10-27 09:52 UTC, apoudret commented on Tutorials/tutorialFootprintGuidelines.rst
> +- The maximum alpha level of your display device
i agree its weird. i got this doc from the forum: https://forum.microej.com/t/flash-footprint-how-to-reduce-the-memory-footprint-of-an-application/44
i think the point was that if the screen is 2 colors only (black & white for example), then using 4 BPP for a font is useless.
i suggest `- The pixel depth of your display device`

2020-10-27 09:56 UTC, jcourcelmicroej commented on Tutorials/tutorialFootprintGuidelines.rst
> +- Check the size of the stack of each RTOS task. For example, 1.0KB may be enough for the MicroJVM task but it can be increased to allow deep native calls.
Running a full jvm-j2me testsuite and getting computing the high watermark. It can differs from platform but 1KB seems to be very low.

2020-10-27 09:57 UTC, apoudret commented on Tutorials/tutorialFootprintGuidelines.rst
> +- Avoid using the string concatenation operator (``+``) when concatenating more than 2 objects into a single string, use ``StringBuilder`` instead. Multiple ``+`` take more code size than multiple ``
yes with friviered we looked at the code generated by the + operator and it is terrible. see  M0081MEJA-1272

2020-10-27 10:01 UTC, apoudret commented on Tutorials/tutorialFootprintGuidelines.rst
> +- Use an optimal compiler such as IAR rather than GCC.
yes IAR is much better (jcourcel estimated to 5-10% gain). the C lib is lighter and the padding is more optimal

2020-10-27 10:03 UTC, apoudret commented on Tutorials/tutorialFootprintGuidelines.rst
> +- Check the size of the stack of each RTOS task. For example, 1.0KB may be enough for the MicroJVM task but it can be increased to allow deep native calls.
well the user can start at 1KB and increase if he needs more i guess

2020-10-27 10:06 UTC, seonmej commented on Tutorials/tutorialFootprintGuidelines.rst
> +- The maximum alpha level of your display device
Yes, I think it is better.

2020-10-27 10:28 UTC, seonmej commented on Tutorials/tutorialFootprintGuidelines.rst
> +- Avoid using the string concatenation operator (``+``) when concatenating more than 2 objects into a single string, use ``StringBuilder`` instead. Multiple ``+`` take more code size than multiple ``
Ok, so I suggest: "Avoid using the string concatenation operator (``+``), use ``StringBuilder`` instead." because it is not dependent of the number of `+`.
And the rule in the coding rules must also be updated.

2020-10-27 11:52 UTC, jerome-leroux commented on Tutorials/tutorialFootprintGuidelines.rst
> +Types, static fields, class names and strings are grouped into separate categories. Since they are packed into separate sections, they can not be distributed in the libraries in which they are used.
👍

2020-10-27 15:56 UTC, apoudret commented on Tutorials/tutorialFootprintGuidelines.rst
> +- Configure the immortals heap to be as small as possible. The minimum value can be known by calling ``Immortals.freeMemory()`` after all immortals object have been created.
yes my point was to call it once, at the best moment. but we can link to the profiling lib which is on central repo (com.microej.library#profiling)

2020-10-28 17:19 UTC, frivieremicroej commented
Link preview:  https://docs.microej.com/en/feature-m0078ddg-331_footprint/

2020-10-28 17:20 UTC, frivieremicroej commented
@apoudret please rebase so that "Improve the Quality of the Code of an Application" tuto does not appear in this branch

2020-10-28 22:43 UTC, jerome-leroux requested changes

2020-10-28 22:43 UTC, jerome-leroux commented on Tutorials/tutorialJavaCodingRules.rst
> +    ``{@code my code}``.
```suggestion
- Use the code tag in the following cases:

  - For keywords.
  - For names.
  - For code example.
  - ``{@code null}``, ``{@code true}``, ``{@code false}``,
    ``{@code my code}``.
```

2020-10-28 22:43 UTC, jerome-leroux commented on Tutorials/tutorialJavaCodingRules.rst
> +  automatically. Prefer using “the given xxx”.
```suggestion
For the methods, follow the rules below:

- The first sentence starts with the third person (as if there is “This
  method” before).
- All parameters and returned values must be described.
- Put as much as possible information in the description, keep
  ``@param`` and ``@return`` minimal.
- Start ``@param`` with a lower case and usually with “the” or “a.”
- Start ``@return`` with a lower case as if the sentence starts with
  “Returns."
- Avoid naming parameters anywhere other than in ``@param``. If the
  parameter is renamed afterward, the comment is not changed
  automatically. Prefer using “the given xxx.”
```

2020-10-28 22:43 UTC, jerome-leroux commented on Tutorials/tutorialJavaCodingRules.rst
> +settings <https://repository.microej.com/packages/formatter/>`__.
```suggestion
MicroEJ recommended formatting rules for Eclipse, which can be found here: `Eclipse Java
settings <https://repository.microej.com/packages/formatter/>`__.
```

2020-10-28 22:43 UTC, jerome-leroux commented on Tutorials/tutorialJavaCodingRules.rst
> +  single statement.
```suggestion
- Braces are mandatory with ``if``, ``else``, ``for``, ``do``, and
  ``while`` statements, even when the body is empty or contains only a
  single statement.
```

2020-10-28 22:43 UTC, jerome-leroux commented on Tutorials/tutorialJavaCodingRules.rst
> +- Braces follow the Kernighan and Ritchie style (“Egyptian brackets”):
```suggestion
- Braces follow the Kernighan and Ritchie style (“Egyptian brackets”) described below:
```

2020-10-28 22:43 UTC, jerome-leroux commented on Tutorials/tutorialJavaCodingRules.rst
> +  the visibility (easier to read).
```suggestion
- All methods of an interface are public. There is no need to specify
  the visibility (easier to read).
```

2020-10-28 22:43 UTC, jerome-leroux commented on Tutorials/tutorialJavaCodingRules.rst
> +    private.
```suggestion
  - Class (static) variables. First, the public class variables, then
    the protected, then package level (no access modifier), and then
    the private.
  - Instance variables. First, the public class variables, then the
    protected, then package level (no access modifier), and then the
    private.
```

2020-10-28 22:43 UTC, jerome-leroux commented on Tutorials/tutorialJavaCodingRules.rst
> +  will always be embedded and consume some Flash.
```suggestion
- Avoid redefining ``toString()`` method for debugging purposes. The method
  will always be embedded and consume some Flash.
```

2020-10-28 22:43 UTC, jerome-leroux commented on Tutorials/tutorialJavaCodingRules.rst
> +- Do not assign fields in field declaration but in constructor.
```suggestion
- Do not assign fields in field declaration but in the constructor.
```

2020-10-28 22:43 UTC, jerome-leroux commented on Tutorials/tutorialJavaCodingRules.rst
> +  of operators priority for example).
```suggestion
- Use parenthesis for complex operation series; it simplifies the understanding 
  of operator priorities.
```

2020-10-28 22:43 UTC, jerome-leroux commented on Tutorials/tutorialJavaCodingRules.rst
> +  ej.library.runtime#component).
```suggestion
- Use component-oriented architecture to separate concerns (Use
  ej.library.runtime#component).
```

2020-10-28 22:43 UTC, jerome-leroux commented on Tutorials/tutorialJavaCodingRules.rst
> +  complex it should be split.
```suggestion
- Create small methods with little complexity. When a method gets too
  complex, it should be split.
```

2020-10-28 22:43 UTC, jerome-leroux commented on Tutorials/tutorialJavaCodingRules.rst
> +  StringBuilder otherwise.
```suggestion
- Use ``+`` operator for single-line string concatenation. Use a
  StringBuilder otherwise.
```

2020-10-28 22:43 UTC, jerome-leroux commented on Tutorials/tutorialJavaCodingRules.rst
> +  be considered.
```suggestion
- Avoid using the Calendar to compute fields to display a watch face
  for example. The computation of the fields of a Calendar may affect
  performance. In a watch face, prefer maintaining a watch model
  (with one field per data: second, minute, hour, etc.) that updates
  its fields every x milliseconds, then every x seconds or minutes. The
  model can be updated using a calendar. An update on an NTP can also
  be considered.
```

2020-10-28 22:43 UTC, jerome-leroux commented on Tutorials/tutorialJavaCodingRules.rst
> +- Use locals for repeated accesses to field or array elements.
```suggestion
- Use locals for repeated access to fields or array elements.
```

2020-10-28 22:43 UTC, jerome-leroux commented on Tutorials/tutorialJavaCodingRules.rst
> +  into immutables to save RAM and execution time.
```suggestion
- All stateless objects initialized at startup could be turned
  into immutables to save RAM and execution time.
```

2020-10-28 22:43 UTC, jerome-leroux commented on Tutorials/tutorialJavaCodingRules.rst
> +collections (list or set elements, map keys, etc.).
```suggestion
objects. The most common use of these methods is to compare instances in
collections (list or set elements, map keys, etc.).
```

2020-10-28 22:43 UTC, jerome-leroux commented on Tutorials/tutorialJavaCodingRules.rst
> +the Javadoc):
```suggestion
The ``equals(Object)`` method implements an equivalence relation (defined in
the Javadoc) with the following properties:
```

2020-10-28 22:43 UTC, jerome-leroux commented on Tutorials/tutorialJavaCodingRules.rst
> +*Effective Java* book by *Joshua Bloch* for more information.
```suggestion
Avoid overriding the ``equals(Object)`` method in a subclass of a class that
already overrides it; it could break the contract above. See
*Effective Java* book by *Joshua Bloch* for more information.
```

2020-10-28 22:43 UTC, jerome-leroux commented on Tutorials/tutorialJavaCodingRules.rst
> +  optional and may be removed if the object have a few fields.
```suggestion
  equals, return ``true``. This test is for performance purposes, so it is
  optional and may be removed if the object has a few fields.
```

2020-10-28 22:43 UTC, jerome-leroux commented on Tutorials/tutorialJavaCodingRules.rst
> +  return ``false``. This check also validates that the argument is not null.
```suggestion
- Use an ``instanceof`` to check if the argument has the correct type. If not,
  return ``false``. This check also validates that the argument is not null.
```

2020-10-28 22:43 UTC, jerome-leroux commented on Tutorials/tutorialJavaCodingRules.rst
> +  plus the hash code of the field and store it as result.
```suggestion
  plus the hash code of the field and store it as the result.
```

2020-10-28 22:43 UTC, jerome-leroux commented on Tutorials/tutorialJavaCodingRules.rst
> +- Prefer black box tests (with a maximum coverage).
```suggestion
- Prefer black-box tests (with a maximum coverage).
```

2020-10-28 22:43 UTC, jerome-leroux commented on Tutorials/tutorialJavaCodingRules.rst
> +    package visibility).
```suggestion
- Here is the test packages naming convention:

  - Suffix package with .test for black-box tests.
  - Use the same package for white-box tests (allow to use classes with
    package visibility).
```

2020-10-28 22:43 UTC, jerome-leroux commented on Tutorials/tutorialStripClassNames.rst
> +By default, when a class is used (due to one of its methods being called for example), the name of the class is embedded too.
```suggestion
By default, when a class is used, the name of the class is embedded too. A class is used when one of its methods is called, for example.
```

2020-10-28 22:43 UTC, jerome-leroux commented on Tutorials/tutorialStripClassNames.rst
> +The assignment between a service and its implementation is done in ``*.properties.list`` files. Both the service class name and the implementation class name must be embedded (i.e. added in a ``*.typ
```suggestion
The assignment between a service and its implementation is done in ``*.properties.list`` files. Both the service class name and the implementation class name must be embedded (i.e., added in a ``*.types.list`` file).
```

2020-10-28 22:43 UTC, jerome-leroux commented on Tutorials/tutorialStripClassNames.rst
> +The application and add-on libraries code must be checked for all uses of uses of:
```suggestion
The application and add-on libraries code must be checked for all uses of the following methods:
```

2020-10-28 22:43 UTC, jerome-leroux commented on Tutorials/tutorialStripClassNames.rst
> +It is not necessary to embed these class names. The :ref:`stack_trace_reader` is able to decipher the output.
```suggestion
It is not necessary to embed these class names. The :ref:`stack_trace_reader` can decipher the output.
```

2020-10-29 15:45 UTC, apoudret commented on Tutorials/tutorialFootprintGuidelines.rst
> +- Configure the images heap to be as small as possible. The optimal size can be computed empirically. It can also be known accurately by counting the size of every image which may be stored in the im
refer to image heap analyzer https://gitlab.cross/M0092_MicroEJ-Architecture-UI/M0092_UI-ImageHeap-Analyser/-/merge_requests/1

2020-10-30 14:01 UTC, apoudret commented on Tutorials/tutorialFootprintGuidelines.rst
> +	#define configCHECK_FOR_STACK_OVERFLOW 1
i added a link with full freertos doc. i keep this quick doc as short as possible, the full explanation can be found on the freertos doc

2020-11-02 16:23 UTC, thomasponsmicroej commented
Suggestion: to make the tutorial more reader-friendly, add screenshots. First example that comes to my mind, is the soar.map and soar.xml files, where do I locate them, an screenshot of the Package explorer view could show it better than words.

2020-11-06 10:22 UTC, apoudret commented on Tutorials/tutorialFootprintGuidelines.rst
> +- Don't declare arrays in ``static final`` fields, use immutables instead.
removed from java coding rules. i added some info and moved it to flash size not runtime

2020-11-06 10:45 UTC, apoudret commented on Tutorials/tutorialFootprintGuidelines.rst
> +The following application code guidelines are recommended in order to minimize the size of the application:
we keep the guidelines specific to footprint into this separate doc as discussed.
regarding duplicated coding rules it should be fixed

2020-11-06 10:47 UTC, apoudret commented on Tutorials/tutorialFootprintGuidelines.rst
> +- Avoid using the string concatenation operator (``+``) when concatenating more than 2 objects into a single string, use ``StringBuilder`` instead. Multiple ``+`` take more code size than multiple ``
i think its OK to keep a rule which is not too restrictive in the generic coding rules. this extra rule (never using + operator) is annoying in most cases and is useful only for footprint optimization. i have reworded this rule though.

2020-11-06 10:49 UTC, apoudret commented on Tutorials/tutorialFootprintGuidelines.rst
> +- Avoid using synchronization. A ``synchronized`` block takes a lot of extra code size, even though it is only a few characters of code.
do you think we should put this rule in the generic java coding rules?

2020-11-09 17:02 UTC, frivieremicroej reviewed
Not finished 
I still need an other pass

2020-11-09 17:02 UTC, frivieremicroej commented on Tutorials/tutorialOptimizeFootprint.rst
> +- Avoid using MicroUI 2 and MWT 2, use MicroUI 3 and MWT 3 instead. Many optimizations have been done in the new versions.
I suggest to remove  ref to UI2 / UI3
"Always check for library updates as some optimizations may have been done in the new versions."

2020-11-09 17:02 UTC, frivieremicroej commented on Tutorials/tutorialOptimizeFootprint.rst
> +A ``SOAR.map`` file is generated after running a MicroEJ launcher on an embedded platform.
after building a MicroEJ Application on Device.

2020-11-13 14:03 UTC, frivieremicroej commented on Tutorials/tutorialFootprintGuidelines.rst
> +- Check the size of the stack of each RTOS task. For example, 1.0KB may be enough for the MicroJVM task but it can be increased to allow deep native calls.
Debug Stack dedicated section

2020-11-16 23:56 UTC, jerome-leroux commented on ApplicationDeveloperGuide/buildOutputFiles.rst
> +The linker regroups all the strings in the same section. The same applies to the static fields, the types and the class names. Each of these sections is displayed in its own category.
Are these elements all grouped into one section or do we have one section per element type?

2020-11-17 00:14 UTC, jerome-leroux requested changes

2020-11-17 00:14 UTC, jerome-leroux commented on Tutorials/tutorialOptimizeMemoryFootprint.rst
> +Before jumping into code optimizations, it is recommended to list every area of improvement, and estimate for each area how much memory can be saved and how much effort it requires.
```suggestion
Before jumping into code optimizations, it is recommended to list every area of improvement and estimate for each area how much memory can be saved and how much effort it requires.
```

2020-11-17 00:14 UTC, jerome-leroux commented on Tutorials/tutorialOptimizeMemoryFootprint.rst
> +Moreover, each optimization described hereafter may allow significant memory savings for an application while it may not be relevant for an other application.
```suggestion
Moreover, each optimization described hereafter may allow significant memory savings for an application while it may not be relevant for another application.
```

2020-11-17 00:14 UTC, jerome-leroux commented on Tutorials/tutorialOptimizeMemoryFootprint.rst
> +Without performing the memory analysis first, the developer might start working on a minor optimization which takes a lot of effort for little improvements, whereas he could be working on a major opt
```suggestion
Without performing the memory analysis first, the developer might start working on a minor optimization that takes a lot of effort for little improvements. In contrast, he could work on a major optimization, allowing faster and bigger improvements.
```

2020-11-17 00:14 UTC, jerome-leroux commented on Tutorials/tutorialOptimizeMemoryFootprint.rst
> +To understand how to read these files, please refer to the :ref:`outputfiles` documentation.
```suggestion
The MicroEJ Application linker generates files useful for footprint analysis, such as the SOAR map file and the SOAR information file.
To understand how to read these files, please refer to the :ref:`outputfiles` documentation.
```

2020-11-17 00:14 UTC, jerome-leroux commented on Tutorials/tutorialOptimizeMemoryFootprint.rst
> +This section explains how a map file generated by GCC is structured and how to browse it. The structure is not the same on every compiler but it is often similar.
```suggestion
This section explains how a map file generated by GCC is structured and how to browse it. The structure is not the same on every compiler, but it is often similar.
```

2020-11-17 10:40 UTC, apoudret commented on ApplicationDeveloperGuide/buildOutputFiles.rst
> +The linker regroups all the strings in the same section. The same applies to the static fields, the types and the class names. Each of these sections is displayed in its own category.
one section per type

2020-11-17 10:40 UTC, apoudret commented on ApplicationDeveloperGuide/buildOutputFiles.rst
> +The linker regroups all the strings in the same section. The same applies to the static fields, the types and the class names. Each of these sections is displayed in its own category.
what sentence would you use @jerome-leroux ?

2020-11-17 19:57 UTC, jerome-leroux commented on ApplicationDeveloperGuide/buildOutputFiles.rst
> +The linker regroups all the strings in the same section. The same applies to the static fields, the types and the class names. Each of these sections is displayed in its own category.
```suggestion
SOAR creates one section for each following element sets:

- literal strings
- static fields 
- types
- class names
```

I don't think we should specify it is "per application". It is a little bit confusing.

2020-11-17 20:03 UTC, jerome-leroux commented on ApplicationDeveloperGuide/buildOutputFiles.rst
> +When building a MicroEJ Application on Device, multiple files are generated next to the ELF file.
```suggestion
When building a MicroEJ Application, multiple files are generated next to the ELF file.
```

2020-11-23 13:10 UTC, apoudret commented on ApplicationDeveloperGuide/buildOutputFiles.rst
> +The linker regroups all the strings in the same section. The same applies to the static fields, the types and the class names. Each of these sections is displayed in its own category.
@jerome-leroux the goal of the paragraph was to explain that every string of every lib is grouped into a single section. i think your sentence loses the information

2020-11-23 13:14 UTC, apoudret commented on ApplicationDeveloperGuide/buildOutputFiles.rst
> +- every embedded immutable (in ``selected_immutables`` tag)
@jerome-leroux do you think that @frivieremicroej suggestion is correct and clear?

2020-11-23 13:31 UTC, frivieremicroej commented on ApplicationDeveloperGuide/buildOutputFiles.rst
> +The linker regroups all the strings in the same section. The same applies to the static fields, the types and the class names. Each of these sections is displayed in its own category.
@jerome-leroux I wanted to say that it is an "unmodifiable" section:, it cannot be divided / splitted and will augment as the application will grow...

2020-11-23 15:44 UTC, merged