M0078DDG-341 Add chapter on NLS in Application Developer Guide
MicroEJ/docs pull request #102
Opened 2020-10-26 09:20 UTC by tdelhomenie-microej

2020-10-26 10:30 UTC, gjadi-mej requested changes
Mostly formatting with double backquotes in rst + some minor rephrasing

2020-10-26 10:30 UTC, gjadi-mej commented on ApplicationDeveloperGuide/classpath.rst
> +Native Language Support allows the application to support internationalization.
```suggestion
Native Language Support (NLS) allows the application to support internationalization.
```

2020-10-26 10:30 UTC, gjadi-mej commented on ApplicationDeveloperGuide/classpath.rst
> +For each line, PO files whose name starts with the interface name (`Messages` and `Labels`
```suggestion
For each line, PO files whose name starts with the interface name (``Messages`` and ``Labels` `
```

2020-10-26 10:30 UTC, gjadi-mej commented on ApplicationDeveloperGuide/classpath.rst
> +- a Java interface with the given FQN, containing a field for each `msgid` of the PO files
```suggestion
- a Java interface with the given FQN, containing a field for each ``msgid`` of the PO files
```

2020-10-26 10:30 UTC, gjadi-mej commented on ApplicationDeveloperGuide/classpath.rst
> +So, in the example, the generated interface `com.mycompany.myapp.Labels` will gather all the
```suggestion
So, in the example, the generated interface ``com.mycompany.myapp.Labels`` will gather all the 
```

2020-10-26 10:30 UTC, gjadi-mej commented on ApplicationDeveloperGuide/classpath.rst
> +translations from files named `Labels*.po` and located in the MicroEJ Classpath.
```suggestion
translations from files named ``Labels*.po`` and located in the MicroEJ Classpath.
```

2020-10-26 10:30 UTC, gjadi-mej commented on ApplicationDeveloperGuide/classpath.rst
> +PO files are generally suffixed by their locale (`Labels_en_US.po`) but it is only for convenience
```suggestion
PO files are generally suffixed by their locale (``Labels_en_US.po``) but it is only for convenience
```

2020-10-26 10:30 UTC, gjadi-mej commented on ApplicationDeveloperGuide/classpath.rst
> +-  Native Language Support resources, described in section :ref:`section.classpath.elements.nls`;
```suggestion
-  Native Language Support (NLS) resources, described in section :ref:`section.classpath.elements.nls`;
```

2020-10-26 10:30 UTC, gjadi-mej commented on ApplicationDeveloperGuide/classpath.rst
> +The generation is triggered when building the application, but also after any change done in PO or ``*.nls.list`` files.
```suggestion
The generation is triggered when building the application or after a change done in any PO or ``*.nls.list`` files.
```

I'm not sure about my own suggested formulation.  But the `but` formulation puzzled me.

2020-10-26 13:14 UTC, frivieremicroej commented
Link: https://docs.microej.com/en/feature-m0078ddg-341_add-nls-chapter/

2020-10-28 17:17 UTC, frivieremicroej commented on ApplicationDeveloperGuide/applicationResources.rst
> +Use
please remove this sub-title, as the rest of the body is directly included without sub-title:
![image](https://user-images.githubusercontent.com/19801840/97471923-89321580-1949-11eb-947b-78f592a80bcf.png)

2020-10-28 17:17 UTC, frivieremicroej commented on ApplicationDeveloperGuide/applicationResources.rst
> +  <dependency org="ej.library.runtime" name="nls" rev="..."/>
Set the latest version available to the Central repo, so that the line can be directly copy-pasted to a module.ivy without errors
```suggestion
  <dependency org="ej.library.runtime" name="nls" rev="3.0.1"/>
```

2020-10-29 12:52 UTC, tdelhomenie-microej commented on ApplicationDeveloperGuide/applicationResources.rst
> +Use
Done.

2020-10-29 12:54 UTC, tdelhomenie-microej commented on ApplicationDeveloperGuide/applicationResources.rst
> +  <dependency org="ej.library.runtime" name="nls" rev="..."/>
Done.
I am torn on this because it is more convenient for the developer, but it is harder to maintain.

2020-10-29 14:25 UTC, frivieremicroej commented on ApplicationDeveloperGuide/applicationResources.rst
> +For each line, PO files whose name starts with the interface name (``Messages`` and ``Labels` `
```suggestion
For each line, PO files whose name starts with the interface name (``Messages`` and ``Labels``
```

2020-10-29 14:42 UTC, gjadi-mej approved these changes

2020-10-29 14:43 UTC, merged