Minimal documentation on howto create and configure a runtime-api project with SDK 6.
MicroEJ/docs pull request #1022
Opened 2024-08-26 09:04 UTC by bguedas

2024-08-26 09:09 UTC, denisbedin requested changes
@bguedas You can also add a section in https://docs.microej.com/en/latest/SDK6UserGuide/moduleNatures.html to document the different tasks that is added by the plugin.

2024-08-26 09:12 UTC, tdelhomenie-microej commented
@bguedas we should also have a SDK6 version of the page https://docs.microej.com/en/latest/KernelDeveloperGuide/runtimeEnvironment.html (with the "extend" section).

2024-08-27 10:27 UTC, tdelhomenie-microej reviewed
@bguedas the build fails because of this error:
```
/home/docs/checkouts/readthedocs.org/user_builds/microej-docs/checkouts/feature-sdk6_runtime_api/KernelDeveloperGuide/runtimeEnvironment.rst:36: WARNING: undefined label: '_sdk_6_create_project:'
```

2024-08-27 10:27 UTC, tdelhomenie-microej commented on KernelDeveloperGuide/runtimeEnvironment.rst
> +   .. tab:: Gradle (build.gradle.kts)
We use `SDK 6` and `SDK 5` in the tabs, we should be consistent IMO.

2024-08-27 10:27 UTC, tdelhomenie-microej commented on KernelDeveloperGuide/runtimeEnvironment.rst
> +.. tabs::
Shouldn't we create a dedicated section in SDK 5 and SDK 6 documentations, as we did for Applications and Libs?

2024-08-27 11:03 UTC, bguedas commented on KernelDeveloperGuide/runtimeEnvironment.rst
> +   .. tab:: Gradle (build.gradle.kts)
Actually, I reused the tabs from https://docs.microej.com/en/latest/ApplicationDeveloperGuide/runtime.html for consistency :) But Ok, i'll change the latter to SDK 5/SDK 6

2024-08-27 12:46 UTC, tdelhomenie-microej commented on KernelDeveloperGuide/runtimeEnvironment.rst
> +   .. tab:: Gradle (build.gradle.kts)
Ah yes, right :)

2024-08-28 09:24 UTC, denisbedin requested changes

2024-08-28 09:24 UTC, denisbedin commented on SDK6UserGuide/moduleNatures.rst
> +- :ref:`sdk6_module_natures.tasks.checkModule`
In the `checkModule` task section, can you add the runtime-api plugin to the list of plugins that use the task?

2024-08-28 13:40 UTC, bguedas commented on SDK6UserGuide/moduleNatures.rst
> +- :ref:`sdk6_module_natures.tasks.checkModule`
done

2024-08-28 13:41 UTC, bguedas commented on KernelDeveloperGuide/runtimeEnvironment.rst
> +   .. tab:: Gradle (build.gradle.kts)
Changed

2024-08-28 14:25 UTC, denisbedin approved these changes

2024-08-28 14:27 UTC, tdelhomenie-microej approved these changes

2024-08-28 15:55 UTC, merged