Refactor Overview section
MicroEJ/docs pull request #1024
Opened 2024-08-30 14:32 UTC by acolleux-microej

2024-09-23 08:06 UTC, gharelMicroEJ requested changes

2024-09-23 08:06 UTC, gharelMicroEJ commented on overview/index.rst
> +- a network connection with security (SSL/TLS, HTTPS, REST, MQTT, ...),
I would not use connection here, framework is used in the other bullet points.

2024-09-23 08:06 UTC, gharelMicroEJ commented on overview/index.rst
> +The firmware will generally be produced by the device OEM, it includes
```suggestion
The firmware will generally be produced by the device's OEM, it includes
```

2024-09-23 08:06 UTC, gharelMicroEJ commented on overview/index.rst
> +MICROEJ SDK offers a comprehensive toolset to build the embedded software of
```suggestion
MICROEJ SDK offers a comprehensive toolset to build the software for embedded devices. 
```

2024-09-30 15:51 UTC, acolleux-microej commented on overview/index.rst
> +- a network connection with security (SSL/TLS, HTTPS, REST, MQTT, ...),
Fixed

2024-10-08 06:16 UTC, frivieremicroej requested changes
State on Introduction vs Overview

2024-10-08 06:16 UTC, frivieremicroej requested changes

2024-10-08 06:16 UTC, frivieremicroej commented on overview/executableBuildWorkflow.rst
> +.. _executableBuildWorkflow:
State on Introduction vs Overview

2024-10-09 08:00 UTC, merged