add to changelog with new monitoring apis
MicroEJ/docs pull request #1028
Opened 2024-09-12 05:58 UTC by frivieremicroej

2024-09-12 16:12 UTC, jerome-leroux requested changes

2024-09-12 16:12 UTC, jerome-leroux commented on VEEPortingGuide/architectureChangelog.rst
> +   -  ``void LLMJVM_MONITOR_IMPL_on_quantum_counters_reset()``: called by the Core Engine when the quantum computation is reset.
I am note sure:
```suggestion
   -  ``void LLMJVM_MONITOR_IMPL_on_quota_reset(int32_t context_id, int32_t quota)``: called by the Core Engine when a quota is reset for an execution context.
   -  ``void LLMJVM_MONITOR_IMPL_on_quota_reached(int32_t context_id)``: called by the Core Engine the quota of the given execution context has been reached.
   -  ``void LLMJVM_MONITOR_IMPL_on_quantum_counters_reset()``: called by the Core Engine when all the quantum counters are reset.
```

Should we review the changelog entry for `LLKERNEL_quantaConsumed(int32_t quanta)`:
```
- [Multi] - Added function `LLKERNEL_quantaConsumed(int32_t quanta)` in `LLKERNEL.h` to allow a native function to increase the quantum counter for CPU control.
```

2024-09-13 07:07 UTC, frivieremicroej commented on VEEPortingGuide/architectureChangelog.rst
> +   -  ``void LLMJVM_MONITOR_IMPL_on_quantum_counters_reset()``: called by the Core Engine when the quantum computation is reset.
updated, see new commits

2024-09-13 07:08 UTC, frivieremicroej commented
once stabilized, TODO report changes to the original header file

2024-09-13 07:09 UTC, frivieremicroej reviewed
once stabilized, TODO report changes to the original header file

2024-09-13 16:16 UTC, jerome-leroux commented on VEEPortingGuide/architectureChangelog.rst
> +   -  ``void LLMJVM_MONITOR_IMPL_on_quota_reached(int32_t context_id)``: called by the Core Engine the quota for an execution context has been reached.
```suggestion
   -  ``void LLMJVM_MONITOR_IMPL_on_quota_reached(int32_t context_id)``: called by the Core Engine when the quota for an execution context has been reached.
```

2024-09-16 09:48 UTC, merged