simplify SDK 6 project creation with VS Code and CLI
MicroEJ/docs pull request #1045
Opened 2024-09-24 14:48 UTC by denisbedin

2024-09-25 16:30 UTC, tdelhomenie-microej requested changes

2024-09-25 16:30 UTC, tdelhomenie-microej commented on SDK6UserGuide/createProject.rst
> +      - Click on :guilabel:`Explorer` > :guilabel:`Clone Repository`.
- This menu is not available if a project is already opened
- It is not very clear where is the Explorer menu, it took me a bit a time to find it, we should probably add a screenshot here

2024-09-25 16:30 UTC, tdelhomenie-microej commented on SDK6UserGuide/createProject.rst
> +      - When the Gradle project is loaded, open a Terminal at the root of the project to remove the Git Repository::
We should document how to do it in VSCode, either by opening the terminal in VSCode (Ctrl+J), or by explaining how to do it via the IDE.

2024-09-26 13:44 UTC, denisbedin commented on SDK6UserGuide/createProject.rst
> +      - When the Gradle project is loaded, open a Terminal at the root of the project to remove the Git Repository::
Done.

2024-09-26 13:46 UTC, denisbedin commented on SDK6UserGuide/createProject.rst
> +      - Click on :guilabel:`Explorer` > :guilabel:`Clone Repository`.
Instead of using the Explorer menu, the documentation has been updated to use the Command Palette (`View` > `Command Palette...`).

2024-09-26 15:07 UTC, denisbedin commented on SDK6UserGuide/createProject.rst
> +         .. tab:: Linux
Done.

2024-09-26 15:07 UTC, denisbedin commented on SDK6UserGuide/createProject.rst
> +         .. tab:: Linux
Done.

2024-09-26 15:19 UTC, tdelhomenie-microej approved these changes

2024-09-27 07:16 UTC, merged