Add an how-to about dependencies versions check.
MicroEJ/docs pull request #1052
Opened 2024-10-01 08:05 UTC by bguedas

2024-10-01 14:06 UTC, denisbedin requested changes

2024-10-01 14:06 UTC, denisbedin commented on SDK6UserGuide/howtos/checkDependenciesVersions.rst
> +        configurations.jdtCompilerClasspath {
```suggestion
        configurations.all {

```

2024-10-02 10:07 UTC, tdelhomenie-microej commented on SDK6UserGuide/howtos/checkDependenciesVersions.rst
> +This Gradle plugin lists all the dependencies declared in the ``build.grate.kts`` file, and tells whether they are up-to-date or if a new version is available.
```suggestion
This Gradle plugin lists all the dependencies declared in the ``build.gradle.kts`` file, and tells whether they are up-to-date or if a new version is available.

```

2024-10-02 10:07 UTC, tdelhomenie-microej commented on SDK6UserGuide/howtos/checkDependenciesVersions.rst
> +For instance, here is the report generated on `Example-Java-Widget 8.1.0 <https://github.com/MicroEJ/Example-Java-Widget/tree/8.1.0>`__::
```suggestion
Here is an example of report::

```

2024-10-02 10:07 UTC, tdelhomenie-microej commented on SDK6UserGuide/howtos/checkDependenciesVersions.rst
> +        }
I would remove this note completely.

2024-10-02 10:18 UTC, bguedas commented on SDK6UserGuide/howtos/checkDependenciesVersions.rst
> +        }
Done

2024-10-02 10:49 UTC, tdelhomenie-microej approved these changes

2024-10-02 11:06 UTC, denisbedin approved these changes

2024-10-02 11:06 UTC, denisbedin commented on SDK6UserGuide/howtos/checkDependenciesVersions.rst
> +
```suggestion

```

2024-10-02 11:59 UTC, merged