Upgrade Gradle distribution from 8.0.2 to 8.6.
MicroEJ/docs pull request #1057
Opened 2024-10-03 12:38 UTC by bguedas

2024-10-03 12:58 UTC, denisbedin requested changes

2024-10-03 12:58 UTC, denisbedin commented on SDK6UserGuide/createProject.rst
> +  distributionUrl=https\://services.gradle.org/distributions/gradle-8.6-bin.zip
In the tabs that describe the project creation, each IDE has a note about the version used by the Gradle wrapper. These notes must be updated:
- Eclipse and IntelliJ IDEA use Gradle 8.10.2
- Android Studio Koala uses Gradle 8.7 but I don't know for the other distributions, so maybe the note must be updated to indicate that the user must check if the wrapper uses at least 8.6.

2024-10-04 07:30 UTC, bguedas commented on SDK6UserGuide/createProject.rst
> +  distributionUrl=https\://services.gradle.org/distributions/gradle-8.6-bin.zip
I've updated the tabs

2024-10-04 08:35 UTC, denisbedin requested changes

2024-10-04 08:35 UTC, denisbedin commented on SDK6UserGuide/createProject.rst
> +         The newly created Gradle project with Android Studio Koala (``2024.1.2``) uses Gradle Wrapper with Gradle version ``8.7``.
I don't think it is necessary to talk about Android Studio Koala, I think something like "Make sure that the newly created project uses at least Gradle Wrapper version ``8.6``" is enough.

2024-10-04 12:31 UTC, bguedas commented on SDK6UserGuide/createProject.rst
> +         The newly created Gradle project with Android Studio Koala (``2024.1.2``) uses Gradle Wrapper with Gradle version ``8.7``.
This part has been rephrased.

2024-10-04 12:34 UTC, denisbedin approved these changes

2024-10-04 12:34 UTC, merged