document how to create custom ExecTool tasks
MicroEJ/docs pull request #1070
Opened 2024-10-11 08:49 UTC by denisbedin

https://docs.microej.com/en/feature-sdk6_create_custom_exectool_tasks/SDK6UserGuide/howtos/createCustomExecToolTask.html

2024-10-11 14:55 UTC, tdelhomenie-microej requested changes

2024-10-11 14:55 UTC, tdelhomenie-microej commented on SDK6UserGuide/howtos/createCustomExecToolTask.rst
> +but it is possible to create a custom Gradle task for a specific tool as follows:
We should add an use case example, why would I need to create a task for a specific tool ? The use case we met is for automatically executing the tool after or before another task in the build.

2024-10-11 14:55 UTC, tdelhomenie-microej commented on SDK6UserGuide/howtos/createCustomExecToolTask.rst
> +    ))
Where should I put these lines? If they must be put in the task definition, it should be moved directly in the previous code snippet.

2024-10-11 14:55 UTC, tdelhomenie-microej commented on SDK6UserGuide/howtos/createCustomExecToolTask.rst
> +As an example, here is the code of a custom Gradle task specific to the :ref:`sdk6_localDeployTool`::
We should describe what the example does exactly, something like "Here is how create a task which calls the local deploy tool and ...".
And we could add the code to execute it after the buildFeature task for example, that would be a complete example. WDYT?

2024-10-14 10:47 UTC, denisbedin commented on SDK6UserGuide/howtos/createCustomExecToolTask.rst
> +but it is possible to create a custom Gradle task for a specific tool as follows:
Done.

2024-10-14 10:50 UTC, denisbedin commented on SDK6UserGuide/howtos/createCustomExecToolTask.rst
> +    ))
I moved them in the other code snippet. Actually, I first wanted to separate the inputs common to all tasks of type "ExecToolTask" and the inputs specific to the tool, but it was not very clear so I fixed it.

2024-10-14 10:58 UTC, denisbedin commented on SDK6UserGuide/howtos/createCustomExecToolTask.rst
> +As an example, here is the code of a custom Gradle task specific to the :ref:`sdk6_localDeployTool`::
I fixed the sentence, I didn't added the example with "buildFeature" since, as discussed, the .fo will be built two times.

2024-10-14 12:06 UTC, tdelhomenie-microej approved these changes

2024-10-14 12:17 UTC, merged