Comment option for trace redirection by default
MicroEJ/docs pull request #1115
Opened 2024-11-19 16:51 UTC by tdelhomenie-microej

2024-11-19 17:16 UTC, bguedas requested changes

2024-11-19 17:16 UTC, bguedas commented on SDK6UserGuide/testProject.rst
> +                              "microej.testsuite.properties.testsuite.trace.port" to "5555",
Is the comma useful? By default, the other lines are commented. The other option is to uncoment the last line but comment the line with the comma...

2024-11-19 17:16 UTC, bguedas commented on SDK6UserGuide/testProject.rst
> -                              // Tell the testsuite engine that the VEE Port Run script redirects execution traces
Can you add newlines to separate blocks (comment + option)?

2024-11-20 07:21 UTC, tdelhomenie-microej commented on SDK6UserGuide/testProject.rst
> +                              "microej.testsuite.properties.testsuite.trace.port" to "5555",
Having a trailing comma is supported, and allow the configuration to still be valid if the developer uncomment the last line but forget to comment the port and ip properties lines, but I would keep it like that.

2024-11-20 07:22 UTC, tdelhomenie-microej commented on SDK6UserGuide/testProject.rst
> -                              // Tell the testsuite engine that the VEE Port Run script redirects execution traces
I added a blank line before the "Configure the TCP/IP address ..." comment, but kept the other options together since they are very related.

2024-11-26 15:54 UTC, bguedas approved these changes

2024-11-27 07:37 UTC, merged