Feature/m0081 meja 2054 inject a constant as application option
MicroEJ/docs pull request #1128
Opened 2024-11-26 14:26 UTC by frivieremicroej

2024-11-26 14:31 UTC, jerome-leroux requested changes

2024-11-26 14:31 UTC, jerome-leroux commented on ApplicationDeveloperGuide/classpath.rst
> +   microej.constant.myconstantkey=com.mycompany.myconstantvalue
```suggestion
   microej.constant.myconstantkey=myconstantvalue
```

2024-11-26 16:39 UTC, frivieremicroej commented on ApplicationDeveloperGuide/classpath.rst
> +   microej.constant.myconstantkey=com.mycompany.myconstantvalue
Thanks for catching but I wanted to define the same property than above
```suggestion
   microej.constant.com.mycompany.myconstantkey=com.mycompany.myconstantvalue
```

2024-11-28 08:44 UTC, frivieremicroej commented on ApplicationDeveloperGuide/classpath.rst
> +   microej.constant.myconstantkey=com.mycompany.myconstantvalue
finally I fully removed `com.mycompany.` prefix to simplify the option name

2024-11-28 10:14 UTC, merged