Feature/m0081 meja 2367 managedc friviere review
MicroEJ/docs pull request #1155
Opened 2024-12-20 15:02 UTC by frivieremicroej

2024-12-23 09:07 UTC, dalgassimou reviewed
LGTM

2024-12-23 16:07 UTC, jerome-leroux requested changes

2024-12-24 08:12 UTC, dalgassimou commented on ApplicationDeveloperGuide/runtime.rst
> +The SOAR loads both Java bytecode ``.class`` files and WebAssembly ``.wasm`` files as long as other application-related :ref:`files and resources <chapter.microej.classpath>` and links it all to prod
LGTM

2024-12-24 08:59 UTC, jerome-leroux commented on ApplicationDeveloperGuide/images/build-flow.png
Let's remove any reference to a specific compiler in the diagram (JDT, etc.)

2024-12-24 10:17 UTC, merged