Feature/m0228 j 43 microjs
MicroEJ/docs pull request #127
Opened 2020-12-01 10:17 UTC by plaupretre

2020-12-01 10:49 UTC, tdelhomenie-microej approved these changes

2020-12-01 13:31 UTC, gjadi-mej commented
Render branch: https://docs.microej.com/en/feature-m0228j-43_microjs/ApplicationDeveloperGuide/microjs/

PS: don't forget rst uses double backquotes for code not single-backquote (that's in markdown).

2021-07-06 07:58 UTC, frivieremicroej requested changes

2021-07-06 07:58 UTC, frivieremicroej commented on ApplicationDeveloperGuide/index.rst
> +   js/index
Let Limitations the last section
```suggestion
   js/index
   limitations
```

2021-07-06 07:58 UTC, frivieremicroej commented on ApplicationDeveloperGuide/js/builtin.rst
> +Built-in objects
Upper case titles (TODO perform a whole pass)

2021-07-06 07:58 UTC, frivieremicroej commented on ApplicationDeveloperGuide/js/getting_started.rst
> +Let's walk through the steps required to use Javascript in your MicroEJ application:
Where are the Prerequisites ? 
```
The JavaScript bundle is currently in preview and is available on demand. Please contact :ref:`our support team <get_support>`.
```

then 
- unzip the module repo
- briefly explains what it contains
- setup the settings file
- ...

2021-07-06 07:58 UTC, frivieremicroej commented on ApplicationDeveloperGuide/js/getting_started.rst
> +You can have more information on the project types in the :ref:`Module Natures page <module_natures>`.
```suggestion
Javascript is supported in the following :ref:`Module Natures page <module_natures>: 
- :ref:`module_natures.addon_lib`, 
- :ref:`module_natures.standalone_application`,
- :ref:`module_natures.sandboxed_application`.
```

2021-07-06 07:58 UTC, frivieremicroej commented on ApplicationDeveloperGuide/js/index.rst
> +..
please share the associated pptx source files for js_toolchain.png and js_processor_overview.png?

2021-07-06 07:58 UTC, frivieremicroej commented on ApplicationDeveloperGuide/js/index.rst
> +.. figure:: images/js_toolchain.png
I don't like to duplicate this schematic just to add a Java and JS logo
moreover: 
- we are not allowed to use the coffee cup 
- we must ask to legal for using the JS logo.

=> I prefer to replace with the block diagram with JavaScript Addon Library positioning
![image](https://user-images.githubusercontent.com/19801840/124561661-6e9c2e80-de3e-11eb-8b90-8e84773bba6b.png)

2021-07-06 07:58 UTC, frivieremicroej commented on ApplicationDeveloperGuide/js/index.rst
> +Besides Java, the MicroEJ engine allows to develop applications in JavaScript.
Not besides
Please reuse the jleroux kickoff  something like JavaScript "on top of" Java 
TBD 
```suggestion
MicroEJ allows to develop parts of an application in JavaScript. Basically, a MicroEJ Application boots in Java, then it initializes the JavaScript module to run a mix of Java and JavaScript code.
```

We can also link "JavaScript sources processing" to get more details on how it works.

2021-07-06 07:58 UTC, frivieremicroej commented on ApplicationDeveloperGuide/js/internals.rst
> +Internals
Not sure of the term Internals that indicates this is something "behind the scene"
I prefer "Advanced" term

2021-07-06 07:58 UTC, frivieremicroej commented on ApplicationDeveloperGuide/mmm.rst
> +.. _mmm.cli.commands.init:
duplicate init command to be merged to existing one

2021-07-06 09:03 UTC, bguedas commented on ApplicationDeveloperGuide/js/internals.rst
> +Internals
"Behind the scene" is exactly what we mean because you don't need to know how it works in practice to use it. I've just picked two other projects for example! https://jerryscript.net/internals/ ou https://github.com/jruby/jruby/wiki/Internals

2021-07-06 09:22 UTC, bguedas commented on ApplicationDeveloperGuide/js/builtin.rst
> +Built-in objects
Done.

2021-07-06 09:45 UTC, bguedas commented on ApplicationDeveloperGuide/js/index.rst
> +Besides Java, the MicroEJ engine allows to develop applications in JavaScript.
I'm okay with your proposal, maybe "initializes the JavaScript engine" instead of "initializes the JavaScript module", what's your opinion?

2021-07-06 11:51 UTC, tdelhomenie-microej commented on ApplicationDeveloperGuide/mmm.rst
> +.. _mmm.cli.commands.init:
Done

2021-07-06 12:39 UTC, bguedas commented on ApplicationDeveloperGuide/js/index.rst
> +.. figure:: images/js_toolchain.png
The picture has been replaced. Not sure about the size.

2021-07-06 12:39 UTC, bguedas commented on ApplicationDeveloperGuide/js/getting_started.rst
> +Let's walk through the steps required to use Javascript in your MicroEJ application:
I've added a note.

2021-07-07 09:20 UTC, frivieremicroej commented on ApplicationDeveloperGuide/js/internals.rst
> +Internals
OK for the processing flow, but this is not the case for FFI which is not internals: it is required for the JavaScript developer that wants to interact with Java

2021-07-07 09:24 UTC, bguedas commented on ApplicationDeveloperGuide/js/internals.rst
> +Internals
This part on FFI is just about how it is generated, the developer does not need to know it. There is another section explaining how to interface Java and JS called "Communication between Java and JS"

2021-07-07 09:34 UTC, frivieremicroej commented on ApplicationDeveloperGuide/js/internals.rst
> +Internals
After all, I think we should just pull-up FFI just below Built-in Objects and keep Internals with JS Processing section

2021-07-07 09:40 UTC, frivieremicroej commented on ApplicationDeveloperGuide/js/internals.rst
> +Internals
OK my mistake, this section is not necessary tfor the JavaScript developer (this is the Communication Between Java and JS
 section)

2021-07-07 10:10 UTC, bguedas commented on ApplicationDeveloperGuide/js/index.rst
> +..
Done.

2021-07-07 12:47 UTC, frivieremicroej approved these changes

2021-07-07 12:47 UTC, merged