M0228J-74 Add getting started and remove empty chapters
MicroEJ/docs pull request #138
Opened 2020-12-09 17:19 UTC by tdelhomenie-microej

This change adds a getting started and remove empty chapters.

I am not sure the use of the Standalone Application in the getting started is the right choice:
- is it the most commonly used application type for starting ? What about a Java lib ?
- it requires to add the platform before the build since it builds the firmware
- it fails if the property "sp.server.port" is not set (not in the default common.properties)

2020-12-10 11:33 UTC, bguedas requested changes
I've not tested the HTML page layout yet.

2020-12-10 11:33 UTC, bguedas commented on ApplicationDeveloperGuide/microjs/getting_started.rst
> +    MicroJsRuntime.ENGINE.run();
The `stop()` below won't be called because `run()` never returns. You might use `MicroJsRuntime.ENGINE.runOneJob()`.

2020-12-10 11:33 UTC, bguedas commented on ApplicationDeveloperGuide/microjs/getting_started.rst
> +  Once done, you can continue with the MicroEJ SDK or with your favorite IDE.
not a list item (missing `-`)?

2020-12-10 11:33 UTC, bguedas commented on ApplicationDeveloperGuide/microjs/getting_started.rst
> +- create a file named ``hello.js`` in the folder ``src/main/js`` with the following content:
`src/main/js` should be the right folder, but at the moment it is still `src/main/resources`.

2020-12-10 11:33 UTC, bguedas commented on ApplicationDeveloperGuide/mmm.rst
> +- publishing a module in a module repository
Shouldn't we end each list item with `;` and the last one with `.`?

2020-12-10 11:33 UTC, bguedas commented on ApplicationDeveloperGuide/mmm.rst
> +
I guess that all the text above is a copy of the REAME. Should the doc refer to the README or the README to the doc?

The benefit of the README is that it is versioned with the code.

2020-12-10 14:38 UTC, tdelhomenie-microej commented on ApplicationDeveloperGuide/microjs/getting_started.rst
> +    MicroJsRuntime.ENGINE.run();
What is the best ? run wihtout stop or runOneJob with stop ?

2020-12-10 14:39 UTC, tdelhomenie-microej commented on ApplicationDeveloperGuide/microjs/getting_started.rst
> +  Once done, you can continue with the MicroEJ SDK or with your favorite IDE.
No, I go to a new line to avoid having a very long line, but in HTML it is on the same line.

2020-12-10 14:41 UTC, bguedas commented on ApplicationDeveloperGuide/microjs/getting_started.rst
> +  Once done, you can continue with the MicroEJ SDK or with your favorite IDE.
Ok, I was not sure

2020-12-10 14:41 UTC, tdelhomenie-microej commented on ApplicationDeveloperGuide/mmm.rst
> +- publishing a module in a module repository
The practice is to either use `.` or nothing, but most importantly to be consistent. Is there a convention at MicroEJ about this ?

2020-12-10 14:45 UTC, tdelhomenie-microej commented on ApplicationDeveloperGuide/mmm.rst
> +
Right, mostly copy/paste. I agree keeping the README sounds better, but I was not sure it is a common practice to refer to a README in the doc. Let's go to make a link to the README ?

2020-12-10 14:46 UTC, bguedas commented on ApplicationDeveloperGuide/microjs/getting_started.rst
> +    MicroJsRuntime.ENGINE.run();
I think that `MicroJsRuntime.ENGINE.runOneJob()` with `MicroJsRuntime.stop()` is the best option for a HelloWorld: the former executes the only scheduled job whereas the latter stops the timer (otherwise there is a time scheduler thread that continues).

2020-12-10 14:48 UTC, tdelhomenie-microej commented on ApplicationDeveloperGuide/microjs/getting_started.rst
> +    MicroJsRuntime.ENGINE.run();
ok. Done.

2020-12-10 14:49 UTC, tdelhomenie-microej commented on ApplicationDeveloperGuide/microjs/getting_started.rst
> +- create a file named ``hello.js`` in the folder ``src/main/js`` with the following content:
Thanks. Done.

2020-12-10 15:21 UTC, bguedas commented on ApplicationDeveloperGuide/mmm.rst
> +- publishing a module in a module repository
Okay, you're right. This is the practice in english.

2020-12-10 15:23 UTC, bguedas commented on ApplicationDeveloperGuide/mmm.rst
> +
I don't know, it was just to start the discussion :) We may ask the others their opinion

2020-12-10 15:36 UTC, dalgassimou commented on ApplicationDeveloperGuide/microjs/getting_started.rst
> +    MicroJsRuntime.ENGINE.run();
How about changing in the runOneJob ==> to run and run ==> runUntilStopped
The run method will run all jobs and stop itself when there is no job in it queue (it'll also call the engine.stop to clean up)
and runUntilStopped will run until someone call the stop method.

2020-12-10 16:09 UTC, bguedas commented on ApplicationDeveloperGuide/mmm.rst
> +
as discussed in meeting, the full explainations are kept in the doc.

2020-12-10 16:18 UTC, tdelhomenie-microej commented on ApplicationDeveloperGuide/mmm.rst
> +
I will push a MR with the update of the README.

2020-12-10 16:31 UTC, tdelhomenie-microej commented on ApplicationDeveloperGuide/mmm.rst
> +
https://gitlab.cross/M0090_IDE/M0090_MMM-CLI/-/merge_requests/10

2020-12-11 13:52 UTC, bguedas approved these changes

2020-12-11 14:33 UTC, merged