Feature/m0078 ddg 355 improve mmm doc
MicroEJ/docs pull request #139
Opened 2020-12-10 09:52 UTC by gjadi-mej

- how to enable MMM semantic to a module
- how to set MMM matchinig rule on a dependency
- how to enable icy-update easyant plugin
- how to set dependency visibility on a dependency

2020-12-10 10:18 UTC, tdelhomenie-microej commented
Most of the content added in the PR is already in the spec https://repository.microej.com/packages/documentation/TLT-0831-SPE-MicroEJModuleManager-2.0-D.pdf which is referenced in the documentation here : https://docs.microej.com/en/latest/ApplicationDeveloperGuide/mmm.html#specification
It would duplicate the information.
Actually I think we should move all the relevant content of the pptx in the doc directly and remove the pptx. It would make the content searchable.
WDYT ?

2020-12-10 11:30 UTC, gjadi-mej commented
I disagree.

If some information about how to **use** MMM is missing from the doc, then it should be added.  But the specification document may (and probably should) contain more details.  IMO the MMM Spec is similar to the B-ON or SNI specification.

For example, I don't think it is necessary to add to docs.microej.com all the examples about which dependencies are fetched depending of the matching rules.  Yet it is valuable to have it.  (Though, it could be added in an Appendix).

2020-12-10 12:43 UTC, tdelhomenie-microej commented
The "spec" mixes information types, it contains also usage documentation, that's why most of the content of the PR is already in the MMM spec. My initial concern is that it duplicates the information and it is always difficult to maintain consistency, that's why I proposed a way to avoid that.
Having resolution examples in the doc sounds good to me, it helps to understand how it works and to troubleshoot. Maven or gradle for example have detailed documentation about dependency resolution. The doc could be split in several parts to make it easy to read (usage / reference ?).

2020-12-10 12:48 UTC, tdelhomenie-microej requested changes

2020-12-10 12:48 UTC, tdelhomenie-microej commented on ApplicationDeveloperGuide/mmm.rst
> +The MMM semantic is enabled in a the module by adding the MicroEJ XML
```suggestion
The MMM semantic is enabled in a module by adding the MicroEJ XML
```

2020-12-10 12:48 UTC, tdelhomenie-microej commented on ApplicationDeveloperGuide/mmm.rst
> +namespace in the ``ivy-module`` node:
```suggestion
namespace and the ``ej:version`` attribute in the ``ivy-module`` node:
```

2020-12-10 13:12 UTC, gjadi-mej commented on ApplicationDeveloperGuide/mmm.rst
> +The MMM semantic is enabled in a the module by adding the MicroEJ XML
thanks.

2020-12-10 13:12 UTC, gjadi-mej commented on ApplicationDeveloperGuide/mmm.rst
> +namespace in the ``ivy-module`` node:
Thanks.

2020-12-10 13:16 UTC, gjadi-mej commented
I agree with your reasoning but this is a bigger rework.
Until we decide how to present the spec, I think this PR makes it better _now_. :)

2020-12-10 14:30 UTC, tdelhomenie-microej commented
ok, if @frivieremicroej agrees, let's merge this PR and open a ticket for the bigger rework. I will try to find the time to do it soon.

2020-12-14 10:54 UTC, frivieremicroej commented on ApplicationDeveloperGuide/mmm.rst
> +
Indicate this is automatically set by Module Nature Skeletons

2020-12-14 10:54 UTC, frivieremicroej commented on ApplicationDeveloperGuide/mmm.rst
> +Dependency Matching Rule
Module Dependency

- Add the default line and explain this is "compatible"
- Matchind Rule
- Visibility

2020-12-14 10:54 UTC, frivieremicroej commented on ApplicationDeveloperGuide/mmm.rst
> +Dependency Visibility
moved to Module Denpendency

2020-12-14 10:58 UTC, frivieremicroej commented on ApplicationDeveloperGuide/mmm.rst
> +dependency.
```suggestion
the version declared in the module file and update it to the highest
version available which satisfies the matching rule of the
dependency.
```

2020-12-14 11:00 UTC, frivieremicroej commented
> ok, if @frivieremicroej agrees, let's merge this PR and open a ticket for the bigger rework. I will try to find the time to do it soon.

Goal is move all Ivy specific stuff to MMM docs and then later remove from the PDF specification

2020-12-14 11:00 UTC, merged