refresh the platform import section
MicroEJ/docs pull request #147
Opened 2020-12-14 17:05 UTC by frivieremicroej

moved the current documentation to "binary platforms" section

2020-12-15 14:37 UTC, gjadi-mej commented
Preview: https://docs.microej.com/en/feature-m0078ddg-333_sync_how_to_get_platforms_section

2020-12-18 16:53 UTC, gjadi-mej commented on ApplicationDeveloperGuide/platform.rst
> +Once projects are imported, follow the Platform specific documentation for how to build the Platform.
I'm not sure about this formulation either.  I'll try to come up with something.

2020-12-18 22:24 UTC, jerome-leroux requested changes

2020-12-18 22:24 UTC, jerome-leroux commented on ApplicationDeveloperGuide/platform.rst
> +at https://repository.microej.com/index.php?resource=JPF.
```suggestion
In addition, MicroEJ provides platforms for various development boards (see https://repository.microej.com/index.php?resource=JPF).
```

2020-12-18 22:24 UTC, jerome-leroux commented on ApplicationDeveloperGuide/platform.rst
> +- Click on :guilabel:`Finish` button.
```suggestion
- Click on the :guilabel:`Finish` button.
```

2020-12-18 22:24 UTC, jerome-leroux commented on ApplicationDeveloperGuide/platform.rst
> +- Select the zip of the project (e.g. ``x.zip``). The wizard will automatically discover projects to import.
```suggestion
- Select the zip of the project (e.g., ``x.zip``). The wizard will automatically discover projects to import.
```

2020-12-18 22:24 UTC, jerome-leroux commented on ApplicationDeveloperGuide/platform.rst
> +- Click on :guilabel:`Finish` button.
```suggestion
- Click on the :guilabel:`Finish` button.
```

2020-12-18 22:24 UTC, jerome-leroux commented on ApplicationDeveloperGuide/platform.rst
> +Once projects are imported, follow the Platform specific documentation for how to build the Platform.
```suggestion
MicroEJ Platforms are usually shared with only the Platform configuration files. 
Once the projects are imported, follow the platform-specific documentation to build the Platform.
```

2020-12-18 22:24 UTC, jerome-leroux commented on ApplicationDeveloperGuide/platform.rst
> +The ``source`` folder contains the Platform content which can be set to the ``target.platform.dir`` option.
Where should this option be set? Why?

2020-12-18 22:24 UTC, jerome-leroux commented on ApplicationDeveloperGuide/platform.rst
> +After downloading the MicroEJ Platform ``.jpf`` file, launch MicroEJ SDK to import the MicroEJ Platform:
```suggestion
After downloading the MicroEJ Platform ``.jpf`` file, launch MicroEJ SDK and follow these steaps to import the MicroEJ Platform:
```

2020-12-18 22:24 UTC, jerome-leroux commented on ApplicationDeveloperGuide/platform.rst
>     :guilabel:`Preferences` > :guilabel:`MicroEJ` > :guilabel:`Platforms`. The
Add a '.' at the end of the sentence.

2020-12-21 15:46 UTC, gjadi-mej commented on ApplicationDeveloperGuide/platform.rst
> +A MicroEJ Standalone Application requires a MicroEJ Platform to be executed on Simulator or to build the Firmware binary for the target device.
I find the sentence confusing because it can be read as if the platform is executed on the simulator.

2020-12-21 15:47 UTC, gjadi-mej commented on ApplicationDeveloperGuide/platform.rst
> +After downloading the MicroEJ Platform ``.jpf`` file, launch MicroEJ SDK to import the MicroEJ Platform:
@jerome-leroux there is a typo in your suggestion.  `s/steaps/steps/`.

2020-12-23 20:26 UTC, jerome-leroux commented on ApplicationDeveloperGuide/platform.rst
> +A MicroEJ Standalone Application requires a MicroEJ Platform to be executed on Simulator or to build the Firmware binary for the target device.
OK.

```suggestion
A MicroEJ Platform is required to run a MicroEJ Standalone Application on the Simulator or build the Firmware binary for the target device.
```
?

2020-12-23 20:27 UTC, jerome-leroux commented on ApplicationDeveloperGuide/platform.rst
> +After downloading the MicroEJ Platform ``.jpf`` file, launch MicroEJ SDK to import the MicroEJ Platform:
Fixed

2020-12-28 09:12 UTC, frivieremicroej commented on ApplicationDeveloperGuide/platform.rst
> +The ``source`` folder contains the Platform content which can be set to the ``target.platform.dir`` option.
OK I will enhance later by pull-up this section in Standalone Application build
https://docs.microej.com/en/latest/KernelDeveloperGuide/buildType.html#change-the-platform-used-to-build-the-firmware-and-the-virtual-device

2020-12-28 09:18 UTC, merged