Feature/M0078DDG-375 fix mixup stacktracereader
MicroEJ/docs pull request #172
Opened 2021-01-27 14:47 UTC by fpinel-microej

2021-01-27 15:43 UTC, frivieremicroej commented on ApplicationDeveloperGuide/stackTraceReader.rst
> +---------------------------
I suggest to merge the title

Use (Standalone Application)
===================

Use (Sandboxed Application)
===================

2021-01-27 17:20 UTC, frivieremicroej commented on ApplicationDeveloperGuide/stackTraceReader.rst
> +(in the case of a platform with full BSP connection (see :ref:`BSP Connection Cases <bsp_connection_cases>`), the file is ``application.out`` in the output folder).
avoid nested parenthesis

2021-01-27 17:20 UTC, frivieremicroej commented on ApplicationDeveloperGuide/stackTraceReader.rst
>  This tool is a built-in platform tool.
- blur the platform / vd in the screeshots

2021-01-27 17:20 UTC, frivieremicroej commented on ApplicationDeveloperGuide/stackTraceReader.rst
> +.. figure:: images/STR_configuration_standalone.png
- remove Serial To Socket transmitter launch in standalone screenshot

2021-01-27 17:24 UTC, frivieremicroej commented on ApplicationDeveloperGuide/stackTraceReader.rst
> +   Select Stack Trace Reader Tool
Stack Trace Reader Tool Configuration (Platform Selection)

2021-01-27 17:24 UTC, frivieremicroej commented on ApplicationDeveloperGuide/stackTraceReader.rst
>     Select Stack Trace Reader Tool
Stack Trace Reader Tool Configuration (Virtual Device Selection)

2021-01-27 17:24 UTC, frivieremicroej commented on ApplicationDeveloperGuide/stackTraceReader.rst
>     :alt: Read the Stack Trace
Stack Trace Reader Console

2021-01-27 17:24 UTC, frivieremicroej commented on ApplicationDeveloperGuide/stackTraceReader.rst
> +   Read the Stack Trace
Stack Trace Reader Console

2021-01-27 18:07 UTC, jerome-leroux requested changes

2021-01-27 18:07 UTC, jerome-leroux commented on ApplicationDeveloperGuide/stackTraceReader.rst
> +(in the case of a platform with full BSP connection (see :ref:`BSP Connection Cases <bsp_connection_cases>`), the file is ``application.out`` in the output folder).
```suggestion
To decode an application stack trace, the stack trace reader tool requires the application executable ELF file.
In the case of a platform with full BSP connection (see :ref:`BSP Connection Cases <bsp_connection_cases>`), the file is ``application.out`` in the output folder. 
In the other cases, the ELF file is generated by the C toolchain when building the BSP project (usually a ``.out`` or ``.axf`` file).
```

2021-01-28 08:11 UTC, frivieremicroej commented on ApplicationDeveloperGuide/stackTraceReader.rst
> +Create a new MicroEJ Tool configuration. In the :guilabel:`Execution` tab, select your target platform, then select the :guilabel:`Stack Trace Reader` tool. Set an output folder in the :guilabel:`Out
Felix tested with only the `.fodbg` file.

(the Kernel executable may not be able to the app developer)

We should explain both cases: (the base option is mandatory)
- If you have the Kernel executable => put it in the base option and put the `.fodbg` in additionnal files
- If you don't have the Kernel executable => put the `.fodbg` in the base option

2021-01-28 08:12 UTC, frivieremicroej commented on ApplicationDeveloperGuide/stackTraceReader.rst
> +available by your firmware provider).
ok see comment below => to be moved to the Use (Sandboxed Application) section

2021-01-28 18:10 UTC, fpinel-microej commented on ApplicationDeveloperGuide/stackTraceReader.rst
> +Create a new MicroEJ Tool configuration. In the :guilabel:`Execution` tab, select your target platform, then select the :guilabel:`Stack Trace Reader` tool. Set an output folder in the :guilabel:`Out
I am not sure what is the difference here, how can I (or any developer for that matter) get access to the Kernel executable and use it with the stack trace reader ? From the previous version of the tutorial I gathered that only the `.fodbg` file was needed to use the STR, not sure how to proceed from here.

2021-01-28 21:19 UTC, fpinel-microej commented on ApplicationDeveloperGuide/stackTraceReader.rst
> +Create a new MicroEJ Tool configuration. In the :guilabel:`Execution` tab, select your target platform, then select the :guilabel:`Stack Trace Reader` tool. Set an output folder in the :guilabel:`Out
Following jleroux's explanations, wrote a first draft for the Kernel executable file usage. Feedback welcome

2021-01-28 21:30 UTC, jerome-leroux commented on ApplicationDeveloperGuide/stackTraceReader.rst
> +Create a new MicroEJ Tool configuration. In the :guilabel:`Execution` tab, select your target platform, then select the :guilabel:`Stack Trace Reader` tool. Set an output folder in the :guilabel:`Out
Looks good to me

2021-01-29 12:26 UTC, frivieremicroej commented on ApplicationDeveloperGuide/stackTraceReader.rst
> +Create a new MicroEJ Tool configuration. In the :guilabel:`Execution` tab, select your target platform, then select the :guilabel:`Stack Trace Reader` tool. Set an output folder in the :guilabel:`Out
Yes it's very clear.
I just pulled up the "multi-trace" capability in functional description.
Thanks @fpinel-microej

2021-01-29 12:28 UTC, merged