Feature/m0090 ide 3546 mmm cli friviere review
MicroEJ/docs pull request #194
Opened 2021-02-18 14:50 UTC by frivieremicroej

2021-02-18 16:49 UTC, tdelhomenie-microej requested changes

2021-02-18 16:49 UTC, tdelhomenie-microej commented on ApplicationDeveloperGuide/mmm.rst
> +Build Option
Singular because there is only 1 option listed ? Aren't there others general options available ?

2021-02-18 16:49 UTC, tdelhomenie-microej commented on ApplicationDeveloperGuide/mmm.rst
> -This Build Kit is the good tool if you want to work in a terminal or in any other IDE, or if you want to build your modules in a Continuous Integration tool.
Not sure if "headless mode" is easy to understand. That's why I talked about "terminal".

2021-02-18 16:49 UTC, tdelhomenie-microej commented on ApplicationDeveloperGuide/mmm.rst
> +     mmm [OPTION]... [COMMAND].
The trailing dot must be removed.

2021-02-18 16:49 UTC, tdelhomenie-microej commented on ApplicationDeveloperGuide/mmm.rst
> +- to run on the Simulator, the project must be configured one of the following :ref:`module_natures`:
"... must be configured with one of the ..."

2021-02-18 16:49 UTC, tdelhomenie-microej commented on ApplicationDeveloperGuide/mmm.rst
> +- the module must have been built once before running the Simulator. So the ``mmm build`` command must be executed before running the Simulator the first time or after project clean (``mmm clean`` co
"...  after project a clean ..."

2021-02-18 16:58 UTC, tdelhomenie-microej requested changes

2021-02-18 16:58 UTC, tdelhomenie-microej commented on ApplicationDeveloperGuide/mmm.rst
> +- ``help``: displays help information about the specified command
```suggestion
- ``help``: displays help information about the specified command
```

2021-02-19 07:38 UTC, frivieremicroej commented on ApplicationDeveloperGuide/mmm.rst
> +Build Option
No we may declare multiple generic options. 
Here I wanted to align with `Module Dependency` section so that we can link the section each time speaking about a build option (:ref:`mmm_build_option` ``xxx``). I also moved the anchor to singular

And I also added links to module dependency section in the same way (:ref:`mmm_module_dependency`)

2021-02-19 07:44 UTC, frivieremicroej commented on ApplicationDeveloperGuide/mmm.rst
> -This Build Kit is the good tool if you want to work in a terminal or in any other IDE, or if you want to build your modules in a Continuous Integration tool.
ok I added back
moreover please note that I removed the "in an other IDE" because this is not a supported feature in MicroEJ 5.x

2021-02-19 07:45 UTC, frivieremicroej commented on ApplicationDeveloperGuide/mmm.rst
> +- to run on the Simulator, the project must be configured one of the following :ref:`module_natures`:
done

2021-02-19 07:45 UTC, frivieremicroej commented on ApplicationDeveloperGuide/mmm.rst
> +- the module must have been built once before running the Simulator. So the ``mmm build`` command must be executed before running the Simulator the first time or after project clean (``mmm clean`` co
"... after **a** project  clean ..."

2021-02-19 07:45 UTC, frivieremicroej commented on ApplicationDeveloperGuide/mmm.rst
> +     mmm [OPTION]... [COMMAND].
done

2021-02-19 07:48 UTC, tdelhomenie-microej commented on ApplicationDeveloperGuide/mmm.rst
> +Build Option
So that's weird to have a chapter title in singular whereas there are potentially several options. The link text can be changed in the references, no need to tight them IMO (different contexts, different forms).

2021-02-19 07:48 UTC, tdelhomenie-microej commented on ApplicationDeveloperGuide/mmm.rst
> -This Build Kit is the good tool if you want to work in a terminal or in any other IDE, or if you want to build your modules in a Continuous Integration tool.
👍

2021-02-19 07:49 UTC, tdelhomenie-microej commented on ApplicationDeveloperGuide/mmm.rst
> +- the module must have been built once before running the Simulator. So the ``mmm build`` command must be executed before running the Simulator the first time or after project clean (``mmm clean`` co
😂 yes !

2021-02-19 10:10 UTC, frivieremicroej commented on ApplicationDeveloperGuide/mmm.rst
> +Build Option
done

2021-02-19 10:30 UTC, tdelhomenie-microej approved these changes

2021-02-19 10:30 UTC, merged