document null analysis tool
MicroEJ/docs pull request #196
Opened 2021-02-22 11:05 UTC by frivieremicroej

- @tdelhomenie-microej review for global understanding
- @seonmej for checking correct wiki/rules translation

Thanks

2021-02-23 07:35 UTC, tdelhomenie-microej requested changes

2021-02-23 07:35 UTC, tdelhomenie-microej commented on ApplicationDeveloperGuide/nullAnalysis.rst
> +`NullPointerException <https://repository.microej.com/javadoc/microej_5.x/apis/ej/annotation/NonNullByDefault.html>`_ thrown at runtime is one of the most common causes for failure of Java programs.
Why a link to the javadoc of the NonNullByDefault annotation to illustrate NullPointerException ?

2021-02-23 07:35 UTC, tdelhomenie-microej commented on ApplicationDeveloperGuide/nullAnalysis.rst
> +Null Analysis tool can detect such programming errors (misuse of potential ``null`` Java values) at compile-time.
"A Null Analysis tool ..." or "Null Analysis tools ..."

2021-02-23 07:35 UTC, tdelhomenie-microej commented on ApplicationDeveloperGuide/nullAnalysis.rst
> +  This rule can be overridden on each element by using Nullable annotation.
```suggestion
  This rule can be overridden on each element by using the Nullable annotation.
```

2021-02-23 07:35 UTC, tdelhomenie-microej commented on ApplicationDeveloperGuide/nullAnalysis.rst
> +- `@NonNullBydefault <https://repository.microej.com/javadoc/microej_5.x/apis/ej/annotation/NonNullByDefault.html>`_: Indicates that all fields, method return values or parameters can never be null i
```suggestion
- `@NonNullByDefault <https://repository.microej.com/javadoc/microej_5.x/apis/ej/annotation/NonNullByDefault.html>`_: Indicates that all fields, method return values or parameters can never be null in the annotated package or type.
```

2021-02-23 07:35 UTC, tdelhomenie-microej commented on ApplicationDeveloperGuide/nullAnalysis.rst
> +  This allow to declare all fields and methods that can never be null, which is considered to be the default case unless it is not explicitly marked ``@Nullable``.
```suggestion
  This allows to declare all fields and methods that can never be null, which is considered to be the default case unless it is not explicitly marked ``@Nullable``.
```

2021-02-23 07:35 UTC, tdelhomenie-microej commented on ApplicationDeveloperGuide/nullAnalysis.rst
> +   MicroEJ SDK ``5.3.0`` or higher require annotations declared in `EDC-1.3.3 <https://repository.microej.com/modules/ej/api/edc/1.3.3/>`_ or higher. See `EDC 1.3.3 Changelog <https://repository.micr
```suggestion
   MicroEJ SDK ``5.3.0`` or higher requires annotations declared in `EDC-1.3.3 <https://repository.microej.com/modules/ej/api/edc/1.3.3/>`_ or higher. See `EDC 1.3.3 Changelog <https://repository.microej.com/modules/ej/api/edc/1.3.3/CHANGELOG-1.3.3.md>`_ for more details.
```

2021-02-23 07:35 UTC, tdelhomenie-microej commented on ApplicationDeveloperGuide/nullAnalysis.rst
> +To enable Null Analysis tool, a :ref:`module project <mmm_module_skeleton>` must be configured as follows:
```suggestion
To enable the Null Analysis tool, a :ref:`module project <mmm_module_skeleton>` must be configured as follows:
```

2021-02-23 07:35 UTC, tdelhomenie-microej commented on ApplicationDeveloperGuide/nullAnalysis.rst
> +  .. figure:: images/null_analysis_project_configuration_annotations.png
We should list the value to set in full text here, it would make it easier and less error-prone for users to copy/paste.

2021-02-23 07:35 UTC, tdelhomenie-microej commented on ApplicationDeveloperGuide/nullAnalysis.rst
> +If you have multiple projects to configure, you can then copy the content of the ``.settings`` folder to an other :ref:`module project <mmm_module_skeleton>`.
We should warn that it will erase any other custom configuration done on these projects.

2021-02-23 07:35 UTC, tdelhomenie-microej commented on ApplicationDeveloperGuide/nullAnalysis.rst
> +  This allows APIs returning ``null`` (e.g. `HashMap.get(Object) <https://repository.microej.com/javadoc/microej_5.x/apis/java/util/HashMap.html#get-java.lang.Object->`_) only when an element is not
```suggestion
  This allows APIs to return ``null`` (e.g. `HashMap.get(Object) <https://repository.microej.com/javadoc/microej_5.x/apis/java/util/HashMap.html#get-java.lang.Object->`_) only when an element is not contained in the collection.
```

2021-02-23 07:35 UTC, tdelhomenie-microej commented on ApplicationDeveloperGuide/tools.rst
>     | Copyright 2008-2020, MicroEJ Corp. Content in this space is free
```suggestion
   | Copyright 2008-2021, MicroEJ Corp. Content in this space is free 
```

2021-02-23 14:21 UTC, seonmej commented on ApplicationDeveloperGuide/nullAnalysis.rst
> +  This allow to declare all fields and methods that can never be null, which is considered to be the default case unless it is not explicitly marked ``@Nullable``.
```suggestion
  This declares the objects to be non-null unless they are annotated with ``@Nullable``. This is the opposite as Java language that assumes that everything can be null by default.
```

2021-02-23 14:21 UTC, seonmej commented on ApplicationDeveloperGuide/nullAnalysis.rst
> +   MicroEJ SDK ``5.3.0`` or higher require annotations declared in `EDC-1.3.3 <https://repository.microej.com/modules/ej/api/edc/1.3.3/>`_ or higher. See `EDC 1.3.3 Changelog <https://repository.micr
```suggestion
   MicroEJ SDK ``5.3.0`` or higher requires the annotations available in `EDC-1.3.3 <https://repository.microej.com/modules/ej/api/edc/1.3.3/>`_ or higher. See `EDC 1.3.3 Changelog <https://repository.microej.com/modules/ej/api/edc/1.3.3/CHANGELOG-1.3.3.md>`_ for more details.
```

2021-02-23 14:21 UTC, seonmej commented on ApplicationDeveloperGuide/nullAnalysis.rst
> +- In :guilabel:`Null analysis` section, configure options as follows:
```suggestion
- In the :guilabel:`Null analysis` section, configure options as follows:
```

2021-02-23 14:21 UTC, seonmej commented on ApplicationDeveloperGuide/nullAnalysis.rst
> +- In :guilabel:`Annotations` section, check :guilabel:`Suppress optional errors with '@SuppressWarnings'` option:
```suggestion
- In the :guilabel:`Annotations` section, check :guilabel:`Suppress optional errors with '@SuppressWarnings'` option:
```

2021-02-23 14:21 UTC, seonmej commented on ApplicationDeveloperGuide/nullAnalysis.rst
> +For more information about Null Analysis detection and inter-procedural analysis, please visit `Eclipse JDT Null Analysis documentation <https://help.eclipse.org/2020-06/index.jsp?topic=/org.eclipse.
```suggestion
For more information about Null Analysis and inter-procedural analysis, please visit `Eclipse JDT Null Analysis documentation <https://help.eclipse.org/2020-06/index.jsp?topic=/org.eclipse.jdt.doc.user/tasks/task-using_null_annotations.htm>`_.
```

2021-02-23 14:21 UTC, seonmej commented on ApplicationDeveloperGuide/nullAnalysis.rst
> +So if these additional constraints are not acceptable for your project, please disable Null Analysis detection.
```suggestion
So if these additional constraints are not acceptable for your project, please disable Null Analysis.
```

2021-02-23 14:21 UTC, seonmej commented on ApplicationDeveloperGuide/nullAnalysis.rst
> +Many libraries available on :ref:`central_repository` are annotated with Null Analysis. If you are using a library which is not yet annotated, please ask to support@microej.com.
In the page tutorialUnderstandMicroEJFirmwareBuild, there is another way to contact our support:
`If any questions, feel free to contact our support team with the following information (the table below is an example):` with a link to https://www.microej.com/contact/#form_2.
Perhaps we can add a generic support section that can be referred each time it is needed?

2021-02-23 14:22 UTC, seonmej commented on ApplicationDeveloperGuide/nullAnalysis.rst
> +- Click on :guilabel:`Configure...` link to configure MicroEJ annotations:
```suggestion
- Click on the :guilabel:`Configure...` link to configure MicroEJ annotations:
```

2021-02-24 11:08 UTC, frivieremicroej commented on ApplicationDeveloperGuide/nullAnalysis.rst
> +`NullPointerException <https://repository.microej.com/javadoc/microej_5.x/apis/ej/annotation/NonNullByDefault.html>`_ thrown at runtime is one of the most common causes for failure of Java programs.
fixed

2021-02-24 11:11 UTC, frivieremicroej commented on ApplicationDeveloperGuide/nullAnalysis.rst
> +  This allow to declare all fields and methods that can never be null, which is considered to be the default case unless it is not explicitly marked ``@Nullable``.
@seon rewording not understood TBD

2021-02-24 11:18 UTC, frivieremicroej commented on ApplicationDeveloperGuide/nullAnalysis.rst
> +Null Analysis tool can detect such programming errors (misuse of potential ``null`` Java values) at compile-time.
fixed

2021-02-24 11:18 UTC, frivieremicroej commented on ApplicationDeveloperGuide/nullAnalysis.rst
> +To enable Null Analysis tool, a :ref:`module project <mmm_module_skeleton>` must be configured as follows:
fixed

2021-02-24 11:36 UTC, frivieremicroej commented on ApplicationDeveloperGuide/nullAnalysis.rst
> +Many libraries available on :ref:`central_repository` are annotated with Null Analysis. If you are using a library which is not yet annotated, please ask to support@microej.com.
goot point 
I extracted the get support and redirecte everywhere

2021-02-24 14:09 UTC, frivieremicroej commented on ApplicationDeveloperGuide/nullAnalysis.rst
> +  This allow to declare all fields and methods that can never be null, which is considered to be the default case unless it is not explicitly marked ``@Nullable``.
fixed with @tdelhomenie-microej

2021-02-24 14:09 UTC, frivieremicroej commented on ApplicationDeveloperGuide/nullAnalysis.rst
> +If you have multiple projects to configure, you can then copy the content of the ``.settings`` folder to an other :ref:`module project <mmm_module_skeleton>`.
fixed

2021-02-24 14:28 UTC, merged