Document MicroEJ Packs flavors and packs naming convention
MicroEJ/docs pull request #200
Opened 2021-02-24 16:59 UTC by gjadi-mej

https://docs.microej.com/en/feature-m0018pqt-253_microej_pack_naming_convention

2021-02-24 17:18 UTC, frivieremicroej requested changes

2021-02-24 17:18 UTC, frivieremicroej commented on PlatformDeveloperGuide/platformCreation.rst
> +#. MicroEJ Architecture Specific Pack provided at https://repository.microej.com/architectures/.
unordered list (there is no order not priority)

2021-02-24 17:18 UTC, frivieremicroej commented on PlatformDeveloperGuide/platformCreation.rst
> +#. MicroEJ Architecture Specific Pack provided at https://repository.microej.com/architectures/.
use https://repository.microej.com/modules/com/microej/architecture instead

2021-02-24 17:18 UTC, frivieremicroej commented on PlatformDeveloperGuide/platformCreation.rst
> +https://repository.microej.com/architectures/com/microej/architecture/CM4/CM4hardfp_GCC48/flopi4G25-ui-pack/.
https://repository.microej.com/modules/com/microej/architecture/CM4/CM4hardfp_GCC48/flopi4G25-ui-pack/

2021-02-24 17:18 UTC, frivieremicroej commented on PlatformDeveloperGuide/platformCreation.rst
> +        <!-- MicroEJ Architecture Specific Pack and Legacy MicroEJ Generic Pack  -->
split legacy generic pack in an other dependency belox the generic pack dependency

2021-02-24 17:18 UTC, frivieremicroej commented on PlatformDeveloperGuide/platformCreation.rst
> +          <!-- MicroEJ Architecture Specific Pack and Legacy MicroEJ Generic Pack  -->
```suggestion
          <!-- MicroEJ Architecture Specific Pack  -->
```

2021-02-24 17:18 UTC, frivieremicroej commented on PlatformDeveloperGuide/platformCreation.rst
> +          </dependency>
```suggestion
          <dependency org="com.microej.architecture.CM4.CM4hardfp_GCC48" name="flopi4G25-ui-pack" rev="13.0.4"/>
```
shoud be sufficient since we do not need to filter eval/prod configuration

2021-02-24 17:18 UTC, frivieremicroej commented on PlatformDeveloperGuide/platformCreation.rst
> +Modules Modules are provided by MicroEJ Architecture Specific Packs
to be rewiewed

- use Platform modules everywhere it applies to avoid conflicting with MMM modules
- Platform modules are provided by Architecture, Architecture Specific Packs & Legacy Packs

2021-02-24 17:18 UTC, frivieremicroej commented on PlatformDeveloperGuide/platformCreation.rst
> +There are two flavors of MicroEJ Packs:
)use same wording than for platforms (https://docs.microej.com/en/feature-m0018pqt-253_microej_pack_naming_convention/ApplicationDeveloperGuide/platform.html#) (MicroEJ Platforms are distributed in two packages ...)

MicroEJ Packs are distributed in two packages:
xxx
yyy

2021-02-25 08:31 UTC, gjadi-mej commented on PlatformDeveloperGuide/platformCreation.rst
> +#. MicroEJ Architecture Specific Pack provided at https://repository.microej.com/architectures/.
Ok

2021-02-25 08:35 UTC, gjadi-mej commented on PlatformDeveloperGuide/platformCreation.rst
> +#. MicroEJ Architecture Specific Pack provided at https://repository.microej.com/architectures/.
Ok

2021-02-25 08:35 UTC, gjadi-mej commented on PlatformDeveloperGuide/platformCreation.rst
> +https://repository.microej.com/architectures/com/microej/architecture/CM4/CM4hardfp_GCC48/flopi4G25-ui-pack/.
Ok

2021-02-25 08:44 UTC, gjadi-mej commented on PlatformDeveloperGuide/platformCreation.rst
> +          </dependency>
Ok.  It works, tested on WROVER.

2021-02-25 09:01 UTC, gjadi-mej commented on PlatformDeveloperGuide/platformCreation.rst
> +        <!-- MicroEJ Architecture Specific Pack and Legacy MicroEJ Generic Pack  -->
Ok

2021-02-25 09:02 UTC, gjadi-mej commented on PlatformDeveloperGuide/platformCreation.rst
> +Modules Modules are provided by MicroEJ Architecture Specific Packs
Ok

Note that I did not specified `Platform module` for every occurrences of `module` when I thought it was obvious from the context.

2021-02-25 09:03 UTC, gjadi-mej commented on PlatformDeveloperGuide/platformCreation.rst
> +There are two flavors of MicroEJ Packs:
Ok.

2021-02-26 13:34 UTC, gjadi-mej commented on PlatformDeveloperGuide/platformCreation.rst
> +- ``VERSION``: pack version (e.g. ``7.12.0``).
```suggestion
- ``VERSION``: pack version (e.g. ``13.0.4``).
```

2021-02-26 13:49 UTC, gjadi-mej commented on PlatformDeveloperGuide/platformCreation.rst
> +These Platforms are built from MicroEJ Architecture Specific Packs and Legacy MicroEJ Generic Packs (packaged as ``.xpfp`` files).
```suggestion
This section is only relevant for older MicroEJ Platforms with no :ref:`mmm_module_description`.
These Platforms are built from MicroEJ Architecture Specific Packs and Legacy MicroEJ Generic Packs (packaged as ``.xpfp`` files) that must be imported manually.
```

2021-02-26 15:51 UTC, merged