Add a tutorial on how to create Build Scripts for a Platform.
MicroEJ/docs pull request #222
Opened 2021-04-02 12:19 UTC by bguedas

2021-04-02 16:56 UTC, gjadi-mej commented
Preview: https://docs.microej.com/en/feature-m0018pqt-274_build_scripts_tutorial/Tutorials/tutorialCreateBuildScripts.html

2021-04-06 08:54 UTC, gjadi-mej requested changes

2021-04-06 08:54 UTC, gjadi-mej commented on Tutorials/tutorialCreateBuildScripts.rst
> +Create Platform Build Scripts
Please add an anchor so we can reference the tuto elsewhere (e.g. `.. _tutorialCreateBuildScripts:`)

2021-04-06 08:54 UTC, gjadi-mej commented on Tutorials/tutorialCreateBuildScripts.rst
> +The audience for this document is Platform engineers who want to
```suggestion
The audience for this document are Platform engineers who want to
```

2021-04-06 08:54 UTC, gjadi-mej commented on Tutorials/tutorialCreateBuildScripts.rst
> +- ease application development by removing the link to the BSP
What do you mean by "removing the link to the BSP"?

2021-04-06 08:54 UTC, gjadi-mej commented on Tutorials/tutorialCreateBuildScripts.rst
> +In  :ref:`Create a MicroEJ Firmware From Scratch<create_firmware_from_scratch>`, the :ref:`BSP connection<bsp_connection>` is partial: the final binary is produced by invoking ``make`` in the FreeRTO
That's incorrect, the connection is partial means that the property `root.dir` is defined in the application launcher instead of being defined in the platform.

2021-04-06 08:54 UTC, gjadi-mej commented on Tutorials/tutorialCreateBuildScripts.rst
> +There are four scripts:
You present 2 scripts (build.xxx and run.xxx) not 4.

2021-04-06 08:54 UTC, gjadi-mej commented on Tutorials/tutorialCreateBuildScripts.rst
> +2. Verify that the scrit succesfully build our firmware and put it in the current directory with the name ``application.out``.
```suggestion
2. Verify that the script successfully built our firmware and put it in the current directory with the name ``application.out``.
```

2021-04-06 08:54 UTC, gjadi-mej commented on Tutorials/tutorialCreateBuildScripts.rst
> +4. Create a file called ``run.sh`` in the ``microej/scripts`` directory with the following content:
The run.xxx script should program the application.out located in the directory of execution.  In this case it is not necessary to copy it, but it might be worth mentioning it.

2021-04-06 08:54 UTC, gjadi-mej commented on Tutorials/tutorialCreateBuildScripts.rst
> +  This script is very simple because our application is just run with QEMU instead of a real hardware. To deploy the applcation on a device, the script would have to setup and call a flash tool. See
```suggestion
  This script is very simple because our application is just run with QEMU instead of a real hardware. To deploy the application on a device, the script would have to setup and call a flash tool. See for instance the build script for `Espressif-ESP-WROVER-KIT-V4.1 <https://github.com/MicroEJ/Platform-Espressif-ESP-WROVER-KIT-V4.1/blob/1.7.0/ESP32-WROVER-Xtensa-FreeRTOS-bsp/Projects/microej/scripts/build.sh>`_. 
```

2021-04-06 08:54 UTC, gjadi-mej commented on Tutorials/tutorialCreateBuildScripts.rst
> +As our toolchain has only be configured for Linux in WSL, we simply create wrappers that call shell scripts through WSL.
```suggestion
As our toolchain has only be configured for Linux in WSL, we create wrappers that call shell scripts through WSL.
```

2021-04-06 08:54 UTC, gjadi-mej commented on Tutorials/tutorialCreateBuildScripts.rst
> +Links the Platform to the BSP
```suggestion
Link the Platform to the BSP
```

2021-04-06 08:54 UTC, gjadi-mej commented on Tutorials/tutorialCreateBuildScripts.rst
> + The application launcher does not know anymore where the BSP is located Nevertheless it still builds a full firmware ready to be flashed. The link to the BSP is now configured in the platform and ev
```suggestion
 The application launcher does not know anymore where the BSP is located. Nevertheless it still builds a full firmware ready to be flashed. The link to the BSP is now configured in the platform and every MicroEJ mono-sandboxed application projects can use it without extra configuration.
```

2021-04-06 09:21 UTC, gjadi-mej commented on Tutorials/tutorialCreateBuildScripts.rst
> +4. Create a file called ``run.sh`` in the ``microej/scripts`` directory with the following content:
If possible, find a way to terminate the QEMU session

2021-04-06 11:54 UTC, bguedas commented on Tutorials/tutorialCreateBuildScripts.rst
> +The audience for this document is Platform engineers who want to
Not that clear. I've picked this sentence from another tutorial. The subject is "the audience". https://ell.stackexchange.com/questions/77797/most-of-the-audience-is-are

2021-04-06 11:56 UTC, bguedas commented on Tutorials/tutorialCreateBuildScripts.rst
> +- ease application development by removing the link to the BSP
I mean that the app developer does not need to be aware of the BSP, he only configures is platform.

2021-04-06 12:03 UTC, gjadi-mej commented on Tutorials/tutorialCreateBuildScripts.rst
> +The audience for this document is Platform engineers who want to
You're correct, and I now remember I've been bitten by this one on the other tutorial :P

2021-04-07 05:22 UTC, bguedas commented on Tutorials/tutorialCreateBuildScripts.rst
> +Create Platform Build Scripts
Done

2021-04-07 05:22 UTC, bguedas commented on Tutorials/tutorialCreateBuildScripts.rst
> +There are four scripts:
Fixed

2021-04-07 05:23 UTC, bguedas commented on Tutorials/tutorialCreateBuildScripts.rst
> +In  :ref:`Create a MicroEJ Firmware From Scratch<create_firmware_from_scratch>`, the :ref:`BSP connection<bsp_connection>` is partial: the final binary is produced by invoking ``make`` in the FreeRTO
This part has been rewritten.

2021-04-09 13:31 UTC, gjadi-mej commented on Tutorials/tutorialCreateBuildScripts.rst
> +In  :ref:`Create a MicroEJ Firmware From Scratch<create_firmware_from_scratch>`, the :ref:`BSP connection<bsp_connection>` the final binary is produced by invoking ``make`` in the FreeRTOS BSP. The c
```suggestion
In  :ref:`Create a MicroEJ Firmware From Scratch<create_firmware_from_scratch>`, the final binary is produced by invoking ``make`` in the FreeRTOS BSP. The command to type is dependant of the toolchain used. The application is then launched in QEMU but could have been instead flashed to a device with another specific command. This tutorial explain how to write `build` and `run` scripts for these two tasks. 
```

2021-04-09 13:33 UTC, gjadi-mej commented on Tutorials/tutorialCreateBuildScripts.rst
> +1. Create a file called `build.bat` in the `microej/scripts` directory with the following content:
```suggestion
1. Create a file called ``build.bat`` in the ``microej/scripts`` directory with the following content:
```

2021-04-09 13:34 UTC, gjadi-mej commented on Tutorials/tutorialCreateBuildScripts.rst
> +Finish full BSP connection (optional)
```suggestion
Convert from partial BSP connection to full BSP connection (optional)
```

2021-04-09 13:37 UTC, gjadi-mej commented
@bguedas I just noticed, please use `#.` instead of `1.  2.   3.` for ordered list.
See https://sublime-and-sphinx-guide.readthedocs.io/en/latest/lists.html for the list syntax.

2021-04-14 07:16 UTC, frivieremicroej commented on Tutorials/tutorialCreateBuildScripts.rst
> +- ease application development by removing the link to the BSP
2 remarks to be discussed:
- build script**s** is not correct: rather use BSP scripts (composed of build script https://docs.microej.com/en/latest/PlatformDeveloperGuide/platformCreation.html#build-script-file and run script https://docs.microej.com/en/latest/PlatformDeveloperGuide/platformCreation.html#run-script-file)
- I think this tuto should be renamed "tutoConfigurePlatformBSPConnection" (Configure MicroEJ Platform BSP Connection)

2021-04-14 15:30 UTC, gjadi-mej commented on Tutorials/tutorialCreateBuildScripts.rst
> +- ease application development by removing the link to the BSP
We agreed on "build and run script".  @bguedas please you this naming throughout the tutorial.

2021-04-15 07:11 UTC, frivieremicroej commented
@fpinel-microej please review to run this tutorial

2021-04-15 13:03 UTC, bguedas commented on Tutorials/tutorialCreateBuildScripts.rst
> +- ease application development by removing the link to the BSP
The introduction does not talk about BSP connection, but BSP connection is listed in 'intended audience' because someone who wants to configure a full BSP connection will find useful information in this tutorial too. This part only lists all the cases where reading the tutorial may be useful.

What do you think of someting like
```
The audience for this document is Platform engineers who want to
- write build and run scripts for their platform 
- validate their platform using MicroEJ test suites


Platform engineers who want to configure a full :ref:`BSP connection<bsp_connection>` with their platform will also find useful information in this tutorial.
```

2021-04-15 13:07 UTC, bguedas commented on Tutorials/tutorialCreateBuildScripts.rst
> +4. Create a file called ``run.sh`` in the ``microej/scripts`` directory with the following content:
I've tried, but didn't find a satisfying solution.

2021-04-15 13:20 UTC, bguedas commented on Tutorials/tutorialCreateBuildScripts.rst
> +- ease application development by removing the link to the BSP
I've changed `build script` with `build and run scripts`

2021-04-15 16:17 UTC, gjadi-mej commented on Tutorials/tutorialCreateBuildScripts.rst
> +4. Create a file called ``run.sh`` in the ``microej/scripts`` directory with the following content:
Ok,  Let's drop this for now then.

2021-04-15 16:18 UTC, gjadi-mej commented on Tutorials/tutorialCreateBuildScripts.rst
> +Links the Platform to the BSP
Not relevant anymore

2021-04-15 16:18 UTC, gjadi-mej commented on Tutorials/tutorialCreateBuildScripts.rst
> +<<<<<<< HEAD
Looks like a merge leftover.  Please fix it.

2021-04-15 16:31 UTC, bguedas commented on Tutorials/tutorialCreateBuildScripts.rst
> +<<<<<<< HEAD
fixed

2021-04-16 23:46 UTC, fpinel-microej commented on Tutorials/tutorialCreateBuildScripts.rst
> +- describe step-by-step how to ceate the build and run scripts both for shell and batch terminals. These scripts automate platform build and firmware execution in QUEMU as presented in :ref:`Create a
"QUEMU" ==> QEMU ?

2021-04-16 23:46 UTC, fpinel-microej commented on Tutorials/tutorialCreateBuildScripts.rst
> +7. Edit the file ``bsp/bsp.properties`` as follow:
I think it could be nice to remind to rebuild the platform after editing `bsp.properties`.

2021-04-16 23:46 UTC, fpinel-microej commented on Tutorials/tutorialCreateBuildScripts.rst
> +  This script is very simple because our application is just run with QEMU instead of a real hardware. To deploy the application on a device, the script would have to setup and call a flash tool. See
"instead of a real hardware" ==> should be "instead of real hardware" (or "instead of a real hardware board/device/something") I believe

2021-04-16 23:53 UTC, fpinel-microej commented
Note : after setting Eclipse to run build.bat, my build is successful but I get this warning. I'm not sure how important or not this is : 
```
Execution of script 'C:\Users\fpinel\src\tuto-from-scratch\FreeRTOS\FreeRTOS\Demo\CORTEX_LM3S6965_GCC\microej\scripts\build.bat' started...
make: Warning: File 'microej/lib/microejruntime.a' has modification time 0.084 s in the future
  LD    gcc/RTOSDemo.axf
make: warning:  Clock skew detected.  Your build may be incomplete.
Execution of script 'C:\Users\fpinel\src\tuto-from-scratch\FreeRTOS\FreeRTOS\Demo\CORTEX_LM3S6965_GCC\microej\scripts\build.bat' done.
=============== [ Completed Successfully ] ===============
```

2021-04-19 07:55 UTC, gjadi-mej commented on Tutorials/tutorialCreateBuildScripts.rst
> +- describe step-by-step how to ceate the build and run scripts both for shell and batch terminals. These scripts automate platform build and firmware execution in QUEMU as presented in :ref:`Create a
```suggestion
- describe step-by-step how to ceate the build and run scripts both for bash and Windows Batch Script files. These scripts automate platform build and firmware execution in QUEMU as presented in :ref:`Create a MicroEJ Firmware From Scratch<create_firmware_from_scratch>` tutorial.
```

2021-04-19 07:56 UTC, gjadi-mej commented on Tutorials/tutorialCreateBuildScripts.rst
> +8. Run the `HelloWorld` application once again. This should print the following result:
```suggestion
8. Build the `HelloWorld` application once again. This should print the following result:
```

2021-04-19 14:18 UTC, frivieremicroej approved these changes

2021-04-19 14:22 UTC, frivieremicroej commented
> Note : after setting Eclipse to run build.bat, my build is successful but I get this warning. I'm not sure how important or not this is :
> 
> ```
> Execution of script 'C:\Users\fpinel\src\tuto-from-scratch\FreeRTOS\FreeRTOS\Demo\CORTEX_LM3S6965_GCC\microej\scripts\build.bat' started...
> make: Warning: File 'microej/lib/microejruntime.a' has modification time 0.084 s in the future
>   LD    gcc/RTOSDemo.axf
> make: warning:  Clock skew detected.  Your build may be incomplete.
> Execution of script 'C:\Users\fpinel\src\tuto-from-scratch\FreeRTOS\FreeRTOS\Demo\CORTEX_LM3S6965_GCC\microej\scripts\build.bat' done.
> =============== [ Completed Successfully ] ===============
> ```

let's ignore this warning because no one else reproduces the issue with WSL2

2021-04-19 14:24 UTC, frivieremicroej commented on Tutorials/tutorialCreateBuildScripts.rst
> +  This script is very simple because our application is just run with QEMU instead of a real hardware. To deploy the application on a device, the script would have to setup and call a flash tool. See
fixed

2021-04-19 14:25 UTC, merged