WIP: Overview PQT
MicroEJ/docs pull request #223
Opened 2021-04-02 16:55 UTC by gjadi-mej

2021-04-07 04:39 UTC, bguedas requested changes

2021-04-07 04:39 UTC, bguedas commented on PlatformDeveloperGuide/platformQualification.rst
> +respective Abstraction Layers.
Don't you mean Adaptation Layers? Is there a resource explaining what's an Adaptation Layers (for instance the glossary)?

2021-04-07 04:39 UTC, bguedas commented on PlatformDeveloperGuide/platformQualification.rst
> +  - Configure the BSP Connection to call the Build and Run Scripts.
I don't think that the first letter of "Connection" should be capitalized. Same for Build and Run Scripts.

2021-04-07 04:39 UTC, bguedas commented on PlatformDeveloperGuide/platformQualification.rst
> +  development and whenever a Low Level APIs implementations is added
"a Low Level API**~~s~~** implementation**~~s~~** is added"

2021-04-07 08:31 UTC, gjadi-mej commented on PlatformDeveloperGuide/platformQualification.rst
> +  development and whenever a Low Level APIs implementations is added
fixed

2021-04-07 08:32 UTC, gjadi-mej commented on PlatformDeveloperGuide/platformQualification.rst
> +  - Configure the BSP Connection to call the Build and Run Scripts.
fixed

2021-04-08 13:42 UTC, bguedas requested changes

2021-04-08 13:42 UTC, bguedas commented on PlatformDeveloperGuide/platformQualification.rst
> +.. figure:: images/overview-platform-qualification.png
In the PQT validation picture, it is not clear that the right part is the legend.

2021-04-08 13:42 UTC, bguedas commented on PlatformDeveloperGuide/platformQualification.rst
> +  - Validate the Low Level APIs implementations
I know how to find this compements because I've already look at the Github repo, but I think that we should add URL to these parts. It would not be necessary if theses components were directly visible at the root of the repo (for instance it contains exactly 3 direrectories which contain the components), but they are not.

These components may be describes in the README and the doc refers to this README section (write once).

2021-04-08 13:42 UTC, bguedas commented on PlatformDeveloperGuide/platformQualification.rst
> +  or changed.  See :ref:`tutoRunTestSuiteOnDevice`.
It is not very clear whether this list enumerates (maybe independant) contexts, or steps to follow/check to validate a platform.

2021-04-13 08:54 UTC, gjadi-mej commented on PlatformDeveloperGuide/platformQualification.rst
> +.. figure:: images/overview-platform-qualification.png
I reworked the figure.

2021-04-13 09:26 UTC, gjadi-mej commented on PlatformDeveloperGuide/platformQualification.rst
> +  - Validate the Low Level APIs implementations
Done

2021-04-13 09:26 UTC, gjadi-mej commented on PlatformDeveloperGuide/platformQualification.rst
> +  or changed.  See :ref:`tutoRunTestSuiteOnDevice`.
I reworked this part.

2021-04-19 15:23 UTC, merged