Feature/m0078 ddg 401 watchdog fl public doc
MicroEJ/docs pull request #237
Opened 2021-04-23 09:19 UTC by emoreac-microej

Watchdog Foundation Library public documentation.

2021-04-26 06:24 UTC, jcourcelmicroej commented on PlatformDeveloperGuide/appendix/llapi.rst
> +The Watchdog API is delivered with a Generic CCO implementation on which the platform must
```suggestion
The Watchdog API is delivered with a Generic C implementation on which the platform must
```

2021-04-26 08:52 UTC, jcourcelmicroej requested changes

2021-04-28 18:51 UTC, jerome-leroux commented on PlatformDeveloperGuide/watchdog.rst
> +			private final int taskID = Watchdog.registerCheckpoint();
Rename `taskID` into `checkpointId`

2021-04-28 18:53 UTC, jerome-leroux commented on PlatformDeveloperGuide/watchdog.rst
> +				// refreshed.
Move the comment above the code.

2021-04-28 18:53 UTC, jerome-leroux commented on PlatformDeveloperGuide/watchdog.rst
> +         LLWATCHDOG_IMPL_checkpoint(checkpoint_id); // Since this is our only checkpoint registered, the watchdog is refreshed.
Move the comment above the code.

2021-04-28 20:44 UTC, jerome-leroux commented on PlatformDeveloperGuide/watchdog.rst
> +         printf("MonitoredTask with ID = %d did watchdog checkpoint!\n\r", checkpoint_id);
Remove all the `\r`. Keep only `\n`.

Actually, on windows it would be `\r\n` (CR LF) but I think it is not necessary when using `printf`.

2021-06-11 09:40 UTC, frivieremicroej commented on PlatformDeveloperGuide/watchdog.rst
> +	<dependency org="com.microej.pack.monitoring" name="monitoring-pack" rev="1.0.0" />
@jcourcelmicroej @jerome-leroux we have to finish our discussion about the naming convention
- watchdog conflict VM watchdog
- monitoring term: already used for vm introspection

After checking, I suggest to reuse the watchdog name as we aim toward building fine grained packs 
- Pack: com.microej.pack.watchdog
- API ej.api.watchdog => 2.0.0 to avoid conflicts

2021-06-11 09:40 UTC, frivieremicroej commented on PlatformDeveloperGuide/watchdog.rst
> +Then, build the platform: right-click on ``-configuration`` project > ``Build module``.
Prefer a more generic link

```suggestion
The Platform must be rebuilt (:ref:`platform_build`)
```

2021-06-11 09:40 UTC, frivieremicroej commented on PlatformDeveloperGuide/watchdog.rst
> +	<dependency changing="true" org="com.microej.clibrary.llimpl" name="watchdog-generic" rev="2.0.0" transitive="false"/>
How do we package this CCO => move to new Github ? 
This is not an abstraction layer but a 'stack' whith has its own AbstractionLayer right ?

2021-06-11 09:40 UTC, frivieremicroej commented on PlatformDeveloperGuide/watchdog.rst
> +Overview
Please add a section about how the mock behaves

2021-06-11 09:40 UTC, frivieremicroej commented on PlatformDeveloperGuide/watchdog.rst
> +Use in C inside the BSP
where are documented the watchdog_helper LLAPIs ?

2021-07-26 09:54 UTC, emoreac-microej commented on PlatformDeveloperGuide/watchdog.rst
> +	<dependency changing="true" org="com.microej.clibrary.llimpl" name="watchdog-generic" rev="2.0.0" transitive="false"/>
That is the generic implementation of the watchdog of the watchdog-timer-llapi.

This generic part also needs a hardware-dependent implementation that can be done directly in the platform or retrieved from another cco such as this module `org="com.microej.clibrary.llimpl" name="watchdog-timer-realtek-amebad"`.

2021-07-26 09:59 UTC, emoreac-microej commented on PlatformDeveloperGuide/watchdog.rst
> +Use in C inside the BSP
This is documented in `llapi.rst` with also the file `LLWATCHDOG_TIMER_impl.h` to explain that `watchdog_timer_helper.h` contains hardware-dependent functions that must be completed by engineers.

2021-09-03 06:31 UTC, frivieremicroej requested changes

2021-09-03 06:31 UTC, frivieremicroej commented on PlatformDeveloperGuide/watchdog-timer.rst
> +	<dependency changing="true" org="com.microej.clibrary.llimpl" name="watchdog-timer-generic" rev="3.0.1" transitive="false"/>
changing and transitive should not be necessary
```suggestion
	<dependency org="com.microej.clibrary.llimpl" name="watchdog-timer-generic" rev="3.0.1"/>
```

2021-09-03 06:31 UTC, frivieremicroej commented on PlatformDeveloperGuide/watchdog-timer.rst
> +	<dependency org="ej.api" name="watchdog-timer" rev="2.0.0" transitive="false"/>
```suggestion
	<dependency org="ej.api" name="watchdog-timer" rev="2.0.0"/>
```

2021-09-03 06:31 UTC, frivieremicroej commented on PlatformDeveloperGuide/watchdog-timer.rst
> +The `WatchdogTimer API Module <https://repository.microej.com/artifacts/ej/hal/watchdog-timer/>`_
this link does not exist

2021-09-06 07:23 UTC, merged