Feature/m0078 ddg 406 migrate sdk release notes
MicroEJ/docs pull request #244
Opened 2021-05-06 06:59 UTC by frivieremicroej

2021-05-06 07:04 UTC, frivieremicroej commented on overview/sdkChangeLog.rst
> +-  Included MicroEJ Studio / SDK ``5.4.0``
Please turn all SDK version to clickable link to the changelog section (everywhere):
Example:
![image](https://user-images.githubusercontent.com/19801840/117255021-7133d500-ae49-11eb-82a5-81efb2b5a3b8.png)

2021-05-06 07:04 UTC, frivieremicroej commented on overview/sdkChangeLog.rst
> +Known Issues
Known issue / misc wrong title level (shoudl not appear in the toc)
![image](https://user-images.githubusercontent.com/19801840/117255151-99bbcf00-ae49-11eb-88b7-d1785488271f.png)

2021-05-06 07:04 UTC, frivieremicroej commented on overview/sdkChangeLog.rst
> +MicroEJ SDK Distribution Changelog
changelog sections shall be moved under release notes
![image](https://user-images.githubusercontent.com/19801840/117255474-fae3a280-ae49-11eb-83ec-1f7cd22c5ec1.png)

2021-05-07 07:13 UTC, frivieremicroej commented
Preview: https://docs.microej.com/en/feature-m0078ddg-406_migrate_sdk_release_notes/overview/sdk.html

2021-05-07 07:36 UTC, tdelhomenie-microej requested changes

2021-05-07 07:36 UTC, tdelhomenie-microej commented on overview/sdk.rst
> +.. include:: sdkMigrationNotes.rst
We should not include the content of these pages in the SDK Overview page, it makes the page really big for an overview. And most of the time when I go to an overview page of a product I don't need the details of the content of each release. Most of the products do it this way.
I would just add links for each one of these inclusions and make them independent pages.

2021-05-07 09:37 UTC, frivieremicroej commented on overview/sdk.rst
> +.. include:: sdkMigrationNotes.rst
thanks it's ok now

2021-05-07 09:38 UTC, merged