Add getting started tutorials step 1  through 17
MicroEJ/docs pull request #257
Opened 2021-06-01 18:20 UTC by VictorMisael

2021-06-02 13:33 UTC, thomasponsmicroej commented
I feel this makes a long tutorial. Will the reader go along all the steps or abort before the end?
I think we could split the content into multiple UI-oriented tutorials (?) @stephanemainchain @jerome-leroux what do you think?

2021-06-02 13:38 UTC, thomasponsmicroej commented on Tutorials/gettingstarted/MJ5minutes.rst
> +#. Select ``File > Import > MicroEJ > Architectures`` click on ``Next>`` and
```suggestion
#. Go to :guilabel:`File` > :guilabel:`Import` > :guilabel:`MicroEJ` > :guilabel:`Architectures`, click on :guilabel:`Import.. ` and

```

2021-06-02 13:45 UTC, thomasponsmicroej commented on Tutorials/gettingstarted/MJ5minutes.rst
> +#. Select ``File > Import > MicroEJ > Architectures`` click on ``Next>`` and
Intended result with the :guilabel:`` 
![image](https://user-images.githubusercontent.com/48557644/120491191-5194bb80-c3b9-11eb-9623-1a3519f2dcab.png)

2021-06-02 14:19 UTC, thomasponsmicroej commented on Tutorials/gettingstarted/Step14.rst
> +.. |imageexpanded| image:: expanded.png
seems like the path is not correct. it makes the doc build fail:

/home/docs/checkouts/readthedocs.org/user_builds/microej-docs/checkouts/feature-getting-started-docs/Tutorials/gettingstarted/Step14.rst:216: WARNING: image file not readable: Tutorials/gettingstarted/expanded.png
/home/docs/checkouts/readthedocs.org/user_builds/microej-docs/checkouts/feature-getting-started-docs/Tutorials/gettingstarted/index.rst: WARNING: document isn't included in any toctree

2021-06-02 14:32 UTC, thomasponsmicroej commented on Tutorials/gettingstarted/Step06.rst
> +- Every class that extends Widget inherits the handleEvent method
```suggestion
- Every class that extends ``Widget`` inherits the ``handleEvent()`` method.

```

Wraps every inlined code, variables, types, methods with ``

2021-06-02 14:37 UTC, thomasponsmicroej commented on Tutorials/gettingstarted/Step06.rst
> +- It is possible to handle events overriding this class on a created sample
```suggestion
- Add custom event handling by overriding the ``handleEvent()`` method of a widget.

```

2021-06-02 14:39 UTC, thomasponsmicroej commented on Tutorials/gettingstarted/Step06.rst
> +- Using as a sample the Button class
```suggestion
- Using the Button class from the ``Widget`` library as a sample:

```

2021-06-02 14:44 UTC, thomasponsmicroej commented on Tutorials/gettingstarted/Step06.rst
> +
Could you highlight what this code actually do? Either with comments in the code or with a small text below the sample.
I guess this is the first time the reader gets in touch with MicroUI events in the tutorial, so we may explain that this code handle Pointer events PRESSED, RELEASED and manage to call the handleClick() method when a click is detected.

2021-06-02 14:50 UTC, thomasponsmicroej commented on Tutorials/gettingstarted/Step06.rst
> +- It's important to know that the widget should be setEnabled(true) in order to events to work
```suggestion
- It's important to note that only widgets that are "enabled" will receive input events. One can enable a widget by calling ``setEnabled(true)``.

```

2021-06-02 14:54 UTC, thomasponsmicroej commented on Tutorials/gettingstarted/Step06.rst
> +
Is there a place where you introduce what are events?
Like in the training a very short introduction could help understanding the principles:
Example: 
```suggestion
- MicroUI generates integer-based events that encode the low-level input type and action. The application can handle these events in the ``handleEvent`` method.

```

2021-06-02 15:02 UTC, thomasponsmicroej commented on Tutorials/gettingstarted/Step06.rst
> +- The handleClick method is where the clickListener is used
```suggestion
- In the ``Button`` class, the click triggers an action which is defined by the registered ``OnClickListener``. The ``handleClick`` method is where the listener is called:

```

2021-06-02 15:03 UTC, thomasponsmicroej commented on Tutorials/gettingstarted/Step06.rst
> +-------------------------------
Same length than title

```suggestion
-------------------------
```

2021-06-02 15:11 UTC, thomasponsmicroej commented on Tutorials/gettingstarted/Step06.rst
> +
+ indicate that we generally end calling super.handleEvent if the event was not handled

2021-06-02 15:13 UTC, thomasponsmicroej commented on Tutorials/gettingstarted/Step06.rst
> +Events are handled in the same way
I don't get the transition with previous section. Do you want to show the button in action (with the OnClickListener)? If so, please rephrase.

2021-06-02 15:14 UTC, thomasponsmicroej commented on Tutorials/gettingstarted/Step06.rst
> +- Using the code created in the Last Step, it is possible to simply add the onClick Listener
```suggestion
- Using the code created in the previous step, let's add a simple action to the button by adding a ``OnClickListener``.
```

2021-06-02 15:16 UTC, thomasponsmicroej commented on Tutorials/gettingstarted/Step06.rst
> +This should be shown in the console
```suggestion
When running the modified sample, this should be shown in the console:
```

2021-06-02 15:19 UTC, thomasponsmicroej commented on Tutorials/gettingstarted/Step07.rst
> +            // handles input events. We'll address this later.
Will the tutorial address that later or is it a remainder of the training? Please remove if not applicable

2021-06-02 15:24 UTC, thomasponsmicroej commented on Tutorials/gettingstarted/Step07.rst
> +    Displayable myDisplayable = new Displayable() {
How does this snippet is supposed to be used? Should the reader paste this in its main() or in a new class?
If it's in the main, maybe put the whole whole main() code.

2021-06-02 15:32 UTC, thomasponsmicroej commented on Tutorials/gettingstarted/Step07.rst
> +Basic drawing/Drawing on screen
I think that drawing images and shapes using MicroUI core features could be part of a dedicated tutorial. This way when you address widget creation you don't have to introduce these APIs: you can just refer to the other tutorial.

2021-06-02 15:36 UTC, thomasponsmicroej commented on Tutorials/gettingstarted/Step07.rst
> +Basic drawing/Drawing on screen
I feel it confusing to address widgets (Flow, Label, Button) and then switch to MicroUI APIs. The reader might wonder what is the point of discussing core APIs for drawing shapes and images when we just discussed using widgets.

2021-06-02 15:39 UTC, thomasponsmicroej commented on Tutorials/gettingstarted/Step07.rst
> +   |image0|
Conform to the image import:
example:
.. image:: images/myImage.png
        :align: center

2021-06-02 15:48 UTC, thomasponsmicroej commented on Tutorials/gettingstarted/Step07.rst
> +Geometric objects
```suggestion
Drawing basic shapes
```

2021-06-02 15:49 UTC, thomasponsmicroej commented on Tutorials/gettingstarted/Step07.rst
> +-  It is also possible to also draw geometric objects using Displayable
This is not Displayable that allows to draw shapes but the MicroUI APIs of the Painter class.

2021-06-02 15:50 UTC, thomasponsmicroej commented on Tutorials/gettingstarted/Step07.rst
> +       Painter.drawLine(g, 0, 0, 100, 50);
comment what it does, the reader does not know the API

2021-06-02 15:51 UTC, thomasponsmicroej commented on Tutorials/gettingstarted/Step07.rst
> +Images can also be set
```suggestion
Drawing images
```

2021-06-02 15:51 UTC, thomasponsmicroej commented on Tutorials/gettingstarted/Step07.rst
> +-  Adding the image as shown in step 3
```suggestion
-  Drawing the image as shown in step 3:
```

2021-06-02 15:52 UTC, thomasponsmicroej commented on Tutorials/gettingstarted/Step07.rst
> +       Image image = Image.getImage("/images/mj.png");
rename image to best describe what it represent

2021-06-02 15:53 UTC, thomasponsmicroej commented on Tutorials/gettingstarted/Step07.rst
> +       // draws the image at x,y coordinates (50, 50).
did you mention somewhere that the x,y origin is the top-left corner of the screen. Maybe worth mentionning.
```suggestion
       // draws the image at x,y coordinates (150, 50).
```

2021-06-02 15:55 UTC, thomasponsmicroej commented on Tutorials/gettingstarted/Step07.rst
> +       ShapePainter.drawThickFadedLine(g, 20, 20, 100, 80, 10, 6, Cap.ROUNDED, Cap.PERPENDICULAR);
Please describe the APIs shortly in a comment for example

2021-06-02 15:56 UTC, thomasponsmicroej commented on Tutorials/gettingstarted/Step07.rst
> +-  Drawing thick shapes is very straight forward
Avoid "it's easy", 'its simple" etc. as mentionned by the Google doc guide: https://developers.google.com/style/tone?hl=en#some-things-to-avoid-where-possible

2021-06-04 16:11 UTC, VictorMisael commented on Tutorials/gettingstarted/Step14.rst
> +.. |imageexpanded| image:: expanded.png
this was fixed in the newest commit

2021-06-07 06:25 UTC, frivieremicroej reviewed
Made a first pass only on the "setup"

2021-06-07 06:25 UTC, frivieremicroej commented on Tutorials/gettingstarted/MJ5minutes.rst
> +Start your first MicroEJ GUI application in 15 Minutes
About the general toc

![image](https://user-images.githubusercontent.com/19801840/120968215-dc363b80-c768-11eb-8b0e-b338095b272d.png)

- why introducing a Getting Started level ?
- all other titles should be under `Start your first MicroEJ GUI application in 15 Minutes`

I expect `Tutorials/tutorialStartFirstGUIApplicationIn15Minutes.rst`

2021-06-07 06:25 UTC, frivieremicroej commented on Tutorials/gettingstarted/MJ5minutes.rst
> +- A Java™ Runtime Environment 8 is needed on your host computer for running MICROEJ SDK 21.03. [Download Java™ Runtime Environments]
```suggestion
- A Java™ Runtime Environment 8 is needed on your host computer for running MICROEJ SDK Dist. 21.03. [Download Java™ Runtime Environments]

```

2021-06-07 06:25 UTC, frivieremicroej commented on Tutorials/gettingstarted/MJ5minutes.rst
> +#. Select the :guilabel:`File` > :guilabel:`Import` > :guilabel:`General` > :guilabel:`Existing Projects into`
update to the github platform https://github.com/MicroEJ/Platform-STMicroelectronics-STM32F7508-DK

2021-06-07 06:25 UTC, frivieremicroej commented on Tutorials/gettingstarted/Step01.rst
> +   **Run>Run As>MicroEJ Application> Select the device you added**
use guilabel

2021-06-07 06:25 UTC, frivieremicroej commented on Tutorials/gettingstarted/MJ5minutes.rst
> +#. Inside the **stm32f7508_freertos-configuration** project, open the
use guilabel

2021-06-08 13:42 UTC, VictorMisael commented on Tutorials/gettingstarted/Step06.rst
> +Events are handled in the same way
Yes, the goal is to show the Button in action

2021-06-08 14:03 UTC, VictorMisael commented on Tutorials/gettingstarted/Step07.rst
> +            // handles input events. We'll address this later.
This was addressed on step 6, Will be removed

2021-06-08 14:06 UTC, VictorMisael commented on Tutorials/gettingstarted/Step07.rst
> +    Displayable myDisplayable = new Displayable() {
This should be pasted on main

2021-06-16 14:47 UTC, apineau-microej commented on Tutorials/gettingstarted/index.rst
> +Getting Started
It could be good to mention that this tutorial is about UI (rename it 'Getting Started with UI' for example)

2021-06-16 15:21 UTC, apineau-microej commented on Tutorials/gettingstarted/MJ5minutes.rst
> +   |image0|
Could you name the images with a meaningful name like tuto_ui_import_architecture.png etc. ?

2021-06-16 15:24 UTC, apineau-microej commented on Tutorials/gettingstarted/MJ5minutes.rst
> +#. First, Go to :guilabel:`File` > :guilabel:`New` > :guilabel:`Standalone Project`
```suggestion
#. First, Go to :guilabel:`File` > :guilabel:`New` > :guilabel:`Standalone Application Project`

```

2021-06-16 15:25 UTC, apineau-microej commented on Tutorials/gettingstarted/MJ5minutes.rst
> +#. The Project Structure should look like this
```suggestion
#. The Project Structure should look like this:
```

2021-06-16 15:26 UTC, apineau-microej commented on Tutorials/gettingstarted/MJ5minutes.rst
> +- A Java™ Runtime Environment 8 is needed on your host computer for running MICROEJ SDK Dist. 21.03. [Download Java™ Runtime Environments]
n the prerequisites, a reader should know about the reference documentation (ideally a subject is documented with reference doc + tuto).
Here it is worth mentioning that one should have read the Graphical User Interface section of the App dev Guide: https://docs.microej.com/en/latest/ApplicationDeveloperGuide/UI/ui.html

2021-06-16 15:29 UTC, apineau-microej commented on Tutorials/gettingstarted/MJ5minutes.rst
> +- instructions to download import and launch Demo Widget
Where are instructions the to download import and launch Demo Widget?

2021-06-16 15:37 UTC, apineau-microej commented on Tutorials/gettingstarted/Step01.rst
> +#. To add a label, just instantiate a ´´Label`` object and add it to the
```suggestion
#. To add a label, just instantiate a ``Label`` object and add it to the
```

2021-06-16 16:41 UTC, VictorMisael commented on Tutorials/gettingstarted/MJ5minutes.rst
> +   import all available Eclipse projects,and then click **Finish**
No, I just imported everything to make it as simple as possible

2021-06-17 06:47 UTC, apineau-microej commented on Tutorials/gettingstarted/MJ5minutes.rst
> +#.  Download the installer package corresponding to your host computer OS `MicroEJ SDK <https://repository.microej.com/packages/SDK/21.03/MicroEJ-SDK-Installer-Win64-21.03.exe>`__
Maybe link to the install page rather than direct link to the sdk because the link could be soon be deprecated.
https://repository.microej.com/packages/SDK/? https://developer.microej.com/get-started/?

2021-06-17 06:49 UTC, apineau-microej commented on Tutorials/gettingstarted/Step01.rst
> +Desktop
Title is not very explicit. It should describe what the section addresses. i.e "Specify the Application's Desktop"?

2021-06-17 06:50 UTC, apineau-microej commented on Tutorials/gettingstarted/MJ5minutes.rst
> +   MicroEJ platform configuration file, click on the link Build Platform
Maybe ensure that the platform is correctly built before going further? i.e the console printed BUILD SUCCESSFUL or the workspace contains the platform folder STM32F7508-SingleApp-CM7hardfp_IAR83-1.2.0

2021-06-17 06:52 UTC, apineau-microej commented on Tutorials/gettingstarted/Step01.rst
> +   It may contain only a single widget, and at most one desktop is shown
`only a single widget`: yes it's true but this widget is the root widget of all the widget tree. I feel this wording is a bit reductive and could lead one to believe that there is one single widget at a time on the display.
The Desktop holds the widget tree/hierarchy. (at this point we have not introduced the Container yet)

2021-06-17 06:53 UTC, apineau-microej commented on Tutorials/gettingstarted/Step01.rst
> +#. Desktop automatically triggers the layout and rendering phases for
This automatic layout and rendering is done when the Desktop is requested to show.

2021-06-17 06:57 UTC, apineau-microej commented on Tutorials/gettingstarted/Step02.rst
> +Using Canvas
Could you make it clear what is the purpose here? Trying multiple containers of the widget library to see the differences/options?
The reader may not get the point of switching to a canvas. He may wonder the benefit of using a canvas over a flow.
I feel this is just an example of various containers avalibale but it may not be clear for new comers.

2021-06-17 06:58 UTC, apineau-microej commented on Tutorials/gettingstarted/Step02.rst
> +         canvas.addChild(label2, 0, 15, Widget.NO_CONSTRAINT, Widget.NO_CONSTRAINT);
To show that the canvas allows to position widgets freely, why not using different x coordinates for the widgets?
Here both widgets are displayed vertically like in a list.

2021-06-17 07:00 UTC, apineau-microej commented on Tutorials/gettingstarted/Step03.rst
> +   -  Combinators (base on relationships)
```suggestion
   -  Combinators (based on relationships)
```

2021-06-17 07:05 UTC, apineau-microej commented on Tutorials/gettingstarted/Step03.rst
> +         EditableStyle style = css.getSelectorStyle(new TypeSelector(Label.class));
Here you instantiate the `CascadingStylesheet` with name `stylesheet` but you use the name `css` afterward. I think `css` should be replaced by `stylesheet` every where in this step

2021-06-17 07:08 UTC, apineau-microej commented on Tutorials/gettingstarted/Step03.rst
> +           style.setMargin(new UniformOutline(4));
Maybe set an oversized margin? the visual difference is not very clear with 4pw of margin. Same for padding

2021-06-17 07:23 UTC, apineau-microej commented on Tutorials/gettingstarted/Step04.rst
> +Create two packages on the Resources folder, one named list and another
- copy/paste an image (or the mj image)
- create a *.images.list file

2021-06-17 07:58 UTC, apineau-microej commented on Tutorials/gettingstarted/Step05.rst
> +           Flow flow = new Flow(LayoutOrientation.VERTICAL);
Why not sticking to the same container from the beginning? canvas or flow.

2021-06-17 09:32 UTC, apineau-microej commented on Tutorials/gettingstarted/Step07.rst
> +    Display.getDisplay().requestShow(myDisplayable);
```suggestion
        Display.getDisplay().requestShow(myDisplayable);

```

2021-06-17 09:33 UTC, apineau-microej commented on Tutorials/gettingstarted/Step07.rst
> +       Displayable myDisplayable = new Displayable() {
```suggestion
       MicroUI.start();
       Displayable myDisplayable = new Displayable() {
```

2021-06-17 09:39 UTC, apineau-microej commented on Tutorials/gettingstarted/Step07.rst
> +-  Drawing the image as shown in step 3:
In step 4 (not 3) why use an ImageWidget, I don't think it's useful to mention this step here

2021-06-17 12:44 UTC, apineau-microej commented on Tutorials/gettingstarted/Step08.rst
> +Animation
This step is ok for me but maybe something more visual could be good for an animation tutorial (i.e. a shape moving)

2021-06-17 12:45 UTC, apineau-microej commented on Tutorials/gettingstarted/Step08.rst
> +Animation
Ok I see that we create a progress bar in the next step so that's ok for me

2021-06-17 12:51 UTC, apineau-microej commented on Tutorials/gettingstarted/Step09.rst
> +-  Using the code made in Step 8, doing the modifications below, it is
I think we should write `Using the code made in [link to previous step` instead of `Step 8` as the user doesn't know what is step 8 (he can only see the step number in the url)

2021-06-17 13:03 UTC, apineau-microej commented on Tutorials/gettingstarted/Step10.rst
> +-  Fonts, just like images, must be declared at the \yourapp.fonts.list
```suggestion
-  Fonts, just like images, must be declared in a ``*.fonts.list`` file 
```

2021-06-17 13:07 UTC, apineau-microej commented on Tutorials/gettingstarted/Step10.rst
> + It is important to have the font that you want installed at the system already
```suggestion
 It is important to have the font that you want installed on your system already
```

2021-06-17 13:10 UTC, apineau-microej commented on Tutorials/gettingstarted/Step10.rst
> +-  To add the font, you simple change the font on a StyleSheet
```suggestion
-  To add the font, you must change the font in the StyleSheet

```

2021-06-17 13:12 UTC, apineau-microej commented on Tutorials/gettingstarted/Step10.rst
> +   If you are using a latin based alphabet, just leave the settings as they are and click finish
You could talk about size and baseline, on the image the `MS Gothic` font is selected and the size and baseline are not properly set

2021-06-17 13:14 UTC, apineau-microej commented on Tutorials/gettingstarted/Step10.rst
> +   Normally **Resources-> fonts**
In the previous step you would have written ``Resources`` -> ``fonts``

2021-06-17 13:28 UTC, apineau-microej commented on Tutorials/gettingstarted/Step11.rst
> +-  Using as an example the code used before, with the new font, adding
It seems the default font is used on the image

2021-06-17 13:50 UTC, apineau-microej commented on Tutorials/gettingstarted/Step11.rst
> +   }
Maybe move this code before the image

2021-06-17 13:58 UTC, apineau-microej commented on Tutorials/gettingstarted/Step12.rst
> +-  As explained in step 9, it is possible to create our own widget by
Same as before for `step 9`

2021-06-17 14:07 UTC, apineau-microej commented on Tutorials/gettingstarted/Step12.rst
> +- And it should look like this:
It would be nice if the images were centered in the circles

2021-06-18 07:04 UTC, apineau-microej commented on Tutorials/gettingstarted/Step13.rst
> +    import com.mycompany.pos.Labels;
```suggestion
    import com.mycompany.myapp.Labels;
```

2021-06-18 07:07 UTC, apineau-microej commented on Tutorials/gettingstarted/Step13.rst
> +|image1|
Images show that another font than the default one is used, but in the code no other font is defined. It would be better to use the default font on the images as some letters are cropped here (M**y** label 1)

2021-06-18 07:26 UTC, apineau-microej commented on Tutorials/gettingstarted/Step14.rst
> +    style.setColor(DemoColors.DEFAULT_FOREGROUND);
We have no `DemoColors` in the project

2021-06-18 07:28 UTC, apineau-microej commented on Tutorials/gettingstarted/Step14.rst
> +        Scroll scroll = new Scroll(LayoutOrientation.VERTICAL, animator);
The `Scroll` class added before has no constructor with `Animator` field, it seems to work well when removing `animator`

2021-06-18 08:14 UTC, apineau-microej commented on Tutorials/gettingstarted/Step15.rst
> +- All the code needed for this tutorial can be found `here <link>`__.
dead link

2021-06-18 08:15 UTC, apineau-microej commented on Tutorials/gettingstarted/Step15.rst
> +Transitions
Maybe this step could be before "Expandable Widget" as we use the `QuadEaseOutFunction`

2021-06-18 08:17 UTC, apineau-microej commented on Tutorials/gettingstarted/Step16.rst
> +    Button b = new Button("TESTE");
```suggestion
    Button b = new Button("Test");
```

2021-06-18 08:18 UTC, apineau-microej commented on Tutorials/gettingstarted/Step16.rst
> +.. code:: java
Maybe move this code snippet after we define the popup code

2021-06-18 08:20 UTC, apineau-microej commented on Tutorials/gettingstarted/Step16.rst
> +- Finally, a RenderPolicy will be used for this desktop
Explain what a RenderPolicy is

2021-06-18 08:36 UTC, apineau-microej commented on Tutorials/gettingstarted/Step16.rst
> +The popup code
- Maybe you can add the final code of `Popup`
- Is `MyRenderPolicy` an inner class of `Popup`?
- `Popup` overrides Desktop's `layOut()` but it is a package method so `Popup` should be in `ej.mwt` is it the right solution?

2021-06-18 08:43 UTC, apineau-microej commented on Tutorials/gettingstarted/Step17.rst
> +Menu
For this step maybe we could have a simple example for the user to code. It's a bit weird to me to have 2 code snippets and then say to the user to see the Demo Widget code

2021-06-18 17:04 UTC, VictorMisael commented on Tutorials/gettingstarted/Step15.rst
> +- All the code needed for this tutorial can be found `here <link>`__.
This should link to a repo with the code, for now it's private

2021-07-05 16:09 UTC, VictorMisael commented on Tutorials/gettingstarted/Step07.rst
> +       Image image = Image.getImage("/images/mj.png");
Sure

2021-07-05 18:48 UTC, VictorMisael commented on Tutorials/gettingstarted/Step13.rst
> +|image1|
It's the one used in the step before this one, as I thought this as a sequence

2021-07-06 16:39 UTC, apoudret-microej commented on Tutorials/gettingstarted/Step05.rst
> +-  -  Let's add a button to the application, with the MicroEJ logo as background.
fix double `-`

2021-07-06 16:39 UTC, apoudret-microej commented on Tutorials/gettingstarted/Step05.rst
> +       EditableStyle style = css.getSelectorStyle(new ClassSelector(BUTTON));;
fix double `;`

2021-07-06 16:39 UTC, apoudret-microej commented on Tutorials/gettingstarted/Step05.rst
> +       public static void main(String[] args) {
fix indentation

2021-07-06 16:39 UTC, apoudret-microej commented on Tutorials/gettingstarted/Step08.rst
> +        @Override public boolean tick(longcurrentTimeMillis) {
fix missing space after `long`

2021-07-06 16:39 UTC, apoudret-microej commented on Tutorials/gettingstarted/Step08.rst
> +        @Override public boolean tick(longcurrentTimeMillis) {
add missing `int tick = 0;` line

2021-07-06 16:39 UTC, apoudret-microej commented on Tutorials/gettingstarted/Step10.rst
> +   The font used was FiraCode
this seems irrelevant, i suggest to remove this note

2021-07-06 16:39 UTC, apoudret-microej commented on Tutorials/gettingstarted/Step10.rst
> +   Don't forget to add the Style to the Desktop
the stylesheet

2021-07-06 16:39 UTC, apoudret-microej commented on Tutorials/gettingstarted/Step11.rst
> +   |image0|
fix formatting (remove indentation otherwise `|image0| ` is part of the code block)

2021-07-06 16:39 UTC, apoudret-microej commented on Tutorials/gettingstarted/Step12.rst
> +    public ContactWidget(String contactname, Image img) {
contactname => contactName
img => image

2021-07-06 16:39 UTC, apoudret-microej commented on Tutorials/gettingstarted/Step12.rst
> +        this.cname = contactname;
cname => contactName

2021-07-06 16:39 UTC, apoudret-microej commented on Tutorials/gettingstarted/Step12.rst
> +        this.img = img;
img => image

2021-07-06 16:39 UTC, apoudret-microej commented on Tutorials/gettingstarted/Step12.rst
> +        // TODO Auto-generated method stub
remove this comment

2021-07-06 16:39 UTC, apoudret-microej commented on Tutorials/gettingstarted/Step12.rst
> +        // TODO Auto-generated method stub
remove this comment

2021-07-06 16:39 UTC, apoudret-microej commented on Tutorials/gettingstarted/Step12.rst
> +        size.setSize(width, (int) (height * 2.5));
width should rather be `image width + string width`
and height should rather be `max(image height, string height)`

2021-07-06 16:39 UTC, apoudret-microej commented on Tutorials/gettingstarted/Step13.rst
> +- Import the interface set in the nls.List file
i think this its not necessary to explain to import the class

2021-07-07 09:15 UTC, apoudret-microej commented on Tutorials/gettingstarted/Step16.rst
> +- The usage should look liken this
liken => like

2021-07-07 09:15 UTC, apoudret-microej commented on Tutorials/gettingstarted/Step16.rst
> +    MicroUI.start();
fix indentation

2021-07-07 09:15 UTC, apoudret-microej commented on Tutorials/gettingstarted/Step16.rst
> +    /**
remove this empty javadoc block

2021-07-07 09:15 UTC, apoudret-microej commented on Tutorials/gettingstarted/Step16.rst
> +    public MyRenderPolicy(Desktop desktop) {
fix indentation

2021-07-07 12:22 UTC, VictorMisael commented on Tutorials/gettingstarted/Step07.rst
> +Basic drawing/Drawing on screen
So this step may be an single tutorial ?

2021-07-07 13:42 UTC, VictorMisael commented on Tutorials/gettingstarted/MJ5minutes.rst
> +#. Download and unzip the platform sources for
Sure, Thanks

2021-07-14 18:03 UTC, VictorMisael commented on Tutorials/gettingstarted/Step13.rst
> +- Import the interface set in the nls.List file
I actually haven't tested to see if it automatically imports classes on the nls file

2021-07-14 18:15 UTC, VictorMisael commented on Tutorials/gettingstarted/Step03.rst
> +           style.setMargin(new UniformOutline(4));
I put a oversized sample in the code

2021-07-14 21:21 UTC, VictorMisael commented on Tutorials/gettingstarted/Step12.rst
> +- And it should look like this:
I feel that too, but I had some issues trying to perfectly center it

2021-07-14 21:22 UTC, VictorMisael commented on Tutorials/gettingstarted/Step12.rst
> +- And it should look like this:
I tried to avoid adding values and just multiplyed all

2021-07-14 21:25 UTC, VictorMisael commented on Tutorials/gettingstarted/Step12.rst
> +        size.setSize(width, (int) (height * 2.5));
Thank you

2021-07-14 21:36 UTC, VictorMisael commented on Tutorials/gettingstarted/Step11.rst
> +-  Using as an example the code used before, with the new font, adding
Removed this quote,thanks

2021-07-14 21:47 UTC, VictorMisael commented on Tutorials/gettingstarted/Step15.rst
> +Transitions
Just reorder on the index then?

2021-07-16 11:48 UTC, frivieremicroej commented on Tutorials/gettingstarted/MJ5minutes.rst
> +Start your first MicroEJ GUI application in 15 Minutes
Resolved but no explanations ?

At least rename the folder to follow the naming convention of other tutorials

`Tutorials/gettingstarted/` => `Tutorials/getStartedWithGUI`

2021-07-16 12:02 UTC, frivieremicroej commented on Tutorials/gettingstarted/tutorialStartFirstGUIApplicationIn15Minutes.rst
> +   |image0|
Center the images and screenshots everywhere
```
    :align: center

```

2021-07-16 12:02 UTC, frivieremicroej commented on Tutorials/gettingstarted/MJ5minutes.rst
> +#. Select the :guilabel:`File` > :guilabel:`Import` > :guilabel:`General` > :guilabel:`Existing Projects into`
Please comment. Is it postponed ?

2021-07-16 12:11 UTC, frivieremicroej requested changes
2nd pass

2021-07-16 12:11 UTC, frivieremicroej commented on Tutorials/gettingstarted/tutorialStartFirstGUIApplicationIn15Minutes.rst
> +#. To get your UID from the MicroEJ SDK, select :guilabel:`Window` > :guilabel:`Preferences` > :guilabel:`MicroEJ` > :guilabel:`Architectures` > :guilabel:`click on one of the available architectures
![image](https://user-images.githubusercontent.com/19801840/125944516-2a64f9b5-dd3a-4575-aac2-dbf910bd2d9d.png)

2021-07-16 12:11 UTC, frivieremicroej commented on Tutorials/gettingstarted/tutorialStartFirstGUIApplicationIn15Minutes.rst
> +- `MicroEJ SDK <https://github.com/MicroEJ/Demo-Widget>`__
Put an appropriate name to the link
![image](https://user-images.githubusercontent.com/19801840/125944642-9314a585-f41d-4ce7-a104-06c8fcda4255.png)

Such as: `Widget Demo GitHub Repository`

2021-07-16 12:11 UTC, frivieremicroej commented on Tutorials/gettingstarted/Step01.rst
> +#. To run your code on the simulator, left click on the Project Go To
wrong rendering
![image](https://user-images.githubusercontent.com/19801840/125944764-51dae7b3-8063-4c73-a7c0-0c4779661ea1.png)

2021-07-16 12:11 UTC, frivieremicroej commented on Tutorials/gettingstarted/Step01.rst
> +#. To run your code on the simulator, left click on the Project Go To
glossary term (see an other comment)
```suggestion
#. To run your code on the Simulator, left click on the Project Go To
```

2021-07-16 12:11 UTC, frivieremicroej commented on Tutorials/gettingstarted/Step01.rst
> +#. To run the code go to the **Main.java** file and right click it, hover over Run As and select MicroEJ Application
guillabel

![image](https://user-images.githubusercontent.com/19801840/125944924-c2ec2487-dcbb-4070-9f30-c736ab7b5bfb.png)

2021-07-16 12:11 UTC, frivieremicroej commented on Tutorials/index.rst
> +   gettingstarted/index
Overall, here is a summary of the main rendering issues I noticed:
- Glossary terms are case sensitive
- Titles with uppercase (most are ok, but there is still a whole pass to fix remaining ones)
- Images centered
- Window screenshots cropped to exact window bounds
- Still missing some GUIlabels + lots of them are not correctly rendered

2021-07-16 12:14 UTC, frivieremicroej requested changes

2021-07-16 12:14 UTC, frivieremicroej commented on Tutorials/gettingstarted/Step16.rst
> +    public static void main(String[] args) {
For some reason, indentation is lost

![image](https://user-images.githubusercontent.com/19801840/125945612-005d8e61-2902-446a-81a2-eb5666749ff4.png)

2021-07-16 12:14 UTC, frivieremicroej commented on Tutorials/gettingstarted/Step16.rst
> +    @Override
Review indentation 
![image](https://user-images.githubusercontent.com/19801840/125945743-52deb051-c88a-4e0a-92a6-daf502098e2a.png)

2021-07-16 12:17 UTC, frivieremicroej requested changes

2021-07-16 12:17 UTC, frivieremicroej commented on Tutorials/gettingstarted/index.rst
> +Getting Started With UI
```suggestion
Getting Started With GUI
```

2021-07-16 12:17 UTC, frivieremicroej commented on Tutorials/gettingstarted/tutorialStartFirstGUIApplicationIn15Minutes.rst
> +   - `Github <https://github.com/MicroEJ/Platform-STMicroelectronics-STM32F7508-DK>`__
Why just adding Github link ? It is expected to replace the full packaging zip files

2021-07-19 16:54 UTC, VictorMisael commented on Tutorials/gettingstarted/tutorialStartFirstGUIApplicationIn15Minutes.rst
> +.. |image0| image:: images/architeture.PNG
I had some trouble doing it, but it is done

2021-07-19 16:56 UTC, VictorMisael commented on Tutorials/index.rst
> +   gettingstarted/index
I added some spacing on gui labels, still pending to see how it renders

2021-07-20 15:16 UTC, VictorMisael commented on Tutorials/gettingstarted/MJ5minutes.rst
> +#. Select the :guilabel:`File` > :guilabel:`Import` > :guilabel:`General` > :guilabel:`Existing Projects into`
Updated

2021-07-20 15:24 UTC, VictorMisael commented on Tutorials/gettingstarted/Step16.rst
> +    public static void main(String[] args) {
I don't know why this is,maybe if I make again, and reupload should fix

2021-07-20 15:25 UTC, VictorMisael commented on Tutorials/gettingstarted/Step16.rst
> +    public static void main(String[] args) {
This is how it looks on my machine 
![image](https://user-images.githubusercontent.com/84846071/126351310-8de1fc86-50b7-47da-97e1-5ad7576d46ba.png)

2021-07-20 15:34 UTC, VictorMisael commented on Tutorials/gettingstarted/Step16.rst
> +    public static void main(String[] args) {
I redone Identation in this code

2021-08-05 12:47 UTC, seonmej requested changes

2021-08-05 12:47 UTC, seonmej commented on Tutorials/gettingstarted/Step14.rst
> +- All the code needed for this tutorial can be found `here <link>`__.
Missing link.

2021-08-05 12:47 UTC, seonmej commented on Tutorials/gettingstarted/Step14.rst
> +Transitions
For me the followings steps (14, 15, 16, 17) should be elsewhere. They are too complex. I don't think they really help the customer to learn something.
What could be interesting (from steps 14 and 15) is to show how to use Motion and MotionAnimation. But with a simpler example.

2021-08-05 12:47 UTC, seonmej commented on Tutorials/gettingstarted/Step16.rst
> +Popup
Not sure it is the best way to implement a popup:
    - we cannot animate the popup (or the desktop below will be erased)
    - the desktop below cannot be updated (if it contains the time for example)
    - my solution in another project is: having a dedicated container at the root of the desktop. It contains the standard content of the application and a popup. When we show/hide the popup, an animation is started for the popup to slide down/up. The PointerEventDispatcher is subclassed to dispatch the events only to the popup when there is one. The style is updated to darken the application below the popup.

2021-08-05 12:47 UTC, seonmej commented on Tutorials/gettingstarted/Step17.rst
> +Menu
I totally agree.

2021-08-05 12:47 UTC, seonmej commented on Tutorials/gettingstarted/Step07.rst
> +Basic Drawing on Screen
I think that this step should one of the first. It feels weird to present all widgets stuff and now showing how to use pure MicroUI.

2021-08-05 12:52 UTC, VictorMisael commented on Tutorials/gettingstarted/Step14.rst
> +- All the code needed for this tutorial can be found `here <link>`__.
Hi sebastian, I send the repo with the code related in the tutorial, I need to upload this code to a microej repo

2021-08-05 13:42 UTC, VictorMisael commented on Tutorials/gettingstarted/Step07.rst
> +Basic Drawing on Screen
I found the widget library easier because it already has all the facilities to do UI stuff, So I thought explaining microUI is a step ahead of the widget library

2021-08-05 13:46 UTC, VictorMisael commented on Tutorials/gettingstarted/Step14.rst
> +- All the code needed for this tutorial can be found `here <link>`__.
@gharelMicroEJ Did you upload the source code to github?

2021-08-05 13:47 UTC, VictorMisael commented on Tutorials/gettingstarted/Step14.rst
> +Transitions
@gharelMicroEJ @thomasponsmicroej Should we remove from the big tutorial to decide later?

2021-08-05 15:30 UTC, seonmej commented on Tutorials/gettingstarted/Step07.rst
> +Basic Drawing on Screen
Maybe it is not necessary to show the usage of a Displayable in this tutorial?
But keeping the drawing part in a widget? So merging this step with the step 9. What do you think?

2021-08-05 18:28 UTC, VictorMisael commented on Tutorials/gettingstarted/Step07.rst
> +Basic Drawing on Screen
It's a good idea, it also makes the whole tutorial a little shorter

2021-08-09 13:37 UTC, merged