Feature/m0127 cc 629 tutorial non blocking sni
MicroEJ/docs pull request #261
Opened 2021-06-09 16:02 UTC by acolleux-microej

2021-06-09 22:22 UTC, jerome-leroux requested changes

2021-09-27 15:18 UTC, frivieremicroej requested changes

2021-09-27 15:18 UTC, frivieremicroej commented on Tutorials/index.rst
> +   tutorialSNINonBlockingCall
```suggestion
   tutorialImplementABlockingNativeMethodWithSNI
```

2021-09-27 15:18 UTC, frivieremicroej commented on Tutorials/tutorialSNINonBlockingCall.rst
> +Example code
Please review titles everywhere
```suggestion
Example Code
```

2021-09-27 15:18 UTC, frivieremicroej commented on Tutorials/tutorialSNINonBlockingCall.rst
> +.. image:: ./images/tuto_sni_non_blocking_call_blocking_case.PNG
Please submit all schematics to design review (especially colors review: light-orange background colors/ yellow font...)

2021-09-27 16:44 UTC, jerome-leroux commented on Tutorials/index.rst
> +   tutorialSNINonBlockingCall
done

2021-09-27 16:45 UTC, jerome-leroux commented on Tutorials/tutorialSNINonBlockingCall.rst
> +Example code
done

2021-09-27 16:45 UTC, jerome-leroux commented on Tutorials/tutorialSNINonBlockingCall.rst
> +.. image:: ./images/tuto_sni_non_blocking_call_blocking_case.PNG
@acolleux-microej: can you do that?

2021-10-20 13:39 UTC, acolleux-microej commented on Tutorials/tutorialSNINonBlockingCall.rst
> +.. image:: ./images/tuto_sni_non_blocking_call_blocking_case.PNG
@jerome-leroux @frivieremicroej I updated the schematics

2021-11-22 12:42 UTC, frivieremicroej approved these changes
approved once glossary terms are commited

2021-11-22 12:42 UTC, frivieremicroej commented on Tutorials/tutorialImplementABlockingNativeMethodWithSNI.rst
> +The audience for this document is Platform developers who want to implement abstraction layer interfaces.
please perform a whole pass on glossary terms
```suggestion
The audience for this document is Platform developers who want to implement Abstraction Layer interfaces.
```

2021-11-22 12:42 UTC, frivieremicroej commented on Tutorials/tutorialImplementABlockingNativeMethodWithSNI.rst
> +The following document assumes the reader already has a setup ready to run a MicroEJ application on a target device.
```suggestion
The following document assumes the reader already has a setup ready to run a MicroEJ Standalone Application on a target device.
```

2021-11-22 12:42 UTC, frivieremicroej commented on Tutorials/tutorialImplementABlockingNativeMethodWithSNI.rst
> +Let's start with a MicroEJ Application that calls a blocking Java method implemented in C.
```suggestion
Let's start with a MicroEJ Standalone Application that calls a blocking Java method implemented in C.
```

2021-11-23 16:57 UTC, merged