Feature/bounds check label
MicroEJ/docs pull request #267
Opened 2021-06-14 16:51 UTC by VictorMisael

2021-06-18 09:20 UTC, apineau-microej commented on Tutorials/tutorialBoundsCheck.rst
> +Inside of the method ,get the Font from the Style that the widget is using, and then, get the Font
```suggestion
Inside of the method, get the Font from the Style that the widget is using, and then, get the Font 
```

2021-06-18 09:21 UTC, apineau-microej commented on Tutorials/tutorialBoundsCheck.rst
> +        canvas.addChild(new MyLabel("Teste"), 15, 0, 15, 10);
I think all the strings should be in english

2021-06-18 11:06 UTC, frivieremicroej requested changes

2021-06-18 11:06 UTC, frivieremicroej commented on Tutorials/index.rst
> +   tutorialBoundsCheck
I don't this kind of documentation shall be put in the general purpose Tutorials chapter (moreover if it is a tutorial it should at least start with a verb).

@seonmej @thomasponsmicroej I suggest to introduce a new section in the ADG
in https://docs.microej.com/en/latest/ApplicationDeveloperGuide/UI/Widgets/index.html

Section Name TDB: something like: GUI Tips, Advanced Techniques, Usual Practices, Resolved Problems...

2021-06-18 15:17 UTC, seonmej commented on Tutorials/tutorialBoundsCheck.rst
> +        final int labelWidth = this.getContentBounds().getWidth();
```suggestion
        final int contentWidth = getContentBounds().getWidth();
```

2021-06-18 15:18 UTC, seonmej commented on Tutorials/tutorialBoundsCheck.rst
> +        if (stringWidth > labelWidth) {
```suggestion
        if (stringWidth > contentWidth) {
```

2021-06-18 15:18 UTC, seonmej commented on Tutorials/tutorialBoundsCheck.rst
> +            System.err.println("The text size is greater than the Widget content Width!");
```suggestion
            System.err.println("The text size is greater than the widget content width!");
```

2021-06-18 15:24 UTC, seonmej commented on Tutorials/tutorialBoundsCheck.rst
> +- Using canvas, it's possible to set constraints to each added widget
```suggestion
The check can be easily validated by putting the widget in a canvas and setting its bounds manually (a little shorter than the text size).
```

2021-06-18 15:25 UTC, seonmej commented on Tutorials/tutorialBoundsCheck.rst
> +- and the console should show this
```suggestion
The console should show this:
```

2021-06-18 15:27 UTC, seonmej commented on Tutorials/tutorialBoundsCheck.rst
> +This block of code can be also extracted to a helper class,to be used also in other Widgets, not only the one extending Label
```suggestion
This block of code can be also extracted to a helper class in order to be used in several Widgets.
```

2021-06-18 15:28 UTC, seonmej commented on Tutorials/tutorialBoundsCheck.rst
> +        if (Constants.getBoolean("myapp.debugtextsize")) {
You should also present the usage of the constants to enable/disable the check (and explain that the production is not impacted by these development checks).

2021-06-18 15:28 UTC, seonmej commented on Tutorials/tutorialBoundsCheck.rst
> +    }
I think that this bracket is not necessary.

2021-06-18 15:29 UTC, seonmej commented on Tutorials/tutorialBoundsCheck.rst
> +
Maybe we can also talk about printing the path to the widget to help finding it.

2021-06-18 15:30 UTC, seonmej commented on Tutorials/index.rst
> +   tutorialBoundsCheck
I would even prefer proposing some stuff in the widget library instead of explaining what is missing.

2021-06-18 15:31 UTC, seonmej commented on Tutorials/tutorialBoundsCheck.rst
> +                        System.out.println(text + "\" trucantes after \"" + text.substring(0, i) + "\""); //$NON-NLS-1$ //$NON-NLS-2$
```suggestion
                        System.out.println(text + "\" truncates after \"" + text.substring(0, i) + "\""); //$NON-NLS-1$ //$NON-NLS-2$
```

2021-06-18 15:34 UTC, seonmej commented on Tutorials/tutorialBoundsCheck.rst
> +    static void fits(final Font font, final String text, final int contentWidth) {
For me, a method named "fits" return a boolean (like "equals"). Maybe "check" instead?

2021-06-18 15:36 UTC, seonmej commented on Tutorials/tutorialBoundsCheck.rst
> +To make the debugging process easier, it's possible to show on which section of the text is truncated
```suggestion
To make the correction process easier, it's possible to indicate where the text is truncated.
```

2021-06-18 15:36 UTC, seonmej commented on Tutorials/tutorialBoundsCheck.rst
> +                    System.out.println(text + "\" trucantes after \"" + text.substring(0, i) + "\""); //$NON-NLS-1$ //$NON-NLS-2$
```suggestion
                    System.out.println(text + "\" truncates after \"" + text.substring(0, i) + "\""); //$NON-NLS-1$ //$NON-NLS-2$
```

2021-06-21 21:29 UTC, VictorMisael commented on Tutorials/tutorialBoundsCheck.rst
> +        if (Constants.getBoolean("myapp.debugtextsize")) {
Yes, I thought using this on a differente tutorial since I didn't want to mix, I will just remove this if statement to avoid confusion on those who are going to read

2021-06-22 07:06 UTC, seonmej commented on Tutorials/tutorialBoundsCheck.rst
> +    The text size is greater than the Widget content Width!
```suggestion
    The text size is greater than the widget content width!
```

2021-06-22 07:07 UTC, seonmej commented on Tutorials/tutorialBoundsCheck.rst
> +        if (Constants.getBoolean("myapp.debugtextsize")) {
I think it is mandatory for the user to have otherwise he will have this code embedded in the production firmware (or he will have to remove it manually).

2021-07-01 15:14 UTC, thomasponsmicroej requested changes

2021-07-01 15:14 UTC, thomasponsmicroej commented on ApplicationDeveloperGuide/UI/MWT/how-bounds-check-widget.rst
> +In this tutorial, the `Label` class will be extended by `MyLabel`.
```suggestion
The objective is to check if the text to display fits in the content bounds of a widget. A straightforward way to test this is to extend or modify the widget.
In this article, the type `MyLabel` will be extend the type `Label` from the Widget library which displays a text.
```

2021-07-01 15:14 UTC, thomasponsmicroej commented on ApplicationDeveloperGuide/UI/MWT/how-bounds-check-widget.rst
> +        public MyLabel(String txt) {
```suggestion
        public MyLabel(String text) {
```

2021-07-01 15:14 UTC, thomasponsmicroej commented on ApplicationDeveloperGuide/UI/MWT/how-bounds-check-widget.rst
> +            super(txt);
```suggestion
            super(text);
```

2021-07-01 15:14 UTC, thomasponsmicroej commented on ApplicationDeveloperGuide/UI/MWT/how-bounds-check-widget.rst
> +    }
```suggestion
        @Override
        protected void onLaidOut() {
            super.onLaidOut();
        }
    }
```

2021-07-01 15:14 UTC, thomasponsmicroej commented on ApplicationDeveloperGuide/UI/MWT/how-bounds-check-widget.rst
> +Inside of the method, get the Font from the Style that the widget is using, and then, get the Font
```suggestion
As soon as a widget is laid out, its position and size are set and its `onLaidOut()` method is called.
Overriding this method is the best place to check whether the text fits or not.

In the method body, get the `Font` from the `Style` of the widget, and compare the text width to the content width.
```

2021-07-01 15:14 UTC, thomasponsmicroej commented on ApplicationDeveloperGuide/UI/MWT/how-bounds-check-widget.rst
> +        final Font font = getStyle().getFont();
```suggestion
        super.onLaidOut();
        final Font font = getStyle().getFont();
```

2021-07-01 15:14 UTC, thomasponsmicroej commented on ApplicationDeveloperGuide/UI/MWT/how-bounds-check-widget.rst
> +Testing with a Canvas
```suggestion
Testing
```

2021-07-01 15:14 UTC, thomasponsmicroej commented on ApplicationDeveloperGuide/UI/MWT/how-bounds-check-widget.rst
> +The check can be easily validated by putting the widget in a canvas and setting its bounds manually (a little shorter than the text size).
```suggestion
The check can be easily validated by putting the widget in a canvas and setting its bounds manually (a little shorter than the text width).
```

2021-07-01 15:14 UTC, thomasponsmicroej commented on ApplicationDeveloperGuide/UI/MWT/how-bounds-check-widget.rst
> +    }
Add some comments to explain what it does, the reader might not know all the APIs

2021-07-01 15:14 UTC, thomasponsmicroej commented on ApplicationDeveloperGuide/UI/MWT/how-bounds-check-widget.rst
> +            System.err.println("The text size is greater than the widget content width!");
Print the text and the widget hierarchy path so that the debug is easier

2021-07-02 07:37 UTC, thomasponsmicroej requested changes

2021-07-02 07:37 UTC, thomasponsmicroej commented on ApplicationDeveloperGuide/UI/MWT/how-bounds-check-widget.rst
> +This block of code can be also extracted to a helper class in order to be used in several Widgets.
```suggestion
This block of code may also be extracted to a helper class in order to be used in other Widgets.
```

2021-07-02 07:37 UTC, thomasponsmicroej commented on ApplicationDeveloperGuide/UI/MWT/how-bounds-check-widget.rst
> +    static void fits(final Font font, final String text, final int contentWidth) {
```suggestion
    public static void fits(final Font font, final String text, final int contentWidth) {
```
- make it `public` if the intent is to make it widely available.
- the intent of this method is to check and print the issue. The naming `fits` suggest you are returning a `boolean`. Either return a `boolean` or rename the method to best describe what it does.

2021-07-02 07:37 UTC, thomasponsmicroej commented on Tutorials/index.rst
> +   tutorialBoundsCheck
Until we provide some tooling for this, I agree that it should be moved to a dedicated section like @frivieremicroej proposed: ADG/UI/Advanced or ADG/UI/Widgets/Advanced

2021-07-02 07:37 UTC, thomasponsmicroej commented on ApplicationDeveloperGuide/UI/MWT/how-bounds-check-widget.rst
> +
Could you add a snippet where you show how you use the `fits` method in your widget?

You could also use the BON constants like
```
if (Constants.getBoolean("com.mycompany.checkTextOverflow")) {
       fits();
}
```
to show that the code can be executed or not with an option.

2021-07-02 07:37 UTC, thomasponsmicroej commented on ApplicationDeveloperGuide/UI/MWT/how-bounds-check-widget.rst
> +Improving the Bounds Check
```suggestion
Improving the bounds check
```

2021-07-08 08:08 UTC, seonmej commented on Tutorials/index.rst
> +   tutorialBoundsCheck
I prefer `ADG/UI/Advanced`

2021-07-08 16:23 UTC, VictorMisael commented on ApplicationDeveloperGuide/UI/MWT/how-bounds-check-widget.rst
> +
I think this could be adding in another article complemeting this one

2021-07-08 16:29 UTC, VictorMisael commented on ApplicationDeveloperGuide/UI/MWT/how-bounds-check-widget.rst
> +    }
Sure

2021-07-08 16:34 UTC, VictorMisael commented on Tutorials/index.rst
> +   tutorialBoundsCheck
So should I move ?

2021-07-08 16:42 UTC, VictorMisael commented on ApplicationDeveloperGuide/UI/MWT/how-bounds-check-widget.rst
> +            System.err.println("The text size is greater than the widget content width!");
Like an exception

2021-07-09 07:23 UTC, seonmej commented on ApplicationDeveloperGuide/UI/MWT/how-bounds-check-widget.rst
> +
@thomasponsmicroej I prefer the check inside the `fits()` method to be sure that all the callers will have the benefit of this check. (All the calls to `fits()` should be removed by the SOAR once the method is detected as empty.)

2021-07-09 07:27 UTC, seonmej commented on ApplicationDeveloperGuide/UI/MWT/how-bounds-check-widget.rst
> +            System.err.println("The text size is greater than the widget content width!");
With a print. Something like: `The text of Desktop > Dock > List > Label "Test" is larger than the widget content width.` for example.

2021-07-09 07:38 UTC, thomasponsmicroej requested changes

2021-07-09 07:38 UTC, thomasponsmicroej commented on ApplicationDeveloperGuide/UI/MWT/how-bounds-check-widget.rst
> +        //This method gets the string width by the size of each character and fonts
```suggestion
        // get the width of the text with the specified font
```

2021-07-09 07:38 UTC, thomasponsmicroej commented on ApplicationDeveloperGuide/UI/MWT/how-bounds-check-widget.rst
> +        //Gets the bounds of the Widget
```suggestion
        // get the available width for the content in the widget (excluding outlines)
```

2021-07-13 16:43 UTC, thomasponsmicroej commented on ApplicationDeveloperGuide/UI/MWT/how-bounds-check-widget.rst
> +            System.err.println("The text size is greater than the widget content width!");
@VictorMisael our suggestion is the nice to have, it will help the developper identifying wich widget has text overflow. But if you want we can postpone this request to another time, but at least please print the text that overflows in your System.err.println(...)

2021-07-13 16:49 UTC, thomasponsmicroej commented on ApplicationDeveloperGuide/UI/MWT/how-bounds-check-widget.rst
> +
if you are talking about wrapping the code in the `if (Constants.getBoolean("com.mycompany.checkTextOverflow"))` block, we already have places in the doc about that, this is why I suggest that you use it in the article. Still, it is a nice to have so it could be postponed.
examples of the usage of BON Constants in the doc:
https://docs.microej.com/en/latest/Tutorials/tutorialInstrumentJavaCodeForLogging.html#remove-logging-related-code
https://docs.microej.com/en/latest/ApplicationDeveloperGuide/classpath.html?highlight=constants#constants
https://docs.microej.com/en/latest/Tutorials/tutorialOptimizeMemoryFootprint.html?highlight=constants#application-code

2021-07-13 16:51 UTC, VictorMisael commented on ApplicationDeveloperGuide/UI/MWT/how-bounds-check-widget.rst
> +
Ok, I will be adding this

2021-07-13 17:19 UTC, VictorMisael commented on ApplicationDeveloperGuide/UI/MWT/how-bounds-check-widget.rst
> +            System.err.println("The text size is greater than the widget content width!");
Hello @thomasponsmicroej , There's a code that shows that on the Improving Bounds Check Section

https://github.com/MicroEJ/docs/blob/3d5fb180054c13cb0fcd2fffa59903cd14741504/ApplicationDeveloperGuide/UI/MWT/how-bounds-check-widget.rst#L74-L91

2021-07-13 17:24 UTC, VictorMisael commented on Tutorials/tutorialBoundsCheck.rst
> +    static void fits(final Font font, final String text, final int contentWidth) {
I changed this method to return false when it fails, and true when it doesn't

2021-08-02 07:48 UTC, seonmej commented on Tutorials/tutorialBoundsCheck.rst
> +    static void fits(final Font font, final String text, final int contentWidth) {
What is the usage of this return value? Since the error is already handled (with a print) inside the method, I doubt that the user will do something with the return value.

2021-08-02 07:50 UTC, seonmej commented on ApplicationDeveloperGuide/UI/MWT/how-bounds-check-widget.rst
> +    if (Constants.getBoolean("com.mycompany.checkTextOverflow")) {
I would have preferred this check in the static method to avoid having it for each caller (with the risk of forgetting one, and a code that is less readable).

2021-08-17 08:56 UTC, thomasponsmicroej commented
@seonmej fyi, I did some updates from our comments in july.

2021-08-19 06:23 UTC, frivieremicroej requested changes

2021-08-19 06:23 UTC, frivieremicroej commented on ApplicationDeveloperGuide/UI/Advanced/how-to-text-overflow.rst
> +How to detect text overflow
please review titles with upper case : 
=> How to Detect Text Overflow

2021-08-20 14:11 UTC, thomasponsmicroej commented on ApplicationDeveloperGuide/UI/MWT/how-bounds-check-widget.rst
> +            System.err.println("The text size is greater than the widget content width!");
resolving this comment (done in commit c9aadc8175354821c3c6137c1267e63d10ce8822)

2021-08-20 14:15 UTC, thomasponsmicroej commented on ApplicationDeveloperGuide/UI/MWT/how-bounds-check-widget.rst
> +    if (Constants.getBoolean("com.mycompany.checkTextOverflow")) {
as requested, Constant check moved to the static method. @seonmej can we resolve this one?

2021-08-20 14:17 UTC, thomasponsmicroej commented on Tutorials/index.rst
> +   tutorialBoundsCheck
Moved to ADG/UI/Advanced. Resolving this.

2021-08-20 14:19 UTC, thomasponsmicroej commented on ApplicationDeveloperGuide/UI/Advanced/how-to-text-overflow.rst
> +How to detect text overflow
@frivieremicroej Fixed titles.

2021-08-20 14:22 UTC, thomasponsmicroej approved these changes

2021-08-23 07:52 UTC, thomasponsmicroej commented on Tutorials/tutorialBoundsCheck.rst
> +        if (Constants.getBoolean("myapp.debugtextsize")) {
done

2021-08-23 07:52 UTC, thomasponsmicroej commented on Tutorials/tutorialBoundsCheck.rst
> +
done

2021-08-23 07:52 UTC, thomasponsmicroej commented on Tutorials/tutorialBoundsCheck.rst
> +    }
fixed

2021-08-23 08:08 UTC, frivieremicroej approved these changes

2021-08-23 08:09 UTC, merged