Feature/overlap render policy
MicroEJ/docs pull request #268
Opened 2021-06-15 19:00 UTC by ricardobnaquino

2021-07-05 16:03 UTC, thomasponsmicroej commented on ApplicationDeveloperGuide/UI/MWT/how-to-overlap-render-policy.rst
> +- To avoid this, it's possible to change the render policy as follows
```suggestion
Unlike the ``DefaultRenderPolicy``, the ``OverlapRenderPolicy`` will inspect the relative order of other widgets when rendering a widget. Widgets that comes after in the widget tree (Depth-first search) will be rendered too, if there bounds intersect those of the widget.
Overriding the method ``createRenderPolicy()`` of the desktop, as follows, will make the ``OverlapRenderPolicy`` apply when rendering widgets:
```

2021-07-05 16:06 UTC, thomasponsmicroej commented on ApplicationDeveloperGuide/UI/MWT/how-to-overlap-render-policy.rst
> +.. image:: images/tutorial_MicroEJ_renderpolicy.png
```suggestion
.. image:: images/tutorial_MicroEJ_renderpolicy.png

Widget 1 is displayed on top of Widget 2 in all cases: when requesting a new render of Widget 2, the render policy detects that Widget 1 overlaps with Widget 2, and it renders Widget 1 afterwards.

The ``OverlapRenderPolicy`` can be used to ensure that the order of widgets in the widget hierarchy is respected when widgets are rendered.

Note that the ``OverlapRenderPolicy`` is slightly more time-consuming because it must traverse the widget hierarchy to determine which widgets are overlapping.
```

2021-07-05 16:08 UTC, thomasponsmicroej commented on ApplicationDeveloperGuide/UI/MWT/how-to-overlap-render-policy.rst
> +Since widget1 was added after widget2, the hierarchy should be respected and the shown like this
```suggestion
Here is the result when using the ``OverlapRenderPolicy``:
```

2021-07-09 07:49 UTC, thomasponsmicroej commented on Tutorials/index.rst
> +   tutorialOverlapRenderPolicy
```suggestion
```

2021-07-09 15:04 UTC, VicMisael commented on Tutorials/index.rst
> +   tutorialOverlapRenderPolicy
Thank you

2021-08-19 06:25 UTC, frivieremicroej requested changes

2021-08-19 06:25 UTC, frivieremicroej commented on ApplicationDeveloperGuide/UI/MWT/how-to-overlap-render-policy.rst
> +Making widgets overlap
please review titles with upper case :
=> Making Widgets Overlap

2021-08-19 06:25 UTC, frivieremicroej commented on ApplicationDeveloperGuide/UI/MWT/how-to-overlap-render-policy.rst
> +Overlap Render Policy
according to the name of the file, should we rename to "How to Overlap Render Policy" in order to be similar to the other one "How to Detect Text Overflow" ?

2021-08-19 09:10 UTC, seonmej commented on ApplicationDeveloperGuide/UI/MWT/how-to-overlap-render-policy.rst
> +So far, the ``DefaultRenderPolicy`` is being used and it seems to look fine: the widgets of the desktop are rendered recursively in order after the call to ``desktop.requestShow()``.
```suggestion
So far, the ``DefaultRenderPolicy`` is being used and it seems to look fine: the widgets of the desktop are rendered successively in order after the call to ``desktop.requestShow()``.
```

2021-08-19 09:32 UTC, thomasponsmicroej commented on ApplicationDeveloperGuide/UI/MWT/how-to-overlap-render-policy.rst
> +Making widgets overlap
should be fixed

2021-08-19 09:32 UTC, thomasponsmicroej commented on ApplicationDeveloperGuide/UI/MWT/how-to-overlap-render-policy.rst
> +Overlap Render Policy
I changed to "How to Use the Overlap Render Policy"

2021-08-20 14:29 UTC, thomasponsmicroej approved these changes

2021-08-23 07:46 UTC, merged