Feature/gui test robot
MicroEJ/docs pull request #269
Opened 2021-06-16 13:14 UTC by VictorMisael

2021-06-21 09:18 UTC, gjadi-mej commented
See the rendering at https://docs.microej.com/en/feature-gui-test-robot/Tutorials/tutorialGuiTestRobot.html.
I don't know why, but all the text is in bullet list, please fix it.

2021-06-21 09:24 UTC, gjadi-mej commented
> 
> 
> See the rendering at https://docs.microej.com/en/feature-gui-test-robot/Tutorials/tutorialGuiTestRobot.html.
> I don't know why, but all the text is in bullet list, please fix it.

Hmm maybe you should rebase your branch on top of the master branch.  It looks like it wasn't built properly.  So the rendering is from a previous version.

2021-06-21 09:40 UTC, gjadi-mej requested changes
Thanks for this tutorial.  I did a first pass on it without looking too much at the code.  I'll go through it a second time.

2021-06-21 09:40 UTC, gjadi-mej commented on Tutorials/tutorialGuiTestRobot.rst
> +Here is the custom EventHandler named WatchPointerEventHandler.
```suggestion
Here is the custom ``EventHandler`` named ``WatchPointerEventHandler``.
```

2021-06-21 09:40 UTC, gjadi-mej commented on Tutorials/tutorialGuiTestRobot.rst
> +    - OutOfMemory
```suggestion
    - ``OutOfMemory``
```

2021-06-21 09:40 UTC, gjadi-mej commented on Tutorials/tutorialGuiTestRobot.rst
> +    - StackOverflow
```suggestion
    - ``StackOverflow``
```

2021-06-21 09:40 UTC, gjadi-mej commented on Tutorials/tutorialGuiTestRobot.rst
> +This EventHandler does two things.
```suggestion
This ``EventHandler`` does two things:
```

2021-06-21 09:40 UTC, gjadi-mej commented on Tutorials/tutorialGuiTestRobot.rst
> +    #. It forwards all events to the initial EventHandler. Without that, our handler would hijack the initial handler and our UI would be unresponsive because it would receive no event.
```suggestion
    #. It forwards all events to the initial ``EventHandler``. Without that, our handler would hijack the initial handler and our UI would be unresponsive because it would receive no event.
```

2021-06-21 09:40 UTC, gjadi-mej commented on Tutorials/tutorialGuiTestRobot.rst
> +Note that WatchPointerEventHandler outputs the commands on the standard output. More on this a bit later.
```suggestion
Note that ``WatchPointerEventHandler`` outputs the commands on the standard output. More on this a bit later.
```

2021-06-21 09:40 UTC, gjadi-mej commented on Tutorials/tutorialGuiTestRobot.rst
> +Record events with WatchPointerEventHandler
```suggestion
Record events with ``WatchPointerEventHandler``
```

2021-06-21 09:40 UTC, gjadi-mej commented on Tutorials/tutorialGuiTestRobot.rst
> +    #. saves the default EventHandler of the Pointer to pass it to the WatchPointerEventHandler so that it can forward the events
```suggestion
    #. saves the default ``EventHandler`` of the Pointer to pass it to the ``WatchPointerEventHandler`` so that it can forward the events
```

2021-06-21 09:40 UTC, gjadi-mej commented on Tutorials/tutorialGuiTestRobot.rst
> +    #. we start the recording by replacing the EventHandler
```suggestion
    #. we start the recording by replacing the ``EventHandler``
```

2021-06-21 09:40 UTC, gjadi-mej commented on Tutorials/tutorialGuiTestRobot.rst
> +    #. and we stop it by restoring the initial EventHandler.
```suggestion
    #. and we stop it by restoring the initial ``EventHandler``.
```

2021-06-21 09:40 UTC, gjadi-mej commented on Tutorials/tutorialGuiTestRobot.rst
> +The API of our WatchPointer is straightforward, just start() and stop() the recording of events. A good place to start the recording is after the initialization of your GUI.
```suggestion
The API of our ``WatchPointer`` is straightforward, just ``start()`` and ``stop()`` the recording of events. A good place to start the recording is after the initialization of your GUI.
```

2021-06-21 09:40 UTC, gjadi-mej commented on Tutorials/tutorialGuiTestRobot.rst
> +The API of our WatchPointer is straightforward, just start() and stop() the recording of events. A good place to start the recording is after the initialization of your GUI.
Please avoid formulations such as _is straightforward_ or _just do XXX_.

> Call the ``WatchPointer.start()`` method to record events and call the ``WatchPointer.stop()`` method to stop recording events.

2021-06-21 09:40 UTC, gjadi-mej commented on Tutorials/tutorialGuiTestRobot.rst
> +And that's it
Please use a more formal tone.
Something like:

> At this point we are able to do X and Y...

Or remove it if it is not needed.

2021-06-21 09:40 UTC, gjadi-mej commented on Tutorials/tutorialGuiTestRobot.rst
> +The robot can also be run on board with the WatchPointer enabled. The events will be outputted on the trace output (typically a UART).
```suggestion
The robot can also be run on board with the ``WatchPointer`` enabled. The events will be outputted on the trace output (typically a UART).
```

2021-06-21 09:40 UTC, gjadi-mej commented on Tutorials/tutorialGuiTestRobot.rst
> +Playing a robot is easy. We just need to send the recorded events. Here is our Robot class.
Same as earlier.  Please don't judge if it's easy or not.   Explain how it works and how to use it.

2021-06-21 09:40 UTC, gjadi-mej commented on Tutorials/tutorialGuiTestRobot.rst
> +The Robot API implements the commands that were generated in the WatchPointerEventHandler. Through the basic operations press(), move() and release() the click and drag actions are simulated. With th
```suggestion
The Robot API implements the commands that were generated in the ``WatchPointerEventHandler``. Through the basic operations ``press()``, ``move()`` and ``release()`` the click and drag actions are simulated. With the ``pause()`` we ensure we do it exactly at the same speed as the human who recorded it.
```

2021-06-21 09:40 UTC, gjadi-mej commented on Tutorials/tutorialGuiTestRobot.rst
> +Copy the commands into a function and call it from the main application at the same place where WatchPointer was called.
```suggestion
Copy the commands into a function and call it from the main application at the same place where ``WatchPointer`` was called.
```

2021-06-21 09:40 UTC, gjadi-mej commented on Tutorials/tutorialGuiTestRobot.rst
> +And that’s it! We now have the basics to create and to play software robots to test our applications.
Same as above.
```suggestion
At this point, we have the basics to create and to play software robots to test our applications.
```

2021-06-21 09:40 UTC, gjadi-mej commented on Tutorials/tutorialGuiTestRobot.rst
> +Let’s assume that we have a Main.getCurrentWidget() method that returns the current Widget. We update WatchPointerEventHandler like this:
```suggestion
Let’s assume that we have a ``Main.getCurrentWidget()`` method that returns the current Widget. We update WatchPointerEventHandler like this:
```

2021-06-21 09:40 UTC, gjadi-mej commented on Tutorials/tutorialGuiTestRobot.rst
> +Depending on your application architecture, you most likely have some kind of central class that manages which is the main Widget currently displayed. For example you may use a TransitionContainer. W
```suggestion
Depending on your application architecture, you most likely have some kind of central class that manages which is the main Widget currently displayed. For example you may use a ``TransitionContainer``. What we need, is a way to retrieve the Widget currently displayed.
```

2021-06-21 09:40 UTC, gjadi-mej commented on Tutorials/tutorialGuiTestRobot.rst
> +Conversely, we update Robot to add the checkWidget() method.
```suggestion
Conversely, we update Robot to add the ``checkWidget()`` method.
```

2021-06-21 09:40 UTC, gjadi-mej commented on Tutorials/tutorialGuiTestRobot.rst
> +When we record new robots, we will record the current Widget before a press action is executed. And when we play the robots, we will ensure that the same Widget is displayed before sending the press
```suggestion
When we record new robots, we will record the current Widget before a press action is executed. And when we play the robots, we will ensure that the same Widget is displayed before sending the press event. If the Widget is not the one recorded, ``checkWidget`` will raise an exception, otherwise, we proceed as before.
```

2021-06-21 09:40 UTC, gjadi-mej commented on Tutorials/tutorialGuiTestRobot.rst
> +It is possible to integrate the robot into a JUnit test suite if we use assertEquals instead of raising an Exception.
```suggestion
It is possible to integrate the robot into a JUnit test suite if we use ``assertEquals`` instead of raising an Exception.
```

2021-06-21 09:40 UTC, gjadi-mej commented on Tutorials/tutorialGuiTestRobot.rst
> +The checkWidget() method can also be used as a performance regression framework. If a Widget display time becomes much slower because of a regression, assuming the robot was recorded by a “not too sl
```suggestion
The ``checkWidget()`` method can also be used as a performance regression framework. If a Widget display time becomes much slower because of a regression, assuming the robot was recorded by a “not too slow” human, our robot will fail with an Exception.
```

2021-06-23 13:19 UTC, VictorMisael commented
rebased this branch onto master

2021-06-24 08:08 UTC, gjadi-mej reviewed
Can you re-rebase your work on master?
The build was broken, I believe it has been fixed now. Sorry :/

2021-06-24 08:08 UTC, gjadi-mej commented on Tutorials/tutorialGuiTestRobot.rst
> +    - the MicroEJ Java application is based in MicroUI 2.x, MWT 2.x and Widget 2.x
Is that true?  Looking at the API used I think it is compatible with MicroUI 3.
Can you check if it is compatible with MicroUI 3 APIs?

2021-06-25 07:51 UTC, gjadi-mej commented on Tutorials/tutorialGuiTestRobot.rst
> +    - the MicroEJ Java application is based in MicroUI 2.x, MWT 2.x and Widget 2.x
Ok so I just got confirmation it's not compatible with UI3.  The API are similar but the behavior is not.
To forward the event the following snippet must be used:
`Display.getDisplay().getDisplayable().handleEvent(event);`
(instead of `this.initialEventHandler.handleEvent(event);`)

2021-07-13 13:31 UTC, gjadi-mej commented on Tutorials/tutorialGuiTestRobot.rst
> +To record the events we will develop a custom ``EventHandler`` and we will inject it into the ``EventGenerator`` of ``Pointer`` events. The handler will record the events and generate the Java code t
Added.

2021-08-24 16:45 UTC, closed without merging