M0078DDG-423 added warning block regarding cached build warnings
MicroEJ/docs pull request #270
Opened 2021-06-18 08:31 UTC by fpinel-microej

2021-07-06 06:59 UTC, frivieremicroej requested changes
I made some suggestions to simplify the wording

2021-07-06 06:59 UTC, frivieremicroej commented on README.rst
> +ReST syntax errors warnings are setup to make the build fail to avoid them being pushed to the repository unadressed. However, when building locally, resulting warnings are cached once source files h
```suggestion
Syntax warnings are configured to make the build fail. When building locally, warnings are cached once source files have been read once (even during linkcheck) and thus won't reappear on subsequent builds. 
To get all the warnings locally, clean the `_build` directory (``make clean``) and rebuild the whole documentation (``make html`` , ``make linkcheck``).
```

2021-07-06 06:59 UTC, frivieremicroej commented on README.rst
> +Warning
```suggestion
Warnings Processing
```

2021-07-07 08:35 UTC, fpinel-microej commented on README.rst
> +Warning
Actually this "title" was supposed to be not a title but a "Warning !" (I even wanted to use a ReST warning:: directive to make a visible red block but GitHub doesn't seem to support that so the point is moot) 
if you're fine with this as a sub-title it's fine but I hope it is visible and "catchy" enough for people to actually read it.

2021-07-07 08:36 UTC, fpinel-microej commented on README.rst
> +ReST syntax errors warnings are setup to make the build fail to avoid them being pushed to the repository unadressed. However, when building locally, resulting warnings are cached once source files h
Changed.

2021-09-03 06:22 UTC, merged