Feature/compute optimal size
MicroEJ/docs pull request #272
Opened 2021-06-22 13:48 UTC by VictorMisael

2021-07-01 13:16 UTC, thomasponsmicroej requested changes

2021-07-01 13:16 UTC, thomasponsmicroej commented on ApplicationDeveloperGuide/UI/MWT/how-to-widget-bounds-revalidation.rst
> +        }
This is the code from the widget library. To me, there is little interest in copy/pasting the widget code here:

- the widget code is sometimes not the easiest to read (optimizations, etc.)
- the code is already available for the developer by other means

My recommendation: take a very simple usecase of a container and write the custom `computeContentOptimalSize()` for it. Your code snippet for the container could replace this one:
![image](https://user-images.githubusercontent.com/48557644/124128160-cde3f280-da7c-11eb-91b0-45b6ee864211.png)

For example, it could be a container that splits the area into 2 equal parts. 
+ given that the existing `layoutChildren` is too minimal 
![image](https://user-images.githubusercontent.com/48557644/124128385-084d8f80-da7d-11eb-97d5-fa880b48debb.png), you could also replace it with a snippet that positions the 2 children (left and right).

2021-07-01 13:16 UTC, thomasponsmicroej commented on ApplicationDeveloperGuide/UI/MWT/how-to-widget-bounds-revalidation.rst
> +
Same comment that for the `Flow` snippet

2021-07-06 10:29 UTC, VictorMisael commented on Tutorials/index.rst
> +   tutorialWidgetBoundsRevalidation
Yes, it's a leftover from when it was at the tutorials section,

2021-07-06 12:59 UTC, VictorMisael commented on ApplicationDeveloperGuide/UI/MWT/how-to-widget-bounds-revalidation.rst
> +How compute Optimal Size works
Yes, Maybe as a complement explaining how compute optimal size works

2021-07-06 14:20 UTC, VictorMisael commented on ApplicationDeveloperGuide/UI/MWT/how-to-widget-bounds-revalidation.rst
> +As a Container is also a Widget,it also contains a computeOptimalsize, calculating its size using its children
I separated these into smaller paragraphs

2021-07-06 14:29 UTC, VictorMisael commented on ApplicationDeveloperGuide/UI/MWT/how-to-widget-bounds-revalidation.rst
> +        }
Should I remove this code and refer to the API?

2021-07-06 14:29 UTC, VictorMisael commented on ApplicationDeveloperGuide/UI/MWT/how-to-widget-bounds-revalidation.rst
> +        }
The same question for the comment below

2021-07-06 15:00 UTC, thomasponsmicroej commented on ApplicationDeveloperGuide/UI/MWT/how-to-widget-bounds-revalidation.rst
> +        }
You should remove Canvas and Flow examples and create your own example (simple with at least two children) to show how to code the `computeContentOptimalSize`. imho your example should replace this one https://docs.microej.com/en/latest/ApplicationDeveloperGuide/UI/MWT/how-to-container.html#codecell0 which is too simple and not typical (only one child).
I think we can redirect the reader to the containers of the Widget library or of the Demo Widget for advanced examples on how containers are coded. In the reference documentation we can focus on the core principles.

2021-07-08 07:44 UTC, apoudret-microej commented on ApplicationDeveloperGuide/UI/MWT/how-to-widget-bounds-revalidation.rst
> +How compute Optimal Size works
it is good to have an extra example but to keep the MWT documentation concise i would move this new doc to the tutorials (or the ui getting started)

2021-07-08 16:55 UTC, VictorMisael commented on ApplicationDeveloperGuide/UI/MWT/how-to-widget-bounds-revalidation.rst
> +        }
OK, I'm going to have a look on implement this, and put the code there

2021-07-13 07:45 UTC, apineau-microej commented on ApplicationDeveloperGuide/UI/MWT/how-to-widget-bounds-revalidation.rst
> +As a Container is also a Widget,it also contains a computeOptimalsize, calculating its size using its children
```suggestion
As a Container is also a Widget, it also contains a computeOptimalsize, calculating its size using its children
```

2021-07-13 07:46 UTC, apineau-microej commented on ApplicationDeveloperGuide/UI/MWT/how-to-widget-bounds-revalidation.rst
> +Every call to computeOptimalsize stores the Size needed to show the Widget correctly Including outlines(Example: Margin,Padding) and Sets the Size atrribute
```suggestion
Every call to computeOptimalSize stores the Size needed to show the Widget correctly Including outlines(Example: Margin,Padding) and Sets the Size atrribute
```

2021-07-13 07:48 UTC, apineau-microej commented on ApplicationDeveloperGuide/UI/MWT/how-to-widget-bounds-revalidation.rst
> +A Container has multiple children widgets, to compute the size of each of the children on a container
- As Thomas said in the last comment it feels like the sentence is truncated
- Instead of starting talking about Container you could just talk about Widget here

2021-08-23 09:41 UTC, thomasponsmicroej commented on ApplicationDeveloperGuide/UI/MWT/how-to-widget-bounds-revalidation.rst
> +How compute Optimal Size works
@apoudret-microej agree

2021-08-23 09:51 UTC, thomasponsmicroej commented
@apoudret-microej @apineau-microej
Can we close this one? It is a duplicate and we agreed that some extra examples of `computeContentOptimalSize()` implementations could be added elsewhere (there are already some in the UI tuto).

2021-08-24 16:43 UTC, closed without merging