M0078DDG-417 Document available IoT libraries
MicroEJ/docs pull request #273
Opened 2021-06-22 15:33 UTC by pauffray

2021-08-09 11:53 UTC, frivieremicroej approved these changes

2021-08-09 14:23 UTC, tdelhomenie-microej requested changes

2021-08-09 14:23 UTC, tdelhomenie-microej commented on ApplicationDeveloperGuide/networking.rst
> +      -  - `Bluetooth utility Library <https://repository.microej.com/modules/ej/library/iot/bluetooth-util/>`_
As a developer I would like a description of the API features, the Ivy dependency snippet to quickly setup my project, and documentation on how to use it:
- API features: the description is very light, it is hard to know what the API contains. Don't we have more detailed description ? A link to a README at least ?
- Ivy dependency: the link in the "Module link" column allows to find the information about the module but it is not easy, especially for someone not familiar with Ivy. We should add the Ivy coordinates directly to make the developer life easier.
- documentation: we need documentation about API usage. Examples are a good thing but it is not easy for developers to extract what they want. And some library do not even have example. Don't we have documentation for these APIs ? Or at least a javadoc link ?

2021-08-09 14:23 UTC, tdelhomenie-microej commented on ApplicationDeveloperGuide/networking.rst
> +.. figure:: images/networking_overview.png
It should be "Example Applications" instead of "Examples Applications" IMO.

2021-08-09 14:23 UTC, tdelhomenie-microej commented on ApplicationDeveloperGuide/networking.rst
> +IoT Libraries
Maybe we should put these chapters in a "Add-On Libraries" chapter to match with the schema ?

2021-08-11 11:24 UTC, frivieremicroej commented on ApplicationDeveloperGuide/networking.rst
> +      -  - `Bluetooth utility Library <https://repository.microej.com/modules/ej/library/iot/bluetooth-util/>`_
- API Features: the goal of this first page is to start to list libraries that have never been documented. This is a first version we could enhance in the future when we will have more documentation. Please note that a link to the README has been added when it contains valuable information.
- Ivy Dependency: I thought it too, but I finally did not do it for 2 reasons: 
  - 1) it avoids to put lots of hardcoded versions (the link points to the module name, not a specific version); 
  - 2) the dependency line would be too large to fit in a table column.
- The `Use` column contains what is publicly available (examples, README, user manual or other utility libraries). Sure we need many more documentation for each library in the future. Again this is not the purpose of this PR to produce the library documentation, but just a summary of what is already available.

2021-08-11 11:27 UTC, frivieremicroej commented on ApplicationDeveloperGuide/networking.rst
> +      -  - `Bluetooth utility Library <https://repository.microej.com/modules/ej/library/iot/bluetooth-util/>`_
For Javadoc, please have a look to feature/M0078DDG-417_documentation_library_iot_with_javadoc_link
I started a new column for Foundation Libraries, what do you think about that ?

2021-08-11 11:33 UTC, frivieremicroej commented on ApplicationDeveloperGuide/networking.rst
> +IoT Libraries
done

2021-08-12 12:22 UTC, tdelhomenie-microej approved these changes

2021-08-12 13:53 UTC, merged