Feature/microui threading
MicroEJ/docs pull request #276
Opened 2021-06-24 16:11 UTC by ricardobna

Draft of MicroUI Threads

2021-07-05 09:37 UTC, gjadi-mej requested changes
After having read this tutorial, I feel like the content is interesting and it should go to the Application Developer Guide under the MicroUI section: https://docs.microej.com/en/latest/ApplicationDeveloperGuide/UI/MicroUI/index.html

The specificities of the MWT Widget API should go to the MWT section: https://docs.microej.com/en/latest/ApplicationDeveloperGuide/UI/MWT/index.html
maybe in the concepts or in a howto

For the Animation, if something is missing or unclear it should be fixed in the howto: https://docs.microej.com/en/latest/ApplicationDeveloperGuide/UI/MWT/how-to-animate-widget.html

2021-07-05 09:37 UTC, gjadi-mej commented on Tutorials/tutorialMicroUIAndThreading.rst
> +- The handleEvent 3 method is also called in the DisplayPump.
What's the `3`? is that a typo?
```suggestion
- The handleEvent method is also called in the DisplayPump.
```

2021-07-05 09:37 UTC, gjadi-mej commented on Tutorials/tutorialMicroUIAndThreading.rst
> +- revalidate asynchronously calls :guilabel:`validate` (and :guilabel:`validateContent`) then :guilabel:`setBounds` (and :guilabel:`setBoundsContent`).
I'm not sure about the `guilabel` usage here.
My understanding is that it is used for GUI label, as in, GUI components in the IDE.  For code we use the back-ticks ``.

Also, please add at least one link to the documentation for the Widget. https://repository.microej.com/javadoc/microej_5.x/apis/ej/mwt/Widget.html

2021-07-05 09:37 UTC, gjadi-mej commented on Tutorials/tutorialMicroUIAndThreading.rst
> +On MicroEJ there are two threads that handle the application, ``DisplayPump`` and ``InputPump``.
It may be worth precising that the developer can create additional Threads if needed.
Also, maybe create a section on the configuration of the input queue size for the application : https://docs.microej.com/en/latest/ApplicationDeveloperGuide/UI/MicroUI/applicationOptions.html

2021-07-05 09:37 UTC, gjadi-mej commented on Tutorials/tutorialMicroUIAndThreading.rst
> +To avoid slowing down the rendering (and the animations), long running algorithm should be executed in another thread. For example the creation of a new complex page could be done entirely in another
Can you be a bit more specific when you write about the creation of the page?
Something like:

> For example the retrieval of data to be displayed on a complex page could be done entirely in another thread. ...

Otherwise when I read the sentence it feels like I can do the drawing in a separate thread and then request the display on screen in the UI thread.

2021-07-05 09:37 UTC, gjadi-mej commented on Tutorials/tutorialMicroUIAndThreading.rst
> +Widget library provides an :guilabel:`Animator` that repeatedly executes several animations. This animator uses the unique instance of Timer registered in the service loader :guilabel:`ServiceLoader.
The `Animator` class is provided by the MWT module.
To see which module provides a class, check the top right corner of the javadoc: https://repository.microej.com/javadoc/microej_5.x/apis/ej/mwt/animation/Animator.html
```xml
<dependency org="ej.library.ui" name="mwt" rev="3.2.1" />
```

2021-07-05 15:02 UTC, gjadi-mej commented
> After having read this tutorial, I feel like the content is interesting and it should go to the Application Developer Guide under the MicroUI section: https://docs.microej.com/en/latest/ApplicationDeveloperGuide/UI/MicroUI/index.html

Correction.  The threading model also belongs to MWT, not MicroUI, sorry.

2021-08-23 14:25 UTC, thomasponsmicroej requested changes
Is it on purpose that this article is UI2-oriented?
If so, maybe mention it in the introduction. If not, migrate to UI3.
TBD: where to put this documentation? (tuto, ADG/UI/MWT, ADG/UI/Advanced, ...)

2021-08-23 14:25 UTC, thomasponsmicroej commented on Tutorials/tutorialMicroUIAndThreading.rst
> +#. ``InputPump`` waits for native events and immediately delegates their handling to the ``DisplayPump``.
Deprecated with UI3. By the way, the roles of the MicroUI thread are already specified in the doc:

```
This thread has several roles:

- It manages all display events (requestRender(), requestShow(), etc.).
- It reads the I/O devices inputs and dispatches them into the event generators’ listeners. See input section: Input.
- It allows to run some piece of code using the callSerially() method
```

Now, if you want to indicate what MWT/Widget operations should be done in the UI thread, you could say something like:
```
The UI thread is the right place for:
- Handling the user input events
- Laying out the widgets
- Rendering the widgets
```

NB: not sure but I think that this naming convention applies to titles, not lists of elements (to be verified).

2021-08-23 14:25 UTC, thomasponsmicroej commented on Tutorials/tutorialMicroUIAndThreading.rst
> +DisplayPump
Prefer to refer to the "MicroUI Thread" or "UI Thread" in the whole article.

2021-08-23 14:25 UTC, thomasponsmicroej commented on Tutorials/tutorialMicroUIAndThreading.rst
> +Some methods request an action asynchronously in the DisplayPump:
The methods and types listed above are UI2. Update to UI3.

2021-08-23 14:25 UTC, thomasponsmicroej commented on Tutorials/tutorialMicroUIAndThreading.rst
> +- To execute methods in the ``DisplayPump``, use ``Display.callSerially``.
There is very few places in the doc where we talk about `ej.microui.MicroUI.callSerially(Runnable)`.
This is a good place to put a small example. Typically, a non-UI thread has updated the business model and wants to reflect that on the UI: this is perfect place to use the `callSerially` to asynchronously update one widget.

2021-08-30 15:36 UTC, seonmej requested changes

2021-08-30 15:36 UTC, seonmej commented on Tutorials/tutorialMicroUIAndThreading.rst
> +MicroUI and Threading
This article is merely a copy of an article based on UI2 on the forum (https://forum.microej.com/t/microui-and-multithreading/652).
I think it would be interesting to update it to UI3. Some of the concepts are the same but some others are quite different (MicroUI threads, Animator, asynchronous methods, methods to call in the UI thread, etc.).

2021-09-09 18:16 UTC, VicMisael commented on Tutorials/tutorialMicroUIAndThreading.rst
> +If an animation needs to modify the UI, don’t forget to delegate it in the DisplayPump.
Changed

2021-09-09 18:16 UTC, VicMisael commented on Tutorials/tutorialMicroUIAndThreading.rst
> +On MicroEJ, there are two Threads that handle the application, ``DisplayPump`` and ``InputPump``.
Removed references from inputPump

2021-09-09 18:18 UTC, VicMisael commented on Tutorials/tutorialMicroUIAndThreading.rst
> +The user can add more Threads if needed.
Maybe I can remove this, and put a section about CallSerially?

2021-09-09 18:18 UTC, VicMisael commented on Tutorials/tutorialMicroUIAndThreading.rst
> +#. ``InputPump`` waits for native events and immediately delegates their handling to the ``DisplayPump``.
Fixed

2021-09-09 18:21 UTC, VictorMisael commented on Tutorials/tutorialMicroUIAndThreading.rst
> +If an animation needs to modify the UI, don’t forget to delegate it in the DisplayPump.
Fixed this

2021-09-09 18:21 UTC, VictorMisael commented on Tutorials/tutorialMicroUIAndThreading.rst
> +On MicroEJ, there are two Threads that handle the application, ``DisplayPump`` and ``InputPump``.
removed reference to InputPump

2021-09-09 18:23 UTC, VictorMisael commented on Tutorials/tutorialMicroUIAndThreading.rst
> +#. ``InputPump`` waits for native events and immediately delegates their handling to the ``DisplayPump``.
Also fixed this session

2021-09-21 13:10 UTC, VictorMisael commented on Tutorials/tutorialMicroUIAndThreading.rst
> +MicroUI and Threading
I based myself on the comments above and modified some parts it accurate with microui

2021-09-28 11:17 UTC, closed without merging