Feature/event propagation
MicroEJ/docs pull request #280
Opened 2021-07-02 12:08 UTC by VictorMisael

2021-08-23 11:19 UTC, thomasponsmicroej requested changes

2021-08-23 11:19 UTC, thomasponsmicroej commented on ApplicationDeveloperGuide/images/EventPropagation1.plantuml
> +@startuml
This diagram is interesting to have an example of pointer event dispatching. It could be moved in the Concepts page in the PointerEventDispatcher section (https://docs.microej.com/en/latest/ApplicationDeveloperGuide/UI/MWT/concepts.html#pointer-event-dispatcher). 
@apoudret-microej do you have an idea where this uml could land?

Still, it can be improved because it is not 100% correct (types involved and methods names):
This is my proposal:
![image](https://user-images.githubusercontent.com/48557644/130437566-9a2969cf-e25c-488c-b850-c156f49f1960.png)

and the code:
```
@startuml
' Copyright 2019-2020 MicroEJ Corp. All rights reserved.
    ' This library is provided in source code for use, modification and test, subject to license terms.
    ' Any modification of the source code will break MicroEJ Corp. warranties on the whole library.


    skinparam backgroundColor #f7f8f9
    skinparam roundcorner 20
    skinparam linetype ortho
    skinparam Shadowing false
    skinparam Participant {
        BackgroundColor #cbd3d7
        BorderColor #cbd3d7
        FontColor automatic
        FontName Source Sans Pro
    }
    skinparam SequenceDivider {
        FontColor automatic
        BackgroundColor #ee502e
        BorderColor #ee502e
    }

    queue DisplayPump #cbd3d7
    participant Desktop
    == The user presses the touch screen ==
    DisplayPump -> Desktop : handleEvent(event)
    Desktop -> PointerEventDispatcher : dispatchEvent(event)
    PointerEventDispatcher -> Desktop : getWidgetAt(x, y)
    PointerEventDispatcher -> Widget : handleEvent(event)
    PointerEventDispatcher <-- Widget : false (the event has not been consumed)
    PointerEventDispatcher -> Widget : getParent()
    PointerEventDispatcher -> Parent : handleEvent(event)
    PointerEventDispatcher <-- Parent : true (the event has been consumed)

    == The user starts a drag gesture ==
    DisplayPump -> Desktop : handleEvent(event)
    Desktop -> PointerEventDispatcher :  dispatchEvent(event)
    PointerEventDispatcher -> Parent:  handleEvent(event)
    PointerEventDispatcher <-- Parent : true (the event has been consumed)

    == The user releases the touch screen ==
    DisplayPump -> Desktop : handleEvent(event)
    Desktop -> PointerEventDispatcher :  dispatchEvent(event)
    PointerEventDispatcher -> Parent:  handleEvent(event)
    PointerEventDispatcher <-- Parent : true (the event has been consumed)
@enduml
```

2021-08-30 15:43 UTC, seonmej commented on ApplicationDeveloperGuide/images/EventPropagation1.plantuml
> +@startuml
I agree that this whole article should be moved/merged in the `Pointer Event Dispatcher` section.

2021-09-28 10:23 UTC, gharelMicroEJ commented
Only the diagram was integrated see: https://github.com/MicroEJ/docs/pull/314

2021-09-28 10:23 UTC, closed without merging