Feature/m0078 ddg 266 ej api trace
MicroEJ/docs pull request #32
Opened 2020-04-23 12:04 UTC by flardy

2020-04-24 12:14 UTC, frivieremicroej commented on ApplicationDeveloperGuide/trace.rst
> +.. _apiTrace:
Please rebase this branch on master without the new tutorials section stuff

2020-04-24 12:29 UTC, flardy commented on ApplicationDeveloperGuide/trace.rst
> +.. _apiTrace:
Branch was rebased on master.

2020-04-27 18:09 UTC, jerome-leroux commented
This documentation is redundant with the Javadoc (http://repository.microej.com/javadoc/microej_5.x/foundation/index.html?ej/trace/Tracer.html) and is not useful. Reading the javadoc provides almost the same information.

Remove all the information that is already in the javadoc and add more global information.

The information we need:
- Describe what is a record: 
  - event type (identified by an eventId) + a list of values
  - a record can be:
    - a single event (no end)
    - a period of time with a start and an end
- Describe what is a Tracer: identified by a name, has a limited number of event types
- Describe how to start/stop the trace system: with the Java API, with the C API, with the launcher option ; how to activate the trace system (launcher).
- Describe that we have a Java API (link to Javadoc + ivy dependency) and a C API (C header file name)
- Describe how it is implemented:
  - Default implementation that displays a message in the standard output for every record (does it print a timestamp?).
  - Implementation can be overridden by implementing the LLXXX_impl.h file
  - There is an implementation that uses SystemView and explain in this implementation how the Trace concepts (Tracer, record, etc.) are mapped into SystemView concepts.
- Describe some usage examples:
  - Trace a single event
  - Trace a method execution with a start that traces the parameters, an end that traces the result and explain that we can so trace the execution time of the function.

2020-07-08 11:18 UTC, jerome-leroux commented on ApplicationDeveloperGuide/trace.rst
> +  - When using a serial port reader that can display the timestamp at each print, you can compute the execution time of the traced function.
I don't know if it is a good idea to say that. 
With this solution, the timestamp depends on the baudrate and the serial reader. 

Actually, that's why we didn't put timestamp in the traces when printing on the serial port. The print is so slow that it can drastically impact the performances.

2020-07-08 11:18 UTC, jerome-leroux commented on ApplicationDeveloperGuide/trace.rst
> +  -
Empty bullet

2020-07-08 11:33 UTC, flardy commented on ApplicationDeveloperGuide/trace.rst
> +- This class gives access to the String constant ``TRACE_ENABLED_CONSTANT_PROPERTY`` representing the System property ``core.trace.enabled``.
This part was removed but will be present in the tutorial Log traces in an application.
Should we keep a part on this point on this doc ?

2020-07-08 11:37 UTC, jerome-leroux commented on ApplicationDeveloperGuide/trace.rst
> +- This class gives access to the String constant ``TRACE_ENABLED_CONSTANT_PROPERTY`` representing the System property ``core.trace.enabled``.
I think so. We should explain that using these BON constants allows to define some portions of code that can be removed at compile time (no impact on the footprint and the performances when disabled)

2020-07-08 11:43 UTC, jerome-leroux commented on ApplicationDeveloperGuide/trace.rst
> +- The method ``recordEvent(...)`` always need the eventID as the first parameter and can have up to ten int parameters as custom value for the event.
In the "description" section, keep a paragraph about how to record events. 
You explain how to active the trace, how to start it. We don't explain how to do a trace.

2020-09-03 21:53 UTC, jerome-leroux requested changes
Remove almost all the bullets. They can be normal paragraph. Keep bullets only for the lists.

2020-09-03 21:53 UTC, jerome-leroux commented on ApplicationDeveloperGuide/trace.rst
> +    not be embedded with the application and thus, will not impact the performances.
```suggestion
  - This **BON Constant** can be used to remove, at build time, portions of code when trace is disabled. To do that, just surround tracer record calls with a if statement that checks the state of the constant. When the constant is set to false, the code inside the if statement will not be embedded with the application and thus, will not impact the performances.
```

2020-09-03 21:53 UTC, jerome-leroux commented on ApplicationDeveloperGuide/trace.rst
> +- It does not print a timestamp when displaying the trace message because it drastically impacts the performances.
```suggestion
- It does not print a timestamp when displaying the trace message because it can drastically impact the performances.
```

2020-09-03 21:53 UTC, jerome-leroux commented on ApplicationDeveloperGuide/trace.rst
> +  It only print the ID of the recorded event followed by the value given in parameters.
```suggestion
  It only prints the ID of the recorded event followed by the value given in parameters.
```

2020-09-03 21:53 UTC, jerome-leroux commented on ApplicationDeveloperGuide/trace.rst
> +- An implementation of this API is mapped to **SEGGER SystemView** concepts.
```suggestion
- An implementation of this API mapped to **SEGGER SystemView** concepts is available.
```

2020-09-03 21:53 UTC, jerome-leroux commented on ApplicationDeveloperGuide/trace.rst
> +  - This allow to visualize the different trace directly in **SEGGER SystemView**.
```suggestion
  - This allows to visualize the different traces directly in **SEGGER SystemView**.
```

2020-09-03 21:53 UTC, jerome-leroux commented on ApplicationDeveloperGuide/trace.rst
> +  - Then a low-level API named ``LLTRACE_sysview.c`` implements the ``LLTRACE_impl.h`` defined functions, using the functions of the **SystemView** module.
```suggestion
  - Then a low-level API named ``LLTRACE_sysview.c`` implements the function defined in ``LLTRACE_impl.h`` using the **SystemView** library.
```

2020-09-07 15:07 UTC, flardy commented on ApplicationDeveloperGuide/trace.rst
> +  - To add the library to your project, add the following dependency line in your module.ivy file:
Changed indentation of the all document and fixed this wrong one.

2020-09-08 13:27 UTC, flardy commented
Is it possible to squash the commits (especially all the commits Update ApplicationDeveloperGuide/trace.rst that were created when doing Commit suggestion) when merging like in Gitlab ?

2020-09-08 20:50 UTC, jerome-leroux commented on ApplicationDeveloperGuide/trace.rst
> +  - To add the library to your project, add the following dependency line in your module.ivy file:
Indentation is not good for several bullets lists. Remove extra spaces at the beginning of the line.

2020-09-08 20:52 UTC, jerome-leroux commented on ApplicationDeveloperGuide/trace.rst
> +    - Check the option ``Start execution traces automatically``.
These items are not displayed properly in the github preview.

2020-09-08 20:54 UTC, jerome-leroux commented on ApplicationDeveloperGuide/trace.rst
> +To record an event, use the method ``recordEvent(int eventId)``. The event ID needs to be in the range ``0 to nbEventTypes-1``.
```suggestion
To record an event, use the method ``recordEvent(int eventId)``. The event ID needs to be in the range ``0`` to ``nbEventTypes-1``.
```

Specify what is `nbEventTypes`.

2020-09-08 20:54 UTC, jerome-leroux commented on ApplicationDeveloperGuide/trace.rst
> +The methods ``recordEvent(...)`` always needs the eventID as the first parameter and can have up to ten int parameters as custom value for the event.
```suggestion
The methods ``recordEvent(...)`` always needs the eventID as the first parameter and can have up to ten int parameters as custom values for the event.
```

2020-09-08 20:55 UTC, jerome-leroux commented on ApplicationDeveloperGuide/trace.rst
> +  - This **BON Constant** can be used to remove, at build time, portions of code when trace is disabled. To do that, just surround tracer record calls with a if statement that checks the state of the
Remove bullet.

2020-09-08 20:57 UTC, jerome-leroux commented on ApplicationDeveloperGuide/trace.rst
> +      }
```suggestion
      if(Constants.getBoolean(Tracer.TRACE_ENABLED_CONSTANT_PROPERTY)) {
        // This code is not embedded if TRACE_ENABLED_CONSTANT_PROPERTY is set to false.       
        tracer.recordEventEnd(0);
      }
```

2020-09-08 20:58 UTC, jerome-leroux commented on ApplicationDeveloperGuide/trace.rst
> +  It only prints the ID of the recorded event followed by the value given in parameters.
```suggestion
It only prints the ID of the recorded event followed by the values given in parameters.
```

2020-09-08 20:59 UTC, jerome-leroux commented on ApplicationDeveloperGuide/trace.rst
> +  - Then a low-level API named ``LLTRACE_sysview.c`` implements the function defined in ``LLTRACE_impl.h`` using the **SystemView** library.
```suggestion
  - Then a low-level API named ``LLTRACE_sysview.c`` implements the functions defined in ``LLTRACE_impl.h`` using the **SystemView** library.
```

2020-09-08 21:01 UTC, jerome-leroux commented on ApplicationDeveloperGuide/trace.rst
> +  - Ouput on serial port (standard ouput):
```suggestion
  Ouput on serial port (standard ouput): 
```

2020-09-08 21:02 UTC, jerome-leroux commented on ApplicationDeveloperGuide/trace.rst
> +  - Ouput on serial port (standard ouput):
```suggestion
  Ouput on serial port (standard ouput): 
```

2020-09-11 09:13 UTC, flardy commented on ApplicationDeveloperGuide/trace.rst
> +To record an event, use the method ``recordEvent(int eventId)``. The event ID needs to be in the range ``0 to nbEventTypes-1``.
Added small part on initialization of the Tracer Object and link to ``nbEventTypes``.

2020-09-11 09:13 UTC, flardy commented on ApplicationDeveloperGuide/trace.rst
> +  - To add the library to your project, add the following dependency line in your module.ivy file:
Changed indentation, is it good now ?

2020-09-21 12:23 UTC, jerome-leroux approved these changes

2020-09-24 21:14 UTC, jerome-leroux requested changes

2020-09-24 21:14 UTC, jerome-leroux commented on ApplicationDeveloperGuide/trace.rst
> +- Right click on the project and go to ``Run As > Run Configurations``,
```suggestion
- Right-click on the project and go to ``Run As > Run Configurations``,
```

2020-09-24 21:14 UTC, jerome-leroux commented on ApplicationDeveloperGuide/trace.rst
> +  - Right click on the project and go to ``Run As > Run Configurations``,
```suggestion
  - Right-click on the project and go to ``Run As > Run Configurations``,
```

2020-09-24 21:14 UTC, jerome-leroux commented on ApplicationDeveloperGuide/trace.rst
> +To record an event, you first need to instantiate a ``Tracer`` object by calling its contructor with two parameters.
```suggestion
To record an event, you first need to instantiate a ``Tracer`` object by calling its constructor with two parameters.
```

2020-09-24 21:14 UTC, jerome-leroux commented on ApplicationDeveloperGuide/trace.rst
> +The first parameter, ``name``, is a String that will represent the name of the ``Tracer`` object group.
```suggestion
The first parameter, ``name``, is a String that will represent the ``Tracer`` object group's name.
```

2020-09-24 21:14 UTC, jerome-leroux commented on ApplicationDeveloperGuide/trace.rst
> +The ``recordEventEnd(...)`` method can also have another int parameter for a custom value for the event end. It can be used to trace the returned value of a method.
```suggestion
The ``recordEventEnd(...)`` method can also have another int parameter for a custom value for the event end. One can use it to trace the returned value of a method.
```

2020-09-24 21:14 UTC, jerome-leroux commented on ApplicationDeveloperGuide/trace.rst
> +To do that, just surround tracer record calls with a if statement that checks the state of the constant.
```suggestion
To do that, just surround tracer record calls with a if statement that checks the constant's state. 
```

2020-09-24 21:14 UTC, jerome-leroux commented on ApplicationDeveloperGuide/trace.rst
> +The default implementation can be overridden by implementing the ``LLTRACE_impl.h`` file.
```suggestion
One can override the default implementation by implementing the ``LLTRACE_impl.h`` file.
```

2020-09-24 21:14 UTC, jerome-leroux commented on ApplicationDeveloperGuide/trace.rst
> +- This allows to visualize the different traces directly in **SEGGER SystemView**.
```suggestion
- This implementation allows visualizing the different traces directly in **SEGGER SystemView**.
```

2020-09-25 10:31 UTC, jerome-leroux approved these changes

2020-10-02 14:45 UTC, merged