Feature/m0078 ddg 308 tutorial debug applications
MicroEJ/docs pull request #334
Opened 2021-11-03 14:45 UTC by gjadi-mej

2021-11-26 17:05 UTC, frivieremicroej requested changes
Hello @gjadi-mej 
This is my first quick pass.
I have to enter more in deep in each section later.
I also suggest to prepare a dedicated PR with what has been added in the ADG & PDG so that it can be merged before the tutorial.

2021-11-26 17:05 UTC, frivieremicroej commented on Tutorials/tutorialDebug.rst
> +* Configure the MPU to configure the access to the JVM heap and stack to prevent any other native threads from altering this area.
this could be better to point a reference platform that implements MPU protectioj of MicroEJ internal structures

2021-11-26 17:05 UTC, frivieremicroej commented on Tutorials/tutorialDebug.rst
> +   void Java_com_mycompany_MyClass_myNativeFunction(void) {
not onlythe CRC
there is also a hook to implement - friviere to retrieve

2021-11-26 17:05 UTC, frivieremicroej commented on Tutorials/tutorialDebug.rst
> +* Check the native stack is not full (usually there shall have remaining init patterns in memory on top of stack such as "0xDEADBEEF")
move the C stack to the beginning of memory, so that overflow will be easily detected

2021-11-29 10:51 UTC, gjadi-mej commented on ApplicationDeveloperGuide/gettingStartedApp.rst
> +Debug on the Simulator
Done

2021-11-29 10:53 UTC, gjadi-mej commented on PlatformDeveloperGuide/coreEngine.rst
> +It is recommended to do a VM dump as a last resort in a fault handler.
The line after explains that `Calling ``LLMJVM_dump`` is undefined if the VM is not paused.`

2021-11-29 11:09 UTC, gjadi-mej commented on Tutorials/tutorialDebug.rst
> +A quick way to check if the Java threads are scheduled correctly is, here again, to
Added comment + snippet to address this issue

2021-11-29 11:10 UTC, gjadi-mej commented on Tutorials/tutorialDebug.rst
> +* ARM Documentation Center http://infocenter.arm.com/help/index.jsp
it's the starting point to get the ARM doc on the device used by the customer.
I don't have a strong opinion on the importance of this link

2021-11-29 11:25 UTC, gjadi-mej commented on Tutorials/tutorialDebug.rst
> +   void Java_com_mycompany_MyClass_myNativeFunction(void) {
I don't understand. What is missing?

2021-12-03 09:41 UTC, gjadi-mej commented on PlatformDeveloperGuide/coreEngine.rst
> +Trigger VM dump from a fault handler
Done

2021-12-03 09:43 UTC, gjadi-mej commented on PlatformDeveloperGuide/coreEngine.rst
> +Trigger VM dump from a fault handler
Done

2021-12-03 09:44 UTC, gjadi-mej commented on PlatformDeveloperGuide/coreEngine.rst
> +It is recommended to do a VM dump as a last resort in a fault handler.
Done

2021-12-03 09:55 UTC, gjadi-mej commented on PlatformDeveloperGuide/coreEngine.rst
> +To trigger a VM dump from the debugger, set the PC register to the ``LLMJVM_dump`` address.
Done

2021-12-03 09:56 UTC, gjadi-mej commented on Tutorials/tutorialDebug.rst
> +Add traces and visualize the system behaviors
Done

2021-12-03 10:03 UTC, gjadi-mej commented on Tutorials/tutorialDebug.rst
> +
Added

2021-12-03 10:06 UTC, gjadi-mej commented on Tutorials/tutorialDebug.rst
> +* Check the native stack is not full (usually there shall have remaining init patterns in memory on top of stack such as "0xDEADBEEF")
done

2021-12-03 10:06 UTC, gjadi-mej commented on PlatformDeveloperGuide/coreEngine.rst
> +The symbol for the ``LLMJVM_dump`` address is ``__icetea__virtual__com_is2t_microjvm_IGreenThreadMicroJvm___dump`` or ``__icetea__virtual__com_is2t_microjvm_mowana_VMTask___dump``.
done

2021-12-03 10:07 UTC, gjadi-mej commented on Tutorials/tutorialDebug.rst
> +Add traces and visualize the system behaviors
Updated after sma review

2021-12-03 10:34 UTC, gjadi-mej commented on Tutorials/tutorialDebug.rst
> +Use case 1:  Debugging an UI application freeze
It integrates all its content. I closed #54.

2021-12-03 11:05 UTC, gjadi-mej commented on Tutorials/tutorialDebug.rst
> +Guide <https://docs.microej.com/en/latest/PlatformDeveloperGuide/coreEngine.html>`__.
Done

2021-12-03 11:11 UTC, gjadi-mej commented on Tutorials/tutorialDebug.rst
> +* Configure the MPU to configure the access to the JVM heap and stack to prevent any other native threads from altering this area.
We don't have such ref platform. The best we have is https://github.com/MicroEJ/Platform-STMicroelectronics-STM32F7508-DK/blob/e4e7c7e5205463b815b61c3662142725b18a392b/stm32f7508_freertos-bsp/projects/microej/main/src/main.c#L358

2021-12-03 12:49 UTC, gjadi-mej commented on Tutorials/tutorialDebug.rst
> +      ============ VM Dump ============
Done (in the tuto + core engine doc)

2021-12-06 14:14 UTC, frivieremicroej requested changes
2nd pass

2021-12-06 14:14 UTC, frivieremicroej commented on ApplicationDeveloperGuide/debug.rst
> +.. figure:: images/debug1.png
please reduce the image width to make it readable

2021-12-06 14:14 UTC, frivieremicroej commented on ApplicationDeveloperGuide/debug.rst
> +and select :guilabel:`Run` > :guilabel:`Debug as` > :guilabel:`MicroEJ Application`.
```suggestion
and select :guilabel:`Debug As` > :guilabel:`MicroEJ Application`.
```

2021-12-06 14:14 UTC, frivieremicroej commented on Tutorials/tutorialDiscoverEmbeddedDebuggingTools.rst
> +* `LLJVM check integrity <https://forum.microej.com/t/architecture-7-13-check-integrity-utility/769/2>`_ is a low-level API to detect memory corruptions in native functions.
```suggestion
* `LLMJVM check integrity <https://forum.microej.com/t/architecture-7-13-check-integrity-utility/769/2>`_ is a low-level API to detect memory corruptions in native functions.
```

2021-12-06 14:14 UTC, frivieremicroej commented on Tutorials/tutorialDiscoverEmbeddedDebuggingTools.rst
> +* `LLJVM check integrity <https://forum.microej.com/t/architecture-7-13-check-integrity-utility/769/2>`_ is a low-level API to detect memory corruptions in native functions.
Please introduce a new section in PDG instead (do not pointing to a forum link)

2021-12-06 14:14 UTC, frivieremicroej commented on Tutorials/tutorialDiscoverEmbeddedDebuggingTools.rst
> +Use Case 1:  Debugging An UI Application Freeze
```suggestion
Use Case 1:  Debugging an UI Application Freeze
```

2021-12-06 14:14 UTC, frivieremicroej commented on Tutorials/tutorialDiscoverEmbeddedDebuggingTools.rst
> +Use Case 2: Debugging A Hardfault
```suggestion
Use Case 2: Debugging a Hardfault
```

2021-12-06 14:14 UTC, frivieremicroej commented on Tutorials/tutorialDiscoverEmbeddedDebuggingTools.rst
> +When A Hardfault Occurs
```suggestion
When a Hardfault Occurs
```

2021-12-06 14:14 UTC, frivieremicroej commented on Tutorials/tutorialDiscoverEmbeddedDebuggingTools.rst
> +Extract Information And Coredump
```suggestion
Extract Information and Coredump
```

2021-12-06 14:14 UTC, frivieremicroej commented on Tutorials/tutorialDiscoverEmbeddedDebuggingTools.rst
> +Trigger A VM Dump
```suggestion
Trigger a VM Dump
```

2021-12-06 16:06 UTC, gjadi-mej commented on ApplicationDeveloperGuide/debug.rst
> +.. figure:: images/debug1.png
done

2021-12-06 16:26 UTC, gjadi-mej commented on ApplicationDeveloperGuide/debug.rst
> +.. figure:: images/debug1.png
Done

2021-12-06 16:26 UTC, gjadi-mej commented on Tutorials/tutorialDiscoverEmbeddedDebuggingTools.rst
> +* `LLJVM check integrity <https://forum.microej.com/t/architecture-7-13-check-integrity-utility/769/2>`_ is a low-level API to detect memory corruptions in native functions.
Done

2021-12-06 17:25 UTC, frivieremicroej requested changes

2021-12-06 17:25 UTC, frivieremicroej commented on Tutorials/tutorialDiscoverEmbeddedDebuggingTools.rst
> +- The MicroEJ Runtime stopped scheduling the Java threads.
bullet rendering issue

2021-12-06 17:25 UTC, frivieremicroej commented on Tutorials/tutorialDiscoverEmbeddedDebuggingTools.rst
> +* :ref:`Debug an application <application_debugger>` on simulator, add breakpoints, inspect stack frame, use step-by-step, etc.
```suggestion
* :ref:`Debug an Application <application_debugger>` on Simulator, add breakpoints, inspect stack frame, use step-by-step, etc.
```

2021-12-06 17:25 UTC, frivieremicroej commented on Tutorials/tutorialDiscoverEmbeddedDebuggingTools.rst
> +As a reminder, the architecture of the MicroEJ runtime is called green
add a link to https://docs.microej.com/en/feature-m0078ddg-308_tutorial_debug_applications/PlatformDeveloperGuide/coreEngine.html#architecture

2021-12-06 17:25 UTC, frivieremicroej commented on Tutorials/tutorialDiscoverEmbeddedDebuggingTools.rst
> +- Output information on the standard output ``System.out`` and use the :ref:`stack_trace_reader` to read and decode the MicroEJ stack traces.
# Tracing and Logging
-
-
-
# Runtime State Dump
1) Stack Trace Reader
2) LLMJVM_dump

# Memory Inspection
-

2021-12-07 11:06 UTC, gjadi-mej commented on Tutorials/tutorialDiscoverEmbeddedDebuggingTools.rst
> +- The MicroEJ Runtime stopped scheduling the Java threads.
fixed

2021-12-07 11:12 UTC, gjadi-mej commented on Tutorials/tutorialDiscoverEmbeddedDebuggingTools.rst
> +As a reminder, the architecture of the MicroEJ runtime is called green
done, there is a link in the next sentence.

2021-12-07 12:45 UTC, gjadi-mej commented on Tutorials/tutorialDiscoverEmbeddedDebuggingTools.rst
> +- Output information on the standard output ``System.out`` and use the :ref:`stack_trace_reader` to read and decode the MicroEJ stack traces.
done

2021-12-08 12:31 UTC, frivieremicroej commented on Tutorials/tutorialDebug.rst
> +* ARM Documentation Center http://infocenter.arm.com/help/index.jsp
I prefer either to remove it as it does not gives extra information or find a page in arm documentation center which explains faults

2021-12-08 12:52 UTC, frivieremicroej requested changes
3rd pass
some "reserved words" usage to be reviewed

but globally: 
- title, introduction,  general layout is approved
- Tools section is approved

Please also indicate who technically approved the content of use case 1 and use case 2 sections.

2021-12-08 12:52 UTC, frivieremicroej commented on Tutorials/tutorialDiscoverEmbeddedDebuggingToolsAndMethods.rst
> +Read more about the MicroEJ Runtime architecture in the :ref:`Platform Developer Guide <core_engine>`.
Remove "architecture" word to describe the threading model
```suggestion
As a reminder, the threading model implemented by MicroEJ runtime is called green thread: it defines a multi-threaded environment without relying on any native RTOS capabilities. 
Therefore, the whole Java threads run in a single RTOS task.
For more details, please refer to the :ref:`MicroEJ Core Engine<core_engine>` section.
```

2021-12-08 12:52 UTC, frivieremicroej commented on Tutorials/tutorialDiscoverEmbeddedDebuggingToolsAndMethods.rst
> +- The RTOS task that runs the MicroEJ runtime is never given CPU time (suspended or blocked).
the explanation of green thread appears after (as a reminder...) 
I think this should be explained before.

2021-12-08 12:52 UTC, frivieremicroej commented on Tutorials/tutorialDiscoverEmbeddedDebuggingToolsAndMethods.rst
> +- The RTOS task that runs the MicroEJ runtime is never given CPU time (suspended or blocked).
review usage of "MicroEJ runtime" everywhere: replace by "Core Engine" when speaking about the RTOS "task"
```suggestion
- The RTOS task that runs the Core Engine is never given CPU time (suspended or blocked).
```

2021-12-08 12:52 UTC, frivieremicroej commented on Tutorials/tutorialDiscoverEmbeddedDebuggingToolsAndMethods.rst
> +3. Check if the Java Scheduler properly schedules the MicroUI thread.
```suggestion
1. Check if the RTOS properly schedules the MicroEJ runtime task.
2. Check if the Core Engine properly schedules all Java threads.
3. Check if the Core Engine properly schedules the MicroUI thread.
```

2021-12-08 12:52 UTC, frivieremicroej commented on Tutorials/tutorialDiscoverEmbeddedDebuggingToolsAndMethods.rst
> +Check RTOS Scheduler Liveness
```suggestion
Check RTOS Tasks Scheduling
```

2021-12-08 12:52 UTC, frivieremicroej commented on Tutorials/tutorialDiscoverEmbeddedDebuggingToolsAndMethods.rst
> +Check Java Scheduler Liveness
```suggestion
Check Java Threads Scheduling
```

2021-12-08 12:52 UTC, frivieremicroej commented on Tutorials/tutorialDiscoverEmbeddedDebuggingToolsAndMethods.rst
> +    * What are the code sections for BSP and Java
Java what ? (Java must be followed by a word)

2021-12-08 12:52 UTC, frivieremicroej commented on Tutorials/tutorialDiscoverEmbeddedDebuggingToolsAndMethods.rst
> +    * Besides the Java immortals, what are the other intersection point between the Java and the BSP? (e.g. a temporary RAM buffer for JPEG decoder).
same comment Java what ?

2021-12-08 12:52 UTC, frivieremicroej commented on Tutorials/tutorialDiscoverEmbeddedDebuggingToolsAndMethods.rst
> +* Implement a CRC of the *hot sections* when entering/leaving all natives. *Hot Sections* are memory sections used by both the Java and native code (e.g. C or ASM).
```suggestion
* Implement a CRC of the *hot sections* when entering/leaving all natives. *Hot Sections* are memory sections used by both Java code and native code (e.g. C or ASM).
```

2021-12-08 12:52 UTC, frivieremicroej commented on Tutorials/tutorialDiscoverEmbeddedDebuggingToolsAndMethods.rst
> +        * sections where the Java and BSP are working together
Java what ? (Java must be followed by a word)

2021-12-09 13:19 UTC, gjadi-mej commented on Tutorials/tutorialDebug.rst
> +Debugging applications
Done

2021-12-09 13:19 UTC, gjadi-mej commented on Tutorials/tutorialDebug.rst
> +Solutions
Fixed

2021-12-09 13:20 UTC, gjadi-mej commented on Tutorials/tutorialDebug.rst
> +* ARM Documentation Center http://infocenter.arm.com/help/index.jsp
Removed.

2021-12-09 13:27 UTC, gjadi-mej commented on Tutorials/tutorialDiscoverEmbeddedDebuggingToolsAndMethods.rst
> +- The RTOS task that runs the MicroEJ runtime is never given CPU time (suspended or blocked).
I disagree.
First, because in the introduction I want the user to quickly understand if it is applicable to their use case.
Second, because the green thread explanation is not important there, it's a technical detail but all developers should be able to understand the sentence "RTOS task that runs the MicroEJ runtime".  The green thread explanation helps to understand why it may block the application.  But from an application or firmware developer point of view, both can understand that if the runtime has no CPU time, the application won't be executed.

2021-12-09 13:34 UTC, gjadi-mej commented on Tutorials/tutorialDiscoverEmbeddedDebuggingToolsAndMethods.rst
> +        * sections where the Java and BSP are working together
Added "Java application"

2021-12-09 14:03 UTC, gjadi-mej commented on Tutorials/tutorialDiscoverEmbeddedDebuggingToolsAndMethods.rst
> +    * What are the code sections for BSP and Java
Replaced by Application

2021-12-09 14:04 UTC, gjadi-mej commented on Tutorials/tutorialDiscoverEmbeddedDebuggingToolsAndMethods.rst
> +- The RTOS task that runs the MicroEJ runtime is never given CPU time (suspended or blocked).
Is MicroEJ Core Engine ok here?  To make sure the distinction between the RTOS and the Core Engine is clear.

2021-12-09 14:09 UTC, gjadi-mej commented
@frivieremicroej Use Case 1 : UI Freeze was written and reviewed with tpons, seon, apoudret and tvincent.
Use Case 2 : Hardfault was written and reviewed with smainchain.

2021-12-10 09:58 UTC, gjadi-mej commented on Tutorials/tutorialDiscoverEmbeddedDebuggingToolsAndMethods.rst
> +- The RTOS task that runs the MicroEJ runtime is never given CPU time (suspended or blocked).
It replaced `MicroEJ runtime`  with `MicroEJ Core Engine` here (and here only, I let `Core Engine` at the other location)

2021-12-10 16:41 UTC, frivieremicroej approved these changes

2021-12-10 16:41 UTC, merged