Feature/null analysis external annotations
MicroEJ/docs pull request #335
Opened 2021-11-04 14:18 UTC by tboue

split from https://github.com/MicroEJ/docs/pull/329 .
Part on java 8 won't be added because developers work with java 7.
Part on external-annotations is kept and moved to null annotation page.

2021-11-10 16:35 UTC, gjadi-mej requested changes
first round of review, I'll come back again later.

2021-11-10 16:35 UTC, gjadi-mej commented on ApplicationDeveloperGuide/nullAnalysis.rst
> +If you have multiple projects to configure, you can then copy the content of the ``.settings`` folder to another :ref:`module project <mmm_module_skeleton>`.
Replace `you` formulations with a passive sentence.

2021-11-10 16:35 UTC, gjadi-mej commented on ApplicationDeveloperGuide/nullAnalysis.rst
> +For instance : an ArrayList can contain null values, hence the `get(int)` method can return null values. However, this won't be taken into account by default during null analysis.
```suggestion
For instance : an ``ArrayList`` can contain null values, hence the `get(int)` method can return null values. However, this won't be taken into account by default during the null analysis.
```

2021-11-10 16:35 UTC, gjadi-mej commented on ApplicationDeveloperGuide/nullAnalysis.rst
> +Manually annotate the `get(int)` method return type with @Nullable allows to detect the potential null access:
rst uses double backquotes for the code not one (markdown)

2021-11-10 16:35 UTC, gjadi-mej commented on ApplicationDeveloperGuide/nullAnalysis.rst
> +It's also worth the try with automatic annotations if any problem is encountered.
What do you mean by this?

2021-11-12 12:28 UTC, tboue commented on ApplicationDeveloperGuide/nullAnalysis.rst
> +If you have multiple projects to configure, you can then copy the content of the ``.settings`` folder to another :ref:`module project <mmm_module_skeleton>`.
This part is constructed like a tutorial won't the `you` formulation be ok ?

2021-11-12 13:45 UTC, tboue commented
On hold : external annotations don't seem possible by default in MicroEJ's SDK with ej.annotation package

2022-01-31 10:31 UTC, tboue commented
Everything moved to private documentation because null annotations are already performed on MicroEJ's public libraries.

2022-01-31 10:31 UTC, closed without merging