Feature/m0090 ide 3586 sdk 5.5.0
MicroEJ/docs pull request #338
Opened 2021-11-15 10:31 UTC by frivieremicroej

2021-11-15 10:32 UTC, frivieremicroej commented on ApplicationDeveloperGuide/moduleNatures.rst
> +- :ref:`module_natures.plugins.artifact_checker` [#require_sdk_5_5]_
@tdelhomenie-microej remind first to merge https://github.com/MicroEJ/docs/pull/298

2021-11-15 14:13 UTC, tdelhomenie-microej requested changes

2021-11-22 09:55 UTC, tdelhomenie-microej commented on ApplicationDeveloperGuide/moduleNatures.rst
> +- :ref:`module_natures.plugins.artifact_checker` [#require_sdk_5_5]_
This PR is now obsolete since the changes have already been done in commit 2e4e313.

2021-11-22 09:55 UTC, tdelhomenie-microej approved these changes

2021-11-22 09:57 UTC, merged