M0078DDG-457 Document tracing method invocation.
MicroEJ/docs pull request #359
Opened 2022-01-11 09:51 UTC by dalgassimou

2022-01-13 15:16 UTC, frivieremicroej requested changes

2022-01-13 15:16 UTC, frivieremicroej commented on PlatformDeveloperGuide/advanceTrace.rst
> +Platform which use LD as linker
```suggestion
Platform using GNU LD linker
```

2022-01-13 15:16 UTC, frivieremicroej commented on PlatformDeveloperGuide/advanceTrace.rst
> +Platform which use ILINK as linker (IAR)
```suggestion
Platform using IAR ILINK linker
```

2022-01-13 15:16 UTC, frivieremicroej commented on PlatformDeveloperGuide/advanceTrace.rst
> +Pass the following options to the ILINK linker program
```suggestion
Add the following options to the ILINK linker command line:
```

2022-01-13 15:16 UTC, frivieremicroej commented on PlatformDeveloperGuide/advanceTrace.rst
> +Pass the following options to the LD linker program
```suggestion
Add the following options to the LD linker command line
```

2022-01-18 21:17 UTC, jerome-leroux requested changes

2022-01-18 21:17 UTC, jerome-leroux commented on PlatformDeveloperGuide/advanceTrace.rst
> +- ``LLMJVM_MONITOR_IMPL_on_return_method`` called at the end of the method invocation.
```suggestion
- ``LLMJVM_MONITOR_IMPL_on_return_method`` called when returning from the invoked method.
```

2022-01-18 21:17 UTC, jerome-leroux commented on PlatformDeveloperGuide/advanceTrace.rst
> +so these functions are not called by default when event tracing is enabled and started.
```suggestion
Calling these functions each time a method is invoked can slow down the whole application,
so these functions are not called by default when event tracing is enabled and started.
```

2022-01-18 21:17 UTC, jerome-leroux commented on PlatformDeveloperGuide/advanceTrace.rst
> +To activate them you need:
```suggestion
To activate them, you need to follow these steps:
```

2022-01-18 21:17 UTC, jerome-leroux commented on PlatformDeveloperGuide/advanceTrace.rst
> +MicroEJ allows method execution to be profiled, two new hooks functions are used for that:
```suggestion
MicroEJ allows method execution to be profiled. The following two new hooks functions are used for that:
```

2022-01-18 21:17 UTC, jerome-leroux commented on PlatformDeveloperGuide/advanceTrace.rst
> +Platform using GNU LD linker
```suggestion
Platforms using GNU LD linker
```

2022-01-18 21:17 UTC, jerome-leroux commented on PlatformDeveloperGuide/advanceTrace.rst
> +Platform using IAR ILINK linker
```suggestion
Platforms using IAR ILINK linker
```

2022-01-18 21:17 UTC, jerome-leroux commented on PlatformDeveloperGuide/advanceTrace.rst
> +Add the following options to the LD linker command line
```suggestion
Add the following options to the LD linker command line:
```

2022-02-07 21:17 UTC, jerome-leroux approved these changes

2022-02-08 13:15 UTC, frivieremicroej requested changes

2022-02-08 13:15 UTC, frivieremicroej commented on ApplicationDeveloperGuide/trace.rst
> +Advanced Event tracing
```suggestion
Advanced Event Tracing
```

2022-02-08 13:15 UTC, frivieremicroej commented on PlatformDeveloperGuide/advanceTrace.rst
> +MicroEJ allows method execution to be profiled. The following two new hooks functions are used for that:
```suggestion
MicroEJ Core Engine allows method execution to be profiled. The following two new hooks functions are used for that:
```

2022-02-08 13:15 UTC, frivieremicroej commented on PlatformDeveloperGuide/advanceTrace.rst
> +Calling these functions each time a method is invoked can slow down the whole application,
```suggestion
Calling these functions each time a method is invoked will slow down the application execution,
```

2022-02-08 13:15 UTC, frivieremicroej commented on PlatformDeveloperGuide/advanceTrace.rst
> +- Enable and start the trace see here https://docs.microej.com/en/latest/ApplicationDeveloperGuide/trace.html?highlight=trace#event-recording
turn to internal link

2022-02-14 12:54 UTC, frivieremicroej approved these changes

2022-02-14 12:55 UTC, merged