Remove resource center view
MicroEJ/docs pull request #368
Opened 2022-02-16 15:38 UTC by denisbedin

2022-02-16 16:10 UTC, tdelhomenie-microej requested changes

2022-02-16 16:10 UTC, tdelhomenie-microej commented on ApplicationDeveloperGuide/gettingStartedApp.rst
> -..
We should explain where to find the documentation now.

2022-02-16 16:10 UTC, tdelhomenie-microej commented on ApplicationDeveloperGuide/virtualDevice.rst
> -..
Same here, we should explain where to find the javadoc.

2022-02-18 14:58 UTC, tdelhomenie-microej requested changes

2022-02-21 15:43 UTC, tdelhomenie-microej requested changes

2022-02-21 15:43 UTC, tdelhomenie-microej commented on ApplicationDeveloperGuide/gettingStartedApp.rst
> +- Click :guilabel:`Run` : depending on your Platform :ref:`BSP connection <bsp_connection>`, the application, the runtime library and the header files are automatically deployed to your BSP.
I would instead add a step before with something like:
```
- Configure your BSP connection to define the deployment location of the application, the runtime library and the header files in :guilabel:`configuration` tab > :guilabel:`Device` > :guilabel:`Deploy`:
```
and add the screenshot here. WDYT ?

2022-02-21 15:43 UTC, tdelhomenie-microej commented on ApplicationDeveloperGuide/gettingStartedApp.rst
> +~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
If we add a title here, we should add a title for the first part, for example "Build the application".

2022-02-21 15:43 UTC, tdelhomenie-microej commented on ApplicationDeveloperGuide/gettingStartedApp.rst
> +In case of full :ref:`BSP connection <bsp_connection>`, the application link can be triggered by executing the :ref:`build script <bsp_connection_build_script>` file.
```suggestion
In case of full :ref:`BSP connection <bsp_connection>`, the application link can be triggered by executing the :ref:`build script <bsp_connection_build_script>` file:
```

2022-02-21 15:43 UTC, tdelhomenie-microej commented on ApplicationDeveloperGuide/gettingStartedApp.rst
> +In case of full :ref:`BSP connection <bsp_connection>`, the application link can be triggered by executing the :ref:`build script <bsp_connection_build_script>` file.
So what do I have to do in other cases ?

2022-02-21 15:43 UTC, tdelhomenie-microej commented on ApplicationDeveloperGuide/gettingStartedApp.rst
> +- Click :guilabel:`Apply` and :guilabel:`Run` : the final executable :guilabel:`application.out` file is generated and can now be deployed on your Device using the appropriate flash tool.
Can we add where is located the application.out file?

2022-02-22 13:59 UTC, tdelhomenie-microej requested changes

2022-02-22 13:59 UTC, tdelhomenie-microej commented on ApplicationDeveloperGuide/gettingStartedApp.rst
> +- Click :guilabel:`Run` : The application is compiled and the application, the runtime library and the header files are automatically deployed to the locations defined in your BSP connection.
```suggestion
- Click :guilabel:`Run` : The application is compiled and the application, the runtime library and the header files are automatically deployed to the locations defined in your BSP connection settings. 
```

2022-02-22 13:59 UTC, tdelhomenie-microej commented on ApplicationDeveloperGuide/gettingStartedApp.rst
> +    The MicroEJ platform header files (*.h) have been deployed to: '<relative_path>'.
`relative_path` does not help a lot, we don't know relative to what. Also please use `-` instead of `_` to be consistent.

2022-02-22 13:59 UTC, tdelhomenie-microej commented on ApplicationDeveloperGuide/gettingStartedApp.rst
> +The application link can be triggered by executing the :ref:`build script <bsp_connection_build_script>` file:
```suggestion
The application linking can be triggered by executing the :ref:`build script <bsp_connection_build_script>` file:
```

2022-02-23 09:41 UTC, frivieremicroej requested changes

2022-02-23 09:41 UTC, frivieremicroej commented on ApplicationDeveloperGuide/gettingStartedApp.rst
> +.. figure:: images/bsp-options.png
- wrap the checked option with a red rectangle
- screenshot to be taken gain (bad cropped window)

2022-02-23 14:03 UTC, denisbedin commented on ApplicationDeveloperGuide/gettingStartedApp.rst
> +Build the application
There is already a file named ``standaloneApplication.rst``. The file ``gettingStartedApp.rst`` has been renamed to ``standaloneApplicationTutorial.rst``

2022-02-23 14:06 UTC, denisbedin commented on ApplicationDeveloperGuide/gettingStartedApp.rst
> +- Select the :guilabel:`MicroEJ Application` > :guilabel:`HelloWorld` that is created by the previous chapter.
For a project named ``hello``, the launcher is not ``hello Main`` but ``Hello Main``.

2022-02-25 12:13 UTC, frivieremicroej approved these changes

2022-02-25 12:33 UTC, tdelhomenie-microej approved these changes

2022-02-25 12:33 UTC, merged