Feature/bluetooth
MicroEJ/docs pull request #371
Opened 2022-02-21 10:49 UTC by acmliramicroej

Introduce the bluetooth library documentation

2022-03-02 14:29 UTC, erkanaltanmicroej commented on PlatformDeveloperGuide/bluetooth.rst
>  they are pairing, bonding, requesting data, sending data, notifications
sending data and notifications.

2022-03-02 14:34 UTC, frivieremicroej requested changes

2022-03-02 14:34 UTC, frivieremicroej commented on PlatformDeveloperGuide/appendix/javalibs/bluetooth.rst
> +Bluetooth
Please migrate [PlatformDeveloperGuide/images/bluetooth-principle-diagram.png to latest design resource (ask @vrousseau)

2022-03-24 08:16 UTC, stephanemainchain commented on PlatformDeveloperGuide/bluetooth.rst
> +The MicroEJ Application manages the bluetooth connection using the
Bluetooth

2022-03-24 08:16 UTC, stephanemainchain commented on PlatformDeveloperGuide/bluetooth.rst
> +bluetooth library. The Bluetooth 2.0 (or BLE) concepts are available,
Bluetooth

2022-03-24 08:16 UTC, stephanemainchain commented on PlatformDeveloperGuide/bluetooth.rst
> +1. A peripheral device, like a wifi access point:
Wi-Fi

2022-03-24 08:16 UTC, stephanemainchain commented on PlatformDeveloperGuide/bluetooth.rst
> +2. A central device, like a Wifi station
Wi-Fi

2022-03-24 08:16 UTC, stephanemainchain commented on PlatformDeveloperGuide/bluetooth.rst
> +The bluetooth library depends on the bluetooth pack for the native
Bluetooth

2022-03-24 08:16 UTC, stephanemainchain commented on PlatformDeveloperGuide/bluetooth.rst
> +In addition, to qualify the port of the library, a Kernel API is needed:
Kernel API??

2022-04-14 11:53 UTC, apoudret-microej commented on PlatformDeveloperGuide/bluetooth.rst
> +- Every LLAPI must be implemented.
not true, the platformer can decide to port only the central role or the peripheral role. in that case the port can be validated using a second device which acts as the opposite role

2022-04-14 11:53 UTC, apoudret-microej commented on PlatformDeveloperGuide/bluetooth.rst
> +specifically Bluetooth Low Energy (BLE). Bluetooth Low Energy (BLE),
i suggest to put link to Bluetooth doc/wikipedia instead of putting generic information which is not specific to MicroEJ

2022-04-14 11:53 UTC, apoudret-microej commented on PlatformDeveloperGuide/bluetooth.rst
> +1. Peripheral starts advertising.
add empty line before to fix list formatting

2022-04-14 11:53 UTC, apoudret-microej commented on PlatformDeveloperGuide/bluetooth.rst
> +4. Central sends pairing request.
pairing is optional and is not part of the connection flow. you can separate the list into 2 lists (one for connection flower and one for pairing flow)

2022-04-14 11:53 UTC, apoudret-microej commented on PlatformDeveloperGuide/appendix/javalibs/bluetooth.rst
> +Error Messages
there are not error messages in bluetooth. the lib uses boolean return values and BluetoothStatus enum to indicate errors

2022-12-19 10:25 UTC, closed without merging

2022-12-19 10:26 UTC, frivieremicroej commented
Unfortunately, this PR is inactive for more than 6 months. Please reopen if someone wants to resume.