M0078DDG-467 Add Kernel in Module Natures page
MicroEJ/docs pull request #378
Opened 2022-03-08 13:56 UTC by tdelhomenie-microej

- I kept the alphabetical order for the Module Natures
- I did not factorized the properties with the Standalone Application nature since it would make it less readable IMO

2022-03-11 08:23 UTC, frivieremicroej requested changes

2022-03-11 08:23 UTC, frivieremicroej commented on ApplicationDeveloperGuide/moduleNatures.rst
> +------
```suggestion
Kernel Application
------------------
```

2022-03-11 08:23 UTC, frivieremicroej commented on ApplicationDeveloperGuide/moduleNatures.rst
> +   * - runtime.api.name
can you double check with @dalgassimou 
I though these options were mandatory unless you provide a runtime API module

2022-03-11 09:43 UTC, tdelhomenie-microej commented on ApplicationDeveloperGuide/moduleNatures.rst
> +------
Done

2022-03-14 08:00 UTC, dalgassimou commented on ApplicationDeveloperGuide/moduleNatures.rst
> +   * - runtime.api.name
The build-type firmware-multiapp is capable of loading a properties file found in the `kernelapi` conf.
And our runtime api (developer) provide a properties file, so yes the properties are mandantory unless you have a dependency in `kernelapi` conf which provides a properties file. and of course if this file contains the right properties.

2022-03-14 08:56 UTC, frivieremicroej approved these changes

2022-03-14 08:56 UTC, merged