M0090IDE-3762 Document how to override orgnisation/name/revision of a module
MicroEJ/docs pull request #379
Opened 2022-03-16 14:37 UTC by tdelhomenie-microej

Document how to override organisation/name/revision of a module. It also adds the property of the debug mode.

2022-03-17 15:53 UTC, frivieremicroej requested changes

2022-03-17 15:53 UTC, frivieremicroej commented on SDKUserGuide/mmm.rst
> +Build Execution Configuration
After thinking, I'm embarrassed with the term `execution` here because it is used for something strongly different in our environment

TBD with gradle notion

2022-03-17 15:53 UTC, frivieremicroej commented on SDKUserGuide/mmm.rst
> +When executing a build with MMM, system properties can be passed to the JVM:
use the term option or build option
System Properties is only the way for passing the options through MMM CLI (-D)

![image](https://user-images.githubusercontent.com/19801840/158838537-a9f67692-a27c-4f6c-98b4-b47c23f71e28.png)

2022-03-17 15:53 UTC, frivieremicroej commented on SDKUserGuide/mmm.rst
> +* in the SDK, by adding them in :guilabel:`Window` > :guilabel:`Preferences` > :guilabel:`Ant` > :guilabel:`Runtime` > :guilabel:`Properties`
this should be moved to [file:///C:/Users/user/Documents/Projects/cots/documentation/docs.microej.com/docs/_build/html/SDKUserGuide/mmm.html#options](https://docs.microej.com/en/latest/SDKUserGuide/mmm.html#options)

TBD

2022-03-17 15:53 UTC, frivieremicroej commented on SDKUserGuide/mmm.rst
> +Any custom system properties can be defined.
I believe we should merge https://docs.microej.com/en/latest/SDKUserGuide/mmm.html#options and https://docs.microej.com/en/latest/SDKUserGuide/mmm.html#build-options as a pull-up `Build Options` chapter 

And link to the keep https://docs.microej.com/en/latest/SDKUserGuide/mmm.html#options with only the GUI steps.

2022-03-17 15:56 UTC, frivieremicroej commented on SDKUserGuide/mmm.rst
> +* in command line, by using ``-D``, for example ``mmm build -Dmy.property=value``
also indicate it takes precedence over <ea:property notation/>

2022-03-18 07:26 UTC, tdelhomenie-microej commented on SDKUserGuide/mmm.rst
> +* in the SDK, by adding them in :guilabel:`Window` > :guilabel:`Preferences` > :guilabel:`Ant` > :guilabel:`Runtime` > :guilabel:`Properties`
You mean we add a new way to add options in the chapter [mmm.html#options](https://docs.microej.com/en/latest/SDKUserGuide/mmm.html#options) and we add link here to this chapter ?

2022-03-18 07:28 UTC, tdelhomenie-microej commented on SDKUserGuide/mmm.rst
> +When executing a build with MMM, system properties can be passed to the JVM:
So it should be:
```
When executing a build with MMM, build options can be passed as system properties:
```
to be consistent with the CLI help. ok for you?

2022-03-18 07:31 UTC, tdelhomenie-microej commented on SDKUserGuide/mmm.rst
> +Build Execution Configuration
You mean we should use `Build Configuration` ? If so, I think it confusing with the chapter name "MicroEJ Module Manager Configuration". We probably need to refactor a bit more the sections related to MMM configuration.

2022-07-01 09:26 UTC, frivieremicroej commented on SDKUserGuide/mmm.rst
> +When executing a build with MMM, system properties can be passed to the JVM:
Renamed to Build System Option

2022-07-01 09:28 UTC, frivieremicroej commented on SDKUserGuide/mmm.rst
> +* in command line, by using ``-D``, for example ``mmm build -Dmy.property=value``
No yet availabe (see M0090IDE-3424)

2022-07-01 09:36 UTC, frivieremicroej commented on SDKUserGuide/mmm.rst
> +Build Execution Configuration
Build System Options

2022-07-01 09:36 UTC, frivieremicroej commented on SDKUserGuide/mmm.rst
> +Build Execution Configuration
Build System Options

2022-07-01 09:37 UTC, frivieremicroej commented on SDKUserGuide/mmm.rst
> +When executing a build with MMM, system properties can be passed to the JVM:
Build System Options

2022-07-01 09:37 UTC, frivieremicroej approved these changes

2022-07-01 09:37 UTC, merged