Feature/m0078 ddg 459 document sdk content
MicroEJ/docs pull request #383
Opened 2022-04-08 11:08 UTC by frivieremicroej

- simply overview with product line overview only
- sdk content + big picture
- license EULA coverage

Draft: TODO friviere review the final schematics with design

2022-04-08 12:19 UTC, frivieremicroej commented
https://docs.microej.com/en/feature-m0078ddg-459_document_sdk_content

2022-04-19 12:19 UTC, tdelhomenie-microej requested changes

2022-04-19 12:19 UTC, tdelhomenie-microej commented on PlatformDeveloperGuide/runtime.rst
> +MicroEJ is compatible with the Java language version 7.
This information is very important for Application developers but I can't find it in the Application Developer Guide section, we should add it somewhere IMO.

2022-04-19 12:19 UTC, tdelhomenie-microej commented on PlatformDeveloperGuide/runtime.rst
> +     - http://e-s-r.net/download/specification/ESR-SPE-0001-BON-1.2-F.pdf
It is maybe beyond the scope of this PR but shouldn't we move the PDF files in https://github.com/MicroEJ/docs now ?

2022-04-19 12:19 UTC, tdelhomenie-microej commented on PlatformDeveloperGuide/runtime.rst
> +~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Same for EDC, we should add something in the Application Developer Guide to help the developer understand which standard APIs are available (and which are not).

2022-04-19 16:01 UTC, tdelhomenie-microej commented on overview/gettingStarted.rst
> +   -  Download and run a demo Application with a Virtual Device;
ok I understand, but I still think the term "Simulator" should be used somewhere here, it makes things more clear IMO, so maybe you can even both: "Download and run a demo Application in the Simulator with a Virtual Device" ?

2022-04-20 07:18 UTC, frivieremicroej commented on overview/gettingStarted.rst
>  .. figure:: images/2_download.png
I replaced "SDK Tools Software" to "Software Development Tools"

2022-04-20 10:34 UTC, frivieremicroej commented on overview/gettingStarted.rst
> +   -  Download and run a demo Application with a Virtual Device;
done

2022-04-20 10:34 UTC, frivieremicroej commented on overview/gettingStarted.rst
>     -  Deploy and run a demo Application on the board.
merged & clarified all steps

2022-04-20 10:34 UTC, frivieremicroej commented on overview/gettingStarted.rst
>     -  Build and run your first Application on target hardware.
merged & clarified all steps

2022-04-20 10:35 UTC, frivieremicroej commented on overview/gettingStarted.rst
> +   Getting Started General Components
SDK Workflow Overview

2022-04-20 10:35 UTC, frivieremicroej commented on overview/vee.rst
> +MicroEJ VEE is a scalable Virtual Execution Environment for resource-constrained embedded devices running on microcontrollers or microprocessors.
Good point. These was extracted from MKT main stream slides. I will check.

2022-04-20 10:37 UTC, frivieremicroej commented on PlatformDeveloperGuide/runtime.rst
> +     - http://e-s-r.net/download/specification/ESR-SPE-0001-BON-1.2-F.pdf
Out of scope (we are planning to reintegrate ESR document to MicroEJ documentation with legal - this is an other future topic)

2022-04-20 11:30 UTC, frivieremicroej commented on PlatformDeveloperGuide/runtime.rst
> +~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
OK I moved the whole runtime section to ADG, because the information targets the Java developer

2022-04-20 11:30 UTC, frivieremicroej commented on PlatformDeveloperGuide/runtime.rst
> +MicroEJ is compatible with the Java language version 7.
OK I moved the whole runtime section to ADG, because the information targets the Java developer

2022-04-20 15:29 UTC, frivieremicroej commented on overview/vee.rst
> +MicroEJ VEE is a scalable Virtual Execution Environment for resource-constrained embedded devices running on microcontrollers or microprocessors.
done

2022-04-22 07:29 UTC, tdelhomenie-microej commented on PlatformDeveloperGuide/runtime.rst
> +MicroEJ is compatible with the Java language version 7.
I think we need to rework this page, it mixes basic (java version, available APIs, ...) and advanced (scheduler, GC, ...) information for the developer. But that can probably be done in another ticket.

2022-04-22 08:10 UTC, tdelhomenie-microej commented on SDKUserGuide/licenses.rst
> +   :align: center
The sentence "Modules with SDK EULA License" is confusing IMO, it looks like all modules use this license. Maybe "including Modules with SDK EULA License"?

2022-04-22 08:10 UTC, tdelhomenie-microej commented on SDKUserGuide/index.rst
> +   :scale: 100%
We outline the scope of the SDK EULA license in this schema but we don't mention it anymore in the page, no explanation or no link. Maybe we should remove it since it is already described in the License section?

2022-04-22 10:14 UTC, frivieremicroej commented on SDKUserGuide/index.rst
> +   :scale: 100%
As discussed, here we speak about "general repositories" not only binary repositories. Github repositories contains MicroEJ modules in source form, whereas Central Repository contains MicroEJ modules in binary form.

2022-04-22 10:18 UTC, frivieremicroej commented on PlatformDeveloperGuide/runtime.rst
> +MicroEJ is compatible with the Java language version 7.
yes, so far I just moved "advanced" GC & Scheduler sections after core libraries
Also stored our discussion abour the SDk fragmentation here M0078DDG-474

2022-04-22 10:25 UTC, frivieremicroej commented on SDKUserGuide/licenses.rst
> +   :align: center
done

2022-04-22 10:41 UTC, frivieremicroej commented on SDKUserGuide/index.rst
> +   :scale: 100%
done

2022-04-22 12:07 UTC, tdelhomenie-microej approved these changes

2022-04-22 12:39 UTC, merged