Feature/m0078 ddg 171 application resources
MicroEJ/docs pull request #385
Opened 2022-04-22 15:53 UTC by gjadi-mej

2022-04-25 07:54 UTC, gbalan-microej commented on ApplicationDeveloperGuide/applicationResources.rst
> +-  Internal resource: The resource is taken into consideration during the MicroEJ Application build.
lots of mentions of "MicroEJ" xxx: should we remove that prefix now, right?

2022-04-25 07:54 UTC, gbalan-microej commented on ApplicationDeveloperGuide/applicationResources.rst
> +-  External resource: The resource is not taken into consideration by MicroEJ.
not microej but by the application build ?

2022-04-25 07:54 UTC, gbalan-microej commented on ApplicationDeveloperGuide/applicationResources.rst
> +   See :ref:`section_externalresourceloader` for more information on the its implementation.
"on the its" ?

2022-04-25 07:54 UTC, gbalan-microej commented on ApplicationDeveloperGuide/applicationResources.rst
I think it misses a comment about the list file format (property format, path separator). It is already descried in chapters images, fonts and nls. Maybe some notions can be shared?

2022-04-25 07:54 UTC, gbalan-microej commented on ApplicationDeveloperGuide/applicationResources.rst
>  Overview
this subsection seems useless

2022-04-25 07:54 UTC, gbalan-microej commented on ApplicationDeveloperGuide/applicationResources.rst
>  Overview
this subsection seems useless

2022-04-25 07:54 UTC, gbalan-microej commented on ApplicationDeveloperGuide/applicationResources.rst
there is another chapter that mentions the nls external resources: https://docs.microej.com/en/feature-m0078ddg-171_application_resources/ApplicationDeveloperGuide/nlsExternalLoader.html

2022-04-25 07:54 UTC, gbalan-microej commented on ApplicationDeveloperGuide/applicationResources.rst
actually it is strange: for images and fonts, there is a dedicated short chapter. It is a sump-up; ti have more information, go to the chapter XXX

for nls: the chapter is the full NLS chapter: how it works etc. May be have to extract that in a NLS chapter ?

2022-04-25 07:54 UTC, gbalan-microej commented on ApplicationDeveloperGuide/applicationResources.rst
> +Raw Resources
basic resources == nominal case ? In this case, may be this chapter should be the first one ?

2022-04-25 07:54 UTC, gbalan-microej commented on PlatformDeveloperGuide/externalResourceLoader.rst
> +See :ref:`chapter.microej.applicationResources` for more information on how to declare external resources.
- declare and use external resources ? 
- make the distinction between internal and external resources ?

2022-06-10 12:25 UTC, gjadi-mej commented on ApplicationDeveloperGuide/applicationResources.rst
> +-  Internal resource: The resource is taken into consideration during the MicroEJ Application build.
yes, done.

2022-06-10 12:26 UTC, gjadi-mej commented on ApplicationDeveloperGuide/applicationResources.rst
> +   See :ref:`section_externalresourceloader` for more information on the its implementation.
fixed

2022-06-10 12:26 UTC, gjadi-mej commented on ApplicationDeveloperGuide/applicationResources.rst
>  Overview
fixed

2022-06-10 12:26 UTC, gjadi-mej commented on ApplicationDeveloperGuide/applicationResources.rst
>  Overview
removed

2022-06-10 12:27 UTC, gjadi-mej commented on ApplicationDeveloperGuide/applicationResources.rst
maybe. Do you have some idea on where to put the NLS chapter?

2022-06-10 12:34 UTC, gjadi-mej commented on PlatformDeveloperGuide/externalResourceLoader.rst
> +See :ref:`chapter.microej.applicationResources` for more information on how to declare external resources.
I rephrased it a bit, is it better?

2022-06-13 05:07 UTC, gbalan-microej commented on ApplicationDeveloperGuide/applicationResources.rst
> +-  Internal resource: The resource is taken into consideration during the MicroEJ Application build.
remains "MicroEJ":

- MicroEJ Classpath: to discuss
- MicroEJ Font
- MicroEJ application

2022-06-13 14:42 UTC, gjadi-mej commented on ApplicationDeveloperGuide/applicationResources.rst
> +-  Internal resource: The resource is taken into consideration during the MicroEJ Application build.
should be done now :)

2022-06-13 14:45 UTC, gjadi-mej commented on ApplicationDeveloperGuide/UI/MicroUI/fonts.rst
> +Fonts are declared in :ref:`MicroEJ Classpath<chapter.microej.classpath>` ``*.fonts.list`` files (or ``*.fontsext.list`` for an external resource, see :ref:`section.applicationResources.internal_and_
done

2022-06-13 14:45 UTC, gjadi-mej commented on ApplicationDeveloperGuide/UI/MicroUI/images.rst
> +Immutable images are declared in :ref:`MicroEJ Classpath<chapter.microej.classpath>` ``*.images.list`` files (or ``*.imagesext.list`` for an external resource, see :ref:`section.applicationResources.
done

2022-06-13 14:45 UTC, gjadi-mej commented on ApplicationDeveloperGuide/applicationResources.rst
> +Raw Resources are declared in MicroEJ Classpath using ``*.resources.list`` files (and in ``*.externresources.list`` for external resources).
done

2022-06-13 14:46 UTC, gjadi-mej commented
https://github.com/MicroEJ/docs/pull/385#discussion_r895346576 done

2022-06-16 05:41 UTC, gbalan-microej commented on ApplicationDeveloperGuide/applicationResources.rst
> +      type -> internalRaw
I think it would be better if the raw resource (nominal case) was the first block on the left: raw, image, font, nls

2022-06-16 05:41 UTC, gbalan-microej commented on ApplicationDeveloperGuide/applicationResources.rst
> +      type -> internalRaw
do not forget to update the text just before:
```
(...) files depending on the type (raw, image, font, NLS) and kind (...) 
```

2022-06-16 08:56 UTC, gjadi-mej commented on ApplicationDeveloperGuide/applicationResources.rst
> +      type -> internalRaw
done

2022-06-27 11:55 UTC, frivieremicroej requested changes

2022-06-27 11:55 UTC, frivieremicroej commented on ApplicationDeveloperGuide/UI/ui.rst
> +   NLS/nls
I don't remember why we moved 
(there was already a section in Application Resources)
Also I don't see the file removal in the menus. TBD

2022-06-27 11:55 UTC, frivieremicroej commented on ApplicationDeveloperGuide/classpath.rst
> -Raw Resources
Keep a section `Resources` and point to application resources

2022-06-27 14:03 UTC, gbalan-microej commented on ApplicationDeveloperGuide/UI/ui.rst
> +   NLS/nls
do not explain how NLS works under "resources" chapter, but in a dedicated chapter like images a& fonts

2022-06-27 16:27 UTC, tdelhomenie-microej reviewed
@gjadi-mej @gbalan-microej the latest build fails : https://readthedocs.com/projects/microej-docs/builds/981409/

2022-06-27 16:27 UTC, tdelhomenie-microej commented on ApplicationDeveloperGuide/applicationResources.rst
> +=======================
It seems this chapter duplicates most of the content of the Usage chapter of the NLS section moved to UI/NLS. I find it frustrating to explain almost all steps but not all, and redirect to another page that lists again the same steps with the missing ones. IMO we should either leave all of the steps here, or sum-up what is NLS with just words (no examples), and redirect to the detailed section with all the steps. I would also avoid to duplicate content.

2022-06-27 16:27 UTC, tdelhomenie-microej commented on ApplicationDeveloperGuide/UI/NLS/nls.rst
> +=======================
Is NLS only related to UI? I guess it is mostly used in this use case, but it think it is not limited to it.

2022-06-28 05:07 UTC, gbalan-microej commented
> @gjadi-mej @gbalan-microej the latest build fails : https://readthedocs.com/projects/microej-docs/builds/981409/

@tdelhomenie-microej it seems it is a RTD issue, same issue in other doc: https://readthedocs.com/projects/microej-docs/builds/990785/ and no issue with a local build...

@gjadi-mej you rebase the branch with master ?

2022-06-28 05:11 UTC, gbalan-microej commented on ApplicationDeveloperGuide/classpath.rst
> -Raw Resources
done

2022-06-28 08:46 UTC, tdelhomenie-microej commented
@gbalan-microej @gjadi-mej after a rebase, thanks to the latest changes in the build, the error is more explicit : https://readthedocs.com/projects/microej-docs/builds/993335/
This is due to the link to forge:
```
(line   15) ok        https://www.gnu.org/software/gettext/manual/gettext.html#PO-Files
(line   57) ok        https://repository.microej.com/javadoc/microej_5.x/apis/ej/nls/NLS.html#getMessage-int-
(line  102) broken    https://forge.microej.com/artifactory/webapp/#/artifacts/browse/tree/General/microej-central-repository-release/com/microej/library/runtime/nls-po - Anchor '/artifacts/browse/tree/General/microej-central-repository-release/com/microej/library/runtime/nls-po' not found
writing output... [ 10%] ApplicationDeveloperGuide/UI/Widgets/index
```
https://github.com/MicroEJ/docs/pull/385/files#diff-219b33335594de148bfe4df8ff38c54499a3b0bf5a319ec53b20979f97b3fd82R102

We should probably use the Central Repository link instead : https://repository.microej.com/modules/com/microej/library/runtime/nls-po/2.3.0/

2022-06-28 09:11 UTC, tdelhomenie-microej commented
@gbalan-microej @gjadi-mej I did a test on another branch, the build is ok : https://readthedocs.com/projects/microej-docs/builds/993367/

2022-06-28 09:24 UTC, tdelhomenie-microej commented on ApplicationDeveloperGuide/UI/NLS/nls.rst
> +=======================
That's why we kept everything in Application Resources, not restricted to UI, no duplication.

2022-06-29 04:52 UTC, gbalan-microej commented on ApplicationDeveloperGuide/UI/NLS/nls.rst
> +=======================
- IMO the content of NLS section (how NLS is working) should be outside the "Resources" section. The "Resources" section explains only the "Resources" concepts (types, differences). A dedicated chapter NLS is a better solution.
- The NLS chapter has been moved in UI section (@frivieremicroej idea). 
- Another idea is to put it just after the GUI section and swap JavaScript & Networking sections: GUI/NLS/Networking/JavaScript...

2022-06-29 04:55 UTC, gbalan-microej commented
> @gbalan-microej @gjadi-mej I did a test on another branch, the build is ok : https://readthedocs.com/projects/microej-docs/builds/993367/

TY Thomas. Result is ok https://docs.microej.com/en/feature-test-nls/ApplicationDeveloperGuide/applicationResources.html

2022-06-29 08:34 UTC, tdelhomenie-microej commented on ApplicationDeveloperGuide/UI/NLS/nls.rst
> +=======================
> IMO the content of NLS section (how NLS is working) should be outside the "Resources" section. The "Resources" section explains only the "Resources" concepts (types, differences). A dedicated chapter NLS is a better solution.

Having a dedicated chapter NLS is fine for me, but I am still bothered by the duplication. IMO we put too much details in the "Resources" section.

> Another idea is to put it just after the GUI section and swap JavaScript & Networking sections: GUI/NLS/Networking/JavaScript...

Looks good to me.
I often use the Android documentation for inspiration, that's why I proposed to put everything about NLS in the "Resources" section : https://developer.android.com/guide/topics/resources/localization But that looks good also to have a dedicated chapter.

2022-07-07 15:19 UTC, frivieremicroej approved these changes

2022-07-11 09:13 UTC, merged