Explain Class Extender
MicroEJ/docs pull request #387
Opened 2022-04-28 08:14 UTC by bguedas

2022-05-17 08:22 UTC, frivieremicroej commented
@bguedas please review my changes and add a small section to introduce the purpose of class extensions and refer to the xxx section of the class extender tool for usage

2022-05-17 08:23 UTC, frivieremicroej requested changes

2022-05-17 08:23 UTC, frivieremicroej commented on KernelDeveloperGuide/runtimeEnvironment.rst
> +.. _runtime_environment:
@bguedas please 
- review my changes 
- add a small section to introduce the purpose of class extensions and refer to the xxx section of the class extender tool for usage

2022-05-20 08:42 UTC, frivieremicroej commented
Doc link https://docs.microej.com/en/feature-class_extender/

2022-05-20 09:51 UTC, bguedas reviewed
Reviewed, just a small change.

2022-05-20 09:51 UTC, bguedas commented on KernelDeveloperGuide/runtimeEnvironment.rst
> +- A JAR file with the aggregate set of ``kernel.api`` files, used by Kernel projects to expose APIs when building the Firmware and the Virtual Device.
```suggestion
- A JAR file with the aggregate set of ``kernel.api`` files, used by Kernel projects to expose APIs when building the Firmware and the Virtual Device;
```

2022-05-20 10:28 UTC, bguedas commented on KernelDeveloperGuide/runtimeEnvironment.rst
> +.. _runtime_environment:
Document is reviewed, I only suggest a minor change (use `;` instead of `.` at the end of the second item of list of three).

I also added a section about class extension. Not sure it is exactly what you expected.

2022-05-20 16:21 UTC, tdelhomenie-microej requested changes

2022-05-20 16:21 UTC, tdelhomenie-microej commented on KernelDeveloperGuide/runtimeEnvironment.rst
> +   </dependencies>
We can also mention that we can add libraries in dependencies (not only kernel apis) in order to control the version of the library.

2022-05-20 16:21 UTC, tdelhomenie-microej commented on KernelDeveloperGuide/runtimeEnvironment.rst
> +   1. The custom Runtime Environment is built using the ``runtime-api`` build type. It takes three components as input:
```suggestion
   1. The custom Runtime Environment is built using the ``build-runtime-api`` build type. It takes three components as input:
```

2022-05-20 16:21 UTC, tdelhomenie-microej commented on KernelDeveloperGuide/runtimeEnvironment.rst
> +
We should give an example here, for example by mentioning the String.split use case.

2022-05-20 16:21 UTC, tdelhomenie-microej commented on KernelDeveloperGuide/runtimeEnvironment.rst
> +      - the String extension Add-On library jar file
Where does this jar comes from? If I understand correctly we should explain that the extended class must be packaged in a module before.

2022-05-20 16:21 UTC, tdelhomenie-microej commented on KernelDeveloperGuide/runtimeEnvironment.rst
> +      - a new ``String.java`` API source file in the ``src/main/java`` folder, which includes new methods with their Javadoc specification.
The extended String class should be provided as source in the Runtime Environment project and in a module to extend the implementation, right ?

2022-05-20 16:21 UTC, tdelhomenie-microej commented on KernelDeveloperGuide/runtimeEnvironment.rst
> +   - (**if it is a class method**) add ``isStatic=true`` to the ``@Extended`` annotation parameters
Is it `@Extended` or `@Extend` ?

2022-05-20 16:21 UTC, tdelhomenie-microej commented on KernelDeveloperGuide/runtimeEnvironment.rst
> +
We should add a basic example here IMO, the developer should be able to copy paste the code and built a basic extended API.

2022-05-20 16:21 UTC, tdelhomenie-microej commented on KernelDeveloperGuide/kernelCreation.rst
> +This is the preferred way in case you intend to build and maintain a dedicated Applications ecosystem.
Very good explanation 👍 It should probably be moved in the Overview part since it is one of the core concept of kernels.

2022-05-23 14:46 UTC, frivieremicroej commented on KernelDeveloperGuide/runtimeEnvironment.rst
> +   - (**if it is a class method**) add ``isStatic=true`` to the ``@Extended`` annotation parameters
Please link to javadoc

2022-05-25 09:43 UTC, frivieremicroej commented on KernelDeveloperGuide/runtimeEnvironment.rst
> +   | Copyright 2008-2022, MicroEJ Corp. Content in this space is free
@tdelhomenie-microej to explain
- how to declare the runtime env in application
- add a warning with transitively fetched libraries built on an other runtime env root (central repo) - use transitive if you are sure that the dependencies are met
- how to declare the runtime env in kernel

2022-06-17 15:33 UTC, tdelhomenie-microej commented on KernelDeveloperGuide/runtimeEnvironment.rst
> +It is built by aggregating a set of :ref:`Kernel APIs <kernel.api>`. It also allows to extend the classes of default modules with additional methods.
I removed the sentence.

2022-06-17 15:40 UTC, tdelhomenie-microej commented on KernelDeveloperGuide/runtimeEnvironment.rst
> +- A JAR file with the aggregate set of ``kernel.api`` files, used by Kernel projects to expose APIs when building the Firmware and the Virtual Device.
Documentation updated.

2022-06-17 15:41 UTC, tdelhomenie-microej commented on KernelDeveloperGuide/runtimeEnvironment.rst
> +- A ZIP file with the Javadoc of the APIs for documentation.
Documentation updated, we keep a JAR for the javadoc.

2022-06-17 15:45 UTC, tdelhomenie-microej commented on KernelDeveloperGuide/runtimeEnvironment.rst
> +   1. The custom Runtime Environment is built using the ``runtime-api`` build type. It takes three components as input:
Done.

2022-06-17 15:45 UTC, tdelhomenie-microej commented on KernelDeveloperGuide/runtimeEnvironment.rst
> +A Runtime Environment :ref:`module project <mmm_module_skeleton>` is built with ``runtime-api`` skeleton.
Done.

2022-06-17 15:46 UTC, tdelhomenie-microej commented on KernelDeveloperGuide/runtimeEnvironment.rst
> +      - a new ``String.java`` API source file in the ``src/main/java`` folder, which includes new methods with their Javadoc specification.
Right :)

2022-06-20 11:42 UTC, tdelhomenie-microej commented on KernelDeveloperGuide/runtimeEnvironment.rst
> +A Runtime Environment is a :ref:`module nature <module_natures>` for defining the set of APIs available to an Application developer on a Kernel.
Done.

2022-06-20 12:10 UTC, tdelhomenie-microej commented on KernelDeveloperGuide/runtimeEnvironment.rst
> +   </dependencies>
Done.

2022-06-20 12:43 UTC, tdelhomenie-microej commented on KernelDeveloperGuide/runtimeEnvironment.rst
> +   - (**if it is a class method**) add ``isStatic=true`` to the ``@Extended`` annotation parameters
Done.

2022-06-20 16:27 UTC, bguedas reviewed
Titles should be capitalized

2022-06-20 16:27 UTC, bguedas commented on KernelDeveloperGuide/runtimeEnvironment.rst
> +Kernel APIs as dependencies
```suggestion
Kernel APIs as Dependencies
```

2022-06-20 16:27 UTC, bguedas commented on KernelDeveloperGuide/runtimeEnvironment.rst
> +Kernel APIs as project file
```suggestion
Kernel APIs as Project File
```

2022-06-21 16:12 UTC, tdelhomenie-microej commented on KernelDeveloperGuide/runtimeEnvironment.rst
> +Kernel APIs as dependencies
Done

2022-06-21 16:12 UTC, tdelhomenie-microej commented on KernelDeveloperGuide/runtimeEnvironment.rst
> +Kernel APIs as project file
Done

2022-06-27 08:55 UTC, frivieremicroej reviewed
+ few rewording pushed
@tdelhomenie-microej let's schedule a session to finish together

2022-06-27 08:55 UTC, frivieremicroej commented on KernelDeveloperGuide/runtimeEnvironment.rst
> +  used by Kernel projects to fetch all the ``kernel.api`` files (by transitivity) to expose APIs when building the Firmware and the Virtual Device;
This sentence is too long (I suggest to remove the fetch since it is described in details in `Kernel APIs as dependencies` section


```suggestion
- A JAR file with the ``kernel.api`` file defined in the module (if any), used by Kernel projects to expose APIs when building the Firmware and the Virtual Device;
```

2022-06-27 08:55 UTC, frivieremicroej commented on KernelDeveloperGuide/runtimeEnvironment.rst
> +It is also possible to force the version of the libraries to use by declaring them as direct dependencies.
Explain why it is interesting to fetch a latest version:

```suggestion
It is also possible to force the version of the libraries to use by declaring them as direct dependencies.
This is typically used to get a latest version of the library with documentation improvements such as Javadoc or Null Analysis annotations.
```

2022-06-27 08:55 UTC, frivieremicroej commented on KernelDeveloperGuide/runtimeEnvironment.rst
> +the recommended process is to add this library in the Runtime Environment.
I do not agree with the recommended process, I suggest such reformulation to be discussed
```
.. note::

   Although you can declare any library dependencies, it is highly recommended to declare only dependencies that depend on this Runtime Environment.
   Otherwise this could lead to inconsistent situations, for example by using an API not available at runtime.
   In case an Application needs to use a library not included in the Runtime Environment, the recommended process is
   to rebuild this library from its sources and change its dependencies to the Runtime Environment dependency.
```

2022-07-04 15:46 UTC, frivieremicroej commented on KernelDeveloperGuide/runtimeEnvironment.rst
> +   - (**if it is a class method**) add ``isStatic=true`` to the ``@Extended`` annotation parameters
Class Extender 1.0.5 README has been improved, to be published to Central Repo

2022-07-04 16:02 UTC, frivieremicroej commented on KernelDeveloperGuide/kernelCreation.rst
> +This is the preferred way in case you intend to build and maintain a dedicated Applications ecosystem.
OK both agree to let it as is in the "didactic" Kernel creation page

2022-07-04 16:24 UTC, frivieremicroej approved these changes

2022-07-05 06:32 UTC, tdelhomenie-microej approved these changes

2022-07-05 06:32 UTC, merged