Feature/M0090IDE-3865_javafx_documentation
MicroEJ/docs pull request #388
Opened 2022-04-29 10:19 UTC by denisbedin

2022-04-29 15:06 UTC, tdelhomenie-microej requested changes

2022-04-29 15:06 UTC, tdelhomenie-microej commented on PlatformDeveloperGuide/mock.rst
> +To ensure Mac Aarch64 support, the JavaFX Module is based on JavaFX 17 which requires a JDK 11, so it can not be used with a JDK 1.8.
Even without the support of the Mac M1, we cannot use it with a JDK 8 since there is no version for the JDK, no?

2022-04-29 15:06 UTC, tdelhomenie-microej commented on PlatformDeveloperGuide/mock.rst
> +The JavaFX Module allows the use of `JavaFX <https://openjfx.io/>`_ in the creation of a Mock project or to embed JavaFX in a Platform.
We can add a link to the official JavaFX site on the first occurrence of the JavaFX word.

2022-04-29 16:09 UTC, denisbedin commented on PlatformDeveloperGuide/mock.rst
> +To ensure Mac Aarch64 support, the JavaFX Module is based on JavaFX 17 which requires a JDK 11, so it can not be used with a JDK 1.8.
Yes , this sentence has been removed

2022-04-29 16:11 UTC, denisbedin commented on PlatformDeveloperGuide/mock.rst
> +The JavaFX Module allows the use of `JavaFX <https://openjfx.io/>`_ in the creation of a Mock project or to embed JavaFX in a Platform.
The JavaFX section has been simplified. It was not needed to create two parts for each artifact (jar and rip).

2022-05-02 07:28 UTC, tdelhomenie-microej requested changes

2022-05-02 07:28 UTC, tdelhomenie-microej commented on PlatformDeveloperGuide/mock.rst
> +`JavaFX <https://openjfx.io/>`_ is a platform for creating Java applications with a modern user interface that is highly portable. It can be used to quickly create mocks for your Platform.
```suggestion
`JavaFX <https://openjfx.io/>`_ is a platform for creating Java applications with a modern user interface that is highly portable. It can be used to quickly create graphical mocks for your Platform.
```

2022-05-02 07:28 UTC, tdelhomenie-microej commented on PlatformDeveloperGuide/mock.rst
> +- Until the version 1.8, JavaFX is bundled in the Oracle JDK, so this version allows you to use it right now in your project.
```suggestion
- Until the version 1.8, the Oracle JDK contains JavaFX, so this version allows you to use it right now in your project.
```

2022-05-02 07:28 UTC, tdelhomenie-microej commented on PlatformDeveloperGuide/mock.rst
> +- To use JavaFX with the JDK 11, the additional dependency must be added in your Mock project as well as your Platform project :
```suggestion
- To use JavaFX with the JDK 11, this additional dependency must be added in your Mock project as well as your Platform project :
```

2022-05-02 07:28 UTC, tdelhomenie-microej commented on PlatformDeveloperGuide/mock.rst
> +
I think we should move this chapter at the end, after the `Use` section, since it is optional.

2022-05-02 08:12 UTC, denisbedin commented on PlatformDeveloperGuide/mock.rst
> +
The JavaFX section has been moved and the suggested changes have been applied.

2022-05-02 08:30 UTC, tdelhomenie-microej approved these changes

2022-05-11 09:47 UTC, apoudret-microej commented on PlatformDeveloperGuide/mock.rst
> +    <dependency org="com.microej.tool" name="javafx" rev="1.1.0" />
is it on central repo?

2022-05-11 11:58 UTC, tdelhomenie-microej commented on PlatformDeveloperGuide/mock.rst
> +    <dependency org="com.microej.tool" name="javafx" rev="1.1.0" />
Not yet. We plan to reduce the size of the rip before publishing it to central repository (should be done in the coming days).

2022-05-16 07:38 UTC, frivieremicroej commented on PlatformDeveloperGuide/mock.rst
> +    <dependency org="com.microej.tool" name="javafx" rev="1.1.0" />
@denisbedin please move to developer repo instead

2022-05-16 08:48 UTC, frivieremicroej requested changes

2022-05-16 08:48 UTC, frivieremicroej commented on PlatformDeveloperGuide/mock.rst
> +`JavaFX <https://openjfx.io/>`_ is a platform for creating Java applications with a modern user interface that is highly portable. It can be used to quickly create graphical Mocks for your Platform.
I suggest to remove application & platform terms to avoid confusion

```suggestion
`JavaFX <https://openjfx.io/>`_ is an open-source library for creating modern Java user interfaces that is highly portable. It can be used to quickly create graphical Mocks for your Platform.
```

2022-05-16 08:48 UTC, frivieremicroej commented on PlatformDeveloperGuide/mock.rst
> +- To use JavaFX with the JDK 11, this additional dependency must be added in your Mock project as well as your Platform project :
We should clarify the dependency purpose:
- in Mock project, this is a compile-time dependency (the content is not included in the mock module)
- then it must be added to the Platform project if your platform contains at least one mock (the content will be added to the platform module)

am I right ?

2022-05-16 08:48 UTC, frivieremicroej commented on PlatformDeveloperGuide/mock.rst
> +- Until the version 1.8, the Oracle JDK contains JavaFX, so this version allows you to use it right now in your project.
```suggestion
- If your SDK is running on JDK 8, the Oracle JDK contains JavaFX, so this version allows you to use it right now in your project.
```

2022-05-16 08:48 UTC, frivieremicroej commented on PlatformDeveloperGuide/mock.rst
> +- To use JavaFX with the JDK 11, this additional dependency must be added in your Mock project as well as your Platform project :
```suggestion
- Until the version 1.8, the Oracle JDK contains JavaFX, so this version allows you to use it right now in your project.

- If your SDK is running on JDK 11, JavaFX must be added as an additional dependency to your Mock and Platform project. For that, MicroEJ Corp. provides a ready-to-use packaged module for all supported OS versions.
```

2022-05-20 12:15 UTC, frivieremicroej commented on PlatformDeveloperGuide/mock.rst
> +    <dependency org="com.microej.tool" name="javafx" rev="1.1.0" />
please ask @gharelMicroEJ for a release

2022-05-20 12:17 UTC, frivieremicroej approved these changes

2022-05-25 07:04 UTC, merged