M0137W-660 Add section for Platform Publication
MicroEJ/docs pull request #390
Opened 2022-05-03 10:05 UTC by tdelhomenie-microej

2022-05-04 14:21 UTC, frivieremicroej requested changes
approve

2022-05-04 14:21 UTC, frivieremicroej commented on PlatformDeveloperGuide/platformCreation.rst
> +The publication of the built Platform to an artifact repository is disabled by default.
The publication of the built Platform to a [module repository](link to module repository) is disabled by default.

2022-05-04 15:44 UTC, tdelhomenie-microej commented on PlatformDeveloperGuide/platformCreation.rst
> +The publication of the built Platform to an artifact repository is disabled by default.
Done

2022-05-04 15:45 UTC, tdelhomenie-microej commented
> approve

@frivieremicroej please approve it, so I can merge it.

2022-05-05 12:00 UTC, frivieremicroej approved these changes

2022-05-05 12:00 UTC, merged