M0127CC-568 Building a MicroEJ Firmware
MicroEJ/docs pull request #40
Opened 2020-05-07 15:35 UTC by gjadi-mej

2020-05-12 13:14 UTC, stephanemainchain commented on Tutorials/tutorialBuildingMicroEJFirmware.rst
> +* MicroEJ SDK 4.x is installed with an activated license (evaluation license or production license).
MicroEJ SDK 5

2020-05-12 13:53 UTC, gjadi-mej commented on Tutorials/tutorialBuildingMicroEJFirmware.rst
> +* MicroEJ SDK 4.x is installed with an activated license (evaluation license or production license).
Fixed.

2020-09-24 20:33 UTC, jerome-leroux requested changes

2020-09-24 20:33 UTC, jerome-leroux commented on Tutorials/tutorialUnderstandMicroEJFirmwareBuild.rst
> +The list of supported MicroEJ Architectures can be found here
```suggestion
You can find the list of supported MicroEJ Architectures here
```

2020-09-24 20:33 UTC, jerome-leroux commented on Tutorials/tutorialUnderstandMicroEJFirmwareBuild.rst
> +Depending on the requirements of the project, the MicroEJ Platform can
```suggestion
Depending on the project's requirements, the MicroEJ Platform can
```

2020-09-24 20:33 UTC, jerome-leroux commented on Tutorials/tutorialUnderstandMicroEJFirmwareBuild.rst
> +be connected in various ways to the BSP, see :ref:`bsp_connection` for
```suggestion
be connected in various ways to the BSP; see :ref:`bsp_connection` for
```

2020-09-24 20:33 UTC, jerome-leroux commented on Tutorials/tutorialUnderstandMicroEJFirmwareBuild.rst
> +object code) that is linked with the
```suggestion
object code) linked with the
```

2020-09-24 20:33 UTC, jerome-leroux commented on Tutorials/tutorialUnderstandMicroEJFirmwareBuild.rst
> +  artifacts (libraries, tools, …), see
```suggestion
  artifacts (libraries, tools, etc.), see
```

2020-09-24 20:33 UTC, jerome-leroux commented on Tutorials/tutorialUnderstandMicroEJFirmwareBuild.rst
> +  https://repository.microej.com/. This repository can also be used as an offline repository, see https://developer.microej.com/central-repository/.
```suggestion
  https://repository.microej.com/. You can also use this repository as an offline repository, see https://developer.microej.com/central-repository/.
```

2020-09-24 20:33 UTC, jerome-leroux commented on Tutorials/tutorialUnderstandMicroEJFirmwareBuild.rst
> +  that can be imported in the workspace (see
```suggestion
  that you can import in the workspace (see
```

2020-09-24 20:33 UTC, jerome-leroux commented on Tutorials/tutorialUnderstandMicroEJFirmwareBuild.rst
> +    same features.  The MicroEJ Application will not require any change.
```suggestion
  * To run a MicroEJ Application on a new device, create a new
    MicroEJ Platform for this device with the exact
    same features.  The MicroEJ Application will not require any change.
```

2020-09-24 20:33 UTC, jerome-leroux commented on Tutorials/tutorialUnderstandMicroEJFirmwareBuild.rst
> +* The MicroEJ Platform must be rebuilt in the following cases:
```suggestion
* You must rebuild the MicroEJ Platform in the following cases:
```

2020-09-24 20:33 UTC, jerome-leroux commented on Tutorials/tutorialUnderstandMicroEJFirmwareBuild.rst
> +* The MicroEJ Platform need not to be rebuilt in the following cases:
```suggestion
* You don't need to rebuild the MicroEJ Platform in the following cases:
```

2020-09-24 20:33 UTC, jerome-leroux commented on Tutorials/tutorialUnderstandMicroEJFirmwareBuild.rst
> +following information (the table below is filled with examples):
```suggestion
If you have any questions, feel free to contact our support team with the
following information (the table below is an example):
```

2020-09-24 20:33 UTC, jerome-leroux commented on Tutorials/tutorialUnderstandMicroEJFirmwareBuild.rst
> +  MicroEJ sales & Customer Care team).
```suggestion
* DEV: production license (only MicroEJ sales & Customer Care team distribute this version).
```

2020-09-25 07:47 UTC, gjadi-mej commented on Tutorials/tutorialUnderstandMicroEJFirmwareBuild.rst
> +* the abstraction layers low level API implementation of the platform architecture and foundations libraries
Agreed.

2020-09-25 07:52 UTC, gjadi-mej commented on Tutorials/tutorialUnderstandMicroEJFirmwareBuild.rst
> +Understand how to build a MicroEJ Firmware and its dependencies
I used this term because it is the one used in the Glossary: https://docs.microej.com/en/latest/glossary.html


> Firmware
>
>    A MicroEJ Firmware is the result of the binary link of a MicroEJ Standalone Application with a MicroEJ Platform. The firmware is a binary program that can be programmed into the flash memory of a device.

2020-09-25 15:21 UTC, jerome-leroux commented on Tutorials/tutorialUnderstandMicroEJFirmwareBuild.rst
> +Understand how to build a MicroEJ Firmware and its dependencies
If this is the term used in the glossary, then OK, keep firmware.

I know that Frederic is reviewing the glossary. Can you check with him that this term won't change?

2020-09-25 15:30 UTC, thomasponsmicroej commented
In the diagram you use the term "Library repository", is it the official term? I think we tend to use "Module Repository" now (https://docs.microej.com/en/latest/ApplicationDeveloperGuide/repository.html?highlight=module%20repository)

2020-09-25 15:50 UTC, gjadi-mej commented
Closing this because I deleted my fork. I pushed the branch on this repo. See https://github.com/MicroEJ/docs/pull/75

2020-09-25 15:50 UTC, closed without merging

2020-09-25 16:01 UTC, stephanemainchain commented on Tutorials/tutorialUnderstandMicroEJFirmwareBuild.rst
> +Understand how to build a MicroEJ Firmware and its dependencies
for me it's ok.