Add a section introducing color helpers in Widget library.
MicroEJ/docs pull request #400
Opened 2022-05-12 15:43 UTC by seonmej

2022-05-23 13:45 UTC, frivieremicroej requested changes

2022-05-23 13:45 UTC, frivieremicroej commented on ApplicationDeveloperGuide/UI/Widgets/widget.rst
> +The ``ColorHelper`` is helpful for exploding colors into components, alpha, red, blue, green and building back a color from components.
Please add links to javadoc

2022-06-03 15:40 UTC, seonmej commented on ApplicationDeveloperGuide/UI/Widgets/widget.rst
> +The ``ColorHelper`` is helpful for exploding colors into components, alpha, red, blue, green and building back a color from components.
fixed

2022-06-03 15:40 UTC, seonmej commented on ApplicationDeveloperGuide/UI/Widgets/widget.rst
> +The ``GradientHelper`` is able to blend two colors and can create a gradient from 2 colors.
fixed

2022-06-03 15:40 UTC, seonmej commented on ApplicationDeveloperGuide/UI/Widgets/widget.rst
> +The ``ColorHelper`` is helpful for exploding colors into components, alpha, red, blue, green and building back a color from components.
fixed

2022-06-22 09:49 UTC, frivieremicroej approved these changes

2022-06-22 10:15 UTC, merged