M0078DDG-475 New linkcheck setup at build time
MicroEJ/docs pull request #412
Opened 2022-06-03 20:58 UTC by fpinel-microej

2022-06-07 07:58 UTC, tdelhomenie-microej requested changes

2022-06-07 07:58 UTC, tdelhomenie-microej commented on conf.py
> +#    print(linkcheck_output.decode(errors="ignore"))
We can removed this code IMO, it is not useful anymore.

2022-06-07 07:58 UTC, tdelhomenie-microej commented on .readthedocs.yml
> +    - graphviz
Why do we need graphviz for the linkcheck process? Does it generate some diagrams?

2022-06-07 07:58 UTC, tdelhomenie-microej commented on conf.py
> -linkcheck_timeout = 20
Can we add this parameter back? It caused some issues in the past.

2022-06-08 13:39 UTC, gharelMicroEJ commented on conf.py
> +#    print(linkcheck_output.decode(errors="ignore"))
Agreed.

2022-06-08 13:41 UTC, gharelMicroEJ approved these changes
Pending the remarks of @tdelhomenie-microej , I conditionally approve this PR.

2022-06-09 10:15 UTC, fpinel-microej commented on .readthedocs.yml
> +    - graphviz
(We discussed this orally but for the record :) the graphviz package needs to be specified here for the build to work with this new build config, it was done automatically before. We do use it to draw some diagrams in the Application Dev Guide's UI section.

2022-06-09 10:15 UTC, fpinel-microej commented on conf.py
> +#    print(linkcheck_output.decode(errors="ignore"))
Done

2022-06-16 16:37 UTC, tdelhomenie-microej approved these changes

2022-06-17 08:26 UTC, merged