M0078DDG-480 Improve Sandboxed Application documentation
MicroEJ/docs pull request #416
Opened 2022-06-17 14:42 UTC by tdelhomenie-microej

Preview: https://docs.microej.com/en/feature-m0078ddg-480_sandboxed-application/

This PR aims to improve the documentation on Sandboxed Application development.

2022-07-05 12:40 UTC, tdelhomenie-microej commented on ApplicationDeveloperGuide/sandboxedAppDeploy.rst
> +the `Resources Repository <https://repository.microej.com/index.php?resource=FIRM&topic=ALL&version=ANY&edition=ANY>`_
@frivieremicroej is it ok to refer to this URL for the list of available firmwares ?

2022-07-05 12:40 UTC, tdelhomenie-microej commented on ApplicationDeveloperGuide/sandboxedAppDeploy.rst
> +
@frivieremicroej I used the same content than in the previous doc for Remote Deployment but I don't think it is sufficient. It does not explain what is Forge and how to install and use. Don't we have such a doc somewhere?

2022-07-05 12:40 UTC, tdelhomenie-microej commented on ApplicationDeveloperGuide/sandboxedAppSim.rst
> +Please refer to the :ref:`kernel-developer-guide` to learn to get or create one.
Don't we have some Evaluation VD to link to? Should we redirect to the list of platforms (https://repository.microej.com/index.php?resource=JPF&topic=ALL&version=ANY&edition=ANY) ?

2022-08-22 07:09 UTC, frivieremicroej commented on ApplicationDeveloperGuide/sandboxedAppDeploy.rst
> +the `Resources Repository <https://repository.microej.com/index.php?resource=FIRM&topic=ALL&version=ANY&edition=ANY>`_
OK, event almost all firmware are 4 years old (the last published one has 2 years)

2022-08-22 15:56 UTC, frivieremicroej commented on ApplicationDeveloperGuide/sandboxedAppDeploy.rst
> +
no, this is the only entry point for Forge. OK for me.

2022-08-22 15:59 UTC, frivieremicroej commented on ApplicationDeveloperGuide/sandboxedAppSim.rst
> +Please refer to the :ref:`kernel-developer-guide` to learn to get or create one.
We can point to https://developer.microej.com/create-your-first-application/get-started-app-development-on-espressif-esp32-wroverkit-v41/ VD (https://repository.microej.com/packages/black/1.1.1/vd/ESP32-WROVER/BLACK-ESP32WROVER-RQQAW-1.1.1.vde)

2022-08-22 16:35 UTC, frivieremicroej requested changes

2022-08-22 16:35 UTC, frivieremicroej commented on ApplicationDeveloperGuide/sandboxedAppDeploy.rst
> +- in the ``Execution`` tab, modify the ``Execution`` mode to ``Execute on Device``,
use GUILabels (check everywhere)

2022-08-22 16:35 UTC, frivieremicroej commented on ApplicationDeveloperGuide/sandboxedAppDeploy.rst
> +
please contact our support team if you want more information on Forge and automated Sandboxed Applications deployment through your device management system.

2022-08-22 16:35 UTC, frivieremicroej commented on ApplicationDeveloperGuide/sandboxedAppDeploy.rst
> +
please review & merge https://github.com/MicroEJ/docs/pull/435

2022-08-23 15:52 UTC, tdelhomenie-microej commented on ApplicationDeveloperGuide/sandboxedAppDeploy.rst
> +
Review done

2022-08-23 15:52 UTC, tdelhomenie-microej commented on ApplicationDeveloperGuide/sandboxedAppDeploy.rst
> +- in the ``Execution`` tab, modify the ``Execution`` mode to ``Execute on Device``,
Done

2022-08-31 10:10 UTC, closed without merging

2022-08-31 10:10 UTC, frivieremicroej commented
Replaced by https://github.com/MicroEJ/docs/pull/435