M0090IDE-3910 JRE must not be used to install and launch the SDK
MicroEJ/docs pull request #417
Opened 2022-06-20 12:21 UTC by denisbedin

2022-06-20 12:37 UTC, tdelhomenie-microej requested changes

2022-06-20 12:37 UTC, tdelhomenie-microej commented on SDKUserGuide/systemRequirements.rst
> +   A full JDK is required to run Eclipse, so please ensure that you do not use a JRE to install and launch the SDK.
```suggestion
   Starting from the SDK Distribution 22.06, a JDK is required to install and launch it, so please ensure that you do not use a JRE.
```

2022-06-20 13:05 UTC, denisbedin commented
@tdelhomenie-microej  the suggestion is applied

2022-06-20 13:13 UTC, tdelhomenie-microej approved these changes

2022-06-20 13:13 UTC, tdelhomenie-microej commented
@denisbedin LGTM (to be merged after the SDK release)

2022-06-23 08:01 UTC, denisbedin commented on SDKUserGuide/systemRequirements.rst
> +     - > 7.17
Shouldn't the architecture' version be minimum 7.17 instead of >7.17 ?

2022-06-23 08:07 UTC, tdelhomenie-microej commented on SDKUserGuide/systemRequirements.rst
> +     - > 7.17
Right, good catch. Done.

2022-07-01 08:32 UTC, merged