M0078DDG-316 add javadoc references to Appilcation Developper Guide
MicroEJ/docs pull request #425
Opened 2022-07-04 11:21 UTC by fpinel-microej

2022-07-04 11:47 UTC, fpinel-microej commented
Note :  `apply(GraphicsContext g, Size size)` mentioned in ApplicationDeveloperGuide/UI/MWT/how-to-background.rst doesn't seem to exist, there is only `apply(GraphicsContext g, int width, int height)` in `Background` at least https://repository.microej.com/javadoc/microej_5.x/apis/ej/mwt/style/background/Background.html

2022-07-04 11:53 UTC, fpinel-microej commented
There doesn't seem to be Javadoc for the Javascript methods, so most of the Javascript doc sections don't have much references for now.

2022-07-04 15:37 UTC, frivieremicroej requested changes

2022-07-04 15:37 UTC, frivieremicroej commented on ApplicationDeveloperGuide/UI/Advanced/how-to-text-overflow.rst
> +In this article, the widget ``MyLabel`` will extend the type `Label <https://repository.microej.com/javadoc/microej_5.x/apis/ej/widget/basic/Label.html>`_ from the Widget library, which displays a te
Please replace links with the shortcut version suggested by @tdelhomenie-microej to improve rst readability

2022-07-11 07:43 UTC, frivieremicroej commented
@thomasponsmicroej can you comment on https://github.com/MicroEJ/docs/pull/425#issuecomment-1173724017

2022-07-11 08:04 UTC, thomasponsmicroej commented
> Note : `apply(GraphicsContext g, Size size)` mentioned in ApplicationDeveloperGuide/UI/MWT/how-to-background.rst doesn't seem to exist, there is only `apply(GraphicsContext g, int width, int height)` in `Background` at least https://repository.microej.com/javadoc/microej_5.x/apis/ej/mwt/style/background/Background.html

I fixed the page (method signature + snippet)

2022-07-11 09:57 UTC, fpinel-microej commented on ApplicationDeveloperGuide/UI/Advanced/how-to-text-overflow.rst
> +In this article, the widget ``MyLabel`` will extend the type `Label <https://repository.microej.com/javadoc/microej_5.x/apis/ej/widget/basic/Label.html>`_ from the Widget library, which displays a te
Done

2022-07-11 09:58 UTC, fpinel-microej commented
> > Note : `apply(GraphicsContext g, Size size)` mentioned in ApplicationDeveloperGuide/UI/MWT/how-to-background.rst doesn't seem to exist, there is only `apply(GraphicsContext g, int width, int height)` in `Background` at least https://repository.microej.com/javadoc/microej_5.x/apis/ej/mwt/style/background/Background.html
> 
> I fixed the page (method signature + snippet)

Thank you, I did assume they were the same but wasn't 100% sure so I wanted a second opinion

2022-07-11 10:16 UTC, fpinel-microej commented on ApplicationDeveloperGuide/classpath.rst
> +.. _Class.getResourceAsStream(java.io.InputStream): https://repository.microej.com/javadoc/microej_5.x/apis/java/lang/Class.html#getResourceAsStream-java.lang.String-
Yes, didn't see this change in the merge conflict resolve, fixed

2022-07-11 10:49 UTC, frivieremicroej approved these changes
Thanks @fpinel-microej !

2022-07-11 10:49 UTC, merged