M0078DDG-486 Document SNI limitations
MicroEJ/docs pull request #428
Opened 2022-07-25 14:04 UTC by jerome-leroux

2022-07-25 14:33 UTC, rlouedec-microej requested changes
Except typo, lgtm.

Another general comment: does it make sense to keep the eval/prod columns ?
I would rather split the table in two: 1 with general limitation, 1 with eval/prod differences.
But I'm fine with one table.

2022-07-25 14:33 UTC, rlouedec-microej commented on ApplicationDeveloperGuide/limitations.rst
> +   * - Number of paramaters for an SNI method
Typo:
```suggestion
   * - Number of parameters for an SNI method
```

2022-07-25 16:22 UTC, jerome-leroux commented on ApplicationDeveloperGuide/limitations.rst
> +   * - Number of paramaters for an SNI method
Yes, we could review the table structure. There are not so much differences between eval and prod now.
This could be done later.

2022-07-26 15:03 UTC, rlouedec-microej approved these changes

2022-07-26 15:22 UTC, merged