Document S3 internal memory properties.
MicroEJ/docs pull request #433
Opened 2022-08-22 07:26 UTC by bguedas

2022-08-22 09:38 UTC, frivieremicroej requested changes

2022-08-22 09:38 UTC, frivieremicroej commented on ApplicationDeveloperGuide/applicationOptions.rst
> +   The Simulator uses some system properties to configure internal memory limits.
If these options cannot be set as application options, I suggest to introduce and move to a dedicated Simulation section in the ADG.

2022-08-22 09:38 UTC, frivieremicroej commented on ApplicationDeveloperGuide/sectionSimulatorOptions.rst
> +Heap Size allocated by the Simulator. It is used to allocate object on Java Heap,
You need to increase this option if Java heap + immortal heap application options > 4MB, am I right  ?

2022-08-22 09:38 UTC, frivieremicroej commented on ApplicationDeveloperGuide/sectionSimulatorOptions.rst
> +but also immutable objectss. It thus must be at least equal to the sum of option_java_heap_
```suggestion
but also immutable objects. It thus must be at least equal to the sum of option_java_heap_ 
```

2022-08-22 09:38 UTC, frivieremicroej commented on ApplicationDeveloperGuide/sectionSimulatorOptions.rst
> +*Recomended value*: ``3000``
```suggestion
*Recommended value*: ``3000``
```

2022-08-22 09:38 UTC, frivieremicroej commented on ApplicationDeveloperGuide/sectionSimulatorOptions.rst
> +Memory allocated to system strings. Value is in kilobytes.
"system strings" can you elaborate in which "application" case we will reach this limit (intern strings, application class names ?)

2022-08-22 09:38 UTC, frivieremicroej commented on ApplicationDeveloperGuide/sectionSimulatorOptions.rst
> +Memory allocated to application strings. Value is in kilobytes.
application strings / system strings: not clear (see comment above)

2022-08-22 09:38 UTC, frivieremicroej commented on ApplicationDeveloperGuide/sectionSimulatorOptions.rst
> +*Option Name*: ``S3.JavaMemory.MethodsSize``
? same option name than before ?

2022-08-22 09:38 UTC, frivieremicroej commented on ApplicationDeveloperGuide/sectionSimulatorOptions.rst
> +Memory space allocated for each thread stack. Value is in kilobytes.
do we already reached this option (compared to embedded constraints?)

2022-08-22 09:38 UTC, frivieremicroej commented on ApplicationDeveloperGuide/sectionSimulatorOptions.rst
> +Option: Icetea Heap Start
I guess this value must not be changed and should be hidden

2022-08-22 09:38 UTC, frivieremicroej commented on ApplicationDeveloperGuide/sectionSimulatorOptions.rst
> +Internal heap end address used by the Simulator to manage its own memory. It is an adress in bytes.
does it includes other memories declared above ?
I though there was a case where an option depends on another one

2022-08-22 09:38 UTC, frivieremicroej commented on ApplicationDeveloperGuide/sectionSimulatorOptions.rst
> +..
no options for immutable limit ?

2022-08-22 09:38 UTC, frivieremicroej commented on ApplicationDeveloperGuide/sectionSimulatorOptions.rst
> +   | Copyright 2022, MicroEJ Corp. Content in this space is free
no options for pin objects

2022-08-22 11:41 UTC, bguedas commented on ApplicationDeveloperGuide/applicationOptions.rst
> +   The Simulator uses some system properties to configure internal memory limits.
These options can be set as application option in properties files.

2022-08-22 11:43 UTC, bguedas commented on ApplicationDeveloperGuide/sectionSimulatorOptions.rst
> +Heap Size allocated by the Simulator. It is used to allocate object on Java Heap,
that's right

2022-09-05 09:36 UTC, bguedas commented on ApplicationDeveloperGuide/sectionSimulatorOptions.rst
> +Memory allocated to system strings. Value is in kilobytes.
It is the system interned strings chars. It looks like it's only used by the debugger.

2022-09-05 09:36 UTC, bguedas commented on ApplicationDeveloperGuide/sectionSimulatorOptions.rst
> +Memory allocated to application strings. Value is in kilobytes.
these are the app interned strings. I've modified the text a bit.

2022-09-05 09:47 UTC, bguedas commented on ApplicationDeveloperGuide/sectionSimulatorOptions.rst
> +Memory space allocated for each thread stack. Value is in kilobytes.
Yes we did, in JUnit tests for instance.

2022-09-05 09:49 UTC, bguedas commented on ApplicationDeveloperGuide/sectionSimulatorOptions.rst
> +   | Copyright 2022, MicroEJ Corp. Content in this space is free
No, there is a default value which is hard coded, but the array grows automatically if needed.

2022-09-05 09:56 UTC, bguedas commented on ApplicationDeveloperGuide/sectionSimulatorOptions.rst
> +..
No, they are stored within a hash map that grows automatically

2022-09-05 09:58 UTC, bguedas commented on ApplicationDeveloperGuide/sectionSimulatorOptions.rst
> +Option: Icetea Heap Start
I've removed this option description.

2022-09-09 12:09 UTC, frivieremicroej approved these changes

2022-09-09 12:09 UTC, merged