Feature/glossary update sept 2022
MicroEJ/docs pull request #434
Opened 2022-08-22 10:03 UTC by frivieremicroej

this is a first draft for future glossary updates, please comment.

2022-08-25 14:46 UTC, jerome-leroux requested changes

2022-08-25 14:46 UTC, jerome-leroux commented on glossary.rst
> +      A Mock is a mockup of a board support package (BSP) capability that mimics an hardware functionality for the Simulator.
```suggestion
      A Mock is a mockup of a board support package (BSP) capability that mimics a hardware functionality for the Simulator.
```

2 other occurrences identified in https://docs.microej.com/en/latest/overview/sdk.html?highlight=%22an%20hardware%22#microej-sdk and https://docs.microej.com/en/latest/PlatformDeveloperGuide/ecom-comm.html?highlight=%22an%20hardware%22#comm-port-identifier

2022-11-02 16:35 UTC, frivieremicroej commented on glossary.rst
f/s/r decision: remove the line, keep VEE in the glossary.

```suggestion
```

2022-11-02 16:35 UTC, frivieremicroej commented on glossary.rst
> +            A Standalone Application is the main application that is booted by MICROEJ VEE. It is linked statically.
f/s/r decision
```suggestion
            A Standalone Application is the main application that is booted by MICROEJ VEE. It is linked statically to produce a Mono-Sandbox Executable.
```

2022-11-02 16:35 UTC, frivieremicroej commented on glossary.rst
> +            A Sandboxed Application is an Application that can run over a Multi-Sandbox Executable. It can be linked either statically or dynamically.
f/s/r decision
```suggestion
            A Sandboxed Application is an Application that can run over a Multi-Sandbox Executable. It is linked dynamically.
```

2022-11-02 16:35 UTC, frivieremicroej commented on glossary.rst
> +            A System Application (formerly called a Resident Application) is a Sandboxed Application that is statically linked to a Multi-Sandbox Executable, as it is part of the initial image and ca
f/s/r decision: remove System Application

2022-11-02 22:46 UTC, jerome-leroux requested changes

2022-11-02 22:46 UTC, jerome-leroux commented on glossary.rst
> +      MICROEJ SDK is a comprehensive tools suite for developers to build VEE Ports for their devices, create Applications, build Executable and run Virtual Devices.
```suggestion
      MICROEJ SDK is a comprehensive tools suite for developers to build VEE Ports for their devices, create Applications, build Executable, and run Virtual Devices.
```

2022-11-03 08:59 UTC, stephanemainchain commented on glossary.rst
> +            A Standalone Application is the main application that is booted by MICROEJ VEE. It is linked statically to produce a Mono-Sandbox Executable.
booted: wording => never seen it used like this. Prefer launched?

2022-11-03 08:59 UTC, stephanemainchain commented on glossary.rst
> +      A VEE Port is an implementation of MICROEJ VEE for a target device. It integrates an Architecture, one or more Foundation Libraries with their respective Abstraction Layers, and the board suppo
for a target device or a target hardware ? (device could be reduced to mcu only?) just a suggestion

2022-11-18 10:04 UTC, frivieremicroej commented on glossary.rst
> +      MICROEJ SDK is a comprehensive tools suite for developers to build VEE Ports for their devices, create Applications, build Executable and run Virtual Devices.
done

2022-11-18 10:06 UTC, frivieremicroej commented on glossary.rst
> +            A Standalone Application is the main application that is booted by MICROEJ VEE. It is linked statically to produce a Mono-Sandbox Executable.
I replaced by executed

2022-11-18 10:11 UTC, closed without merging