Feature/m0078 ddg 480 sandboxed application review friviere
MicroEJ/docs pull request #435
Opened 2022-08-22 15:56 UTC by frivieremicroej

2022-08-23 15:20 UTC, tdelhomenie-microej requested changes

2022-08-23 15:20 UTC, tdelhomenie-microej commented on ApplicationDeveloperGuide/sandboxedAppDeploy.rst
> +The deployment of a Sandboxed Application over a Multi-Sandbox Firmware depends on the Kernel implementation. However we can group them in two categories:
Also the term "device" has been removed, is it intended? "Deployment" sounds like a very generic term to me, adding "device" make it more clear IMO.

2022-08-23 15:20 UTC, tdelhomenie-microej commented on ApplicationDeveloperGuide/sandboxedAppDeploy.rst
> +- Local Deployment: the device is connected to the developer's computer and the SDK transfers the Application project on it. (recommended during application development)
Using the term "project" here is confusing IMO, that's why I did not use it initially. Otherwise we may use "transfers the Application from the project".

2022-08-23 15:20 UTC, tdelhomenie-microej commented on ApplicationDeveloperGuide/sandboxedAppDeploy.rst
> +  for available demos of such Multi-Sandbox Firmware),
There is no link to the Kernel Developer Guide anymore so I don't know how to create my kernel if I want to.

2022-08-23 15:20 UTC, tdelhomenie-microej commented on ApplicationDeveloperGuide/sandboxedAppDeploy.rst
> +Remote Deployment requires to build and publish the Standalone Application.
Standalone?

2022-08-23 15:20 UTC, tdelhomenie-microej commented on ApplicationDeveloperGuide/sandboxedAppDeploy.rst
> +The files produced by the build process is located in a dedicated
```suggestion
The files produced by the build process are located in a dedicated
```

2022-08-23 15:20 UTC, tdelhomenie-microej commented on ApplicationDeveloperGuide/sandboxedAppDeploy.rst
> +The file that ends with `.wpk` (the WPK file) is a portable file that contains all necessary binary data to build link `.fo` on any compatible Multi-Sandbox Firmware.
"to build link `.fo` on any compatible" -> "build" should be removed, right ?

2022-08-23 15:20 UTC, tdelhomenie-microej commented on ApplicationDeveloperGuide/sandboxedApplication.rst
> -- the same Application must be installed in multiple Firmwares and devices.
This use case is not relevant?

2022-08-23 15:20 UTC, tdelhomenie-microej commented on ApplicationDeveloperGuide/sandboxedApplication.rst
> +Please refer to the :ref:`kernel-developer-guide` to learn more on Multi-Sandbox Firmware and Virtual Devices, and how to create them.
Why removing the "s" here and keeping it on "Virtual Devices" ?

2022-08-23 15:20 UTC, tdelhomenie-microej commented on ApplicationDeveloperGuide/sandboxedApplication.rst
> +A Sandboxed Application is a Java Application that can run over a Multi-Sandbox Firmware.
Still not convinced it is better like that :) It helps to highlight important things and make the text less "monotonous" IMO.
Is it intended to keep bold texts in the "Fundamental Concepts" chapter. At least we should be consistent ;)

2022-08-26 07:02 UTC, frivieremicroej commented on ApplicationDeveloperGuide/sandboxedApplication.rst
> +Please refer to the :ref:`kernel-developer-guide` to learn more on Multi-Sandbox Firmware and Virtual Devices, and how to create them.
Firmware is singular, no plural form (https://faq-blog.com/does-firmware-have-a-plural)

2022-08-26 07:08 UTC, frivieremicroej commented on ApplicationDeveloperGuide/sandboxedApplication.rst
> -- the same Application must be installed in multiple Firmwares and devices.
I found it redundant with the others:
- the same => modularization
- installed => ota

Moreover this is also relevant for standalone application.
TBD

2022-08-26 07:09 UTC, frivieremicroej commented on ApplicationDeveloperGuide/sandboxedAppDeploy.rst
> +The file that ends with `.wpk` (the WPK file) is a portable file that contains all necessary binary data to build link `.fo` on any compatible Multi-Sandbox Firmware.
WPK->.fo is build

```suggestion
The file that ends with `.wpk` (the WPK file) is a portable file that contains all necessary binary data to build `.fo` on any compatible Multi-Sandbox Firmware.
```

2022-08-26 07:18 UTC, frivieremicroej commented on ApplicationDeveloperGuide/sandboxedAppDeploy.rst
> +The deployment of a Sandboxed Application over a Multi-Sandbox Firmware depends on the Kernel implementation. However we can group them in two categories:
I replaced "over a Multi-Sandbox Firmware" by "on a Device"

2022-08-26 07:20 UTC, frivieremicroej commented on ApplicationDeveloperGuide/sandboxedAppDeploy.rst
> +- Local Deployment: the device is connected to the developer's computer and the SDK transfers the Application project on it. (recommended during application development)
What about "and the SDK directly builds the .fo from the workspace project classes" ?
TBD

2022-08-26 07:22 UTC, frivieremicroej commented on ApplicationDeveloperGuide/sandboxedAppDeploy.rst
> +Remote Deployment requires to build and publish the Standalone Application.
OK Sandboxed

2022-08-26 07:27 UTC, frivieremicroej commented on ApplicationDeveloperGuide/sandboxedApplication.rst
> +A Sandboxed Application is a Java Application that can run over a Multi-Sandbox Firmware.
OK I forgot this chapter and TBD about equivalencies

2022-08-26 16:46 UTC, tdelhomenie-microej commented on ApplicationDeveloperGuide/sandboxedAppDeploy.rst
> +- Local Deployment: the device is connected to the developer's computer and the SDK transfers the Application project on it. (recommended during application development)
Sounds better. To be even more clear: "the device is connected to the developer's computer, the SDK builds the .fo from the workspace project classes and transfers it on the device" ?

2022-08-29 07:44 UTC, frivieremicroej commented on ApplicationDeveloperGuide/sandboxedAppDeploy.rst
> +- Local Deployment: the device is connected to the developer's computer and the SDK transfers the Application project on it. (recommended during application development)
Integrated

2022-08-29 07:45 UTC, frivieremicroej commented on ApplicationDeveloperGuide/sandboxedApplication.rst
> +A Sandboxed Application is a Java Application that can run over a Multi-Sandbox Firmware.
Rewrote TDB

2022-08-31 09:21 UTC, frivieremicroej commented on ApplicationDeveloperGuide/sandboxedApplication.rst
> -- the same Application must be installed in multiple Firmwares and devices.
fixed

2022-08-31 10:02 UTC, frivieremicroej commented on ApplicationDeveloperGuide/sandboxedAppDeploy.rst
> +  for available demos of such Multi-Sandbox Firmware),
reintegrated

2022-08-31 11:25 UTC, tdelhomenie-microej requested changes

2022-08-31 11:25 UTC, tdelhomenie-microej commented on ApplicationDeveloperGuide/sandboxedAppDeploy.rst
> +>>>>>>> 2e593f5 M0078DDG-480 Use guilabel for SDK labels
To be fixed.

2022-08-31 11:25 UTC, tdelhomenie-microej commented on ApplicationDeveloperGuide/sandboxedAppFirstApplication.rst
> +Now that the :ref:`purposes and concepts of the Sandboxed Applications have been explained <sandboxed_application>`, let's create a first application.
I used the term "concepts" because the Fundamental concepts were initially explained in the previous page, but we moved this part, so maybe we should remove this term here?

2022-08-31 11:25 UTC, tdelhomenie-microej commented on ApplicationDeveloperGuide/sandboxedAppSim.rst
> +Please refer to the :ref:`kernel-developer-guide` to learn to get or create one.
```suggestion
Please refer to the :ref:`kernel-developer-guide` to learn how to get or create one.
```

2022-08-31 11:25 UTC, tdelhomenie-microej commented on ApplicationDeveloperGuide/sandboxedAppFundamentalConcepts.rst
> +Therefore, in the next chapters, a Kernel Application relates to the *Kernel* concept, and a Sandboxed Application relates to the *Feature* concept.
"in the next chapters" does not make a lot of sense anymore IMO, maybe we should remove it?

2022-08-31 12:15 UTC, frivieremicroej commented on ApplicationDeveloperGuide/sandboxedAppDeploy.rst
> +>>>>>>> 2e593f5 M0078DDG-480 Use guilabel for SDK labels
fixed

2022-08-31 14:14 UTC, merged