M0090IDE-3982 document resolve in workspace
MicroEJ/docs pull request #443
Opened 2022-09-13 12:50 UTC by denisbedin

2022-09-14 06:14 UTC, tdelhomenie-microej requested changes

2022-09-14 06:14 UTC, tdelhomenie-microej commented on SDKUserGuide/resolve.rst
> +the same workspace as the module, the workspace resolution will link both the module and its dependency instead of downloading the published artifact, provided that the dependency's project has the s
```suggestion
the same workspace as the module, the project is directly used as a dependency instead of downloading the published artifact, provided that the dependency's project has the same version as the one required by the module. 
```

2022-09-14 06:14 UTC, tdelhomenie-microej commented on SDKUserGuide/resolve.rst
> +If the ``mylib`` dependency is located in the workspace and its version is ``1.0.0``, it will be linked with the module A, else the published artifact with the right version will be downloaded.
```suggestion
If the ``mylib`` project is located in the workspace and its version is ``1.0.0``, it is used for compilation and execution. Otherwise the published artifact is downloaded from the artifact repository.
```

2022-09-14 06:14 UTC, tdelhomenie-microej commented on SDKUserGuide/resolve.rst
> +To avoid a dependency to be resolved in the workspace, simply close the corresponding project or remove it from the workspace. The workspace resolution can also be only disabled for the Foundation Li
```suggestion
To avoid a dependency to be resolved in the workspace, simply close the corresponding project or remove it from the workspace. For the case of Foundation Libraries only, the workspace resolution can also be disabled by unchecking th ``Resolve Foundation Library in workspace`` option in :guilabel:`Window` > :guilabel:`Preferences` > :guilabel:`MicroEJ` > :guilabel:`Settings`.
```

2022-09-14 06:14 UTC, tdelhomenie-microej commented on SDKUserGuide/resolve.rst
> +.. resolve:
```suggestion
.. resolveInWorkspace:
```

2022-09-14 06:14 UTC, tdelhomenie-microej commented on SDKUserGuide/resolve.rst
> +the same workspace as the module, the workspace resolution will link both the module and its dependency instead of downloading the published artifact, provided that the dependency's project has the s
We should add a screenshot of a project used as a dependency of a project in the SDK.

2022-09-14 08:36 UTC, denisbedin commented on SDKUserGuide/resolve.rst
> +By default, the ``IvyDE workspace dependencies resolution`` is enabled in the SDK. When resolving a module's dependencies, if a dependency is opened in
Done

2022-09-14 08:36 UTC, denisbedin commented on SDKUserGuide/resolve.rst
> +the same workspace as the module, the workspace resolution will link both the module and its dependency instead of downloading the published artifact, provided that the dependency's project has the s
Done

2022-09-14 12:34 UTC, tdelhomenie-microej requested changes

2022-09-14 12:34 UTC, tdelhomenie-microej commented on SDKUserGuide/resolveInWorkspace.rst
> +   the dependency's project is only used for execution.
I suggest:
```
For the case of :ref:`Foundation Libraries <libraries>`, the API (used at compile time) and the implementation (used at runtime) are organized in 2 projects. When the API is set as a dependency, the project of the implementation is automatically used at runtime if it is available in the workspace. 
```
and it should probably be moved below, at line 30. Maybe we should have a dedicated section for that?

2022-09-14 13:35 UTC, denisbedin commented on SDKUserGuide/resolveInWorkspace.rst
> +   the dependency's project is only used for execution.
I have created a dedicated section for Foundation libs.

2022-09-15 16:17 UTC, frivieremicroej requested changes

2022-09-15 16:17 UTC, frivieremicroej commented on SDKUserGuide/resolveInWorkspace.rst
> +To avoid a dependency to be resolved in the workspace, simply close the corresponding project or remove it from the workspace.
Warning: importing/removing/opening/closing a project does not automatically refreshes the dependency resolution of other previously imported projects => Resolve all button

2022-09-15 16:17 UTC, frivieremicroej commented on SDKUserGuide/resolveInWorkspace.rst
> +To avoid the use of the implementation's project at runtime, uncheck the ``Resolve Foundation Library in workspace`` option in :guilabel:`Window` > :guilabel:`Preferences` > :guilabel:`MicroEJ` > :gu
Sorry but I do not understand why you highlight this option (according to our previous discussions)

2022-09-15 16:17 UTC, frivieremicroej commented on SDKUserGuide/resolveInWorkspace.rst
> +When the API is set as a dependency, the project of the implementation is automatically used for execution if it is opened in the workspace.
I think it is time to describe the Foundation Library mapping (from howto schematic)

2022-09-16 06:25 UTC, tdelhomenie-microej commented on SDKUserGuide/resolveInWorkspace.rst
> +To avoid the use of the implementation's project at runtime, uncheck the ``Resolve Foundation Library in workspace`` option in :guilabel:`Window` > :guilabel:`Preferences` > :guilabel:`MicroEJ` > :gu
No highlighting, just documenting, as any other feature. We discussed with Denis about documenting it or not, but since it is in the product, I consider it should be documented, as any other feature available in the product.

2022-09-16 08:17 UTC, denisbedin commented on SDKUserGuide/resolveInWorkspace.rst
> +To avoid a dependency to be resolved in the workspace, simply close the corresponding project or remove it from the workspace.
A warning has been added for that.

2022-09-16 08:25 UTC, denisbedin commented on SDKUserGuide/resolveInWorkspace.rst
> +When the API is set as a dependency, the project of the implementation is automatically used for execution if it is opened in the workspace.
I described the different parts of a Foundation Library (api,impl,C code, Mock-up) and I have added a note that refers to the How-to.

2022-09-16 14:17 UTC, tdelhomenie-microej commented on SDKUserGuide/resolveInWorkspace.rst
> +When the API is set as a dependency, the project of the implementation is automatically used for execution if it is opened in the workspace.
To be done in a future PR.

2022-09-19 10:17 UTC, denisbedin commented
@tdelhomenie-microej @frivieremicroej I have created the "IDE" page, it contains the documention for resolution in workspace and the "Workspaces and MicroEJ Repositories" page's content,

2022-09-19 11:45 UTC, tdelhomenie-microej requested changes

2022-09-19 11:45 UTC, tdelhomenie-microej commented on SDKUserGuide/ide.rst
> +---------------------------------
This section should be moved in a dedicated page.

2022-09-19 11:45 UTC, tdelhomenie-microej commented on SDKUserGuide/ide.rst
> +SDK Startup
Shouldn't it be "IDE Startup", or even just "Startup" ?

2022-09-19 14:13 UTC, denisbedin commented on SDKUserGuide/ide.rst
> +SDK Startup
The section has been renamed.

2022-09-19 14:22 UTC, denisbedin commented on SDKUserGuide/ide.rst
> +---------------------------------
According to our discussion, all the documentation related to the IDE had to be merged into a single page "IDE", so why should this section be moved ?

2022-09-19 15:54 UTC, tdelhomenie-microej commented on SDKUserGuide/ide.rst
> +---------------------------------
No, all the documentation related to the IDE must be gathered under an "IDE" level, but each one in a dedicated page. Otherwise the page would be huge since we will continue to add content.

2022-09-20 14:17 UTC, denisbedin commented on SDKUserGuide/ide.rst
> +---------------------------------
The "IDE" level has been added

2022-09-21 05:53 UTC, tdelhomenie-microej commented
@frivieremicroej @denisbedin in the page https://docs.microej.com/en/latest/SDKUserGuide/index.html this part is confusing:

    The SDK is composed of the following main elements:
       - SDK Version 5.x, an Integrated Development Environment (IDE)...

"The SDK is composed of the SDK" 🤔 I would replace it by:

    The SDK is composed of the following main elements:
       - an Integrated Development Environment (IDE)...

WDYT?

2022-09-21 05:53 UTC, tdelhomenie-microej requested changes

2022-09-21 05:53 UTC, tdelhomenie-microej commented on SDKUserGuide/ide.rst
> +https://developer.microej.com/microej-sdk-software-development-kit/.
The sentence should be removed IMO, it is related to the whole Distribution.

2022-09-21 05:53 UTC, tdelhomenie-microej commented on SDKUserGuide/ide.rst
> +**SDK Version 5.x**, embedded in MicroEJ SDK, is an Integrated Development Environment (IDE) for creating MicroEJ Applications and building
```suggestion
The SDK provides an Integrated Development Environment (IDE) for creating MicroEJ Applications and building
```

2022-09-21 05:53 UTC, tdelhomenie-microej commented on SDKUserGuide/ide.rst
> +MicroEJ Firmware. The SDK is based on Eclipse Java Edition and relies on the integrated Java Compiler (JDT).
```suggestion
MicroEJ Firmware. It is based on Eclipse Java Edition and relies on the integrated Java Compiler (JDT).
```

2022-09-21 07:26 UTC, denisbedin commented on SDKUserGuide/ide.rst
> +https://developer.microej.com/microej-sdk-software-development-kit/.
Yes, I didn't see that the link to download the SDK was already indicated in https://docs.microej.com/en/latest/SDKUserGuide/install.html, so I added it here. The sentence has been removed.

2022-09-22 07:21 UTC, frivieremicroej commented on SDKUserGuide/ide.rst
> +The SDK provides an Integrated Development Environment (IDE) for creating MicroEJ Applications and building
```suggestion
The SDK provides an Integrated Development Environment (IDE) for creating and building Applications
```

2022-09-22 07:22 UTC, frivieremicroej commented on SDKUserGuide/resolveDependenciesInWorkspace.rst
> +Resolve Foundation Library in workspace
```suggestion
Resolve Foundation Library in Workspace
```

2022-09-22 07:23 UTC, frivieremicroej commented on SDKUserGuide/resolveDependenciesInWorkspace.rst
> +Resolve Foundation Library in workspace
Sync with the previous title: either move to the plural form (Foundation Libraries) or move Dependencies to singular form (Dependency) ?

2022-09-22 07:32 UTC, frivieremicroej commented on SDKUserGuide/resolveDependenciesInWorkspace.rst
> +.. _resolve_foundation_library_in_workspace:
shall we pull-up the sections at the same level of Dependencies ?

![image](https://user-images.githubusercontent.com/19801840/191685445-34024e80-5e51-4368-a79e-d25d6619cb0b.png)



shall we pull up

2022-09-22 07:40 UTC, frivieremicroej commented on SDKUserGuide/resolveDependenciesInWorkspace.rst
> +- A Mock project that contains the implementation of native methods for simulation
The How-To is confusing: a Foundation Library does not include the C implementation code and the Mock.



```suggestion
- An API project that contains Java classes, methods and fields used at compile time with their associated Javadoc,
  
- An Implementation project that contains the runtime code executed by the Platform and Low Level C header files

Beside Foundation Library projects, there is usually a :ref:`Mock <mock>` project that contains the implementation of native methods for simulation.
```

(only focus on the mock project since this is the purpose of this section)

2022-09-22 07:41 UTC, frivieremicroej commented on SDKUserGuide/resolveDependenciesInWorkspace.rst
> +   To learn how to setup a Foundation Library, please consult our MicroEJ How-to available on
```suggestion
   To learn how to setup a Foundation Library, please consult the How-to available on 
```

2022-09-22 07:42 UTC, frivieremicroej commented on SDKUserGuide/startup.rst
> +By default, the SDK suggests to point to the default MicroEJ repository on your operating system,
```suggestion
By default, the SDK suggests to point to the default repository on your operating system, 
```

2022-09-22 07:43 UTC, frivieremicroej commented on ApplicationDeveloperGuide/platform.rst
>  MicroEJ Platforms are distributed in two packages:
```suggestion
Platforms are distributed in two packages:
```

General note: remove MicroEJ prefix in modified pages as much as possible

2022-09-22 07:48 UTC, frivieremicroej commented on SDKUserGuide/resolveDependenciesInWorkspace.rst
> +When the API is set as a dependency, the Implementation project and the Mock project are automatically used for execution on Simulator
```suggestion
When the API is set as a dependency, the Implementation project and the Mock project are automatically used for execution on Simulator 
```

We must separate:

- the Implementation project: it is also taken into account when building the Application on Device 
- the mock project; only on Simulation

2022-09-22 07:51 UTC, frivieremicroej commented on SDKUserGuide/resolveDependenciesInWorkspace.rst
> +When the API is set as a dependency, the Implementation project and the Mock project are automatically used for execution on Simulator
Also add:
- in-place prior to the Platform implementation

Add Warning: the the implementation project must have been built in the Platform once.
What about the mock project ?

2022-09-22 08:40 UTC, tdelhomenie-microej commented
@denisbedin "The integrated environment is composed of the following main elements:"

2022-09-23 10:34 UTC, denisbedin commented on SDKUserGuide/resolveDependenciesInWorkspace.rst
> +Resolve Foundation Library in workspace
Done, I chose to keep the plural form.

2022-09-23 10:34 UTC, denisbedin commented on SDKUserGuide/resolveDependenciesInWorkspace.rst
> +.. _resolve_foundation_library_in_workspace:
Done.

2022-09-23 10:35 UTC, denisbedin commented on SDKUserGuide/resolveDependenciesInWorkspace.rst
> +When the API is set as a dependency, the Implementation project and the Mock project are automatically used for execution on Simulator
Done.

2022-09-23 10:35 UTC, denisbedin commented on SDKUserGuide/resolveDependenciesInWorkspace.rst
> +When the API is set as a dependency, the Implementation project and the Mock project are automatically used for execution on Simulator
I have done some tests and I didn't have to build the Implementation project and the Mock project in the Platform, they were automatically used, so I didn't add Warning.

2022-09-23 10:36 UTC, denisbedin commented
https://docs.microej.com/en/feature-m0090ide-3982_document_resolve_in_workspace/SDKUserGuide/resolveDependenciesInWorkspace.html

2022-09-28 16:26 UTC, frivieremicroej approved these changes

2022-09-28 16:26 UTC, frivieremicroej commented on SDKUserGuide/resolveDependenciesInWorkspace.rst
> +When the API is set as a dependency, the Implementation project and the Mock project are automatically used for execution on Simulator
OK my mistake !

2022-09-29 06:31 UTC, merged