M0137W-732 update download-install sdk pages
MicroEJ/docs pull request #449
Opened 2022-09-20 09:15 UTC by cblanchard-microej

Add the installation of the SDK.

2022-09-20 13:56 UTC, tdelhomenie-microej requested changes

2022-09-20 13:56 UTC, tdelhomenie-microej commented on SDKUserGuide/install.rst
> +- The SDK is available for download at https://repository.microej.com/packages/SDK/21.11/.
Shouldn't we keep the link https://developer.microej.com/microej-sdk-software-development-kit since it is the entry point for the SDK?

2022-09-20 13:56 UTC, tdelhomenie-microej commented on SDKUserGuide/install.rst
> +   A newer version, the ``22.06``, is also available but it requires to have an :ref:`Architecture <architecture_overview>` ``7.17`` or more.
Why not keeping the link to https://repository.microej.com/packages/SDK/ ?

2022-09-20 13:56 UTC, tdelhomenie-microej commented on SDKUserGuide/install.rst
> +     - `22.06 <https://repository.microej.com/packages/SDK/22.06/>`_
Not sure we should highlight all old versions, we want the users to use the latest versions. We could instead add a sentence to say that the previous versions are available at https://repository.microej.com/packages/SDK/. WDYT ?

2022-09-20 13:56 UTC, tdelhomenie-microej commented on SDKUserGuide/install.rst
> +Installation process
```suggestion
Installation
```

2022-09-20 13:56 UTC, tdelhomenie-microej commented on SDKUserGuide/install.rst
> +- Check the :ref:`system-requirements` page for the list of supported environments.
Not sure we should use a list here, the previous sentence sounds good to me.

2022-09-20 13:56 UTC, tdelhomenie-microej commented on SDKUserGuide/install.rst
> +- Select the installation path of your SDK. By default it is ``C:/Program Files/MicroEJ/MicroEJ-SDK-{SDK_VERSION}``. Click on :guilabel:`Next` button.
```suggestion
- Select the installation path of your SDK. By default it is ``C:/Program Files/MicroEJ/MicroEJ-SDK-{SDK_VERSION}``. Then click on the :guilabel:`Next` button.
```

2022-09-20 13:56 UTC, tdelhomenie-microej commented on SDKUserGuide/install.rst
> +- Select the installation path of your SDK. By default it is ``C:/Program Files/MicroEJ/MicroEJ-SDK-{SDK_VERSION}``. Click on :guilabel:`Next` button.
This is the default path for Windows, it should be mentioned IMO.

2022-09-20 13:56 UTC, tdelhomenie-microej commented on SDKUserGuide/install.rst
> +The SDK is now installed on your computer.
Maybe we should add a sentence on how to launch it, something like: you can launch it from your application launcher or by executing the `MicroEJ` executable in the installation path. WDYT?

2022-09-21 13:57 UTC, cblanchard-microej commented on SDKUserGuide/install.rst
> +- The SDK is available for download at https://repository.microej.com/packages/SDK/21.11/.
Keep the link to https://developer.microej.com/microej-sdk-software-development-kit because I thought that the downloading button was only for Windows installer.

2022-09-21 14:07 UTC, cblanchard-microej commented on SDKUserGuide/install.rst
> +     - `22.06 <https://repository.microej.com/packages/SDK/22.06/>`_
I leave as it was before, a sentence to present the SDK distribution 22.06 and a link to https://repository.microej.com/packages/SDK/ so that the user know about the previous distributions.

2022-09-21 14:07 UTC, cblanchard-microej commented on SDKUserGuide/install.rst
> +   A newer version, the ``22.06``, is also available but it requires to have an :ref:`Architecture <architecture_overview>` ``7.17`` or more.
I leave as it was before, a sentence to present the SDK distribution 22.06 and a link to https://repository.microej.com/packages/SDK/ so that the user know about the previous distributions.

2022-09-21 14:08 UTC, cblanchard-microej commented on SDKUserGuide/install.rst
> +- Check the :ref:`system-requirements` page for the list of supported environments.
I let the previous sentence here.

2022-09-26 15:28 UTC, frivieremicroej requested changes

2022-09-26 15:28 UTC, frivieremicroej commented on SDKUserGuide/install.rst
> +--------------------
```suggestion
Installation
------------
```

2022-09-26 15:28 UTC, frivieremicroej commented on SDKUserGuide/install.rst
> +- Launch the installer and click on the :guilabel:`Next` button.
please crop the screenshots properly

2022-10-10 13:57 UTC, frivieremicroej commented
Closed in favor of https://github.com/MicroEJ/docs/pull/462

2022-10-10 13:57 UTC, closed without merging