M0078DDG-500 Update Platform Dev Guide
MicroEJ/docs pull request #452
Opened 2022-09-21 15:54 UTC by thomasponsmicroej

Update of some typos/wording/missing info in the Platform dev guide (creation, migration)

2022-09-22 13:11 UTC, tdelhomenie-microej requested changes

2022-09-22 13:11 UTC, tdelhomenie-microej commented on PlatformDeveloperGuide/platformCreation.rst
> +In a Continuous Integration environment however, the publication is required.
Shouldn't "however" be at the beginning of the sentence?

2022-09-22 13:11 UTC, tdelhomenie-microej commented on PlatformDeveloperGuide/platformCreation.rst
> +  BSP connection is configured when building the MicroEJ Platform (relative locations within the BSP),
```suggestion
  BSP connection is configured when building the Platform (relative locations within the BSP), 
```

2022-09-22 13:11 UTC, tdelhomenie-microej commented on PlatformDeveloperGuide/platformMigration.rst
> +The first step is to create an Architecture Repository, using the MicroEJ Architecture
using -> containing ?

2022-09-22 13:11 UTC, tdelhomenie-microej commented on PlatformDeveloperGuide/platformMigration.rst
> +.. note:: If the Architecture and Packs used by the Platform are already stored on the
```suggestion
.. note:: If the Architecture and Packs used by the Platform are already stored in the 
```

2022-09-22 15:37 UTC, thomasponsmicroej commented on PlatformDeveloperGuide/platformCreation.rst
> +In a Continuous Integration environment however, the publication is required.
fixed

2022-09-23 07:26 UTC, tdelhomenie-microej commented on PlatformDeveloperGuide/platformCreation.rst
> +The contents of this folder will be copied in full in the Platform during the Platform build.
```suggestion
The full content of this folder will be copied in the Platform during the build. 
```

2022-09-23 07:26 UTC, tdelhomenie-microej commented on PlatformDeveloperGuide/platformCreation.rst
> +This feature allows to add some additional libraries, tools
We should we add that it also allows to overwrites existing files?

2022-09-23 09:45 UTC, thomasponsmicroej commented on PlatformDeveloperGuide/platformCreation.rst
> +This feature allows to add some additional libraries, tools
yes, maybe, there is a chapter in which it is described but maybe add a note here too could be good

2022-09-23 11:52 UTC, tdelhomenie-microej commented on PlatformDeveloperGuide/platformCreation.rst
> +This feature allows to add some additional libraries, tools
I was thinking of just changing the sentence to something like: "This feature allows to add or overwrite libraries, tools,
etc. into the Platform."

2022-09-23 12:32 UTC, thomasponsmicroej commented on PlatformDeveloperGuide/platformCreation.rst
> +This feature allows to add some additional libraries, tools
changed

2022-09-29 15:39 UTC, tdelhomenie-microej approved these changes

2022-09-30 08:05 UTC, tdelhomenie-microej commented
@thomasponsmicroej the build fails : https://readthedocs.com/projects/microej-docs/builds/1120383/

2022-09-30 10:07 UTC, thomasponsmicroej commented
> @thomasponsmicroej the build fails : https://readthedocs.com/projects/microej-docs/builds/1120383/

ok, fixed, it passes now

2022-09-30 10:09 UTC, tdelhomenie-microej approved these changes

2022-09-30 10:13 UTC, merged