M0078DDG-502 Update Tutorial Understand How To build a Firmware
MicroEJ/docs pull request #454
Opened 2022-09-22 14:39 UTC by thomasponsmicroej

- Remove "MicroEJ" when possible
- Rewording of some sentences
- Typos

2022-09-23 09:32 UTC, tdelhomenie-microej commented on Tutorials/tutorialUnderstandMicroEJFirmwareBuild.rst
> +The Platform sources consists in the following projects:
I would keep "contains".

2022-09-23 09:33 UTC, tdelhomenie-microej commented on Tutorials/tutorialUnderstandMicroEJFirmwareBuild.rst
> +  * a the Simulator (computer desktop),
```suggestion
  * the Simulator (computer desktop),
```

2022-09-23 09:36 UTC, tdelhomenie-microej commented on Tutorials/tutorialUnderstandMicroEJFirmwareBuild.rst
> +1. Build the Application using MicroEJ SDK (generates a ``microejapp.o`` file).
```suggestion
1. Build the Application using the SDK (generates a ``microejapp.o`` file).
```

2022-09-26 09:32 UTC, tdelhomenie-microej commented on Tutorials/tutorialUnderstandMicroEJFirmwareBuild.rst
> +Firmware (previously known as a MicroEJ Single-app Firmware). The steps
Good point.
But that is quite confusing, the differences are very subtile.
@frivieremicroej cannot we simplify this by merging terms for example?

2022-09-29 16:13 UTC, frivieremicroej commented on Tutorials/tutorialUnderstandMicroEJFirmwareBuild.rst
> +Firmware (previously known as a MicroEJ Single-app Firmware). The steps
I will submit the request for the next glossary meeting. let it as is so far

2022-09-29 16:14 UTC, frivieremicroej requested changes

2022-09-29 16:14 UTC, frivieremicroej commented on Tutorials/tutorialUnderstandMicroEJFirmwareBuild.rst
> +The Architectures are distributed in two versions:
```suggestion
Architectures are distributed in two versions:
```

2022-09-29 16:14 UTC, frivieremicroej commented on Tutorials/tutorialUnderstandMicroEJFirmwareBuild.rst
> +A selection of supported embedded architectures can be found here:
```suggestion
A selection of supported embedded Architectures can be found here:
```

2022-09-30 06:12 UTC, tdelhomenie-microej commented on Tutorials/tutorialUnderstandMicroEJFirmwareBuild.rst
> +Firmware (previously known as a MicroEJ Single-app Firmware). The steps
There is a "glossary meeting" ?

2022-09-30 07:54 UTC, tdelhomenie-microej approved these changes

2022-10-03 08:54 UTC, frivieremicroej approved these changes

2022-10-03 08:54 UTC, merged