M0078DDG-505 Document the option  of the build-artifact-repository build type
MicroEJ/docs pull request #457
Opened 2022-09-28 07:47 UTC by tdelhomenie-microej

2022-09-28 08:44 UTC, frivieremicroej requested changes

2022-09-28 08:44 UTC, frivieremicroej commented on ApplicationDeveloperGuide/moduleNatures.rst
> +     - The coma-separated list of configurations to use for the Architecture modules.
```suggestion
     - The comma-separated list of configurations to use for the Architecture modules.
```

2022-09-28 08:44 UTC, frivieremicroej commented on ApplicationDeveloperGuide/moduleNatures.rst
> +     - The coma-separated list of configurations to use for the Architecture modules.
```suggestion
     - The coma-separated list of configurations to include for the Architecture modules.
```

2022-09-28 08:51 UTC, tdelhomenie-microej commented on ApplicationDeveloperGuide/moduleNatures.rst
> +     - The coma-separated list of configurations to use for the Architecture modules.
Done.

2022-09-29 08:27 UTC, frivieremicroej approved these changes

2022-09-29 08:27 UTC, merged