M0078DDG-493 NLS fallback locale + default locale
MicroEJ/docs pull request #458
Opened 2022-09-28 13:04 UTC by fpinel-microej

2022-09-30 07:02 UTC, seonmej commented on ApplicationDeveloperGuide/nls.rst
> +.. _setCurrentLocale(locale): https://repository.microej.com/javadoc/microej_5.x/apis/ej/nls/NLS.html#getCurrentLocale--
Beware, it references the getter instead of the setter.

2022-09-30 09:14 UTC, fpinel-microej commented on ApplicationDeveloperGuide/nls.rst
> +.. _setCurrentLocale(locale): https://repository.microej.com/javadoc/microej_5.x/apis/ej/nls/NLS.html#getCurrentLocale--
Fixed, thanks. Must have been a clipboard leftover from the `NLS.getCurretLocale` link below.

2022-09-30 09:20 UTC, seonmej approved these changes

2022-11-02 12:32 UTC, frivieremicroej requested changes

2022-11-02 12:32 UTC, frivieremicroej commented on ApplicationDeveloperGuide/nls.rst
> +You can set this fallback locale by specifying a locale name in a ``.nls.list`` file, after the name of the interface you want this locale to be the fallback for, separated by a colon ``:``.
Indicate the version
```suggestion
Starting with version XXX, you can set this fallback locale by specifying a locale name in a ``.nls.list`` file, after the name of the interface you want this locale to be the fallback for, separated by a colon ``:``. 
```

2022-11-03 08:08 UTC, frivieremicroej approved these changes
approve the min version

2022-11-03 08:09 UTC, merged