M0090IDE-3998 Add documentation about Front Panel resolution in the Workspace
MicroEJ/docs pull request #461
Opened 2022-10-04 13:00 UTC by tdelhomenie-microej

2022-10-10 11:13 UTC, frivieremicroej requested changes

2022-10-10 11:13 UTC, frivieremicroej commented on SDKUserGuide/resolveDependenciesInWorkspace.rst
> +   are used regardless of their version or if they are set as dependencies.
I'm not clear about 'if they are set as dependencies' means, here 

```suggestion
   When opened in the workspace, Foundation Library Implementation projects, Mock projects and Front Panel projects
   are loaded regardless of their version prior to the ones provided by the Platform (if any).
```

2022-10-10 16:04 UTC, tdelhomenie-microej commented on SDKUserGuide/resolveDependenciesInWorkspace.rst
> +   are used regardless of their version or if they are set as dependencies.
Done.

2022-11-02 12:45 UTC, frivieremicroej approved these changes

2022-11-02 12:45 UTC, merged