Feature/m0137 w 732 download install sdk refactor download links
MicroEJ/docs pull request #462
Opened 2022-10-10 13:57 UTC by frivieremicroej

2022-10-10 14:49 UTC, frivieremicroej commented on SDKUserGuide/installSDKDistribution21_11.rst
> +   - `Windows (.exe) <https://repository.microej.com/packages/SDK/21.11/MicroEJ-SDK-Installer-Win64-21.11.exe>`__.
@tdelhomenie-microej I remember we discussed to add OS icons

2022-10-10 14:49 UTC, frivieremicroej commented on conf.py
> +linkcheck_ignore = ["https://repository.microej.com/packages/SDK/21.11/", "https://repository.microej.com/packages/SDK/22.06/", "https://repository.microej.com/packages/SDK/21.03/", "https://reposito
@cblanchard-microej please update status of readthedocs support about http HEAD request instead of GET

2022-10-10 14:49 UTC, frivieremicroej commented on SDKUserGuide/installSDKDistributionOther.rst
> +     - `Installer (.exe) <https://repository.microej.com/packages/SDK/22.06/MicroEJ-SDK-Installer-Win64-22.06.exe>`__
We can also duplicate all lines with the Portable package link
```suggestion
     - -`Installer (.exe) <https://repository.microej.com/packages/SDK/22.06/MicroEJ-SDK-Installer-Win64-22.06.exe>`__
       -`Portable (.zip) <https://repository.microej.com/packages/SDK/22.06/zip/microej-sdk-22.06-linux_x86_64.zip>`__ 
```

2022-10-10 15:03 UTC, cblanchard-microej commented on conf.py
> +linkcheck_ignore = ["https://repository.microej.com/packages/SDK/21.11/", "https://repository.microej.com/packages/SDK/22.06/", "https://repository.microej.com/packages/SDK/21.03/", "https://reposito
I sent a ticket, i am waiting for the answer.

2022-10-11 13:31 UTC, cblanchard-microej requested changes

2022-10-11 13:31 UTC, cblanchard-microej commented on conf.py
> +linkcheck_ignore = ["https://repository.microej.com/packages/SDK/21.11/", "https://repository.microej.com/packages/SDK/22.06/", "https://repository.microej.com/packages/SDK/21.03/", "https://reposito
I update the sphinx version on this branch: https://github.com/MicroEJ/docs/tree/feature/update_sphinx_version
The issue with HEAD request instead of GET is solved and this line could be removed.

2022-10-11 13:31 UTC, cblanchard-microej commented on SDKUserGuide/installSDKDistributionOther.rst
> +     - `Installer (.zip) <https://repository.microej.com/packages/SDK/19.05/MicroEJ-SDK-Installer-MacOS-19.05.zip>`__
I got a 404 Not Found issue with this links. I just find the Windows installer in this repository: https://repository.microej.com/packages/SDK/19.05/

2022-10-12 12:06 UTC, tdelhomenie-microej requested changes

2022-10-12 12:06 UTC, tdelhomenie-microej commented on SDKUserGuide/systemRequirements.rst
> +You can download and install a JDK from https://adoptium.net/temurin/releases/.
Why do we talk only about Temurin?

2022-10-12 12:06 UTC, tdelhomenie-microej commented on SDKUserGuide/installSDKDistributionTroubleshooting.rst
> +Troubleshooting
We should move the troubleshooting section for Mac https://docs.microej.com/en/latest/SDKUserGuide/troubleshooting.html#macos-specifics here, or even in the installation steps.

2022-10-12 13:41 UTC, denisbedin commented on SDKUserGuide/installSDKDistributionOther.rst
> +     - `Installer (.zip) <https://repository.microej.com/packages/SDK/20.07/MicroEJ-SDK-Installer-MacOS-20.07.zip>`__
@cblanchard-microej I have uploaded the missing installers so you should not have the 404 error anymore

2022-10-13 07:38 UTC, cblanchard-microej commented on SDKUserGuide/installSDKDistributionOther.rst
> +     - `Installer (.zip) <https://repository.microej.com/packages/SDK/20.07/MicroEJ-SDK-Installer-MacOS-20.07.zip>`__
Yes, it works for me now.

2022-10-17 08:17 UTC, frivieremicroej commented on SDKUserGuide/installSDKDistributionOther.rst
> +     - `Installer (.exe) <https://repository.microej.com/packages/SDK/22.06/MicroEJ-SDK-Installer-Win64-22.06.exe>`__
@denisbedin could you please upload the missing portable files :
- https://repository.microej.com/packages/SDK/20.10/
- https://repository.microej.com/packages/SDK/20.07/
- https://repository.microej.com/packages/SDK/19.02/
- 
Thanks

2022-10-17 08:23 UTC, frivieremicroej commented
Link to the preview: https://docs.microej.com/en/feature-m0137w-732_download_install_sdk_refactor_download_links/

2022-10-17 08:30 UTC, cblanchard-microej approved these changes

2022-10-17 13:33 UTC, frivieremicroej commented on SDKUserGuide/installSDKDistribution21_11.rst
> +   - `Windows (.exe) <https://repository.microej.com/packages/SDK/21.11/MicroEJ-SDK-Installer-Win64-21.11.exe>`__.
could be done later

2022-10-17 13:53 UTC, frivieremicroej commented on SDKUserGuide/installSDKDistributionTroubleshooting.rst
> +Troubleshooting
move all troubleshooting 
+ add a warning macos quarantine
+ windows: notify defender

2022-10-17 13:57 UTC, frivieremicroej commented on requirements.txt
> +Sphinx==3.2.0
@cblanchard-microej please update the local installation procedure on docs.cross to get the correct sphinx version (check @tdelhomenie-microej )

2022-10-17 13:59 UTC, frivieremicroej commented on requirements.txt
> +Sphinx==3.2.0
there is also the doc https://github.com/MicroEJ/docs/blob/master/README.rst

2022-10-19 12:06 UTC, frivieremicroej commented on SDKUserGuide/installSDKDistributionPortable.rst
> +     - ``8``
As discussed, let the Java 8 version as this is the required version for the default SDK version 5.4.0 embedded in Dist 21.11

2022-10-19 12:23 UTC, frivieremicroej commented on SDKUserGuide/installSDKDistributionLatest.rst
> +Now you can check if there is a newer SDK version available.
it updated with the same sentence in the 3 install pages

2022-10-19 13:10 UTC, frivieremicroej commented on SDKUserGuide/installSDKDistributionOther.rst
> +  installSDKDistribution21_11
I rewrote the introduction, please have a look

2022-10-19 13:10 UTC, frivieremicroej commented on SDKUserGuide/installSDKDistributionOther.rst
> +The following table gathers all SDK Distributions links for SDK version ``5.x``.
done

2022-10-19 13:55 UTC, frivieremicroej commented on SDKUserGuide/installSDKDistributionTroubleshooting.rst
> +Troubleshooting
done

2022-10-19 16:49 UTC, jerome-leroux requested changes

2022-10-19 16:49 UTC, jerome-leroux commented on SDKUserGuide/installSDKDistribution21_11.rst
> +This section will guide you to install the SDK Distribution ``21.11`` using the step-by-step executable installer.
```suggestion
This section will guide you through the installation process of the SDK Distribution ``21.11`` using the step-by-step executable installer.
```

2022-10-20 07:22 UTC, tdelhomenie-microej requested changes

2022-10-20 07:22 UTC, tdelhomenie-microej commented on SDKUserGuide/installSDKDistributionOther.rst
> +- you want to install the latest SDK Distribution based on JDK8, see :ref:`sdk_installation_21_11` section.
```suggestion
- you want to install the latest SDK Distribution compatible with JDK8, see :ref:`sdk_installation_21_11` section.
```

2022-10-20 07:22 UTC, tdelhomenie-microej commented on SDKUserGuide/installSDKDistributionOther.rst
> +This section applies when the :ref:`latest SDK Distribution <sdk_installation_latest>` cannot be installed:
```suggestion
This section applies when the installation of the :ref:`latest SDK Distribution <sdk_installation_latest>` via the installer does not fit your case:
```

2022-10-20 07:22 UTC, tdelhomenie-microej commented on SDKUserGuide/installSDKDistribution21_11.rst
> +   - `macOS x86_64 - Intel chip (.zip) <https://repository.microej.com/packages/SDK/21.11/MicroEJ-SDK-Installer-MacOS-21.11.zip>`__.
```suggestion
   - `Windows (.exe) <https://repository.microej.com/packages/SDK/21.11/MicroEJ-SDK-Installer-Win64-21.11.exe>`__
   - `Linux (.zip) <https://repository.microej.com/packages/SDK/21.11/MicroEJ-SDK-Installer-Linux64-21.11.zip>`__
   - `macOS x86_64 - Intel chip (.zip) <https://repository.microej.com/packages/SDK/21.11/MicroEJ-SDK-Installer-MacOS-21.11.zip>`__
```

2022-10-20 07:22 UTC, tdelhomenie-microej commented on SDKUserGuide/systemRequirements.rst
> +You can download and install a JDK from https://adoptium.net/temurin/releases/.
To be done.

2022-10-20 07:22 UTC, tdelhomenie-microej commented on SDKUserGuide/installSDKDistribution21_11.rst
> +    In case of error, check your app has not been put in quarantine (see :ref:`macOS troubleshooting <sdk_install_troubleshooting_macos>` section)
```suggestion
    In case of error, check your app has not been put in quarantine (see :ref:`macOS troubleshooting <sdk_install_troubleshooting_macos>` section).
```

2022-10-20 07:22 UTC, tdelhomenie-microej commented on SDKUserGuide/installSDKDistribution21_11.rst
> +The SDK Distribution ``21.11`` requires a JDK 8 and is not available for macOS with M1 chips.
Version 21.11 or lower work with a JRE as well. We don't mention that anymore? I am ok with that, but we should be consistent. For example in the System Requirements page, we mention JRE and JDK.

2022-10-20 07:22 UTC, tdelhomenie-microej commented on SDKUserGuide/install.rst
> +   troubleshooting
We should add this toctree and add a sentence to redirect to the installation of the latest distribution (22.06).

2022-10-21 13:45 UTC, jerome-leroux commented
Tell Corentin to update getting started link to reference the new documentation.

2022-10-25 13:48 UTC, tdelhomenie-microej commented on SDKUserGuide/updateSDKVersion.rst
> +SDK versions are uploaded to an Eclipse P2 repository located at https://repository.microej.com/p2/sdk/.
I simply removed the sentence. As you said it is not useful for the user.

2022-10-25 13:50 UTC, tdelhomenie-microej commented on SDKUserGuide/installSDKDistribution21_11.rst
> +The SDK Distribution ``21.11`` requires a JDK 8 and is not available for macOS with M1 chips.
Done

2022-10-25 14:35 UTC, tdelhomenie-microej commented on SDKUserGuide/install.rst
> +   troubleshooting
Done.

2022-10-25 14:42 UTC, tdelhomenie-microej commented on SDKUserGuide/systemRequirements.rst
> +You can download and install a JDK from https://adoptium.net/temurin/releases/.
Done.

2022-10-25 21:03 UTC, jerome-leroux approved these changes

2022-10-25 21:03 UTC, merged