M0090IDE-4009 Add chapter about useing libraries in Applications
MicroEJ/docs pull request #468
Opened 2022-10-24 14:59 UTC by tdelhomenie-microej

2022-11-02 13:57 UTC, frivieremicroej requested changes

2022-11-02 13:57 UTC, frivieremicroej commented on ApplicationDeveloperGuide/sandboxedAppLibraries.rst
> +its JAR file can be directly added in the ``META-INF/libraries`` folder of the Application project.
```suggestion
Use an External Library
=======================

A Sandboxed Application can embed external libraries in addition to those declared as :ref:`module dependencies <module-dependencies>`. 

For that, the JAR file must be dropped to the ``META-INF/libraries`` directoy of the Sandboxed Application project.
```

2022-11-02 13:57 UTC, frivieremicroej commented on ApplicationDeveloperGuide/sandboxedAppLibraries.rst
> +its JAR file can be directly added in the ``META-INF/libraries`` folder of the Application project.
@tdelhomenie-microej remind also to add the procedure to add it to eclipse project classpath

2022-11-04 07:53 UTC, tdelhomenie-microej commented on ApplicationDeveloperGuide/sandboxedAppLibraries.rst
> +its JAR file can be directly added in the ``META-INF/libraries`` folder of the Application project.
Your suggestion removes the chapter `Add a library as a dependency`, is it a mistake?

2022-11-04 08:12 UTC, tdelhomenie-microej commented on ApplicationDeveloperGuide/sandboxedAppLibraries.rst
> +its JAR file can be directly added in the ``META-INF/libraries`` folder of the Application project.
> @tdelhomenie-microej remind also to add the procedure to add it to eclipse project classpath

The jars are actually automatically added to the Eclipse project classpath. I guess this is due to the nature `com.is2t.microej.wadapps.workbench.wadappsApplicationNature` that is still present when creating a Sandboxed Application project:
```
	<natures>
		<nature>org.eclipse.jdt.core.javanature</nature>
		<nature>org.apache.ivyde.eclipse.ivynature</nature>
		<nature>com.is2t.microej.wadapps.workbench.wadappsApplicationNature</nature>
	</natures>
```
We should probably adapt this nature to keep only features related to KF-only apps.

2022-11-04 09:17 UTC, tdelhomenie-microej commented on ApplicationDeveloperGuide/sandboxedAppLibraries.rst
> +Use a Library
Done.

2022-11-14 08:44 UTC, frivieremicroej requested changes

2022-11-14 09:24 UTC, frivieremicroej approved these changes

2022-11-14 09:25 UTC, merged