document Architecture 8 new section names
MicroEJ/docs pull request #479
Opened 2022-11-21 15:52 UTC by frivieremicroej

2022-11-21 15:57 UTC, frivieremicroej commented
@fpinel-microej It could be interesting here to use the new tab, can you please update the branch ?

2022-11-21 17:51 UTC, jerome-leroux commented
See https://docs.microej.com/en/feature-m0081meja-186_document_new_section_names/VEEPortingGuide/coreEngine.html#link

2022-11-21 18:05 UTC, jerome-leroux requested changes

2022-11-21 18:05 UTC, jerome-leroux commented on VEEPortingGuide/coreEngine.rst
>  must be linked by the third-party linker.
Are we listing the sections defined by the Core Engine or referenced by the Core Engine?

Should we mention the `.text.*` code sections?

2022-11-21 18:05 UTC, jerome-leroux commented on VEEPortingGuide/coreEngine.rst
> +   |                               | internal heap               |             |            |
Why "Internal"? Is this to mention that it is better to locate this section in internal RAM?

Should we defined an ordered list of the sections to specify which one should be placed in priority in faster memories?

2022-11-21 18:05 UTC, jerome-leroux commented on VEEPortingGuide/coreEngine.rst
>     |                             | statics                     |             |            |
```suggestion
   |                             | static fields               |             |            |
```

2022-11-23 16:37 UTC, fpinel-microej commented
@frivieremicroej Is this what you had in minds for the tabs ? let me know

2022-11-24 16:04 UTC, frivieremicroej commented on VEEPortingGuide/coreEngine.rst
>  must be linked by the third-party linker.
Both. 
Yes, `.text` these are special executable sections that must be mentionned

2022-11-24 16:10 UTC, frivieremicroej commented on VEEPortingGuide/coreEngine.rst
> +	Sections ``.bss.microej.runtime``, ``.bss.microej.heap`` and ``.bss.microej.immortals`` are zero-initialized at Core Engine startup.
done

2022-11-24 16:11 UTC, frivieremicroej commented on VEEPortingGuide/coreEngine.rst
> +   |                               | statics                     |             |            |
done

2022-11-24 16:14 UTC, frivieremicroej commented on VEEPortingGuide/coreEngine.rst
> +   |                               | internal heap               |             |            |
Good catch, I don't remember. 
TBD

2022-11-29 14:15 UTC, jerome-leroux requested changes

2022-11-29 14:15 UTC, jerome-leroux commented on VEEPortingGuide/coreEngine.rst
> +            During its startup, the Core Engine automatically zero-initializes the sections ``.bss.microej.runtime``, ``.bss.microej.heap`` and ``.bss.microej.immortals``.
```suggestion
            During its startup, the Core Engine automatically zero-initializes the sections ``.bss.microej.runtime``, ``.bss.microej.heap``, and ``.bss.microej.immortals``. 
```

2023-01-11 17:34 UTC, jerome-leroux commented on VEEPortingGuide/coreEngine.rst
> +   |                               | internal heap               |             |            |
Link to the note does not jump at the right position. Again, it is hidden by the banner.
I ask Felix to check that.

2023-01-11 17:40 UTC, jerome-leroux requested changes

2023-01-11 17:40 UTC, jerome-leroux commented on VEEPortingGuide/coreEngine.rst
> +            During its startup, the Core Engine automatically zero-initializes the sections ``ICETEA_HEAP``, ``_java_heap`` and ``_java_immortals``.
```suggestion
            During its startup, the Core Engine automatically zero-initializes the sections ``ICETEA_HEAP``, ``_java_heap``, and ``_java_immortals``. 
```

2023-01-12 16:04 UTC, jerome-leroux approved these changes

2023-01-12 16:05 UTC, merged