Document the MicroEJ debugger proxy
MicroEJ/docs pull request #482
Opened 2022-11-24 17:21 UTC by dalgassimou

2022-12-05 13:52 UTC, akhabali requested changes

2022-12-05 13:52 UTC, akhabali commented on ApplicationDeveloperGuide/debuggerProxy.rst
> +It consists of a TCP server implementing the JDWP protocol and acting as a proxy between the debugger and the VEE running on the board.
```suggestion
It consists of a TCP server implementing the JDWP protocol and acting as a proxy between the IDE (debugger) and the VEE (debuggee) running on the board.
```

2022-12-05 13:52 UTC, akhabali commented on ApplicationDeveloperGuide/debuggerProxy.rst
> +   MicroEJ Development Tools Overview of the Debugger on Simulator
```suggestion
   MicroEJ Development Tools Overview of the Debugger on Board
```

2022-12-05 13:52 UTC, akhabali commented on ApplicationDeveloperGuide/debuggerProxy.rst
> +The MicroeEJ debugger proxy only allow a postmortem debug now so it requires among other things a core dump file of a running MicroEJ VEE process.
```suggestion
The current version of the VEE Debugger Proxy only supports postmortem debugging. 
It requires a core dump file of a VEE process and some libraries provided by the VEE project.
```

2022-12-05 13:52 UTC, akhabali commented on ApplicationDeveloperGuide/debuggerProxy.rst
> +MicroEJ Debugger Proxy
```suggestion
VEE Debugger Proxy
```

2022-12-05 13:52 UTC, akhabali commented on ApplicationDeveloperGuide/debuggerProxy.rst
> +The MicroEJ debugger proxy is a Java Debug Wire protocol implementation on top of MicroEJ VEE enabling on board debugging.
```suggestion
The VEE Debugger Proxy is a Java Debug Wire Protocol (JDWP) implementation enabling on board debugging for VEE processes.
```

2022-12-05 13:52 UTC, akhabali commented on ApplicationDeveloperGuide/debuggerProxy.rst
> +
In this section, I would start by explaining how the debugger can be used in production.

The coredump file should be generated whenever the VEE process receive a specific user signal or when a fatal error is raised using interrupts maybe. 

Then this core dump file can be loaded into the Debugger Proxy to perform a postmortem inspection of the VEE process state

2022-12-05 13:52 UTC, akhabali commented on ApplicationDeveloperGuide/debuggerProxy.rst
> +Run the MicroEJ Debugger proxy
```suggestion
Run the VEE Debugger proxy
```

2022-12-05 13:52 UTC, akhabali commented on ApplicationDeveloperGuide/debuggerProxy.rst
> +Please contact :ref:`our support team <get_support>` to get the MicroeEJ Debugger proxy program.
```suggestion
Please contact :ref:`our support team <get_support>` to get the VEE Debugger Proxy program.
```

2022-12-20 17:35 UTC, amorel-microej reviewed
It works with the generic Linux VEE on the WSL.
I tried with a Docker Linux x86 container but it doesn't work, probably the tcp access. But by get the .out and the dump file and copy its into the WSL, the process works.

2022-12-20 17:35 UTC, amorel-microej commented on ApplicationDeveloperGuide/debuggerProxy.rst
> +  Other runtime jars can be provided using this property.
The path must contain the name and the extension of the file (e.g. ./linux-platform/source/tools/soarModelReader.jar).

2022-12-20 17:35 UTC, amorel-microej commented on ApplicationDeveloperGuide/debuggerProxy.rst
> +The MicroEJ debugger proxy is a Java Debug Wire protocol implementation on top of MicroEJ VEE enabling on board debugging.
The MicroEJ debugger proxy is a Java Debug Wire protocol (JDWP) implementation on top of MicroEJ VEE enabling on board debugging.

2022-12-20 17:35 UTC, amorel-microej commented on ApplicationDeveloperGuide/debuggerProxy.rst
> +The MicroeEJ debugger proxy only allow a postmortem debug now so it requires among other things a core dump file of a running MicroEJ VEE process.
The MicroeEJ debugger proxy only allows a postmortem debug now so it requires among other things a core dump file of a running MicroEJ VEE process.

2023-01-03 17:23 UTC, amorel-microej commented on ApplicationDeveloperGuide/debuggerProxy.rst
> +   commands
The command list is for the last breakpoint or catchpoint. Here, the signal catchpoint will not generate the core dump.
It is necessary to duplicate the commands for the catchpoint.
Or to add the breakpoint or catchpoint id to the commands line.

2023-01-03 17:23 UTC, amorel-microej commented on ApplicationDeveloperGuide/debuggerProxy.rst
> +   break LLMJVM_on_Runtime_gc_done # break in the LLMJVM_on_Runtime_gc_done function
It can be helpful to add the symbol "LLMJVM_on_OutOfMemoryError_thrown" as an example.

2023-01-04 14:41 UTC, akhabali approved these changes
LGTM

2023-01-11 10:55 UTC, frivieremicroej commented
Preview: https://docs.microej.com/en/feature-m0081meja-2056_debuggerproxy/

2023-01-11 15:22 UTC, frivieremicroej commented on ApplicationDeveloperGuide/debug.rst
> +Debug on Simulator
Please review & merge https://github.com/MicroEJ/docs/pull/498

2023-01-11 15:23 UTC, frivieremicroej commented on ApplicationDeveloperGuide/debug.rst
> +.. figure:: images/debug2.png
fix crop + windows 10 screenshot (no rounded corners)

2023-01-11 15:24 UTC, frivieremicroej commented on ApplicationDeveloperGuide/debuggerProxy.rst
> +.. figure:: images/debugger_proxy1.png
Then ask @frivieremicroej to update usages of VEE / terms accordingly

2023-02-02 13:33 UTC, dalgassimou commented on ApplicationDeveloperGuide/debuggerProxy.rst
> +   generate-core-file [file] # the argument `file` specifies the file name where to put the core dump
we should replace the [file] by the filename we want

2023-02-02 13:34 UTC, dalgassimou commented on ApplicationDeveloperGuide/debuggerProxy.rst
> +        -Ddebugger.out.format=<elf> \
https://youtrack.cross/issue/M0081MEJA-2096

2023-02-02 13:34 UTC, dalgassimou commented on ApplicationDeveloperGuide/debuggerProxy.rst
> +        -Ddebugger.out.bigEndianness=<false> \
https://youtrack.cross/issue/M0081MEJA-2096

2023-02-02 13:37 UTC, dalgassimou commented on ApplicationDeveloperGuide/debuggerProxy.rst
> +.. figure:: images/debugger_proxy1.png
the schematics is an inline graph like plantuml called mermaid. do you want me to share it in text file?

2023-02-02 13:37 UTC, dalgassimou commented on ApplicationDeveloperGuide/debuggerProxy.rst
> +*  **debugger.out.bigEndianness**: VEE .out file big endian, default to false
https://youtrack.cross/issue/M0081MEJA-2096

2023-02-02 13:40 UTC, dalgassimou commented on ApplicationDeveloperGuide/debuggerProxy.rst
> +* **loader.path**: The path to the platform ``soarModelReader.jar`` and ``vmModelReader.jar`` needs to be provided here.
https://youtrack.cross/issue/M0081MEJA-2097

2023-02-02 13:46 UTC, dalgassimou commented on ApplicationDeveloperGuide/debug.rst
> +.. figure:: images/debug2.png
can you send the process which describe how to take a screenshot

2023-02-20 07:44 UTC, frivieremicroej commented on ApplicationDeveloperGuide/debuggerProxy.rst
> +.. figure:: images/debugger_proxy1.png
yes, share the source file and instructions to rebuild it

2023-03-20 09:17 UTC, dalgassimou commented on ApplicationDeveloperGuide/debuggerProxy.rst
> +.. figure:: images/debugger_proxy1.png
where should I share the doc and the instructions?

2023-03-24 08:35 UTC, dalgassimou commented on ApplicationDeveloperGuide/debuggerProxy.rst
> +.. figure:: images/debugger_proxy1.png
done

2023-03-24 08:35 UTC, dalgassimou commented on ApplicationDeveloperGuide/debuggerProxy.rst
> +   generate-core-file [file] # the argument `file` specifies the file name where to put the core dump
done

2023-03-24 08:36 UTC, dalgassimou commented on ApplicationDeveloperGuide/debuggerProxy.rst
> +Open a shell terminal and run the following command
done

2023-03-24 08:36 UTC, dalgassimou commented on ApplicationDeveloperGuide/debug.rst
> +.. figure:: images/debug2.png
done

2023-03-24 08:36 UTC, dalgassimou commented on ApplicationDeveloperGuide/debuggerProxy.rst
> +Open a shell terminal and enter the following commands:
done

2023-03-24 08:36 UTC, dalgassimou commented on ApplicationDeveloperGuide/debuggerProxy.rst
> +You can also suspend the process and generate the core dump file yourself:
done

2023-03-24 08:36 UTC, dalgassimou commented on ApplicationDeveloperGuide/debuggerProxy.rst
> +   This feature requires Architecture version ``8.0.0`` or higher.
done

2023-03-24 10:33 UTC, frivieremicroej approved these changes

2023-03-24 10:43 UTC, merged