Review images documentation.
MicroEJ/docs pull request #487
Opened 2022-12-05 10:56 UTC by seonmej

2022-12-08 13:41 UTC, microej-sh commented on VEEPortingGuide/uiImageRaw.rst
> +The number of bits-per-pixels and the pixel bits organisation is asked during the MicroEJ format generation and when the ``drawImage`` algorithms are running.
```suggestion
The number of bits per pixel and the pixel bit organization is asked during the MicroEJ format generation and when the ``drawImage`` algorithms are running.
```

2022-12-08 13:41 UTC, microej-sh commented on VEEPortingGuide/uiImageRaw.rst
> +.. note:: From Image Engine point of view, the format stays a MicroEJ format, readable by the Image Renderer.
```suggestion
.. note:: From the Image Engine point of view, the format stays a MicroEJ format, readable by the Image Renderer.
```

2022-12-08 13:41 UTC, microej-sh commented on VEEPortingGuide/uiImageRaw.rst
> +This format requires a small header (around 20 bytes) to store the image size (width, height), format, flags (is_transparent etc.), row stride etc.
```suggestion
This format requires a small header (around 20 bytes) to store the image size (width, height), format, flags (is_transparent etc.), row stride, etc.
```

2022-12-08 13:41 UTC, microej-sh commented on VEEPortingGuide/uiImageRaw.rst
> +The required memory also depends on the number of bits-per-pixels of MicroEJ format:
```suggestion
The required memory also depends on the number of bits per pixels of the MicroEJ format:
```

2022-12-08 13:41 UTC, microej-sh commented on VEEPortingGuide/uiImageRaw.rst
> +-  RGB565: 16-bit format, 5 or 6 per color.
```suggestion
-  RGB565: 16-bit format, 5 for red, 6 for green, 5 for blue.
```

2022-12-08 13:41 UTC, microej-sh commented on VEEPortingGuide/uiImageRaw.rst
> +The pixels order follows this rule:
```suggestion
The pixel order follows this rule:
```

2022-12-08 13:41 UTC, microej-sh commented on VEEPortingGuide/uiImageRaw.rst
> +This format requires a small header (around 20 bytes) to store the image size (width, height), format, flags (is_transparent etc.), row stride etc.
```suggestion
This format requires a small header (around 20 bytes) to store the image size (width, height), format, flags (is_transparent etc.), row stride, etc.
```

2022-12-08 13:41 UTC, microej-sh commented on VEEPortingGuide/uiImageRaw.rst
> +The required memory also depends on the number of bits-per-pixels of MicroEJ format:
```suggestion
The required memory also depends on the number of bits per pixels of the MicroEJ format:
```

2022-12-08 13:41 UTC, microej-sh commented on VEEPortingGuide/uiImageRaw.rst
> +The pixels order follows this rule:
```suggestion
The pixel order follows this rule:
```

2022-12-08 13:41 UTC, microej-sh commented on VEEPortingGuide/uiImageRaw.rst
> +The MicroEJ format may be customized to be platform's GPU compatible. It can be extended by one or several restrictions on the pixels array:
```suggestion
The MicroEJ format may be customized to be compatible with the platform's GPU. It can be extended by one or several restrictions on the pixels array: 
```

2022-12-08 13:41 UTC, microej-sh commented on VEEPortingGuide/uiImageRaw.rst
> +* The MicroEJ format can hold a platform dependant header, located between MicroEJ format header (start of file) and pixels array.
```suggestion
* The MicroEJ format can hold a platform-dependent header, located between the MicroEJ format header (start of file) and the pixel array.
```

2022-12-08 13:41 UTC, microej-sh commented on VEEPortingGuide/uiImageRaw.rst
> +  The MicroEJ format is designed to let the platform encodes and decodes this additional header.
```suggestion
  The MicroEJ format is designed to let the platform encode and decode this additional header.
```

2022-12-08 13:41 UTC, microej-sh commented on VEEPortingGuide/uiImageRaw.rst
> +  For Image Engine software algorithms, this header is useless and never used.
```suggestion
  For Image Engine software algorithms, this header is not needed and never used.
```

2022-12-08 13:41 UTC, microej-sh commented on VEEPortingGuide/uiImageRaw.rst
> +When MicroEJ format holds another header (called ``custom_header``), the required memory is:
```suggestion
When the MicroEJ format holds another header (called ``custom_header``), the required memory is:
```

2022-12-08 13:41 UTC, microej-sh commented on VEEPortingGuide/uiImageRaw.rst
> +The row stride allows to add some padding at the end of each line in order to start next line at an address with a specific memory alignment; it is often required by hardware accelerators (GPU).
```suggestion
The row stride allows to add some padding at the end of each line in order to start the next line at an address with a specific memory alignment; it is often required by hardware accelerators (GPU).
```

2022-12-08 13:41 UTC, microej-sh commented on VEEPortingGuide/uiImageRaw.rst
> +The required RAM memory becomes:
```suggestion
The required memory becomes:
```

2022-12-08 13:41 UTC, microej-sh commented on VEEPortingGuide/uiImageRaw.rst
> +This format is not compatible with the Image Renderer and by MicroUI.
```suggestion
This format is not compatible with the Image Renderer and MicroUI.
```

2022-12-08 13:41 UTC, microej-sh commented on VEEPortingGuide/uiImageRaw.rst
> +It is can be used by MicroUI addon libraries which provide their own images managements.
```suggestion
It is can be used by MicroUI addon libraries which provide their own image management procedures.
```

2022-12-08 13:41 UTC, microej-sh commented on ApplicationDeveloperGuide/UI/MicroUI/images.rst
>  In other words, every image which can not be retrieved using `ej.microui.display.Image.getImage()`_  is saved on the images heap.
```suggestion
In other words, every image which cannot be retrieved using `ej.microui.display.Image.getImage()`_  is saved on the image heap.
```

2022-12-09 14:27 UTC, seonmej commented on VEEPortingGuide/uiImageRaw.rst
> +It is can be used by MicroUI addon libraries which provide their own images managements.
`It is can be` also ;)

2023-02-07 10:04 UTC, seonmej commented on VEEPortingGuide/uiReleaseNotes.rst
> +* According to the VG-Lite GPU revision, the transparent images ARGB8888, ARGB1555 and ARGB4444 are not compatible. The old GPU revisions don't render correctly the transparent images because the pre
Depending on the VG-Lite GPU revision, the transparent images…

2023-02-07 13:46 UTC, microej-sh requested changes

2023-02-07 13:46 UTC, microej-sh commented on VEEPortingGuide/uiReleaseNotes.rst
> +| flush (copy)   | copy of data from back buffer to frame buffer        |
```suggestion
| Fill rectangle |                                                      |
+----------------+------------------------------------------------------+
| Draw image     | ARGB8888, RGB888, RGB565, ARGB1555, ARGB4444, A8, A4 |
+----------------+------------------------------------------------------+
| Flush (copy)   | Copy data from back buffer to frame buffer           |
```

2023-02-07 13:46 UTC, microej-sh commented on VEEPortingGuide/uiReleaseNotes.rst
> +The following table describes the compatibility versions between the C module and the MicroEJ UI Packs:
```suggestion
The following table describes the version compatibility between the C module and the MicroEJ UI Packs:
```

2023-02-07 13:46 UTC, microej-sh commented on VEEPortingGuide/uiReleaseNotes.rst
> +* The rendering time of a simple shape with the GPU (time in the VG-Lite library + GPU setup time + rendering time) is more important than the direct rendering in software. To enable the hardware ren
```suggestion
* The rendering time of a simple shape with the GPU (time in the VG-Lite library + GPU setup time + rendering time) is longer than with software rendering. To enable the hardware rendering for simple shapes, uncomment the definition of ``VGLITE_USE_GPU_FOR_SIMPLE_DRAWINGS``  in ``display_configuration.h``.
```

2023-02-07 13:46 UTC, microej-sh commented on VEEPortingGuide/uiReleaseNotes.rst
> +* The rendering time of a RGB565 image on a RGB565 buffer without applying an opacity (alpha == 0xff) is more important than than the direct rendering in software (this kind of drawing consists to pe
```suggestion
* The rendering time of an RGB565 image into an RGB565 buffer without applying an opacity (alpha == 0xff) is longer than than with software rendering (as this kind of drawing consists in performing a mere memory copy). To enable the hardware rendering for RGB565 images, uncomment the definition of ``VGLITE_USE_GPU_FOR_RGB565_IMAGES``  in ``display_configuration.h``.
```

2023-02-07 13:46 UTC, microej-sh commented on VEEPortingGuide/uiReleaseNotes.rst
> ++-----------------------------+-----------------------------------------------------------+
```suggestion
+-----------------------------+-----------------------------------------------------------+
| Feature                     | Comment                                                   |
+=============================+===========================================================+
| Draw line                   | Disabled by default (see above)                           |
+-----------------------------+-----------------------------------------------------------+
| Fill rectangle              | Disabled by default (see above)                           |
+-----------------------------+-----------------------------------------------------------+
| Draw rounded rectangle      | Disabled by default (see above)                           |
+-----------------------------+-----------------------------------------------------------+
| Fill rounded rectangle      |                                                           |
+-----------------------------+-----------------------------------------------------------+
| Draw circle arc             | Disabled by default (see above)                           |
+-----------------------------+-----------------------------------------------------------+
| Fill circle arc             |                                                           |
+-----------------------------+-----------------------------------------------------------+
| Draw ellipse arc            | Disabled by default (see above)                           |
+-----------------------------+-----------------------------------------------------------+
| Fill ellipse arc            |                                                           |
+-----------------------------+-----------------------------------------------------------+
| Draw ellipse arc            | Disabled by default (see above)                           |
+-----------------------------+-----------------------------------------------------------+
| Fill ellipse arc            |                                                           |
+-----------------------------+-----------------------------------------------------------+
| Draw circle                 | Disabled by default (see above)                           |
+-----------------------------+-----------------------------------------------------------+
| Fill circle                 |                                                           |
+-----------------------------+-----------------------------------------------------------+
| Draw image                  | RGB565, A8, A4 + ARGB8888, ARGB1555, ARGB4444 (see above) |
+-----------------------------+-----------------------------------------------------------+
| Draw thick faded point      | Only with fade <= 1                                       |
+-----------------------------+-----------------------------------------------------------+
| Draw thick faded line       | Only with fade <= 1                                       |
+-----------------------------+-----------------------------------------------------------+
| Draw thick faded circle     | Only with fade <= 1                                       |
+-----------------------------+-----------------------------------------------------------+
| Draw thick faded circle arc | Only with fade <= 1                                       |
+-----------------------------+-----------------------------------------------------------+
| Draw thick faded ellipse    | Only with fade <= 1                                       |
+-----------------------------+-----------------------------------------------------------+
| Draw thick line             |                                                           |
+-----------------------------+-----------------------------------------------------------+
| Draw thick circle           |                                                           |
+-----------------------------+-----------------------------------------------------------+
| Draw thick circle arc       |                                                           |
+-----------------------------+-----------------------------------------------------------+
| Draw thick ellipse          |                                                           |
+-----------------------------+-----------------------------------------------------------+
| Draw flipped image          | See draw image                                            |
+-----------------------------+-----------------------------------------------------------+
| Draw rotated image          | See draw image                                            |
+-----------------------------+-----------------------------------------------------------+
| Draw scaled image           | See draw image                                            |
+-----------------------------+-----------------------------------------------------------+
```

2023-02-07 13:46 UTC, microej-sh commented on VEEPortingGuide/uiReleaseNotes.rst
> +The following table describes the compatibility versions between the C module and the MicroEJ UI Packs:
```suggestion
The following table describes the version compatibility between the C module and the MicroEJ UI Packs:
```

2023-02-07 13:46 UTC, microej-sh commented on VEEPortingGuide/uiReleaseNotes.rst
> +The following table describes the compatibility versions between the C module and the VG-Lite libraries (officially supported):
```suggestion
The following table describes the version compatibility between the C module and the VG-Lite libraries (officially supported):
```

2023-02-16 09:56 UTC, microej-sh approved these changes

2023-02-16 12:28 UTC, merged