Feature/microej sdk 6
MicroEJ/docs pull request #492
Opened 2022-12-13 23:52 UTC by jerome-leroux

Draft PR for review.

2022-12-23 09:08 UTC, jerome-leroux commented on SDK6UserGuide/install.rst
> +First check the System Requirements before proceding.
```suggestion
First, check the System Requirements before proceeding.
```

2022-12-23 14:58 UTC, thomasdelhomenie commented on SDK6UserGuide/install.rst
> +First check the System Requirements before proceding.
Done

2022-12-23 14:59 UTC, thomasdelhomenie commented on SDK6UserGuide/install.rst
> +For starting you can declare them globally to make them available in all your projects:
Done.

2022-12-23 14:59 UTC, thomasdelhomenie commented on SDK6UserGuide/install.rst
> +for example by executing the command ``gradle build`` at the root of the project.
Done.

2022-12-23 14:59 UTC, thomasdelhomenie commented on SDK6UserGuide/install.rst
> +Using an IDE is highly recommended to develop MicroEJ projects, as it makes the development more confortable and increases the productivity.
Done.

2022-12-23 14:59 UTC, thomasdelhomenie commented on SDK6UserGuide/publishProject.rst
> +Please refer to `the official documentation <https://docs.gradle.org/current/userguide/publishing_maven.html#publishing_maven:repositories>`__ for more information on publication repositories.
Done.

2022-12-23 14:59 UTC, thomasdelhomenie commented on SDK6UserGuide/selectVeePort.rst
> +      Please refer to `the Gradle documentation <https://docs.gradle.org/current/dsl/org.gradle.api.artifacts.dsl.DependencyHandler.html>`__
Done.

2022-12-23 14:59 UTC, thomasdelhomenie commented on SDK6UserGuide/testProject.rst
> +Please refer to JUnit documentation to get details on usage of other annotations.
Done.

2022-12-23 15:00 UTC, thomasdelhomenie commented on ApplicationDeveloperGuide/debug.rst
> +   If you use the SDK 6, please refer to the page :ref:`sdk_6_debug_on_simulator`.
This is not directly related to the SDK 6 doc, so I think it is better to do it in a dedicated PR to reduce rebase problems.

2022-12-23 15:00 UTC, thomasdelhomenie commented on ApplicationDeveloperGuide/moduleNatures.rst
> +   If you use the SDK 6, please refer to the page :ref:`sdk6_module_natures`.
This is not directly related to the SDK 6 doc, so I think it is better to do it in a dedicated PR to reduce rebase problems.

2022-12-23 15:00 UTC, thomasdelhomenie commented on ApplicationDeveloperGuide/platformSelection.rst
> +   If you use the SDK 6, please refer to the page :ref:`sdk_6_select_veeport`.
This is not directly related to the SDK 6 doc, so I think it is better to do it in a dedicated PR to reduce rebase problems.

2022-12-23 15:00 UTC, thomasdelhomenie commented on ApplicationDeveloperGuide/sandboxedAppFirstApplication.rst
> +   If you use the SDK 6, please refer to the page :ref:`sdk_6_create_project`.
This is not directly related to the SDK 6 doc, so I think it is better to do it in a dedicated PR to reduce rebase problems.

2022-12-23 15:00 UTC, thomasdelhomenie commented on ApplicationDeveloperGuide/sandboxedAppSim.rst
> +   If you use the SDK 6, please refer to the page :ref:`sdk_6_run_on_simulator`.
This is not directly related to the SDK 6 doc, so I think it is better to do it in a dedicated PR to reduce rebase problems.

2023-01-04 12:08 UTC, frivieremicroej requested changes
This is my first pass.
So far, I wanted to take the hand with SDK 6 current behavior and Gradle, by developing 3 chained modules locally (`lib3<-lib2<-lib1`) using the command line only.

Comments of this review cover both documentation and behaviour (issues or misunderstandings). These latter comments will likely be refined and extracted into dedicated tickets.

So far I did not review the following sections:
- Debug 
- IDE 
- Tests

2023-01-04 12:08 UTC, frivieremicroej commented on SDK6UserGuide/addDependency.rst
> +      implementation("ej.library.runtime:basictool:1.7.0")
We must use "api" instead of "implementation' everywhere in the doc to fetch transitive dependencies by default (We must keep similar MMM behaviour).
I tried a chained build `lib3 <- lib2 <- lib1` , but lib3 cannot be built 

I believe this is for that reason, but I could not test (see comment error when declaring 'api' configuration)
However, there is a strange behaviour: the `runtimeClasspath` contains `lib1`, which should not be the case since the lib1 has been declared as implementation of lib2, thus it should be hidden to lib3.

```
C:\Users\user\Documents\work\sdk6\lib3>gradle app:dependencies    

> Task :app:dependencies

------------------------------------------------------------
Project ':app'
------------------------------------------------------------

addonProcessorClasspath - Addon Processors
+--- ej.api:edc:1.3.5
\--- org.example.lib2:app:1.0.0-RC+ -> 1.0.0-RC202301041235
     +--- ej.api:edc:1.3.5
     \--- org.example.lib1:app:1.0.0-RC+ -> 1.0.0-RC202301041211
          \--- ej.api:edc:1.3.5

annotationProcessor - Annotation processors and their dependencies for source set 'main'.
No dependencies

antLauncher - The Ant Launcher jar on its dependencies.
+--- org.apache.ant:ant:1.9.15
|    \--- org.apache.ant:ant-launcher:1.9.15
\--- org.apache.ant:ant-launcher:1.9.15

apiElements - API elements for main. (n)
No dependencies

archives - Configuration for archive artifacts. (n)
No dependencies

compileClasspath - Compile classpath for source set 'main'.
+--- ej.api:edc:1.3.5
\--- org.example.lib2:app:1.0.0-RC+ -> 1.0.0-RC202301041235

compileOnly - Compile only dependencies for source set 'main'. (n)
No dependencies

default - Configuration for default artifacts. (n)
No dependencies

implementation - Implementation only dependencies for source set 'main'. (n)
+--- ej.api:edc:1.3.5 (n)
\--- org.example.lib2:app:1.0.0-RC+ (n)

javadocElements - javadoc elements for main. (n)
No dependencies

jdtCompiler - Configuration for the JDT Compiler.
+--- org.eclipse.jdt:org.eclipse.jdt.core:3.22.0
\--- org.eclipse.jdt:org.eclipse.jdt.compiler.apt:1.3.1000
     \--- org.eclipse.jdt:org.eclipse.jdt.core:[3.5.0,4.0.0) -> 3.22.0

mainSourceElements - List of source directories contained in the Main SourceSet. (n)
No dependencies

microejVeePort
No dependencies

runtimeClasspath - Runtime classpath of source set 'main'.
+--- ej.api:edc:1.3.5
\--- org.example.lib2:app:1.0.0-RC+ -> 1.0.0-RC202301041235
     +--- ej.api:edc:1.3.5
     \--- org.example.lib1:app:1.0.0-RC+ -> 1.0.0-RC202301041211
          \--- ej.api:edc:1.3.5

runtimeElements - Elements of runtime for main. (n)
No dependencies

runtimeOnly - Runtime only dependencies for source set 'main'. (n)
No dependencies

sourcesElements - sources elements for main. (n)
No dependencies

testAnnotationProcessor - Annotation processors and their dependencies for source set 'test'.
No dependencies

testCompileClasspath - Compile classpath for source set 'test'.
+--- ej.api:edc:1.3.5
\--- org.example.lib2:app:1.0.0-RC+ -> 1.0.0-RC202301041235

testCompileOnly - Compile only dependencies for source set 'test'. (n)
No dependencies

testImplementation - Implementation only dependencies for source set 'test'. (n)
No dependencies

testResultsElementsForTest - Directory containing binary results of running tests for the test Test Suite's test target. (n)
No dependencies

testRuntimeClasspath - Runtime classpath of source set 'test'.
+--- ej.api:edc:1.3.5
\--- org.example.lib2:app:1.0.0-RC+ -> 1.0.0-RC202301041235
     +--- ej.api:edc:1.3.5
     \--- org.example.lib1:app:1.0.0-RC+ -> 1.0.0-RC202301041211
          \--- ej.api:edc:1.3.5

testRuntimeOnly - Runtime only dependencies for source set 'test'. (n)
No dependencies

(*) - dependencies omitted (listed previously)

(n) - Not resolved (configuration is not meant to be resolved)

A web-based, searchable dependency report is available by adding the --scan option.

BUILD SUCCESSFUL in 4s
1 actionable task: 1 executed
C:\Users\user\Documents\work\sdk6\lib3>gradle toto:dependencies 

FAILURE: Build failed with an exception.

* What went wrong:
Cannot locate tasks that match 'toto:dependencies' as project 'toto' not found in root project 'lib3'.

* Try:
> Run gradle projects to get a list of available projects.
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 3s

C:\Users\user\Documents\work\sdk6\lib3>gradle app:dependencies  

> Task :app:dependencies

------------------------------------------------------------
Project ':app'
------------------------------------------------------------

addonProcessorClasspath - Addon Processors
+--- ej.api:edc:1.3.5
\--- org.example.lib2:app:1.0.0-RC+ -> 1.0.0-RC202301041235
     +--- ej.api:edc:1.3.5
     \--- org.example.lib1:app:1.0.0-RC+ -> 1.0.0-RC202301041211
          \--- ej.api:edc:1.3.5

annotationProcessor - Annotation processors and their dependencies for source set 'main'.
No dependencies

antLauncher - The Ant Launcher jar on its dependencies.
+--- org.apache.ant:ant:1.9.15
|    \--- org.apache.ant:ant-launcher:1.9.15
\--- org.apache.ant:ant-launcher:1.9.15

apiElements - API elements for main. (n)
No dependencies

archives - Configuration for archive artifacts. (n)
No dependencies

compileClasspath - Compile classpath for source set 'main'.
+--- ej.api:edc:1.3.5
\--- org.example.lib2:app:1.0.0-RC+ -> 1.0.0-RC202301041235

compileOnly - Compile only dependencies for source set 'main'. (n)
No dependencies

default - Configuration for default artifacts. (n)
No dependencies

implementation - Implementation only dependencies for source set 'main'. (n)
+--- ej.api:edc:1.3.5 (n)
\--- org.example.lib2:app:1.0.0-RC+ (n)

javadocElements - javadoc elements for main. (n)
No dependencies

jdtCompiler - Configuration for the JDT Compiler.
+--- org.eclipse.jdt:org.eclipse.jdt.core:3.22.0
\--- org.eclipse.jdt:org.eclipse.jdt.compiler.apt:1.3.1000
     \--- org.eclipse.jdt:org.eclipse.jdt.core:[3.5.0,4.0.0) -> 3.22.0

mainSourceElements - List of source directories contained in the Main SourceSet. (n)
No dependencies

microejVeePort
No dependencies

runtimeClasspath - Runtime classpath of source set 'main'.
+--- ej.api:edc:1.3.5
\--- org.example.lib2:app:1.0.0-RC+ -> 1.0.0-RC202301041235
     +--- ej.api:edc:1.3.5
     \--- org.example.lib1:app:1.0.0-RC+ -> 1.0.0-RC202301041211
          \--- ej.api:edc:1.3.5

runtimeElements - Elements of runtime for main. (n)
No dependencies

runtimeOnly - Runtime only dependencies for source set 'main'. (n)
No dependencies

sourcesElements - sources elements for main. (n)
No dependencies

testAnnotationProcessor - Annotation processors and their dependencies for source set 'test'.
No dependencies

testCompileClasspath - Compile classpath for source set 'test'.
+--- ej.api:edc:1.3.5
\--- org.example.lib2:app:1.0.0-RC+ -> 1.0.0-RC202301041235

testCompileOnly - Compile only dependencies for source set 'test'. (n)
No dependencies

testImplementation - Implementation only dependencies for source set 'test'. (n)
No dependencies

testResultsElementsForTest - Directory containing binary results of running tests for the test Test Suite's test target. (n)
No dependencies

testRuntimeClasspath - Runtime classpath of source set 'test'.
+--- ej.api:edc:1.3.5
\--- org.example.lib2:app:1.0.0-RC+ -> 1.0.0-RC202301041235
     +--- ej.api:edc:1.3.5
     \--- org.example.lib1:app:1.0.0-RC+ -> 1.0.0-RC202301041211
          \--- ej.api:edc:1.3.5

testRuntimeOnly - Runtime only dependencies for source set 'test'. (n)
No dependencies

(*) - dependencies omitted (listed previously)

(n) - Not resolved (configuration is not meant to be resolved)

A web-based, searchable dependency report is available by adding the --scan option.

BUILD SUCCESSFUL in 5s
```

2023-01-04 12:55 UTC, thomasdelhomenie commented on SDK6UserGuide/install.rst
> +   - 2GB Disk (minimum)
IntelliJ recommends 5GB minimum (including caches). Eclipse recommends less. For Gradle it is more difficult to tell since it depends highly on what you do with it, but I would add 5 more GB, mainly for the cache. So it would be 10GB. And keep 4GB RAM. WDYT?
We should actually update the system requirements for SDK 5 as well, the Ivy cache can grow quickly as well.

2023-01-05 09:17 UTC, thomasdelhomenie commented on SDK6UserGuide/install.rst
> +- in the search field, type ``MicroEJ``:
I used the same sentence used in the [SDK 5 User Guide](https://docs.microej.com/en/latest/SDKUserGuide/index.html): 

> MICROEJ SDK is an integrated environment to create software applications for MicroEJ-ready devices.

2023-01-05 09:17 UTC, thomasdelhomenie commented on SDK6UserGuide/install.rst
> +   ------------------------------------------------------------
Done.

2023-01-05 09:17 UTC, thomasdelhomenie commented on SDK6UserGuide/install.rst
> +Configure repositories
Done.

2023-01-05 09:18 UTC, thomasdelhomenie commented on SDK6UserGuide/install.rst
> +   The support of Eclipse will come soon.
Done.

2023-01-05 09:59 UTC, thomasdelhomenie commented on SDK6UserGuide/install.rst
> +- click on the ``Restart IDE`` button.
I don't have a warning to accept when installing the plugin. Can you send a screenshot please?

2023-01-05 10:01 UTC, thomasdelhomenie commented on SDK6UserGuide/install.rst
> +Install the snapshot version
I wanted to keep it short for this first version, but I agree we should add a dedicated page in the future for early adopters.

2023-01-05 10:02 UTC, thomasdelhomenie commented on SDK6UserGuide/createProject.rst
> +- select the ``application`` project type.
Yes I think that may change depending on the Gradle version, and that's also why I used "select".

2023-01-05 10:04 UTC, thomasdelhomenie commented on SDK6UserGuide/createProject.rst
> +- select your prefered build script DSL language.
Do we really not support Groovy? This is a Gradle feature, so that's sound weird to not support it.

2023-01-05 10:09 UTC, thomasdelhomenie commented on SDK6UserGuide/createProject.rst
> +- decide if you want to use new APIs and behavior.
What do you mean by "fix the behavior"?
I clarified a bit and added your sentence.

2023-01-05 10:09 UTC, thomasdelhomenie commented on SDK6UserGuide/createProject.rst
> +- execute the command ``gradle init``.
Done.

2023-01-05 10:09 UTC, thomasdelhomenie commented on SDK6UserGuide/createProject.rst
> +- choose the name of the project (defaults to the name of the parent folder).
Done.

2023-01-05 10:12 UTC, thomasdelhomenie commented on SDK6UserGuide/troubleshooting.rst
> +  Alternatively, you can set the ``JAVA_HOME`` environment variable to point to the installation directory of the JDK 11.
TODO Add a dedicated section about JDK installation (we currently redirect to the SDK 5 "Get JDK" section in the installation process) and refer to it.

2023-01-05 10:17 UTC, thomasdelhomenie commented on SDK6UserGuide/buildProject.rst
> +- define the VEE Port in the build file of the project.
https://youtrack.cross/issue/M0090IDE-4089/Gradle-Typo-in-error-message-when-no-VEE-Port-defined

2023-01-05 10:23 UTC, thomasdelhomenie commented on SDK6UserGuide/buildProject.rst
> +  The VEE Port is required to execute the tests and to allow to run the Application with the Simulator.
Yes, that was because of a "bug" we had: https://youtrack.cross/issue/M0090IDE-4067/Gradle-Do-not-load-the-VEE-Port-when-there-is-no-test-to-execute. We can revert it now.

TODO

2023-01-05 10:40 UTC, thomasdelhomenie commented on SDK6UserGuide/selectVeePort.rst
> +     veePortFile = "/path/to/my/veePort/file.zip"
I am not sure, we never do that in the documentation. Moreover it required one more step (delete a line) to copy/paste. Maybe we can change the default path, or use something like `veePortFile = "<path-to-the-platform-zip-file>"` and add a line explaining that `<path-to-the-platform-zip-file>`  must be replaced by the absolute path of the platform zip file. WDYT?

2023-01-05 11:01 UTC, thomasdelhomenie commented on SDK6UserGuide/runOnSimulator.rst
> +    $ gradle runOnSimulator --no-daemon
This has been removed since the release of the version 0.3.1, the doc is already updated. It was required before because running the simulator multiple times was done in the same process before (in the daemon process).

2023-01-05 11:15 UTC, thomasdelhomenie commented on SDK6UserGuide/addDependency.rst
> +- **microejVeePort** - VEE Port used by the project for build and test.
VEE Port declared this way are not fetched transitively, so yes it is the same thing than in SDK 5.
The "Implementation" suffix is relevant if we have the "Api" suffix available IMO, not sure it is the case here.

2023-01-05 13:54 UTC, thomasdelhomenie commented on SDK6UserGuide/runOnSimulator.rst
> +   IntelliJ IDEA cannot be used as the debugger client for the moment, so it is recommend to use Eclipse instead.
Done.

2023-01-05 13:54 UTC, thomasdelhomenie commented on SDK6UserGuide/publishProject.rst
> +  $ gradle publish
I detailed the publication page and added the troubleshooting section.

2023-01-05 14:04 UTC, thomasdelhomenie commented on SDK6UserGuide/publishProject.rst
> +
Yes, that's the behavior of Gradle. I did not find an option to change it.

2023-01-05 14:05 UTC, thomasdelhomenie commented on SDK6UserGuide/manageVersion.rst
> +    version = "1.0.0-RC"
Added in the Publish page.

2023-01-05 14:33 UTC, thomasdelhomenie commented on SDK6UserGuide/createProject.rst
> +  - remove the ``application`` block.
Done.
That's not a copy/paste, but it's close.

2023-01-05 14:48 UTC, thomasdelhomenie commented on SDK6UserGuide/publishProject.rst
> +
This is actually not recommended, see https://docs.gradle.org/current/userguide/declaring_repositories.html#sec:case-for-maven-local
In this case you should use Composite Builds, see https://docs.gradle.org/current/userguide/composite_builds.html
Maybe we should add a note or a section on the recommended way to consume local projects, and maybe a section in the migration guide. WDYT?

2023-01-05 14:54 UTC, thomasdelhomenie commented on SDK6UserGuide/publishProject.rst
> +Refer to `the official documentation <https://docs.gradle.org/current/userguide/publishing_maven.html#publishing_maven:repositories>`__ for more information on publication repositories.
what do you mean? The ivy file has not been published when you launch a `gradle publish`?

2023-01-05 14:56 UTC, thomasdelhomenie commented on SDK6UserGuide/publishProject.rst
> +Refer to `the official documentation <https://docs.gradle.org/current/userguide/publishing_maven.html#publishing_maven:repositories>`__ for more information on publication repositories.
By default the name of a module is its folder name. You can customize it by setting the property `rootProject.name` in the settings.gradle.kts at the root of the module.

2023-01-05 14:58 UTC, thomasdelhomenie commented on SDK6UserGuide/resources/microej.init.gradle.kts
> +         /* MicroEJ Forge Central repository for Maven/Gradle modules */
Can you remind me why we declare this repository whereas we already have the Central repository?

2023-01-05 14:59 UTC, thomasdelhomenie commented on SDK6UserGuide/resources/microej.init.gradle.kts
> +         /* MicroEJ Forge Developer repository for Maven/Gradle modules */
We call it Developer repository in the documentation: https://docs.microej.com/en/feature-microej-sdk-6/SDKUserGuide/repository.html#developer-repository

2023-01-05 15:02 UTC, thomasdelhomenie commented on SDK6UserGuide/addDependency.rst
> +
You mean adding a section summarizing the official doc: https://docs.gradle.org/current/userguide/viewing_debugging_dependencies.html#sec:listing_dependencies ?

2023-01-05 15:06 UTC, thomasdelhomenie commented on SDK6UserGuide/addDependency.rst
> +- **api**  (from Gradle Java Library plugin) - Same as the **implementation** configuration, except that the dependency is also exposed to the consumers of your project.
The `api` configuration is provided by the `java-library` plugin, which is not applied by default. I created a ticket to apply it automatically: https://youtrack.cross/issue/M0090IDE-4090/Gradle-Apply-the-plugin-java-library

2023-01-05 15:18 UTC, thomasdelhomenie commented on SDK6UserGuide/publishProject.rst
> +- the main artifact, which is the JAR file for Application and Add-On Library natures.
This warning can be disabled in the plugin. If we consider it is acceptable to allow to fetch our modules by Gradle only (I think it is since we only support Gradle) we can do it.

2023-01-05 15:57 UTC, thomasdelhomenie commented on SDK6UserGuide/addDependency.rst
> +      implementation("ej.library.runtime:basictool:1.7.0")
> We must use "api" instead of "implementation' everywhere in the doc to fetch transitive dependencies by default (We must keep similar MMM behaviour).

The good practice is to use `implementation` by default and to use `api` only in some particular cases. One of the main benefits is to avoid to accidentally leak some APIs from transitive dependencies. It is well documented here: https://docs.gradle.org/current/userguide/java_library_plugin.html#sec:java_library_separation. I agree it was not the behavior with MMM but we should apply the best practices as much as we can IMO. We do a major in the SDK versioning, it is the right time. We can document that in the migration guide.

> However, there is a strange behaviour: the runtimeClasspath contains lib1, which should not be the case since the lib1 has been declared as implementation of lib2, thus it should be hidden to lib3.

Declaring a dependency with the implementation configuration removes it from the compile classpath only, not from the runtime classpath (the lib2 needs lib1 at runtime, so it must be there to work, even if it is fetched transitively). So I think it is the expected behavior. Actually the implementation configuration is not exactly similar to private configuration in MMM.

2023-01-09 15:52 UTC, thomasdelhomenie commented on SDK6UserGuide/install.rst
> +   - 2GB Disk (minimum)
-> 16Gb for the disk

2023-01-09 16:16 UTC, thomasdelhomenie commented on SDK6UserGuide/install.rst
> +- click on the ``Restart IDE`` button.
TODO: try with IJ 2021

2023-01-09 16:17 UTC, thomasdelhomenie commented on SDK6UserGuide/install.rst
> +Install the snapshot version
TODO

2023-01-09 16:20 UTC, thomasdelhomenie commented on SDK6UserGuide/install.rst
> +- in the search field, type ``MicroEJ``:
TODO

2023-01-09 16:24 UTC, thomasdelhomenie commented on SDK6UserGuide/createProject.rst
> +- select your prefered build script DSL language.
TODO

2023-01-09 16:27 UTC, frivieremicroej commented on SDK6UserGuide/createProject.rst
> +- select your prefered build script DSL language.
Yes , including the NOTE

2023-01-09 16:37 UTC, thomasdelhomenie commented on SDK6UserGuide/buildProject.rst
> +- define the VEE Port in the build file of the project.
Fixed in 0.3.2.

2023-01-09 16:40 UTC, frivieremicroej commented on SDK6UserGuide/buildProject.rst
> +    $ gradle build
OK strange, I remember to see a black banner. Let's close it.

2023-01-09 16:44 UTC, frivieremicroej commented on SDK6UserGuide/selectVeePort.rst
> +     veePortFile = "/path/to/my/veePort/file.zip"
From SDK

```
# - This file respects the Java properties file convention: the OS path
#	must use the UNIX path convention (path separator is '/'). The WINDOWS
#	paths must have been converted manually replacing '\' by '/' or by '\\'.

```

2023-01-09 16:45 UTC, thomasdelhomenie commented on SDK6UserGuide/selectVeePort.rst
> +     veePortFile = "/path/to/my/veePort/file.zip"
TODO Windows path only

2023-01-09 16:48 UTC, thomasdelhomenie commented on SDK6UserGuide/selectVeePort.rst
> +At least 1 of these 3 ways is required to build an Application with a VEE Port.
TODO Add a page with how-tos on Gradle, including this one.

2023-01-09 16:49 UTC, frivieremicroej commented on SDK6UserGuide/runOnSimulator.rst
> +    $ gradle runOnSimulator --no-daemon
perfect

2023-01-09 16:58 UTC, frivieremicroej commented on SDK6UserGuide/addDependency.rst
> +- **microejVeePort** - VEE Port used by the project for build and test.
Let's see others opinions.
OK to keep microej prefix since it used out out the microej block

2023-01-09 17:00 UTC, thomasdelhomenie commented on SDK6UserGuide/addDependency.rst
> +- **api**  (from Gradle Java Library plugin) - Same as the **implementation** configuration, except that the dependency is also exposed to the consumers of your project.
Will be integrated in 0.4.0.

2023-01-09 17:12 UTC, frivieremicroej commented on SDK6UserGuide/addDependency.rst
> +      implementation("ej.library.runtime:basictool:1.7.0")
OK `implementation` as the default. 
Widgets library defines APIs that depend on the MWT library. If you forget to set MWT as `api`, you will not be able to execute unit tests, thus the library could not be built.

2023-01-09 17:20 UTC, frivieremicroej commented on SDK6UserGuide/addDependency.rst
> +      implementation("ej.library.runtime:basictool:1.7.0")
OK for  the `runtimeClasspath` but not for  the `addonProcessorClasspath`.

2023-01-10 10:43 UTC, thomasdelhomenie commented on SDK6UserGuide/install.rst
> +   - 2GB Disk (minimum)
DONE.

2023-01-10 10:44 UTC, thomasdelhomenie commented on SDK6UserGuide/createProject.rst
> +- select your prefered build script DSL language.
DONE.

2023-01-10 10:49 UTC, thomasdelhomenie commented on SDK6UserGuide/install.rst
> +- in the search field, type ``MicroEJ``:
https://youtrack.cross/issue/M0090IDE-4097/Gradle-Update-the-IntelliJ-IDEA-plugin-description

2023-01-10 14:49 UTC, thomasdelhomenie commented on SDK6UserGuide/troubleshooting.rst
> +  Alternatively, you can set the ``JAVA_HOME`` environment variable to point to the installation directory of the JDK 11.
Done. I updated the installation page (https://docs.microej.com/en/feature-microej-sdk-6/SDK6UserGuide/install.html#check-your-jdk-version) and added a how-to for this case : https://docs.microej.com/en/feature-microej-sdk-6/SDK6UserGuide/howtos/gradleJavaHome.html

2023-01-10 15:43 UTC, thomasdelhomenie commented on SDK6UserGuide/buildProject.rst
> +  The VEE Port is required to execute the tests and to allow to run the Application with the Simulator.
Done.

2023-01-10 16:35 UTC, thomasdelhomenie commented on SDK6UserGuide/selectVeePort.rst
> +At least 1 of these 3 ways is required to build an Application with a VEE Port.
Done : https://docs.microej.com/en/feature-microej-sdk-6/SDK6UserGuide/howtos/gradleSystemProperty.html

2023-01-18 23:12 UTC, jerome-leroux commented on SDK6UserGuide/manageResolutionConflicts.rst
> +       |- moduleC:3.0.0
We should add the root module, which is the current module.

Could we use graphviz to show this example?

2023-01-18 23:12 UTC, jerome-leroux commented on SDK6UserGuide/manageResolutionConflicts.rst
> +of the ``microej`` configuration block to ``false`` in the project build file:
```suggestion
If you want to come back to the Gradle default behavior,
these 2 rules can be disabled in the project build file by setting the ``microejConflictResolutionRulesEnabled`` 
property of the ``microej`` configuration block to ``false``:
```

2023-01-18 23:12 UTC, jerome-leroux commented on SDK6UserGuide/migrateMMMProject.rst
> +Migrate a MMM Project
```suggestion
Migrate an MMM Project
```

2023-01-18 23:12 UTC, jerome-leroux commented on SDK6UserGuide/migrateMMMProject.rst
> +The structure of a SDK 6 Gradle project is similar to a MMM project.
```suggestion
The structure of an SDK 6 Gradle project is similar to an MMM project.
```

2023-01-18 23:12 UTC, jerome-leroux commented on SDK6UserGuide/migrateMMMProject.rst
> +The configuration of a MMM build is only done with ``ea:property`` tags in the ``module.ivy`` file,
```suggestion
The configuration of an MMM build is only done with ``ea:property`` tags in the ``module.ivy`` file, 
```

2023-01-18 23:12 UTC, jerome-leroux commented on SDK6UserGuide/migrateMMMProject.rst
> +  This change is required since Gradle uses the ``build`` to store the generated files and artifacts (equivalent of the MMM ``target~`` folder).
```suggestion
  This change is required since Gradle uses the ``build`` folder to store the generated files and artifacts (equivalent of the MMM ``target~`` folder).
```

2023-01-23 15:54 UTC, tdelhomenie-microej commented on SDK6UserGuide/install.rst
> +- in the search field, type ``MicroEJ``:
Done

2023-01-23 16:10 UTC, tdelhomenie-microej commented on SDK6UserGuide/publishProject.rst
> +  $ gradle publish
Ok, but add a bullet point to detail the name (explain that the default value is the folder name).

2023-01-23 16:32 UTC, tdelhomenie-microej commented on SDK6UserGuide/resources/microej.init.gradle.kts
> +      repositories {
TODO Add a local repository at `~/.microej/repository`.

2023-01-23 16:34 UTC, tdelhomenie-microej commented on SDK6UserGuide/publishProject.rst
> +
We will add a local repository by default for publication.

2023-01-23 16:35 UTC, tdelhomenie-microej commented on SDK6UserGuide/publishProject.rst
> +Refer to `the official documentation <https://docs.gradle.org/current/userguide/publishing_maven.html#publishing_maven:repositories>`__ for more information on publication repositories.
TODO test

2023-01-23 16:36 UTC, tdelhomenie-microej commented on SDK6UserGuide/publishProject.rst
> +Refer to `the official documentation <https://docs.gradle.org/current/userguide/publishing_maven.html#publishing_maven:repositories>`__ for more information on publication repositories.
OK, will be detailed in the documentation.

2023-01-23 16:39 UTC, tdelhomenie-microej commented on SDK6UserGuide/resources/microej.init.gradle.kts
> +         /* MicroEJ Forge Central repository for Maven/Gradle modules */
TODO check if the central repo is correctly automatically synchronized in forge. If so, remove the Central repository and keep only Forge ones.

2023-01-23 16:41 UTC, tdelhomenie-microej commented on SDK6UserGuide/resources/microej.init.gradle.kts
> +         /* MicroEJ Forge SDK 6 repository for Maven/Gradle modules */
TODO

2023-01-23 16:41 UTC, tdelhomenie-microej commented on SDK6UserGuide/resources/microej.init.gradle.kts
> +         /* MicroEJ Forge Central repository for Ivy modules */
TODO

2023-01-23 16:42 UTC, tdelhomenie-microej commented on SDK6UserGuide/resources/microej.init.gradle.kts
> +         /* MicroEJ Forge Developer repository for Ivy modules */
TODO

2023-01-23 16:42 UTC, tdelhomenie-microej commented on SDK6UserGuide/resources/microej.init.gradle.kts
> +         /* MicroEJ Central repository for Ivy modules */
TODO

2023-01-23 16:42 UTC, tdelhomenie-microej commented on SDK6UserGuide/resources/microej.init.gradle.kts
> +  	 /* MicroEJ Forge SDK 6 repository for Ivy modules */
TODO

2023-01-23 16:42 UTC, tdelhomenie-microej commented on SDK6UserGuide/resources/microej.init.gradle.kts
> +    * Plugins repositories
TODO

2023-01-23 16:44 UTC, tdelhomenie-microej commented on SDK6UserGuide/addDependency.rst
> +
Leave as is.

2023-01-23 16:48 UTC, frivieremicroej commented on SDK6UserGuide/addDependency.rst
> +- **api**  (from Gradle Java Library plugin) - Same as the **implementation** configuration, except that the dependency is also exposed to the consumers of your project.
Also I have to test that it is not possible de declare an api that uses a classes declared in implementation dependency

2023-01-23 16:52 UTC, tdelhomenie-microej commented on SDK6UserGuide/publishProject.rst
> +- the main artifact, which is the JAR file for Application and Add-On Library natures.
TODO disable the warning.

2023-01-24 07:03 UTC, tdelhomenie-microej commented on SDK6UserGuide/resources/microej.init.gradle.kts
> +         /* MicroEJ Forge Central repository for Maven/Gradle modules */
Done

2023-01-24 07:03 UTC, tdelhomenie-microej commented on SDK6UserGuide/resources/microej.init.gradle.kts
> +         /* MicroEJ Central repository for Maven/Gradle modules */
Done

2023-01-24 07:03 UTC, tdelhomenie-microej commented on SDK6UserGuide/resources/microej.init.gradle.kts
> +         /* MicroEJ Forge Developer repository for Maven/Gradle modules */
Done

2023-01-24 07:03 UTC, tdelhomenie-microej commented on SDK6UserGuide/resources/microej.init.gradle.kts
> +         /* MicroEJ Forge SDK 6 repository for Maven/Gradle modules */
Done

2023-01-24 07:03 UTC, tdelhomenie-microej commented on SDK6UserGuide/resources/microej.init.gradle.kts
> +         /* MicroEJ Forge Central repository for Ivy modules */
Done

2023-01-24 07:03 UTC, tdelhomenie-microej commented on SDK6UserGuide/resources/microej.init.gradle.kts
> +         /* MicroEJ Forge Developer repository for Ivy modules */
Done

2023-01-24 07:03 UTC, tdelhomenie-microej commented on SDK6UserGuide/resources/microej.init.gradle.kts
> +         /* MicroEJ Central repository for Ivy modules */
Done

2023-01-24 07:04 UTC, tdelhomenie-microej commented on SDK6UserGuide/resources/microej.init.gradle.kts
> +  	 /* MicroEJ Forge SDK 6 repository for Ivy modules */
Done

2023-01-24 07:04 UTC, tdelhomenie-microej commented on SDK6UserGuide/resources/microej.init.gradle.kts
> +    * Plugins repositories
Done

2023-01-24 07:07 UTC, tdelhomenie-microej commented on SDK6UserGuide/publishProject.rst
> +- the main artifact, which is the JAR file for Application and Add-On Library natures.
https://youtrack.cross/issue/M0090IDE-4107/Gradle-Disable-the-warning-on-non-compatible-version-for-Maven-client

2023-01-24 17:22 UTC, tdelhomenie-microej commented on SDK6UserGuide/install.rst
> +If it is not a JDK 11, the SDK will use and fail.
Fixed.

2023-01-24 17:22 UTC, tdelhomenie-microej commented on SDK6UserGuide/install.rst
> +If the ``JAVA_HOME`` is not set, make sure a JDK 11 execuatble is available in the ``PATH`` environment variable.
Done.

2023-01-24 17:22 UTC, tdelhomenie-microej commented on SDK6UserGuide/createProject.rst
> +- select your prefered language for the field ``Gradle DSL``.
Already done.

2023-01-24 17:22 UTC, tdelhomenie-microej commented on SDK6UserGuide/manageVersion.rst
> +Instead of using the ``-SNAPSHOT`` prefix (i.e. ``1.0.0-SNAPSHOT``),
Done.

2023-01-24 17:22 UTC, tdelhomenie-microej commented on SDK6UserGuide/manageVersion.rst
> +it used the ``-RCxxx`` prefix, where ``xxx`` is the timestamp (i.e. ``1.0.0-RC202212021535``).
Done.

2023-01-24 17:22 UTC, tdelhomenie-microej commented on SDK6UserGuide/addDependency.rst
> +- release version: to depend on a released version of a module, the exact fixed version must be used, i.e. ``1.0.0``.
Done.

2023-01-24 17:22 UTC, tdelhomenie-microej commented on SDK6UserGuide/addDependency.rst
> +- snapshot version: to depend on a snapshot version (``-RC``) of a module, the version must be declared explicitly with the ``-RC+`` suffix, i.e. ``1.0.0-RC+``.
Done.

2023-01-24 17:22 UTC, tdelhomenie-microej commented on SDK6UserGuide/addDependency.rst
> +   or a snapshot version (i.e. ``1.0.0-RCxxx``) otherwise.
Done.

2023-01-24 17:23 UTC, tdelhomenie-microej commented on SDK6UserGuide/selectVeePort.rst
> +- If the module project defined several VEE Ports, the build fails. For example the following cases are not allowed:
Done.

2023-01-24 17:23 UTC, tdelhomenie-microej commented on SDK6UserGuide/manageVersion.rst
> +  You are free to use any version number notation you want but you have to be aware that SDK 5 projects
Done.

2023-01-24 17:23 UTC, tdelhomenie-microej commented on SDK6UserGuide/manageResolutionConflicts.rst
> +The MicroEJ Gradle plugin adds specific rules for compilation, building, resolving dependencies, versioning and publishing.
Done.

2023-01-24 17:23 UTC, tdelhomenie-microej commented on SDK6UserGuide/manageResolutionConflicts.rst
> +By default Gradle selects the highest version amongst all the versions requested for a dependency.
Done.

2023-01-24 17:23 UTC, tdelhomenie-microej commented on SDK6UserGuide/manageResolutionConflicts.rst
> +- the resolution fails when a dependency is requested with 2 incompatible versions in the graph, according to the `Semantic Versioning specification <https://semver.org/>`__.
Done.

2023-01-24 17:23 UTC, tdelhomenie-microej commented on SDK6UserGuide/manageResolutionConflicts.rst
> +- the resolution fails when a direct dependency is resolved with a higher minor version than the one declared.
Done.

2023-01-24 17:23 UTC, tdelhomenie-microej commented on SDK6UserGuide/manageResolutionConflicts.rst
> +  So it means that if 2 versions do not have the same major version, the build fails.
Done.

2023-01-24 17:23 UTC, tdelhomenie-microej commented on SDK6UserGuide/manageResolutionConflicts.rst
> +of the ``microej`` configuration block to ``false`` in the project build file:
Done.

2023-01-24 17:24 UTC, tdelhomenie-microej commented on SDK6UserGuide/migrateMMMProject.rst
> +Migrate a MMM Project
Done.

2023-01-24 17:24 UTC, tdelhomenie-microej commented on SDK6UserGuide/migrateMMMProject.rst
> +The structure of a SDK 6 Gradle project is similar to a MMM project.
Done.

2023-01-24 17:24 UTC, tdelhomenie-microej commented on SDK6UserGuide/migrateMMMProject.rst
> +The configuration of a MMM build is only done with ``ea:property`` tags in the ``module.ivy`` file,
Done.

2023-01-24 17:25 UTC, tdelhomenie-microej commented on SDK6UserGuide/createProject.rst
> +    }
You should not see the JDK classes. Did you install the MicroEJ plugin for Intellij IDEA?

2023-01-24 17:29 UTC, tdelhomenie-microej commented on SDK6UserGuide/selectVeePort.rst
> +     veePortDir = "C:\\path\\to\\my\\veePort\\directory"
I am not sure. This source folder is very confusing.

2023-01-24 17:30 UTC, tdelhomenie-microej commented on SDK6UserGuide/manageResolutionConflicts.rst
> +One of its job is to resolve the conflicts in the dependencies graph, to determine which version should be added to the graph.
"Graphe des dépendences". Sounds good, no?

2023-01-26 09:31 UTC, tdelhomenie-microej commented on SDK6UserGuide/publishProject.rst
> +    }
A local repository has been added in the default configuration.

2023-01-26 09:32 UTC, tdelhomenie-microej commented on SDK6UserGuide/resources/microej.init.gradle.kts
> +      repositories {
Done.

2023-01-30 09:23 UTC, tdelhomenie-microej commented on SDK6UserGuide/addDependency.rst
> +- **api**  (from Gradle Java Library plugin) - Same as the **implementation** configuration, except that the dependency is also exposed to the consumers of your project.
The version 0.4.0 has been released. The Java Library plugin is now available by default.

2023-01-30 09:24 UTC, tdelhomenie-microej commented on SDK6UserGuide/publishProject.rst
> +- the main artifact, which is the JAR file for Application and Add-On Library natures.
Done. Available in the version 0.4.0.

2023-01-30 09:56 UTC, tdelhomenie-microej commented on SDK6UserGuide/install.rst
> +- `Eclipse IDE for Java Developers <https://www.eclipse.org/downloads/packages/release/2022-09/r/eclipse-ide-java-developers>`__ - Minimum supported version is ``2022-03``.
The link already points to the package, not the installer. But I am not sure it is a good thing since it targets a specific version, which is quickly outdated. We should probably point to https://www.eclipse.org/downloads/packages/ and add note to recommend using the package and not the installer. WDYT?

2023-01-30 10:18 UTC, tdelhomenie-microej commented on SDK6UserGuide/install.rst
> +- in IntelliJ IDEA, go to ``File > Settings...``.
Done.

2023-01-30 21:30 UTC, tdelhomenie-microej commented on SDK6UserGuide/publishProject.rst
> +
Done.

2023-01-30 21:50 UTC, jerome-leroux commented on SDK6UserGuide/manageResolutionConflicts.rst
> +property of the ``microej`` configuration block to ``false`` in the project build file:
```suggestion
property of the ``microej`` configuration block to ``false``:
```

2023-01-30 21:50 UTC, jerome-leroux commented on SDK6UserGuide/createProject.rst
> +- select your prefered language for the field ``Gradle DSL``.
I would repeat it here: "select your prefered language for the field ``Gradle DSL`` (MicroEJ uses Kotlin by default)."
?

2023-01-30 21:55 UTC, tdelhomenie-microej commented on SDK6UserGuide/install.rst
> +- click on the ``Restart IDE`` button.
Cannot reproduce with IJ 2021.

2023-01-31 07:25 UTC, tdelhomenie-microej commented on SDK6UserGuide/manageResolutionConflicts.rst
> +       |- moduleC:3.0.0
![image](https://user-images.githubusercontent.com/69317038/215693720-26b7835b-6428-424f-834d-a7ef7035dbe0.png)
WDYT?

2023-01-31 08:17 UTC, tdelhomenie-microej commented on SDK6UserGuide/manageResolutionConflicts.rst
> +property of the ``microej`` configuration block to ``false`` in the project build file:
Done.

2023-01-31 08:23 UTC, tdelhomenie-microej commented on SDK6UserGuide/publishProject.rst
> +Refer to `the official documentation <https://docs.gradle.org/current/userguide/publishing_maven.html#publishing_maven:repositories>`__ for more information on publication repositories.
Works fine for me:
![image](https://user-images.githubusercontent.com/69317038/215706283-75a86805-a61e-4ace-8c16-fc6271799c89.png)
Can you test again please?

2023-01-31 10:07 UTC, tdelhomenie-microej commented on SDK6UserGuide/publishProject.rst
> +Refer to `the official documentation <https://docs.gradle.org/current/userguide/publishing_maven.html#publishing_maven:repositories>`__ for more information on publication repositories.
Done.

2023-01-31 10:08 UTC, tdelhomenie-microej commented on SDK6UserGuide/createProject.rst
> +- select your prefered language for the field ``Gradle DSL``.
Done.

2023-01-31 15:28 UTC, jerome-leroux commented on SDK6UserGuide/selectVeePort.rst
> +     veePortDir = "C:\\path\\to\\my\\veePort\\directory"
@frivieremicroej @seonmej : any opinion?

2023-01-31 15:33 UTC, jerome-leroux commented on SDK6UserGuide/manageResolutionConflicts.rst
> +       |- moduleC:3.0.0
Looks good, but in the second graph it is "moduleA:1.1.0" and not "moduleC:1.1.0".

2023-01-31 15:36 UTC, jerome-leroux commented on SDK6UserGuide/createProject.rst
> +    }
Yes I did. I will check again.

2023-01-31 15:40 UTC, jerome-leroux commented on SDK6UserGuide/manageResolutionConflicts.rst
> +One of its job is to resolve the conflicts in the dependencies graph, to determine which version should be added to the graph.
It is just to keep that consistent with other references in the documentation which say "dependency graph". This is the only place we say "dependencies graph".

2023-01-31 16:14 UTC, tdelhomenie-microej commented on SDK6UserGuide/manageResolutionConflicts.rst
> +       |- moduleC:3.0.0
Done (and fixed).

2023-01-31 16:14 UTC, tdelhomenie-microej commented on SDK6UserGuide/manageResolutionConflicts.rst
> +One of its job is to resolve the conflicts in the dependencies graph, to determine which version should be added to the graph.
ok. Done.

2023-02-02 21:05 UTC, rlouedec-microej commented on SDK6UserGuide/resources/microej.init.gradle.kts
> +             url = uri("https://forge.microej.com/artifactory/microej-central-repository-release")
```suggestion
             url = uri("https://forge.microej.com/artifactory/microej-developer-repository-release")
```

2023-02-02 21:06 UTC, rlouedec-microej commented on SDK6UserGuide/resources/microej.init.gradle.kts
> +             url = uri("https://forge.microej.com/artifactory/microej-central-repository-release")
```suggestion
             url = uri("https://forge.microej.com/artifactory/microej-developer-repository-release")
```

2023-02-02 21:07 UTC, rlouedec-microej commented on SDK6UserGuide/resources/microej.init.gradle.kts
> +             url = uri("https://forge.microej.com/artifactory/microej-central-repository-release")
```suggestion
             url = uri("https://forge.microej.com/artifactory/microej-developer-repository-release")

```

2023-02-02 21:07 UTC, rlouedec-microej commented on SDK6UserGuide/resources/microej.init.gradle.kts
> +             url = uri("https://forge.microej.com/artifactory/microej-central-repository-release")
```suggestion
             url = uri("https://forge.microej.com/artifactory/microej-developer-repository-release")
```

2023-02-02 21:27 UTC, jerome-leroux commented on SDK6UserGuide/createProject.rst
> +    }
I followed the instruction from https://docs.microej.com/en/feature-microej-sdk-6/SDK6UserGuide/createProject.html#intellij-idea to create the project.
Here is the `build.gradle.kts` file content:
```
plugins {
    id("com.microej.gradle.library") version "0.4.0"
}

group = "org.example"
version = "1.0-SNAPSHOT"

dependencies {
    implementation("ej.api:edc:1.3.5")
}
```

<img width="238" alt="image" src="https://user-images.githubusercontent.com/20573510/216453337-5b4a3c95-c363-4f49-87c8-2d982615d466.png">

2023-02-02 21:40 UTC, rlouedec-microej commented on SDK6UserGuide/resources/microej.init.gradle.kts
> +         }
Is there a specific reason not to resolve Ivy modules from local repository ?
```suggestion
         maven {
            name = "localRepository"
            url = uri("${userHome}/.microej/repository")
         }
         ivy {
            name = "localRepositoryIvy"
            url = uri("${userHome}/.microej/repository")
            patternLayout {
                artifact("[organisation]/[module]/[revision]/[artifact]-[revision](-[classifier])(.[ext])")
                ivy("[organisation]/[module]/[revision]/ivy-[revision].xml")
                setM2compatible(true)
            }
        }
```

I am not familiar with Kotlin, but I would assume it should be possible to define a construct:
```
microej {
   name = "..."
   url = uri("...")
}
```
That would be equivalent to having both `maven {}` and `ivy {}`.

2023-02-02 22:10 UTC, rlouedec-microej commented on SDK6UserGuide/migrateMMMProject.rst
> +|    |   |- common.properties    |    |               |- common.properties   |
It seems the build properties file must be in `main` for `runOnSimulator`.
```suggestion
|    |- src                      |    |- src                                 |
|    |   |- main                 |    |   |- main                            |
|    |   |   |- java             |    |   |   |- java                        |
|    |   |   |- resources        |    |   |   |- resources                   |
|    |   |                       |    |   |       |- build                   |
|    |   |                       |    |   |           |- common.properties   |
|    |   |- test                 |    |   |- test                            |
|    |       |- java             |    |       |- java                        |
|    |       |- resources        |    |       |- resources                   |
|    |- build                    |    |           |- build                   |
|    |   |- common.properties    |    |               |- common.properties   |
```

Plus I think a short section explaining this change would help.

2023-02-02 22:42 UTC, rlouedec-microej commented on SDK6UserGuide/selectVeePort.rst
> +- Set the build property ``veePortDir`` in the ``microej`` configuration block to the path of the ``source`` folder of an already imported :ref:`Source VEE Port <source_platform_import>`::
Setting this property will result in the folder being copied into Gradle's `build` folder.
In SDK5, it does load the Platform directly from the given path (no copy).
Is this change intentional ? If so, is there a way to have similar behavior to SDK5 in another way ?
If not, is there a recommended way to modify the platform without deleting & copying the whole folder between each app build ?

2023-02-02 23:11 UTC, rlouedec-microej commented on SDK6UserGuide/runOnSimulator.rst
> +   gradle runOnSimulator --info
Verbose mode in SDK5 applies to the init scripts Ant execution.
With `--info`; I don't have more logs from Ant.
I don't even have the error message & stacktrace:
```
$ gradle runOnSimulator
=============== [ Initialization Stage ] ===============
Java Result: 1

BUILD SUCCESSFUL in 2m 19s
6 actionable tasks: 3 executed, 3 up-to-date
```
---
```
2023-02-02T17:48:01.142-0500 [LIFECYCLE] [class org.gradle.internal.buildevents.TaskExecutionLogger]
2023-02-02T17:48:01.142-0500 [LIFECYCLE] [class org.gradle.internal.buildevents.TaskExecutionLogger] > Task :XXX:runOnSimulator
2023-02-02T17:48:01.142-0500 [DEBUG] [org.gradle.api.internal.tasks.execution.ResolveTaskExecutionModeExecuter] Putting task artifact state for task ':XXX:runOnSimulator' into context took 0.0 secs.
2023-02-02T17:48:01.163-0500 [INFO] [org.gradle.internal.execution.steps.ResolveCachingStateStep] Caching disabled for task ':XXX:runOnSimulator' because:
  Build cache is disabled
2023-02-02T17:48:01.163-0500 [DEBUG] [org.gradle.internal.execution.steps.SkipUpToDateStep] Determining if task ':XXX:runOnSimulator' is up-to-date
2023-02-02T17:48:01.163-0500 [INFO] [org.gradle.internal.execution.steps.SkipUpToDateStep] Task ':XXX:runOnSimulator' is not up-to-date because:
  Task has not declared any outputs despite executing actions.
2023-02-02T17:48:01.164-0500 [DEBUG] [org.gradle.internal.vfs.impl.AbstractVirtualFileSystem] Invalidating VFS paths: []2023-02-02T17:48:01.164-0500 [DEBUG] [org.gradle.api.internal.tasks.execution.TaskExecution] Executing actions for task ':XXX:runOnSimulator'.
2023-02-02T17:48:01.164-0500 [INFO] [org.gradle.api.Task] Starts the simulator from the VEE Port located at /mnt/c/Sources/XXX/XXX/build/veePort
2023-02-02T17:48:04.223-0500 [LIFECYCLE] [org.gradle.cache.internal.DefaultFileLockManager]
2023-02-02T17:48:04.223-0500 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Waiting to acquire shared lock on daemon addresses registry.
2023-02-02T17:48:04.224-0500 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Lock acquired on daemon addresses registry.
2023-02-02T17:48:04.224-0500 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Releasing lock on daemon addresses registry.
2023-02-02T17:48:04.224-0500 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Waiting to acquire shared lock on daemon addresses registry.
2023-02-02T17:48:04.224-0500 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Lock acquired on daemon addresses registry.
2023-02-02T17:48:04.224-0500 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Releasing lock on daemon addresses registry.
2023-02-02T17:48:09.893-0500 [QUIET] [system.out] =============== [ Initialization Stage ] ===============
2023-02-02T17:48:14.223-0500 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Waiting to acquire shared lock on daemon addresses registry.
2023-02-02T17:48:14.223-0500 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Lock acquired on daemon addresses registry.
2023-02-02T17:48:14.223-0500 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Releasing lock on daemon addresses registry.
2023-02-02T17:48:14.224-0500 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Waiting to acquire shared lock on daemon addresses registry.
2023-02-02T17:48:14.224-0500 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Lock acquired on daemon addresses registry.
2023-02-02T17:48:14.224-0500 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Releasing lock on daemon addresses registry.
2023-02-02T17:48:15.304-0500 [QUIET] [system.out] 6
2023-02-02T17:48:15.334-0500 [QUIET] [system.out] Java Result: 1
2023-02-02T17:48:15.339-0500 [DEBUG] [org.gradle.internal.operations.DefaultBuildOperationRunner] Completing Build operation 'Execute run for :XXX:runOnSimulator'
2023-02-02T17:48:15.339-0500 [DEBUG] [org.gradle.internal.operations.DefaultBuildOperationRunner] Completing Build operation 'Executing task ':XXX:runOnSimulator''
2023-02-02T17:48:03.234-0500 [LIFECYCLE] [class org.gradle.internal.buildevents.TaskExecutionLogger]
2023-02-02T17:48:03.234-0500 [LIFECYCLE] [class org.gradle.internal.buildevents.TaskExecutionLogger] > Task :XXX:runOnSimulator
2023-02-02T17:48:15.339-0500 [DEBUG] [org.gradle.internal.operations.DefaultBuildOperationRunner] Build operation 'Execute run for :XXX:runOnSimulator' completed
2023-02-02T17:48:15.339-0500 [DEBUG] [org.gradle.internal.operations.DefaultBuildOperationRunner] Build operation 'Executing task ':XXX:runOnSimulator'' completed
2023-02-02T17:48:15.339-0500 [DEBUG] [org.gradle.internal.vfs.impl.AbstractVirtualFileSystem] Invalidating VFS paths: []2023-02-02T17:48:15.339-0500 [DEBUG] [org.gradle.api.internal.tasks.execution.ResolveTaskExecutionModeExecuter] Removed task artifact state for task ':XXX:runOnSimulator' from context.
2023-02-02T17:48:15.340-0500 [DEBUG] [org.gradle.internal.operations.DefaultBuildOperationRunner] Completing Build operation 'Task :XXX:runOnSimulator'
2023-02-02T17:48:15.340-0500 [DEBUG] [org.gradle.internal.operations.DefaultBuildOperationRunner] Build operation 'Task :XXX:runOnSimulator' completed
2023-02-02T17:48:15.340-0500 [DEBUG] [org.gradle.execution.plan.DefaultFinalizedExecutionPlan] Node :XXX:runOnSimulator completed, executed: true
2023-02-02T17:48:15.340-0500 [DEBUG] [org.gradle.execution.plan.DefaultFinalizedExecutionPlan] Node :XXX:runOnSimulator finished executing
2023-02-02T17:48:15.340-0500 [DEBUG] [org.gradle.internal.resources.AbstractTrackedResourceLock] included builds: released lock on state of build :
2023-02-02T17:48:15.340-0500 [DEBUG] [org.gradle.internal.resources.AbstractTrackedResourceLock] included builds: released lock on task execution for build :
2023-02-02T17:48:15.340-0500 [DEBUG] [org.gradle.internal.resources.AbstractTrackedResourceLock] Execution worker: acquired lock on worker lease
2023-02-02T17:48:15.341-0500 [DEBUG] [org.gradle.internal.resources.AbstractTrackedResourceLock] Execution worker: released lock on worker lease
2023-02-02T17:48:15.342-0500 [DEBUG] [org.gradle.internal.resources.AbstractTrackedResourceLock] Execution worker Thread 3: acquired lock on worker lease
2023-02-02T17:48:15.343-0500 [DEBUG] [org.gradle.internal.resources.AbstractTrackedResourceLock] Execution worker Thread 3: released lock on worker lease
2023-02-02T17:48:15.345-0500 [DEBUG] [org.gradle.internal.resources.AbstractTrackedResourceLock] Execution worker Thread 2: acquired lock on worker lease
2023-02-02T17:48:15.348-0500 [DEBUG] [org.gradle.internal.resources.AbstractTrackedResourceLock] Execution worker Thread 2: released lock on worker lease
2023-02-02T17:48:15.349-0500 [DEBUG] [org.gradle.internal.operations.DefaultBuildOperationRunner] Completing Build operation 'Run tasks'
2023-02-02T17:48:15.349-0500 [DEBUG] [org.gradle.internal.operations.DefaultBuildOperationRunner] Build operation 'Run tasks' completed
2023-02-02T17:48:15.349-0500 [DEBUG] [org.gradle.internal.resources.AbstractTrackedResourceLock] included builds: released lock on worker lease
2023-02-02T17:48:15.350-0500 [DEBUG] [org.gradle.internal.resources.AbstractTrackedResourceLock] Execution worker: acquired lock on worker lease
2023-02-02T17:48:15.350-0500 [DEBUG] [org.gradle.internal.resources.AbstractTrackedResourceLock] Execution worker: released lock on worker lease
2023-02-02T17:48:15.350-0500 [DEBUG] [org.gradle.internal.resources.AbstractTrackedResourceLock] Daemon worker Thread 13: acquired lock on worker lease
2023-02-02T17:48:15.350-0500 [DEBUG] [org.gradle.internal.operations.DefaultBuildOperationRunner] Completing Build operation 'Run main tasks'
2023-02-02T17:48:15.350-0500 [DEBUG] [org.gradle.internal.operations.DefaultBuildOperationRunner] Build operation 'Run main tasks' completed
2023-02-02T17:48:15.350-0500 [DEBUG] [org.gradle.internal.resources.AbstractTrackedResourceLock] Execution worker Thread 2: acquired lock on worker lease
2023-02-02T17:48:15.351-05 [...]

2023-02-02 23:39 UTC, rlouedec-microej commented on SDK6UserGuide/selectVeePort.rst
> +- Set the build property ``veePortDir`` in the ``microej`` configuration block to the path of the ``source`` folder of an already imported :ref:`Source VEE Port <source_platform_import>`::
Note that it seems that the `script` folder is then copied again from `build/veeport/scripts` into `/build/scripts`.

2023-02-02 23:42 UTC, rlouedec-microej commented on SDK6UserGuide/runOnSimulator.rst
> +   gradle runOnSimulator --info
As a workaround, I've managed to get logs with [<record/>](https://ant.apache.org/manual/Tasks/recorder.html).
(Warning: the execution directory is `/build/scripts/`, see https://github.com/MicroEJ/docs/pull/492#discussion_r1095204067)

2023-02-02 23:43 UTC, rlouedec-microej commented on SDK6UserGuide/runOnSimulator.rst
> +   gradle runOnSimulator --info
My issue was related to the Ant lib path not including `veeport/tools/ant/lib/*`:
```
This appears to be an antlib declaration.
Action: Check that the implementing library exists in one of:
        -/home/rlouedec/.sdkman/candidates/gradle/7.6/lib
        -/home/rlouedec/.ant/lib
        -a directory added on the command line with the -lib argument
```
Is this considered unsupported by SDK 6 ?

2023-02-03 00:15 UTC, rlouedec-microej commented on SDK6UserGuide/runOnSimulator.rst
> +   gradle runOnSimulator --info
Also, I noted that the property `application.project.dir` is no longer set.  
I expect breaking changes but I wanted to highlight it, might be something that we want to keep.

2023-02-03 00:22 UTC, rlouedec-microej commented on SDK6UserGuide/install.rst
> +   - Linux distributions (tested on Ubuntu 20.04 and 22.04)
Is WSL supported ?
I've managed to use it with WSL2 (Ubuntu 20.04) up to the MicroUI simulation:
```
Exception in thread "main" @T:ej.microui.MicroUIException@: MicroUI: Issue when loading SystemMicroUI implementation class.
        at java.lang.Throwable.fillInStackTrace(Throwable.java:82)
        at java.lang.Throwable.<init>(Throwable.java:37)
        at java.lang.Exception.<init>(Exception.java:18)
        at java.lang.RuntimeException.<init>(RuntimeException.java:18)
        at ej.microui.MicroUIException.<init>(MicroUIException.java:93)
        at ej.microui.MicroUI.getMicroUIImpl(MicroUI.java:133)
        at ej.microui.MicroUI.<clinit>(MicroUI.java:26)
        at XXX
        at XXX
        at XXX
        at java.lang.MainThread.run(Thread.java:914)
        at java.lang.Thread.runWrapper(Thread.java:387)
Caused by: @T:java.lang.UnsatisfiedLinkError@: No HIL client implementor found (timeout)
        at java.lang.Throwable.fillInStackTrace(Throwable.java:82)
        at java.lang.Throwable.<init>(Throwable.java:37)
        at java.lang.Error.<init>(Error.java:18)
        at java.lang.LinkageError.<init>(LinkageError.java:18)
        at java.lang.UnsatisfiedLinkError.<init>(UnsatisfiedLinkError.java:10)
        at ej.trace.Tracer.<init>(Tracer.java:111)
        at ej.microui.Log.create(Log.java:78)
        at ej.microui.MicroUI.<init>(MicroUI.java:41)
        at ej.microui.SystemMicroUI.<init>(SystemMicroUI.java:24)
        at ej.microui.SystemMicroUIImpl.<init>(SystemMicroUIImpl.java:16)
        at ej.microui.MicroUI.getMicroUIImpl(MicroUI.java:126)
        at ej.microui.MicroUI.<clinit>(MicroUI.java:26)
        at XXX
        at XXX
        at XXX
        at java.lang.MainThread.run(Thread.java:914)
        at java.lang.Thread.runWrapper(Thread.java:387)
Exception in thread "main" @T:java.lang.NullPointerException@
        at java.lang.Throwable.fillInStackTrace(Throwable.java:82)
        at java.lang.Throwable.<init>(Throwable.java:32)
        at java.lang.Exception.<init>(Exception.java:14)
        at java.lang.RuntimeException.<init>(RuntimeException.java:14)
        at java.lang.NullPointerException.<init>(NullPointerException.java:6)
        at ej.microui.MicroUI.start(MicroUI.java:50)
        at XXX
        at XXX
        at XXX
        at java.lang.MainThread.run(Thread.java:914)
        at java.lang.Thread.runWrapper(Thread.java:387)
```
I am not an expert on WSL2 though, it might be the expected behavior for headless systems.

2023-02-03 16:38 UTC, rlouedec-microej commented on SDK6UserGuide/install.rst
> +   - Linux distributions (tested on Ubuntu 20.04 and 22.04)
I've just updated by WSL and confirm I can run GUI apps from it (tested with VLC).
Yet, the simulator does not launch any front panel AND still fails with above exception (which does not terminate the simulation).

2023-02-06 17:22 UTC, rlouedec-microej commented on SDK6UserGuide/resources/microej.init.gradle.kts
> +         }
> Maybe you meant using the Ivy local repository defined in the default SDK 5 ivy settings file: ${user.home}/.ivy2/repository?

Oh ! You're right, this is a different path.
Thing is, I used to manually drop modules in this folder when I needed to.
And that's what I've done to test the SDK6: I manually dropped "SDK 5/Ivy modules" from my app dependencies that were missing from the central/developer repositories in `~/.microej/repository`, and it failed to load them.

But it makes if you don't want to support that (one can still customize its settings anyway).

> It would add a new indirection to understand what it means. For the moment we decided to keep this file explicit.

Ok, it makes sense, I just find this file hard to understand & maintain (compared to how simple it could be).
But indeed, the indirection would make things harder for a user to understand MMM can use any Maven source.

2023-02-07 16:48 UTC, tdelhomenie-microej commented on SDK6UserGuide/migrateMMMProject.rst
> +|    |   |- common.properties    |    |               |- common.properties   |
Done for the files tree, good catch.
For the explanation, there is already something above the tree:

> the build folder located at the root of the project and containing the Application configuration properties is moved to the src/main/resources folder. This change is required since Gradle uses the build folder to store the generated files and artifacts (equivalent of the MMM target~ folder).

Do you think it should be more detailed?

2023-02-07 16:50 UTC, tdelhomenie-microej commented on SDK6UserGuide/resources/microej.init.gradle.kts
> +         }
ok, let's keep it like that for the moment. If we noticed more developers struggle with this, we can change it.

2023-02-07 17:03 UTC, tdelhomenie-microej commented on SDK6UserGuide/selectVeePort.rst
> +- Set the build property ``veePortDir`` in the ``microej`` configuration block to the path of the ``source`` folder of an already imported :ref:`Source VEE Port <source_platform_import>`::
In SDK5, the Platform is also copied into the target folder, we used the same behavior. One benefit of Gradle is that if the Platform did not change, the copy is not done again, whereas it is always done with the SDK5.
Or maybe you are talking about a build type or use case I don't have in mind?

2023-02-07 17:09 UTC, rlouedec-microej commented on SDK6UserGuide/migrateMMMProject.rst
> +|    |   |- common.properties    |    |               |- common.properties   |
Oh I missed that.
Current documentation is good to me.

2023-02-07 17:16 UTC, rlouedec-microej commented on SDK6UserGuide/selectVeePort.rst
> +- Set the build property ``veePortDir`` in the ``microej`` configuration block to the path of the ``source`` folder of an already imported :ref:`Source VEE Port <source_platform_import>`::
Ok you're probably right for the SDK5 build with MMM.
I just had a bad experience when running an application on the simulator compared to SDK5 "run on simulator" Eclipse plugin which does not copy the VEE port files.
Now, "run on simulator" copies the VEE port each time, or at least, each file has to be checked I think (and there is a lot of files !). So it was really slow in my case. (even though I was not in the best conditions: VEE port & Application projects on my Windows file system, SDK 6 running in WSL2)

2023-02-07 17:18 UTC, tdelhomenie-microej commented on SDK6UserGuide/runOnSimulator.rst
> +   gradle runOnSimulator --info
We should see the detailed logs with the `--info` option, but we should also see the stacktrace or the error even without the `--info` option.

> As a workaround, I've managed to get logs with .

With what ? :)

> Is this considered unsupported by SDK 6 ?

I am not sure what you are trying to do. Can you give me a bit more context please ?

> Also, I noted that the property application.project.dir is no longer set.
I expect breaking changes but I wanted to highlight it, might be something that we want to keep.

I don't know about this property.
The goal for the moment is to implement what we consider as the main features for the Java developers. A lot of features or properties are not supported for the moment, it would require work to list them all, that's why we only listed the main features here: https://docs.microej.com/en/feature-microej-sdk-6/SDK6UserGuide/limitations.html Moreover it is not clear what is considered as a public property and what is considered as an internal property in the SDK 5 (since everything is public with easyant).
But can you describe your usage of this property ? We can create a ticket to implement it later if it is a valid use case.

2023-02-07 17:23 UTC, tdelhomenie-microej commented on SDK6UserGuide/install.rst
> +   - Linux distributions (tested on Ubuntu 20.04 and 22.04)
I think we have never tested with WSL. So thanks for the test :)
Does it work fine with MMM CLI ?

2023-02-07 17:29 UTC, tdelhomenie-microej commented on SDK6UserGuide/selectVeePort.rst
> +- Set the build property ``veePortDir`` in the ``microej`` configuration block to the path of the ``source`` folder of an already imported :ref:`Source VEE Port <source_platform_import>`::
Ah yes, when executing the sim from a launcher it does not copy the Platform, that's right. We don't have the equivalent with Gradle for the moment. We don't even know if we will do it, it will depend on the developers' feedbacks.
The "run on simulator" with Gradle does a copy, and then compares a fingerprint of the folder. It is very quick on my side. That could be interesting to understand what is really slow on your side. Maybe you could do some thread dumps to confirm it is only related to I/O or not.

2023-02-07 17:49 UTC, rlouedec-microej commented on SDK6UserGuide/runOnSimulator.rst
> +   gradle runOnSimulator --info
> With what ? :)

HTML characters escape issue fixed 🔼 

> Can you give me a bit more context please ?

I have a custom init script that depends on the Ant Contrib library.
Calling a Ant target from that library failed with above error (no stacktrace, no detailed error message, no debug logs: even with `--info / --debug`).
Root cause of the issue is mentioned above (Ant lib path).
As a summary: I was trying to debug my custom init script.

> I don't know about this property.

Inside a VEE Port init script, I need to generate a file in the VEE Application project.
To do that, I must know the path to this project: this property used to provide exactly that information.
I just checked, it seems the other MicroEJ official init scripts use `output.dir` for the same purpose.
Maybe I should use it instead.

2023-02-07 17:53 UTC, rlouedec-microej commented on SDK6UserGuide/install.rst
> +   - Linux distributions (tested on Ubuntu 20.04 and 22.04)
You are welcome =)

I am not sure how to install MMM CLI on my WSL.
Should I use the build kit exported from my Windows MICROEJ SDK installation ?

2023-02-07 17:58 UTC, rlouedec-microej commented on SDK6UserGuide/selectVeePort.rst
> +- Set the build property ``veePortDir`` in the ``microej`` configuration block to the path of the ``source`` folder of an already imported :ref:`Source VEE Port <source_platform_import>`::
Ok, if it is quick on your side, that is a WSL2 related issue: I should copy the projects on my WSL file system first.
I/O operations on the Windows file system are known to be slow.

If that is the case, we should be fine with the one-time copy.
It may slow down developers working on the platform scripts but that's corner cases already.

2023-02-07 23:14 UTC, rlouedec-microej commented on SDK6UserGuide/install.rst
> +   - Linux distributions (tested on Ubuntu 20.04 and 22.04)
I realized I can now simply install MICROEJ SDK 5 on my WSL2 since GUI Linux apps are now supported. And then export the build kit from it directly.
I tested running the app on the simulator using

- Windows Eclipse: ✅ 
- Windows MMM CLI: ✅ 
- WSL2 Eclipse: ✅ 
- WSL2 MMM CLI: ✅ 
- WSL2 Gradle: ❌

2023-02-08 07:21 UTC, tdelhomenie-microej commented on SDK6UserGuide/install.rst
> +   - Linux distributions (tested on Ubuntu 20.04 and 22.04)
ok. Thanks for the test 👍 
I created a ticket: https://youtrack.cross/issue/M0090IDE-4119/Gradle-Cannot-run-an-UI-application-on-sim-on-WSL

2023-02-08 21:08 UTC, rlouedec-microej commented on SDK6UserGuide/install.rst
> +   - Linux distributions (tested on Ubuntu 20.04 and 22.04)
I've just found the issue: it timeouts just because it is too slow on WSL2.
I managed to run the UI application on the simulator with Gradle at the condition my project is in my WSL2 filesystem.
Probably `MicroUI.start()` just happens to be the first native call which takes long enough to break the HIL connection, leasing me to wrong conclusions.

SDK 6 works great !

2023-02-09 07:19 UTC, tdelhomenie-microej commented on SDK6UserGuide/install.rst
> +   - Linux distributions (tested on Ubuntu 20.04 and 22.04)
Good to hear ! 👍

2023-02-21 06:57 UTC, tdelhomenie-microej commented on SDK6UserGuide/createProject.rst
> +
Done (https://docs.microej.com/en/feature-microej-sdk-6/SDK6UserGuide/createProject.html).

2023-03-06 13:46 UTC, thomasponsmicroej commented
@tdelhomenie-microej reminder to add a note that the message "A message Project JDK is not defined is displayed at the top of the editor (...)" not only in the `Create a Project` section but also when importing/opening a project.

2023-05-02 09:41 UTC, tdelhomenie-microej commented on SDK6UserGuide/moduleNatures.rst
> +which means that it should be called explicitly if it muust be executed.
Done.

2023-08-03 19:03 UTC, rlouedec-microej commented on SDK6UserGuide/testProject.rst
> +   }
I tried to run the test generated by `gradle init` but this configuration failed (with MicroEJ Gradle plugin 0.8.0):
```
Caused by: java.lang.ClassNotFoundException: test.gradle._AllTests_AppTest
```

It looks like the JUnit ADP is not executed. What am I missing ?
Also, when I run the `adp` task after a `clean`, nothing happens (no build dir generated).

2023-08-03 20:19 UTC, rlouedec-microej commented on SDK6UserGuide/buildExecutable.rst
> +  Refer to the :ref:`sdk_6_select_veeport` page to know the different ways to provide a VEE Port for a module project.
This is for `platform->*`, it seems `implementation()` works for `kernelapi->*`, but what to do for `systemapp->*` ?

2023-08-03 20:42 UTC, rlouedec-microej commented on SDK6UserGuide/buildExecutable.rst
> +  Refer to the :ref:`sdk_6_select_veeport` page to know the different ways to provide a VEE Port for a module project.
Found it by looking at the plugin sources: `microejApplication()`. We may document that here:
```suggestion
- A target VEE Port that uses an Architecture version ``7.17`` minimum must be defined.
  Refer to the :ref:`sdk_6_select_veeport` page to know the different ways to provide a VEE Port for a module project.
- In case of a kernel project, kernel/runtime API modules can be added to dependencies with `implementation()`.
- In case of a kernel project, system apps can be defined by adding `microejApplication("com.company:myapp:1.2.3")` to dependencies.
```
Although it seems only supported for `buildVirtualDevice` (not `buildExecutable`, nor `runOnSimulator`), right ?

Also, `microejApplication()` dependency does not support subproject:
```
plugins {
        id("com.microej.gradle.application") version "0.8.0"
}

microej {
        applicationMainClass = "com.microej.example.si.MinimalServiceRegistryKernel"
        veePortDirs = listOf("C:/Users/rlouedec/Sources/MicroEJ/VEE-STM32F7508DK/STM32F7508-Platform-CM7hardfp_GCC48-1.6.1/source")
}

dependencies {
        implementation("ej.api:edc:1.3.5")
        implementation("ej.api:kf:1.7.0")

        implementation("com.microej.kernelapi:edc:1.1.0")
        implementation("com.microej.kernelapi:kf:2.1.0")

        microejApplication(project(":library-kf-service-registry-minimal"))
        microejApplication(project(":application-service-consumer-minimal"))
        microejApplication(project(":application-service-provider-minimal"))
}
```
```
> .\gradlew.bat clean :kernel-service-registry-minimal:buildVirtualDevice

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':kernel-service-registry-minimal:buildVirtualDevice'.
> Could not resolve all dependencies for configuration ':kernel-service-registry-minimal:microejApplication'.
   > Substitution with artifacts for something else than a module is not supported

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.

BUILD FAILED in 8s
```

2023-08-04 06:57 UTC, tdelhomenie-microej commented on SDK6UserGuide/buildExecutable.rst
> +  Refer to the :ref:`sdk_6_select_veeport` page to know the different ways to provide a VEE Port for a module project.
Yes it should have been documented for the release 0.8.0. I created a ticket for that: https://youtrack.cross/issue/M0090IDE-4272/Document-additional-capabilities-for-the-build-of-a-kernel
I think we should keep the prerequisites to build an executable as is, the bare minimum, and add a section below to the kernel case specifically.

2023-08-04 07:19 UTC, tdelhomenie-microej commented on SDK6UserGuide/testProject.rst
> +   }
> I tried to run the test generated by gradle init but this configuration failed (with MicroEJ Gradle plugin 0.8.0):
> It looks like the JUnit ADP is not executed. What am I missing ?

You tried to run the test through the IDE? If so, the execution of the tests require the adp to be executed before, that's a limitation of the current integration. There is no problem when running the tests through the command line (with ``gradle test``) since the adp task is automatically executed in this case.
If you confirm, we should probably improve the error message to explain this and suggest to execute the adp task.

> Also, when I run the adp task after a clean, nothing happens (no build dir generated).

Do you have the same issue if you execute the `test` task? I suspect that in the case you execute only the `adp`task, the dependencies of the testsuite are not considered, so no addon processor is found.

2023-08-04 19:21 UTC, rlouedec-microej commented on SDK6UserGuide/buildExecutable.rst
> +  Refer to the :ref:`sdk_6_select_veeport` page to know the different ways to provide a VEE Port for a module project.
Ok LGTM 👍

2023-08-04 19:21 UTC, rlouedec-microej commented on SDK6UserGuide/testProject.rst
> +   }
> You tried to run the test through the IDE?

No, it failed with the CLI :/

> Do you have the same issue if you execute the `test` task?

This is my use case, and I can see there is no adp build folder created.

2023-08-04 19:27 UTC, rlouedec-microej commented on SDK6UserGuide/buildVirtualDevice.rst
> +======================
This documents how to configure the `buildVirtualDevice` task but does not document any output that can be used for anything useful.
I can see the `<project>/build/virtualDevice` which I assume I can import in a SDK 5 Eclipse workspace, is that all that is currently supported ?

2023-08-07 07:23 UTC, tdelhomenie-microej commented on SDK6UserGuide/testProject.rst
> +   }
ok, can you share your project please?

2023-08-07 09:20 UTC, tdelhomenie-microej commented on SDK6UserGuide/buildVirtualDevice.rst
> +======================
I updated the documentation https://docs.microej.com/en/feature-microej-sdk-6/SDK6UserGuide/buildVirtualDevice.html

The VD built with the SDK 6 can be used in the SDK5, but not imported in Eclipse since we don't provide and publish an artifact yet. It will come soon.

2023-08-07 21:14 UTC, rlouedec-microej commented on SDK6UserGuide/testProject.rst
> +   }
[test-gradle-app.zip](https://github.com/MicroEJ/docs/files/12285240/test-gradle-app.zip)
```
> gradle clean test

> Task :app:compileTestJava
incorrect classpath: C:\\Users\\rlouedec\\Sources\\test-gradle-app\\app\\build\\resources\\main

> Task :app:test FAILED

UnknownClass.MicroEJ TestSuite > UnknownClass.executionError FAILED
    org.junit.platform.commons.JUnitException at EngineExecutionOrchestrator.java:113
        Caused by: java.lang.RuntimeException at MicroejTestEngine.java:375
            Caused by: java.lang.ClassNotFoundException at BuiltinClassLoader.java:581

UnknownClass.MicroEJ TestSuite FAILED

3 tests completed, 2 failed, 1 skipped

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:test'.
> There were failing tests. See the report at: file:///C:/Users/rlouedec/Sources/test-gradle-app/app/build/reports/tests/test/index.html

* Try:
> Run with --scan to get full insights.

BUILD FAILED in 13s
8 actionable tasks: 7 executed, 1 up-to-date
```

2023-08-07 21:18 UTC, rlouedec-microej commented on SDK6UserGuide/testProject.rst
> +   }
With logs after a cleanup, it seems the `compileTestJava` task is broken here: "incorrect classpath" but no failure leading to "corrupted" build folder after this. Requesting `test` again leads to same error without the "incorrect classpath" log.

```
$ touch .\app\src\main\resources\.gitkeep
$ gradle clean test

BUILD SUCCESSFUL in 24s
9 actionable tasks: 8 executed, 1 up-to-date
```

2023-08-07 21:35 UTC, rlouedec-microej commented on SDK6UserGuide/testProject.rst
> +   }
Since I did the "touch" workaround, I cannot reproduce...
I still see the "incorrect classpath" when I remove the `.gitkeep` file but no test execution error anymore...
I have no idea what changed..

2023-08-07 22:16 UTC, rlouedec-microej commented on SDK6UserGuide/buildVirtualDevice.rst
> +======================
Indeed, thank you

2023-08-08 16:27 UTC, tdelhomenie-microej commented on SDK6UserGuide/testProject.rst
> +   }
That's a simple test, it shouldn't fail randomly, weird.
Ok, feel free to reopen this thread if you face the problem again.

2023-09-01 13:49 UTC, arouaux-mej commented on SDK6UserGuide/selectVeePort.rst
> +VEE Port unique name
I am wondering if chapter titles should use "Initial Caps" style.

2023-09-01 13:49 UTC, arouaux-mej commented on SDK6UserGuide/selectVeePort.rst
> +Select multiple VEE Ports
I am wondering if chapter titles should use "Initial Caps" style.

2023-09-01 15:18 UTC, tdelhomenie-microej commented on SDK6UserGuide/selectVeePort.rst
> +VEE Port unique name
Right, it is fixed now, thanks.

2023-09-05 07:59 UTC, arouaux-mej commented on SDK6UserGuide/howtos/gradleSystemProperty.rst
> +      veePortDir = providers.systemProperty("myVeePortDir").get()
With this line I have this error: "Type mismatch: inferred type is String! but (Mutable)List<String!>! was expected"

The correct syntax is probably: veePortDirs = listOf(providers.systemProperty("myVeePortDir").get())

2023-09-05 11:28 UTC, tdelhomenie-microej commented on SDK6UserGuide/howtos/gradleSystemProperty.rst
> +      veePortDir = providers.systemProperty("myVeePortDir").get()
Right, this example has not been updated recently. The variable name should be changed as well, it is now `veePortPaths`, starting from the version 0.9.0. I will do the fix. Thanks!

2023-09-05 11:49 UTC, tdelhomenie-microej commented on SDK6UserGuide/howtos/gradleSystemProperty.rst
> +      veePortDir = providers.systemProperty("myVeePortDir").get()
Done.

2023-09-25 12:45 UTC, thomasponsmicroej commented on SDK6UserGuide/createProject.rst
> +              id("com.microej.gradle.addon-library") version "0.10.0"
0.11.1 ?

2023-09-25 15:56 UTC, tdelhomenie-microej commented on SDK6UserGuide/createProject.rst
> +              id("com.microej.gradle.addon-library") version "0.10.0"
Good catch, done.

2023-10-02 09:45 UTC, thomasponsmicroej commented on SDK6UserGuide/createProject.rst
> +      The project created by Android Studio is a standard Java project (Gradle ``java`` plugin).
i think that the project created by android studio is an Android project right (not Java)? Gradle plugin `com.android.application`

2023-10-02 14:19 UTC, thomasponsmicroej commented on SDK6UserGuide/createProject.rst
> +      - Click on ``File`` > ``New`` > ``Project...``.
In other parts of the documentation, we use :guilabel: for that purpose, has it changed?

2023-10-03 12:26 UTC, thomasponsmicroej commented on SDK6UserGuide/createProject.rst
> +         By default, Android Studio automatically save any file change,
```suggestion
         By default, Android Studio automatically saves any file change, 
```

2023-10-03 14:41 UTC, thomasponsmicroej commented on SDK6UserGuide/createProject.rst
> +      - Click on :guilabel:`Finish` button.
If I use the Phone or Wear template with no activity like specified, it will create a project with an Android application.
I see multiple issues:
- a subproject app with unwanted files (res directory, AndroidManifest) 
![image](https://github.com/MicroEJ/docs/assets/48557644/0db5d36a-6bbd-4439-bc1a-c280c5e4280b)
- a settings.gradle.kts file that contains a repositories configuration taht shadows the one in the init script leading to build errors for the user during resolve.
```
pluginManagement {
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
}
dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
    }
}
```

because we don't say to wipe the content of the settings file and we don't say to wipe the content of the app subproject. Did i miss something?

2023-10-10 12:37 UTC, thomasponsmicroej commented on SDK6UserGuide/install.rst
> +Configure Repositories
```suggestion
.. _sdk_6_configure_repositories:
Configure Repositories
```

2023-10-10 13:21 UTC, tdelhomenie-microej commented on SDK6UserGuide/install.rst
> +Configure Repositories
Done.

2023-12-01 10:18 UTC, bguedas approved these changes

2023-12-01 10:19 UTC, merged