document the Feature installation modes
MicroEJ/docs pull request #499
Opened 2023-01-13 09:26 UTC by frivieremicroej

based on the original PPTX specification

Preview: https://docs.microej.com/en/feature-m0081meja-1798_document_feature_link_flash/

2023-01-25 16:28 UTC, frivieremicroej commented
Link to preview: https://docs.microej.com/en/feature-m0081meja-1798_document_feature_link_flash/

2023-01-27 00:22 UTC, jerome-leroux requested changes

2023-01-27 00:22 UTC, jerome-leroux commented on VEEPortingGuide/multiSandbox.rst
> +- transfer the Feature content (code and resources) to target memory location,
```suggestion
- transfer the Feature content (code and resources) to the target memory location,
```

2023-01-27 00:22 UTC, jerome-leroux commented on VEEPortingGuide/multiSandbox.rst
> +- apply relocations to code (e.g. resolving final addresses to instructions such as method call, static field access, ...).
```suggestion
- apply relocations to code (e.g., resolving final addresses in instructions such as method call, static field access, ...).
```

2023-01-27 00:22 UTC, jerome-leroux commented on VEEPortingGuide/multiSandbox.rst
> +There are 2 kinds of installation:
```suggestion
There are two kinds of installation:
```

2023-01-27 00:22 UTC, jerome-leroux commented on VEEPortingGuide/multiSandbox.rst
> +This is the fastest way to go with Feature installation, since it only requires to connect a ``malloc/free`` implementation.
```suggestion
This is the fastest way to go with Feature installation since it only requires connecting a ``malloc/free`` implementation.
```

2023-01-27 00:22 UTC, jerome-leroux commented on VEEPortingGuide/multiSandbox.rst
> +When the Core Engine or the device restarts the Kernel Working Buffer is reset, thus there is no persistent Feature.
```suggestion
When the Core Engine or the device restarts, the Kernel Working Buffer is reset; thus there is no persistent Feature. 
```

2023-01-27 00:22 UTC, jerome-leroux commented on VEEPortingGuide/multiSandbox.rst
> +The Abstraction Layer implementation is responsible to provide:
```suggestion
The Abstraction Layer implementation is responsible for providing the following elements:
```

2023-01-27 00:22 UTC, jerome-leroux commented on VEEPortingGuide/multiSandbox.rst
> +- the implementation to copy chunk of bytes to the target location.
```suggestion
- the implementation to copy a chunk of bytes to the target location.
```

2023-01-27 00:22 UTC, jerome-leroux commented on VEEPortingGuide/multiSandbox.rst
> +If the Abstraction Layer implementation installs it in a Read-Only memory, the Abstraction Layer implementation can so that the Feature will be available after the Core Engine or the device restarts.
```suggestion
If the Abstraction Layer implementation installs a Feature in a Read-Only memory, it will be available after the Core Engine or the device restarts.
```

2023-01-27 00:22 UTC, jerome-leroux commented on VEEPortingGuide/multiSandbox.rst
> +Once the Core Engine has processed the given number of relocations, it yields the execution to other threads than the one that is calling the `Kernel.install(InputStream)`_ method.
```suggestion
Once the Core Engine has processed the given number of relocations, the thread that called the `Kernel.install(InputStream)`_ method yields the execution to other threads.
```

2023-01-27 00:22 UTC, jerome-leroux commented on VEEPortingGuide/multiSandbox.rst
> +A small number will give more smooth execution for threads but a slowest installation execution. A large number will make the Core Engine blocking for applying relocations for a faster installation e
```suggestion
A small number will give more smooth execution for threads but a slowest installation execution. A large number will make the Core Engine block for applying relocations but a faster installation execution.
```

2023-01-27 21:37 UTC, jerome-leroux requested changes

2023-01-27 21:37 UTC, jerome-leroux commented on VEEPortingGuide/multiSandbox.rst
> +Feature installation is the process of linking a ``.fo`` file in memory.
I would start with a description of the Feature content with a diagram.
Try to reuse standard types of data:
- Code
- RO Data (instead of resource)
- RW Data (java statics)

![image](https://user-images.githubusercontent.com/20573510/215202919-a6c4418f-6b98-487f-8a5e-a77abb13b527.png)

I would use the term "linking" only for the "apply relocations to code" step. 
I would say something like:
Feature installation is triggered by a call to the [Kernel.install(InputStream)](https://repository.microej.com/javadoc/microej_5.x/apis/ej/kf/Kernel.html#install-java.io.InputStream-) method. It consists of the following steps:
- loading Feature's content from .fo file
- linking Feature's code
- storing Feature's content into the target memory

2023-01-27 21:37 UTC, jerome-leroux commented on VEEPortingGuide/multiSandbox.rst
> +   :scale: 70%
I would do a diagram like this one:
![image](https://user-images.githubusercontent.com/20573510/215203133-e5a1356a-d484-4634-b3da-cd4acf0ddda3.png)
Kernel Code and Core Engine could be added too.
Could be merged with "In-Place Feature Installation Steps" diagram?

2023-01-27 21:37 UTC, jerome-leroux commented on VEEPortingGuide/multiSandbox.rst
> +   :scale: 70%
Proposed draft diagram:
![image](https://user-images.githubusercontent.com/20573510/215203492-7e38d72f-fe70-4d64-832d-959d4e5f8936.png)

2023-03-29 15:52 UTC, frivieremicroej commented on VEEPortingGuide/multiSandbox.rst
> +In-Place Feature installation only applies in RAM: the whole Feature content (code and resources) is allocated in the Kernel Working Buffer.
```suggestion
In-Place Feature installation requires relocations to be applied in RAM: the whole Feature content (code and resources) is allocated in the Kernel Working Buffer. 
```

2023-03-30 16:05 UTC, frivieremicroej commented on VEEPortingGuide/multiSandbox.rst
> +In-Place Feature installation only applies in RAM: the whole Feature content (code and resources) is allocated in the Kernel Working Buffer.
paragraph updated TBD

2023-03-31 06:31 UTC, frivieremicroej commented on VEEPortingGuide/multiSandbox.rst
> +Feature installation is the process of linking a ``.fo`` file in memory.
done for the intro

2023-04-11 13:21 UTC, jerome-leroux requested changes

2023-04-14 14:47 UTC, frivieremicroej commented on VEEPortingGuide/images/multisandbox-link-flow.plantuml
> +participant "Custom\nBSP" as BSP
Let is as is (we are in a deep technical schema)

2023-04-14 14:47 UTC, merged