Feature/m0081 meja 1662 base changelog
MicroEJ/docs pull request #508
Opened 2023-01-25 17:26 UTC by frivieremicroej

2023-01-30 18:53 UTC, jerome-leroux requested changes

2023-01-30 18:53 UTC, jerome-leroux commented on VEEPortingGuide/architecture7Migration.rst
> +As a reminder, refer to the :ref:`Architecture 8.0.0 Changelog <changelog-8.0.0>` section for getting the full list of changes and updates.
```suggestion
As a reminder, refer to the :ref:`Architecture 8.0.0 Changelog <changelog-8.0.0>` section for the complete list of changes and updates.
```

2023-01-30 18:53 UTC, jerome-leroux commented on VEEPortingGuide/architecture7Migration.rst
> +Contact `our support team <https://www.microej.com/contact/#form_2>`_ to get the detailed instructions.
```suggestion
Contact `our support team <https://www.microej.com/contact/#form_2>`_ to get detailed instructions. 
```

2023-01-30 18:53 UTC, jerome-leroux commented on VEEPortingGuide/architecture7Migration.rst
> +The Core Engine sections have been renamed to respect the standard ELF convention. See :ref:`Core Engine Link <core_engine_link>` section.
```suggestion
The Core Engine sections have been renamed to respect the standard ELF convention. See :ref:`Core Engine Link <core_engine_link>` section for further details.
```

2023-01-30 18:53 UTC, jerome-leroux commented on VEEPortingGuide/images/Example-Architecture8.ld
> +    *(.bss.microej.immortals)
Add `.bss.microej.features`?

2023-01-30 18:53 UTC, jerome-leroux commented on VEEPortingGuide/architecture7Migration.rst
> +The following dependency must be added the :ref:`module.ivy <mmm_module_description>` of the VEE Port configuration project:
```suggestion
The following dependency must be added to the :ref:`module.ivy <mmm_module_description>` of the VEE Port configuration project:
```

2023-01-30 18:53 UTC, jerome-leroux commented on VEEPortingGuide/architecture7Migration.rst
> +- or integrate the legacy ECOM-COMM Pack files as-is into your VEE Port ``dropins`` folder,
```suggestion
- or integrate the legacy ECOM-COMM Pack files as-is into your VEE Port ``dropins`` folder.
```

2023-01-30 18:53 UTC, jerome-leroux commented on VEEPortingGuide/architectureChangelog.rst
> +- Removed `LLBSP_isInReadOnlyMemory` in Core Engine Abstraction Layer (`LLBSP.h` file).
Should be added to the migration guide?

2023-01-30 18:53 UTC, jerome-leroux commented on VEEPortingGuide/architectureChangelog.rst
> +- Removed `LLBSP_isInReadOnlyMemory` in Core Engine Abstraction Layer (`LLBSP.h` file).
```suggestion
- Removed ``LLBSP_isInReadOnlyMemory`` in Core Engine Abstraction Layer (``LLBSP.h`` file).
```

2023-02-20 11:10 UTC, frivieremicroej commented on VEEPortingGuide/images/Example-Architecture8.ld
> +    *(.bss.microej.immortals)
done

2023-02-20 11:12 UTC, frivieremicroej commented on VEEPortingGuide/images/Example-Architecture8.ld
> +    *(.rodata.microej.resource.*)
done. fixed .rodata.microej.soar (single section)

2023-02-20 11:19 UTC, frivieremicroej commented on VEEPortingGuide/architectureChangelog.rst
> +- Removed `LLBSP_isInReadOnlyMemory` in Core Engine Abstraction Layer (`LLBSP.h` file).
done

2023-02-20 11:41 UTC, frivieremicroej commented on VEEPortingGuide/images/Example-Architecture8.ld
> +    *(.bss.microej.immortals)
also, the screenshot was not in sync with the shared .ld files

2023-03-06 20:12 UTC, jerome-leroux approved these changes

2023-03-23 16:55 UTC, merged