add HOKA user guide to application developer guide
MicroEJ/docs pull request #532
Opened 2023-03-20 14:48 UTC by akhabali

2023-03-22 08:34 UTC, frivieremicroej requested changes
Almost OK, minor changes requested

2023-03-22 08:34 UTC, frivieremicroej commented on ApplicationDeveloperGuide/index.rst
> +   hokaWebserverUserGuide
Move it under `Networking` section, while keeping the page as-is (you can ask to @fpinel-microej hidden toc tree ?)

2023-03-22 08:34 UTC, frivieremicroej commented on ApplicationDeveloperGuide/hokaWebserverUserGuide.rst
> +Static files
Case sensitive titles (please make a whole pass)
```suggestion
Static Files
```

2023-03-22 08:34 UTC, frivieremicroej commented on ApplicationDeveloperGuide/hokaWebserverUserGuide.rst
> +HOKA Web Server
Link to this page in the `Networking > Add-On Library`  summary table
![image](https://user-images.githubusercontent.com/19801840/226844657-b5772cad-30a7-476b-aeae-ce506cda69e8.png)

2023-03-23 12:17 UTC, fpinel-microej commented on ApplicationDeveloperGuide/index.rst
> +   hokaWebserverUserGuide
I think we had the same issue before, but since the Networking page already has subsections we can't just reorder them with a toctree, best I can do is this (cf image) unless you have a better example of it being done the way you wish.
![image](https://user-images.githubusercontent.com/59691291/227201283-fd352a0a-cadc-491e-a45a-f94b722f9cce.png)

2023-03-23 13:02 UTC, akhabali commented on ApplicationDeveloperGuide/hokaWebserverUserGuide.rst
> +Static files
done

2023-03-23 13:03 UTC, akhabali commented on ApplicationDeveloperGuide/hokaWebserverUserGuide.rst
> +HOKA Web Server
done

2023-03-23 13:51 UTC, akhabali commented
result is here: https://docs.microej.com/en/feature-j0153h-72_hoka_user_guide/ApplicationDeveloperGuide/hokaWebserverUserGuide.html

2023-03-23 14:03 UTC, frivieremicroej requested changes

2023-03-23 14:03 UTC, frivieremicroej commented on ApplicationDeveloperGuide/index.rst
> +   hokaWebserverUserGuide
I want Hoka section after general purpose libraries.
So extract "Foundation Libraries" + "Add-On Libraries" to a new file `networkingLibraries.rst`

2023-03-23 15:09 UTC, akhabali commented
result 
![image](https://user-images.githubusercontent.com/25590305/227247185-cb8e7114-3ab0-4a01-9e89-5bc64fb71fca.png)

2023-03-23 15:14 UTC, akhabali commented
FYI: removed the rest server entry from addon libraries list as it's deprecated and replaced with the new HOKA version

2023-03-23 15:20 UTC, frivieremicroej approved these changes

2023-03-23 15:20 UTC, merged