document how to skip a Gradle task
MicroEJ/docs pull request #533
Opened 2023-03-20 16:09 UTC by denisbedin

2023-03-20 16:49 UTC, tdelhomenie-microej requested changes

2023-03-20 16:49 UTC, tdelhomenie-microej commented on SDK6UserGuide/howtos/gradleSkipTask.rst
> +  The task is never executed.
Isn't there a difference between excluding a task with `-x` and with `project.gradle.startParameter.excludedTaskNames`. I had in mind that when you use `-x` it does exclude the tasks on which the excluded task is dependent. Am I wrong?

2023-03-21 08:20 UTC, denisbedin commented on SDK6UserGuide/howtos/gradleSkipTask.rst
> +  The task is never executed.
I didn't notice this difference between the 2 ways to exclude a task. I tried with the `test` task, that depends on the `testClasses` task, and if I exclude the `test` task, the `testClasses` task is also excluded regardless of the way used to exclude the task (`-x` or  `project.gradle.startParameter.excludedTaskNames`).

2023-03-21 08:26 UTC, tdelhomenie-microej commented on SDK6UserGuide/howtos/gradleSkipTask.rst
> +  The task is never executed.
Right, I don't remember I had this assertion in mind.

2023-03-21 08:26 UTC, tdelhomenie-microej approved these changes

2023-03-21 10:09 UTC, tdelhomenie-microej commented on SDK6UserGuide/howtos/gradleSkipTask.rst
> +The next section describes how you can skip a task, but still execute the tasks on which it depends.
I would remove this line, it is redundant with the next one.

2023-03-21 10:19 UTC, denisbedin commented on SDK6UserGuide/howtos/gradleSkipTask.rst
> +The next section describes how you can skip a task, but still execute the tasks on which it depends.
Done.

2023-03-21 10:28 UTC, merged