Feature/m0078 ddg 308 tutorial debug ui freeze
MicroEJ/docs pull request #54
Opened 2020-07-29 09:49 UTC by thomasponsmicroej

A first proposal for a tutorial on how to debug UI Freeze.

2020-09-11 10:03 UTC, flardy requested changes

2020-09-11 10:03 UTC, flardy commented on Tutorials/tutorialDebugUIFreeze.rst
> +only because it don’t react to input events. Replace the desktop
```suggestion
only because it doesn't react to input events. Replace the desktop
```

2020-12-02 09:18 UTC, gjadi-mej commented
Preview: https://docs.microej.com/en/feature-m0078ddg-308_tutorial_debug_ui_freeze/Tutorials/tutorialDebugUIFreeze.html
PS: you need to rebase on top of master.

2020-12-02 10:15 UTC, tvincent-microej commented on Tutorials/tutorialDebugUIFreeze.rst
> +tasks correctly. Make one of the RTOS task act like a heart beat: create
I think we could also advise the reader to use the debugging features of their C IDE for this part.
Then, as a last resort (i.e. if it's not possible to run the application in debug mode), they can add a new task as described here.

2020-12-02 10:17 UTC, tvincent-microej commented on Tutorials/tutorialDebugUIFreeze.rst
> +a dedicated task and make it report in some way at a regular pace (print
What should be this task's priority? Probably lower or equal than the one dedicated to run the VM?

2020-12-04 15:54 UTC, gjadi-mej commented on Tutorials/tutorialDebugUIFreeze.rst
> +-  When a Java native method executes, it executes its C counterpart
fixed.

2020-12-04 15:54 UTC, gjadi-mej commented on Tutorials/tutorialDebugUIFreeze.rst
> +only because it don’t react to input events. Replace the desktop
fixed.

2020-12-04 15:55 UTC, gjadi-mej commented on Tutorials/tutorialDebugUIFreeze.rst
> +Bottom-Up approach
added.

2020-12-14 15:15 UTC, seonmej commented on Tutorials/tutorialDebugUIFreeze.rst
> +Check RTOS scheduler liveness
```suggestion
Check RTOS Scheduler Liveness
```

2020-12-14 15:18 UTC, seonmej commented on Tutorials/tutorialDebugUIFreeze.rst
> +then it means that the MicroEJ Runtime stopped scheduling the Java
It could also means that the Timer is:
- canceled,
- stuck in the execution of a timer task.

2020-12-14 15:19 UTC, seonmej commented on Tutorials/tutorialDebugUIFreeze.rst
> +This code creates a new Java thread that will print the message ``Alive``
If the standard output cannot be read, suggest to use a LED or another way as in the RTOS section.

2020-12-14 15:22 UTC, seonmej commented on Tutorials/tutorialDebugUIFreeze.rst
> +   Timer timer = new Timer();
If the number of threads available in the platform is fitted to the actual number of threads running, the user have to increment this value in the launch configuration. And it may not be possible if the memory is already full.

2020-12-14 15:23 UTC, seonmej commented on Tutorials/tutorialDebugUIFreeze.rst
> +  suspect native functions and print every entry/exit to detect faulty
`trace` instead of `print`

2020-12-14 15:23 UTC, seonmej commented on Tutorials/tutorialDebugUIFreeze.rst
> +This code creates a new Java thread that will print the message ``Alive``
It may also be a trace system such as system view.

2020-12-14 15:25 UTC, seonmej commented on Tutorials/tutorialDebugUIFreeze.rst
> +   Timer timer = new Timer();
Maybe propose to reuse another thread to add this trace (an existing timer or a thread where these kind of periodic traces are easy to put)

2020-12-14 15:31 UTC, seonmej commented on Tutorials/tutorialDebugUIFreeze.rst
> +   ExecutorService executorService = ServiceLoaderFactory.getServiceLoader().getService(ExecutorService.class, SingleThreadExecutor.class);
Are you sure that we have the ExecutorService implementation? I know we have an Executor one though.

2020-12-14 15:33 UTC, seonmej commented on Tutorials/tutorialDebugUIFreeze.rst
> +will give detailled information about the current state of Java
`detailed` instead of `detailled`.

2020-12-14 16:11 UTC, gjadi-mej commented on Tutorials/tutorialDebugUIFreeze.rst
> +   ExecutorService executorService = ServiceLoaderFactory.getServiceLoader().getService(ExecutorService.class, SingleThreadExecutor.class);
SingleThreadExecutor implements ExecutorService (according to https://repository.microej.com/javadoc/microej_5.x/apis/ej/util/concurrent/SingleThreadExecutor.html)

2020-12-14 16:12 UTC, gjadi-mej commented on Tutorials/tutorialDebugUIFreeze.rst
> +  suspect native functions and print every entry/exit to detect faulty
Fixed. thanks.

2020-12-14 16:13 UTC, gjadi-mej commented on Tutorials/tutorialDebugUIFreeze.rst
> +will give detailled information about the current state of Java
Fixed, thanks.

2020-12-14 16:16 UTC, gjadi-mej commented on Tutorials/tutorialDebugUIFreeze.rst
> +This code creates a new Java thread that will print the message ``Alive``
I added a note to suggest blinking a LED.  I'm reluctant to mention systemview since we don't provide any doc for that (yet).

2020-12-14 16:17 UTC, gjadi-mej commented on Tutorials/tutorialDebugUIFreeze.rst
> +   Timer timer = new Timer();
Good point.

2020-12-14 16:20 UTC, gjadi-mej commented on Tutorials/tutorialDebugUIFreeze.rst
> +   Timer timer = new Timer();
I'm considering adding a new section named `Implementation details` or `Implementation consideration` to put this information, and the other about blinking LED.

My idea is to reduce overloading the debugging process with too many implementation details.
What do you think?

2020-12-14 16:24 UTC, gjadi-mej commented on Tutorials/tutorialDebugUIFreeze.rst
> +a dedicated task and make it report in some way at a regular pace (print
I think it should be higher but I think ~~both~~ all three are worth the test.

- If the RTOS task is of higher priority, we are ensuring that the RTOS scheduler is still scheduling.
- If the RTOS task is of equal priority, we are ensuring that the RTOS scheduler should (theoretically) schedule the VM
- If the RTOS task is of lower priority, we are ensuring that the RTOS scheduler can schedule lower priority tasks. 

WDYT?

2020-12-14 16:25 UTC, thomasponsmicroej commented on Tutorials/tutorialDebugUIFreeze.rst
> +This code creates a new Java thread that will print the message ``Alive``
There is no section about SystemView in the docs, but we already mention SystemView in the documentation and in other tutorials. imho, mentioning it could give the hint that this solution exists and that it has already been used in MicroEJ environments. https://docs.microej.com/en/latest/ApplicationDeveloperGuide/trace.html#trace-implementations

2020-12-14 16:44 UTC, seonmej commented on Tutorials/tutorialDebugUIFreeze.rst
> +   Timer timer = new Timer();
Yep, I agree! With a link (in the form `(1)` for example).

2020-12-14 16:45 UTC, seonmej commented on Tutorials/tutorialDebugUIFreeze.rst
> +   ExecutorService executorService = ServiceLoaderFactory.getServiceLoader().getService(ExecutorService.class, SingleThreadExecutor.class);
Ok, I didn't remember that 👍

2021-01-04 16:43 UTC, gjadi-mej commented on Tutorials/tutorialDebugUIFreeze.rst
> +tasks correctly. Make one of the RTOS task act like a heart beat: create
Added.  I also added that the tutorial assumes the freeze only occurs on device and not on simulator.

2021-01-04 16:43 UTC, gjadi-mej commented on Tutorials/tutorialDebugUIFreeze.rst
> +a dedicated task and make it report in some way at a regular pace (print
I added a paragraph and a diagram about the RTOS priorities. WDYT?

If the diagram is OK I'll redo it with MicroEJ graphic identity.

2021-01-04 16:52 UTC, gjadi-mej commented on Tutorials/tutorialDebugUIFreeze.rst
> +   Timer timer = new Timer();
I added a `Implementation details` section. WDYT?

2021-01-05 08:16 UTC, seonmej commented on Tutorials/tutorialDebugUIFreeze.rst
> +   Timer timer = new Timer();
Perhaps add a link to this section when the user has to create a new thread/timer.

2021-01-05 08:16 UTC, seonmej commented on Tutorials/tutorialDebugUIFreeze.rst
> +- The number of threads in the MicroEJ Application must to be
```suggestion
- The number of threads in the MicroEJ Application must be
```

2021-01-05 08:17 UTC, seonmej commented on Tutorials/tutorialDebugUIFreeze.rst
> +  ``Timer`` and ``Thread``.
Do we have a section in the main documentation that explain how to configure the threads? It could be linked from here.

2021-01-05 08:20 UTC, seonmej commented on Tutorials/tutorialDebugUIFreeze.rst
> +  ``Timer`` and ``Thread``.
Such as `Category: Memory` in https://docs.microej.com/en/latest/ApplicationDeveloperGuide/applicationOptions.html#category-runtime

2021-06-17 08:21 UTC, gjadi-mej commented on Tutorials/tutorialDebugUIFreeze.rst
> +- The number of threads in the MicroEJ Application must to be
added

2021-06-17 08:21 UTC, gjadi-mej commented on Tutorials/tutorialDebugUIFreeze.rst
> +  ``Timer`` and ``Thread``.
added

2021-06-17 08:22 UTC, gjadi-mej commented on Tutorials/tutorialDebugUIFreeze.rst
> +   Timer timer = new Timer();
added

2021-06-17 08:27 UTC, gjadi-mej commented on Tutorials/tutorialDebugUIFreeze.rst
> +This code creates a new Java thread that will print the message ``Alive``
added

2021-08-31 09:03 UTC, tvincent-microej commented on Tutorials/tutorialDebugUIFreeze.rst
> +           Display.getDefaultDisplay().callSerially(new Runnable() {
This doesn't work anymore with MicroUI3.

```suggestion
           MicroUI.callSerially(new Runnable() {
```

2021-11-29 12:29 UTC, gjadi-mej commented
Closing this PR.  The development occurs now in #334

2021-11-29 12:29 UTC, closed without merging