Feature/m0078 ddg 534 document kf enabled libraries introduction with security manager
MicroEJ/docs pull request #554
Opened 2023-04-26 16:28 UTC by frivieremicroej

2023-04-27 09:37 UTC, acolleux-microej commented on KernelDeveloperGuide/kfEnabledLibraries.rst
> +- it implements and internal global state: lazy initialization of a singleton, registry of callbacks, internal cache, ...,
```suggestion
- it implements an internal global state: lazy initialization of a singleton, registry of callbacks, internal cache, ...,
```

2023-04-27 09:37 UTC, acolleux-microej commented on KernelDeveloperGuide/kfEnabledLibraries.rst
> +   </kernel>
Where should we put this code ?

2023-05-17 15:10 UTC, frivieremicroej commented on KernelDeveloperGuide/kfEnabledLibraries.rst
> +   </kernel>
done

2023-05-22 15:57 UTC, jerome-leroux requested changes

2023-05-22 15:57 UTC, jerome-leroux commented on KernelDeveloperGuide/kfEnabledLibraries.rst
> +A stateless library is Multi-Sandbox enabled by default: it can be embedded by the Kernel and its APIs directly exposed to Features without code modification.
```suggestion
Otherwise, the library is called a stateless library.
A stateless library is Multi-Sandbox enabled by default: it can be embedded by the Kernel, and its APIs are directly exposed to Features without code modification.
```

2023-05-22 15:57 UTC, jerome-leroux commented on KernelDeveloperGuide/kfEnabledLibraries.rst
> +Context Local Storage for static fields is typically used when the Library defines a lazy initialized singleton.
```suggestion
Context Local Storage for static fields is typically used when the library defines a lazy initialized singleton. 
```

2023-05-22 15:57 UTC, jerome-leroux commented on KernelDeveloperGuide/kfEnabledLibraries.rst
> +The reason is that the Core Engine rejects the assignment of a Feature object in a static field or an instance field owned by the Kernel.
```suggestion
The reason is that the Core Engine rejects assigning a Feature object in a static field or an instance field owned by the Kernel.
```

2023-05-22 15:57 UTC, jerome-leroux commented on KernelDeveloperGuide/kfEnabledLibraries.rst
> +- ``KernelObservable``: Implementation of Observable which can handle observers from any Module.
```suggestion
- ``KernelObservable``: Implementation of Observable that can handle observers from any Module.
```

2023-05-31 12:26 UTC, jerome-leroux approved these changes

2023-05-31 15:13 UTC, merged