fix multiple VEE Ports error message in runOnSimulator page
MicroEJ/docs pull request #555
Opened 2023-04-27 09:39 UTC by denisbedin

2023-04-28 06:33 UTC, tdelhomenie-microej requested changes

2023-04-28 06:33 UTC, tdelhomenie-microej commented on SDK6UserGuide/runOnSimulator.rst
> +   The 'veePort' property must be set to the unique name of one of the following VEE Ports:
We don't explain how to set this property. We should add somewhere that it can be set with `-PveePort=<veePortName>`.

2023-04-28 10:01 UTC, denisbedin commented on SDK6UserGuide/runOnSimulator.rst
> +   The 'veePort' property must be set to the unique name of one of the following VEE Ports:
I modified the error message to indicate how to set the property.

2023-04-28 10:19 UTC, tdelhomenie-microej requested changes

2023-04-28 10:19 UTC, tdelhomenie-microej commented on SDK6UserGuide/runOnSimulator.rst
> +   A VEE Port must be selected using the 'veePort' property ('-PveePort="veePortName"').The following VEE Ports are available:
```suggestion
   A VEE Port must be selected using the 'veePort' property ('-PveePort="veePortName"'). The following VEE Ports are available:
```

2023-05-02 07:35 UTC, tdelhomenie-microej approved these changes

2023-05-02 08:05 UTC, merged