Minor fixes in tutorial "Create a MicroEJ Firmware From Scratch":
MicroEJ/docs pull request #586
Opened 2023-05-24 22:38 UTC by jerome-leroux

- Fix numbered list
- Fix reference to a properties file
- Fix link to commit

2023-05-25 06:19 UTC, frivieremicroej requested changes

2023-05-25 06:19 UTC, frivieremicroej commented on Tutorials/tutorialCreateFirmwareFromScratch.rst
> +  :caption: https://github.com/MicroEJ/FreeRTOS/commit/eb208d846f52c0695c06456b540e412ba96e640a
I see other more recent commits in the branch
![image](https://github.com/MicroEJ/docs/assets/19801840/20356ec4-06db-4754-a520-b74e0267b8e7)

why not updating to the latest commit of the branch ?

2023-05-25 11:46 UTC, jerome-leroux commented on Tutorials/tutorialCreateFirmwareFromScratch.rst
> +  :caption: https://github.com/MicroEJ/FreeRTOS/commit/eb208d846f52c0695c06456b540e412ba96e640a
The tutorial explains the changes step by step with a specific commit for each step.

For example, the commit "Add end symbol for sbrk()" is referenced later in the tutorial.

2023-05-26 06:28 UTC, frivieremicroej commented on Tutorials/tutorialCreateFirmwareFromScratch.rst
> +  :caption: https://github.com/MicroEJ/FreeRTOS/commit/eb208d846f52c0695c06456b540e412ba96e640a
OK

2023-05-26 06:28 UTC, frivieremicroej approved these changes

2023-05-26 06:36 UTC, merged