document the Gradle Wrapper
MicroEJ/docs pull request #617
Opened 2023-06-01 15:14 UTC by denisbedin

https://docs.microej.com/en/feature-microej-sdk-6-wrapper/

2023-06-01 15:20 UTC, tdelhomenie-microej requested changes

2023-06-01 15:20 UTC, tdelhomenie-microej commented on SDK6UserGuide/buildExecutable.rst
> +    $ gradlew buildExecutable
This will not work in Linux environments. If we use `./gradlew ...`, does it work in Windows?

2023-06-01 15:20 UTC, tdelhomenie-microej commented on SDK6UserGuide/createProject.rst
> +The SDK is only compatible with the Gradle version ``8.0.2`` or higher, so ensure that the :ref:`sdk_6_create_project_gradle_wrapper` uses the right version :
I would instead add a sentence below the 2 bullets to say "If you want to know more about the Gradle Wrapper, go to the section ...". WDYT?

2023-06-02 08:31 UTC, denisbedin commented on SDK6UserGuide/createProject.rst
> +The SDK is only compatible with the Gradle version ``8.0.2`` or higher, so ensure that the :ref:`sdk_6_create_project_gradle_wrapper` uses the right version :
I agree, I added a sentence.

2023-06-02 08:32 UTC, denisbedin commented on SDK6UserGuide/buildExecutable.rst
> +    $ gradlew buildExecutable
I added `./gradlew` to all command lines.

2023-06-02 12:46 UTC, tdelhomenie-microej approved these changes

2023-06-02 12:47 UTC, merged