Origin/architecture 8/build files
MicroEJ/docs pull request #630
Opened 2023-06-09 08:11 UTC by bguedas

2023-06-16 12:20 UTC, frivieremicroej requested changes
I'm also rewording in // of these changes

2023-06-16 13:04 UTC, bguedas commented on ApplicationDeveloperGuide/buildOutputFiles.rst
> +      .. figure:: images/build-output-files_arch8.png
Done

2023-06-16 14:05 UTC, bguedas commented on ApplicationDeveloperGuide/buildOutputFiles.rst
> +      .. figure:: images/build-output-files.png
Done

2023-06-21 15:01 UTC, frivieremicroej approved these changes

2023-06-21 15:01 UTC, merged