Feature/m0081 meja 2203 remove installed features
MicroEJ/docs pull request #631
Opened 2023-06-09 11:05 UTC by frivieremicroej

Remove System Applications

System Applications built by the SDK are never used and removed from
Architecture 8.
Replaced by the name "pre-installed Applications", especially in the Virtual Device.

Also full update of Kernel Overview & Kernel creation pages (flow of
schematics, glossary).

2023-06-12 18:22 UTC, jerome-leroux commented
Several warning when building the documentation:
```

ApplicationDeveloperGuide/heapdumper_use.rst:12: CRITICAL: Title level inconsistent:

Option(browse): Executable file
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ApplicationDeveloperGuide/heapdumper_use.rst:24: CRITICAL: Title level inconsistent:

Option(list): Feature files
^^^^^^^^^^^^^^^^^^^^^^^^^^^
ApplicationDeveloperGuide/heapdumper_use.rst:38: CRITICAL: Title level inconsistent:

Option(browse): Heap memory file
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ApplicationDeveloperGuide/heapdumper_use.rst:49: CRITICAL: Title level inconsistent:

Option(list): Memory files
^^^^^^^^^^^^^^^^^^^^^^^^^^
ApplicationDeveloperGuide/heapdumper_use.rst:64: CRITICAL: Title level inconsistent:

Option(text): Heap file name
^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

Probably related to that, a new section appears in the ToC:
![image](https://github.com/MicroEJ/docs/assets/20573510/84c8f7c5-5780-4edd-ac0f-9be138c984ad)

2023-06-12 19:14 UTC, jerome-leroux requested changes

2023-06-12 19:14 UTC, jerome-leroux commented on KernelDeveloperGuide/overview.rst
> +   :alt: Kernel Build Flow
It is not clear how the "Pre-installed applications" are used. From my understanding, it is only for the Virtual Device. If it is the case, it should be stated clearly.

2023-07-03 09:41 UTC, frivieremicroej commented on ApplicationDeveloperGuide/sectionArchitectureOptions.rst
> -*Default value*: ``true``
This option was introduced for legacy static Features and was not modifying the SOAR for a while => just remove it

2023-07-03 09:57 UTC, frivieremicroej commented on ApplicationDeveloperGuide/sectionArchitectureOptions.rst
> -Group: Static Features
Added the removal to the header changelog with a linked to Feature persistency section.
there is no need to document a more detailed step by step migration guide.

2023-07-03 09:58 UTC, frivieremicroej commented on KernelDeveloperGuide/kernelLink.rst
> -Firmware Linker
Added the removal to the header changelog

2023-07-03 10:18 UTC, frivieremicroej commented on KernelDeveloperGuide/overview.rst
> +   :alt: Kernel Build Flow
You are right. As this is an overview schematic, I remove the notion of pre-installed applications that is not important at this step. It is explained further in the Virtual Device builder.

2023-07-03 16:39 UTC, jerome-leroux requested changes

2023-07-03 16:39 UTC, jerome-leroux commented on ApplicationDeveloperGuide/heapdumper_use.rst
> +^^^^^^^^^^^^^^^^^^^^^^^^^^^
Indenting is not the same:
```suggestion
'''''''''''''''''''''''''''
```

2023-07-03 16:39 UTC, jerome-leroux commented on ApplicationDeveloperGuide/heapdumper_use.rst
> +Specify the full path of Feature files (``.fodbg`` files).
```suggestion
Specify the full path of Feature files with debug information (``.fodbg`` files).
```

2023-07-03 16:39 UTC, jerome-leroux commented on ApplicationDeveloperGuide/heapdumper_use.rst
> +Dynamic Features table, ...).
```suggestion
Specify the full path of additional memory files in Intel Hex format (Installed Feature areas,
Dynamic Features table, ...).
```

2023-07-03 16:39 UTC, jerome-leroux commented on KernelDeveloperGuide/applicationLink.rst
> +The Feature ``.fo`` file can be deployed on Device using `Kernel.install()`_ method.
```suggestion
The Feature ``.fo`` file can be deployed to the Device using `Kernel.install()`_ method.
```

2023-07-03 16:39 UTC, jerome-leroux commented on ApplicationDeveloperGuide/virtualDevice.rst
>  The Virtual Device includes the same custom MicroEJ Core, libraries and
```suggestion
The Virtual Device includes the same custom MicroEJ Core, libraries, and
```

2023-07-03 16:39 UTC, jerome-leroux commented on KernelDeveloperGuide/gettingStarted.rst
> +A MicroEJ Demo Flavor is a composition of a set of runtime services, pre-installed Applications and a given MicroEJ Runtime Environment. Any flavor can be customized with MicroEJ SDK for a specific p
```suggestion
A MicroEJ Demo Flavor is a composition of a set of runtime services, pre-installed Applications, and a given MicroEJ Runtime Environment. Any flavor can be customized with MicroEJ SDK for a specific product.
```

2023-07-03 16:39 UTC, jerome-leroux commented on KernelDeveloperGuide/kernelCreation.rst
> +It is possible to build the Executable using :ref:`concepts-microejlaunches` rather than the regular module build.
```suggestion
It is possible to build the Executable using a :ref:`concepts-microejlaunches` rather than the regular module build.
```

2023-07-05 08:52 UTC, merged