Document the buildVirtualDevice task
MicroEJ/docs pull request #655
Opened 2023-07-07 10:09 UTC by denisbedin

https://docs.microej.com/en/feature-microej-sdk-6-buildvirtualdevice-task/

2023-07-07 11:43 UTC, tdelhomenie-microej commented
@denisbedin The documentation describes correctly how to build a VD, but we don't describe exactly what is a VD, in which case we have to build a VD, ... I think it is too early to start a new page explaining what is a VD since it is quickly changing, but we should at least add a link in an introduction sentence to the current VD page https://docs.microej.com/en/feature-microej-sdk-6-buildvirtualdevice-task/ApplicationDeveloperGuide/virtualDevice.html.
Also we should start a Reference page somewhere in SDK6 section which describes precisely what is the structure of a VD.

2023-07-11 09:59 UTC, bguedas requested changes

2023-07-11 09:59 UTC, bguedas commented on SDK6UserGuide/appendix/virtualDevice.rst
> +- the ``javaLibs/`` folder, that contains the Generic Foundation Libraries.
```suggestion
- the ``javaLibs/`` folder, that contains the Foundation Libraries which are common to MICROJVM and S3
```

2023-07-11 09:59 UTC, bguedas commented on SDK6UserGuide/appendix/virtualDevice.rst
> +The Virtual Device contains the Simulation part files of the VEE Port used to build it:
as for JavaDoc, only capitalize the first letter and end with a dot if the item is a proper sentence. See https://www.grammarly.com/blog/bullet-points/

2023-07-11 09:59 UTC, bguedas commented on SDK6UserGuide/appendix/virtualDevice.rst
> +- the ``s3/`` folder.
```suggestion
- the ``S3/`` folder, that contains the Simulator, HIL and Foundation Libraries specific to the Simulator 
```

2023-07-11 09:59 UTC, bguedas commented on SDK6UserGuide/appendix/virtualDevice.rst
> +- the ``MICROJVM/javaLibs/`` folder, that contains the Foundation Libraries specific to the MicroEJ Core Engine.
I think that there should only be one entry for MICROJVM (as for S3). You can explain that it only contains files from VEE Port that are needed for building .fo files

2023-07-11 09:59 UTC, bguedas commented on SDK6UserGuide/appendix/virtualDevice.rst
> +- The ``scripts/init-vd/vd-init.xml`` script that allows to enable or not the Virtual Device. If the Virtual Device is not enabled, the Application main class specified by the user is launched on the
```suggestion
- the ``scripts/init-vd/vd-init.xml`` script, that allows to enable or not the Virtual Device. If the Virtual Device is not enabled, the Application main class specified by the user is launched on the VEE Port
```

2023-07-11 09:59 UTC, bguedas commented on SDK6UserGuide/appendix/virtualDevice.rst
> +- a Kernel Application, whose WPK file is extracted in the ``main-application`` folder of the Virtual Device.
```suggestion
- a Kernel Application, whose WPK file is extracted in the ``main-application`` folder of the Virtual Device
```

2023-07-11 09:59 UTC, bguedas commented on SDK6UserGuide/buildVirtualDevice.rst
> +
empty line

2023-07-11 09:59 UTC, bguedas commented on SDK6UserGuide/buildVirtualDevice.rst
> +  It must be set to the Full Qualified Name of the Application main class, for example::
```suggestion
  It must be set to the fully qualified name of the Application main class, for example::
```

2023-07-11 09:59 UTC, bguedas commented on SDK6UserGuide/buildVirtualDevice.rst
> +If you want to add the property in IntelliJ IDEA :
```suggestion
If you want to add the property in IntelliJ IDEA: 
```

2023-07-11 10:53 UTC, denisbedin commented on SDK6UserGuide/buildVirtualDevice.rst
> +
Fixed.

2023-07-11 10:53 UTC, denisbedin commented on SDK6UserGuide/appendix/virtualDevice.rst
> +The Virtual Device contains the Simulation part files of the VEE Port used to build it:
I fixed the bulleted lists.

2023-07-11 10:54 UTC, denisbedin commented on SDK6UserGuide/appendix/virtualDevice.rst
> +- the ``MICROJVM/javaLibs/`` folder, that contains the Foundation Libraries specific to the MicroEJ Core Engine.
Done.

2023-07-12 15:00 UTC, merged