Create Foundation Library JUnit Test Suite
MicroEJ/docs pull request #659
Opened 2023-07-18 12:01 UTC by jcourcelmicroej

2023-07-20 11:28 UTC, gjadi-mej requested changes
Please see my comments.

I was able to create a test suite and a test suite runner to execute the tests on SIM.

2023-07-20 11:28 UTC, gjadi-mej commented on VEEPortingGuide/platformQualification.rst
> +To create the Test Suite module, click on: ``File > New > Module Project``
Please use guilabel instead.

```suggestion
To create the Test Suite module, click on: :guilabel:`File` > :guilabel:`New` > :guilabel:`Module Project`
```

2023-07-20 11:28 UTC, gjadi-mej commented on VEEPortingGuide/platformQualification.rst
> +Your skeleton project is created and ready to be setup.
It would be nice to have a screenshot of the IDE with the explorer showing the tree of the project.

2023-07-20 11:28 UTC, gjadi-mej commented on VEEPortingGuide/platformQualification.rst
> +To create the Test Suite module, click on: ``File > New > Module Project``
Also, `Module Project` does not exist as is. One has to go into File > New > Project... then select MicroEJ > Module Project (SDK Dist 23.07)

2023-07-20 11:28 UTC, gjadi-mej commented on VEEPortingGuide/platformQualification.rst
> +The console output for this test should be:
Please explain how to run the test or point to the relevant documentation if any.

2023-07-20 11:28 UTC, gjadi-mej commented on VEEPortingGuide/platformQualification.rst
> +Add a ``module.ant`` file at the root of the Test Suite project with the following content:
With that content, I have the following error:
```
Description	Resource	Path	Location	Type
Target resources-std:copy-test-resources does not exist in this project	module.ant	/mytests	line 2	Ant Buildfile Problem
```

Please add a note to say to ignore the error or maybe there is a way to fix it?

2023-07-20 11:28 UTC, gjadi-mej commented on VEEPortingGuide/platformQualification.rst
> +  - ``{PROJECT_LOC}/validation/microej-testsuite-common.properties``: see `microej-testsuite-common.properties template <https://github.com/MicroEJ/VEEPortQualificationTools/blob/2.9.0/tests/core/jav
Please clarify the `PROJECT_LOC`, what does it refer to?

2023-07-20 11:28 UTC, gjadi-mej commented on VEEPortingGuide/platformQualification.rst
> +- Edit the module ``ivy-module > info > build`` node to add the ``testsuite`` keyword to ``microej.lib.name`` and ``rip.printableName``, for example:
Why is this needed?
In my tests, I had to remove the `-testsuite` from the dependency name in the module.ivy of the testsuite runner. Which seems normal since the name of my module doesn't have `testsuite` in it.

2023-08-28 14:27 UTC, jcourcelmicroej commented on VEEPortingGuide/platformQualification.rst
> +To create the Test Suite module, click on: ``File > New > Module Project``
```suggestion
To create the Test Suite module, click on: :guilabel:`File` > :guilabel:`New` > :guilabel:`Project...` then select :guilabel:`MicroEJ` > :guilabel:`Module Project`
```

2023-08-28 14:28 UTC, jcourcelmicroej commented on VEEPortingGuide/platformQualification.rst
> +To create the Test Suite module, click on: ``File > New > Module Project``
Update done

2023-08-28 14:30 UTC, jcourcelmicroej commented on VEEPortingGuide/platformQualification.rst
> +Then, create two test source folders, right-click on your project and click on: ``New > Source Folder``.
```suggestion
Then, create two test source folders, right-click on your project and click on: :guilabel:`New` > :guilabel:`Source Folder`.
```

2023-08-28 14:45 UTC, jcourcelmicroej commented on VEEPortingGuide/platformQualification.rst
> +Your skeleton project is created and ready to be setup.
Screenshot added

2023-08-31 13:34 UTC, jcourcelmicroej commented on VEEPortingGuide/platformQualification.rst
> +Add a ``module.ant`` file at the root of the Test Suite project with the following content:
I don't see any errors on the `module.ant` file on my side (tested with MicroEJ SDK 23.07). Can you attach a screenshot please ?

2023-08-31 13:43 UTC, jcourcelmicroej commented on VEEPortingGuide/platformQualification.rst
> +- Edit the module ``ivy-module > info > build`` node to add the ``testsuite`` keyword to ``microej.lib.name`` and ``rip.printableName``, for example:
Documentation updated

2023-09-01 09:40 UTC, gjadi-mej commented on VEEPortingGuide/platformQualification.rst
> +Add a ``module.ant`` file at the root of the Test Suite project with the following content:
![image](https://github.com/MicroEJ/docs/assets/50209055/ce72e5e2-9583-4f73-99b3-10e0fc9e1cc8)

I am using Dist 21.11 with SDK 5.8.0.

2023-09-01 09:44 UTC, gjadi-mej commented
Please rebase your work on top of master.

2023-09-04 09:50 UTC, jcourcelmicroej commented
> Please rebase your work on top of master.

Rebase on top master done.

2023-09-04 14:16 UTC, gjadi-mej approved these changes

2023-09-22 09:19 UTC, frivieremicroej requested changes
Please review and merge https://github.com/MicroEJ/docs/pull/734

2023-10-04 09:42 UTC, frivieremicroej approved these changes

2023-10-04 10:02 UTC, merged