Feature/m0224 fl 124 add event queue pack
MicroEJ/docs pull request #667
Opened 2023-07-27 07:23 UTC by cblanchard-microej

Add the documentation on the use of the event pack.

2023-07-27 08:28 UTC, jerome-leroux submitted a review, later dismissed

2023-07-27 08:28 UTC, jerome-leroux commented on VEEPortingGuide/eventQueue.rst
> +- `Extended data`: data for extended events. (Length bytes)
```suggestion
- `Extended` (1 bit): event's kind flag (0 for non-extended event, 1 for extended event).
- `Type` (7 bits): event's type, which allows to find the corresponding event listener.
- `Length` (24 bits): length of the data in bytes (for extended events only).
- `Data` (24 bits): non-extended event's data (for non-extended events only).
- `Extended data` (``Length`` bytes): extended event's data (for extended events only).
```

2023-07-27 08:28 UTC, jerome-leroux commented on VEEPortingGuide/eventQueue.rst
> +A listener can be registered for several event types, but each event type can only have one listener.
```suggestion
The same listener can be registered for several event types, but each event type can only have one listener. 
```

2023-07-27 08:28 UTC, jerome-leroux commented on VEEPortingGuide/eventQueue.rst
> +You can create your Event listener by implementing the EventListener interface.
```suggestion
You can create your Event listener by implementing the ``EventListener`` interface. 
```

2023-07-27 08:28 UTC, jerome-leroux commented on VEEPortingGuide/eventQueue.rst
> +Then you can register your listener using the ``registerListener(EventListener listener, int type)`` method from the EventQueue API.
```suggestion
Then you can register your listener using the ``registerListener(EventListener listener, int type)`` method from the ``EventQueue`` class. 
```

2023-07-27 08:28 UTC, jerome-leroux commented on VEEPortingGuide/eventQueue.rst
> +To set the defaultListener, you must use ``setDefaultListener(EventListener listener)`` from the EventQueue API.
```suggestion
To set the defaultListener, you must use ``setDefaultListener(EventListener listener)`` from the ``EventQueue`` class. 
```

2023-07-27 08:28 UTC, jerome-leroux commented on VEEPortingGuide/eventQueue.rst
> +To send a non-extended event through the Event Queue using the Java API, you must use the ``offerEvent(int type, int data)`` method from the EventQueue API.
```suggestion
To send a non-extended event through the Event Queue using the Java API, you must use the ``offerEvent(int type, int data)`` method from the ``EventQueue`` class.
```

2023-07-27 08:28 UTC, jerome-leroux commented on VEEPortingGuide/eventQueue.rst
> +Extended events are events that can not stand on 32 bits.
```suggestion
Extended events are events with data that can not be stored on 24 bits.
```

2023-07-27 08:28 UTC, jerome-leroux commented on VEEPortingGuide/eventQueue.rst
> +- The length of the data in bytes stands on 24 bits.
```suggestion
- The length of the data in bytes stored on 24 bits.
```

2023-07-27 11:57 UTC, cblanchard-microej commented on VEEPortingGuide/eventQueue.rst
> +The Event Queue Foundation Library allows users to send events from the native world to the Java world. It is composed of a Java API that provides mechanisms to register specific event notifications
Done

2023-07-27 11:57 UTC, cblanchard-microej commented on VEEPortingGuide/eventQueue.rst
> +A FIFO mechanism is implemented on the native side and is system specific. The user can offer events to this FIFO by using the native or the Java API.
Done

2023-07-27 11:57 UTC, cblanchard-microej commented on VEEPortingGuide/eventQueue.rst
> +Event notifications are handled using event listeners (Observer design pattern). The application code has to register event listeners to the event handler (provided by the Foundation Library) to be n
Done

2023-07-27 11:57 UTC, cblanchard-microej commented on VEEPortingGuide/eventQueue.rst
> +Then the queue retrieves new events pushed in the FIFO and notifies the application and the event listeners.
Done

2023-07-27 11:57 UTC, cblanchard-microej commented on VEEPortingGuide/eventQueue.rst
> +Only integers (4 bytes) are sent through the FIFO, so there are two kinds of events that can be sent over the Event Queue:
Done

2023-07-27 11:57 UTC, cblanchard-microej commented on VEEPortingGuide/eventQueue.rst
> +Only integers (4 bytes) are sent through the FIFO, so there are two kinds of events that can be sent over the Event Queue:
Done

2023-07-27 11:57 UTC, cblanchard-microej commented on VEEPortingGuide/eventQueue.rst
> +- Extended event: an event that does not fit on 4 bytes.
Done

2023-07-27 11:57 UTC, cblanchard-microej commented on VEEPortingGuide/eventQueue.rst
> +- `Extended data`: data for extended events. (Length bytes)
Done

2023-07-27 11:57 UTC, cblanchard-microej commented on VEEPortingGuide/eventQueue.rst
> +A listener can be registered for several event types, but each event type can only have one listener.
Done

2023-07-27 11:57 UTC, cblanchard-microej commented on VEEPortingGuide/eventQueue.rst
> +You can create your Event listener by implementing the EventListener interface.
Done

2023-07-27 11:57 UTC, cblanchard-microej commented on VEEPortingGuide/eventQueue.rst
> +Before registering your listener, you must get a valid type using the ``getNewType()`` method from EventQueue API.
Done

2023-07-27 11:57 UTC, cblanchard-microej commented on VEEPortingGuide/eventQueue.rst
> +Then you can register your listener using the ``registerListener(EventListener listener, int type)`` method from the EventQueue API.
Done

2023-07-27 11:57 UTC, cblanchard-microej commented on VEEPortingGuide/eventQueue.rst
> +To set the defaultListener, you must use ``setDefaultListener(EventListener listener)`` from the EventQueue API.
Done

2023-07-27 11:57 UTC, cblanchard-microej commented on VEEPortingGuide/eventQueue.rst
> +Non-extended events are events that can stand on 32 bits.
Done

2023-07-27 11:58 UTC, cblanchard-microej commented on VEEPortingGuide/eventQueue.rst
> +Then there is the event type that stands on 7 bits.
Done

2023-07-27 11:58 UTC, cblanchard-microej commented on VEEPortingGuide/eventQueue.rst
> +It stands on 24 bits.
Done

2023-07-27 11:58 UTC, cblanchard-microej commented on VEEPortingGuide/eventQueue.rst
> +There are two ways to send a non-extended event through the Event Queue: from the native API or the Java API.
Done

2023-07-27 11:58 UTC, cblanchard-microej commented on VEEPortingGuide/eventQueue.rst
> +To send a non-extended event through the Event Queue using the native API, you must use the ``LLEVENT_offerEvent(int32_t type, int32_t data)`` method from LLEVENT.h.
Done

2023-07-27 11:58 UTC, cblanchard-microej commented on VEEPortingGuide/eventQueue.rst
> +To send a non-extended event through the Event Queue using the Java API, you must use the ``offerEvent(int type, int data)`` method from the EventQueue API.
Done

2023-07-27 11:58 UTC, cblanchard-microej commented on VEEPortingGuide/eventQueue.rst
> +Extended events are events that can not stand on 32 bits.
Done

2023-07-27 11:58 UTC, cblanchard-microej commented on VEEPortingGuide/eventQueue.rst
> +- The event type that stands on 7 bits,
Done

2023-07-27 11:58 UTC, cblanchard-microej commented on VEEPortingGuide/eventQueue.rst
> +- The length of the data in bytes stands on 24 bits.
Done

2023-07-27 11:58 UTC, cblanchard-microej commented on VEEPortingGuide/eventQueue.rst
> +To process the data from an extended event, you will use the EventDataReader API.
Done

2023-07-27 11:58 UTC, cblanchard-microej commented on VEEPortingGuide/eventQueue.rst
> +With EventDataReader API, there is two way to read an event:
Done

2023-07-27 14:24 UTC, cblanchard-microej commented on VEEPortingGuide/eventQueue.rst
> +
Done, is the example comprehensive enough?
[Example](https://github.com/MicroEJ/docs/blob/8a96d3b324e605aa4b409195129d90396ab3ef74/VEEPortingGuide/eventQueue.rst?plain=1#L113)

2023-07-27 14:24 UTC, cblanchard-microej commented on VEEPortingGuide/eventQueue.rst
> +It will call the default listener if no listener corresponds to the event type.
I had the followiing lines: 

Before registering your listener, you must get a valid unique type using the ``getNewType()`` method from the ``EventQueue`` class.
Then you can register your listener using the ``registerListener(EventListener listener, int type)`` method from the ``EventQueue`` class.

2023-07-27 14:25 UTC, cblanchard-microej commented on VEEPortingGuide/eventQueue.rst
> +   int type = 1;
I added the following comment to the example: 

` // Assuming that event_type has been passed from the Java world through a native method after registering your listener.`

2023-07-27 14:26 UTC, cblanchard-microej commented on VEEPortingGuide/eventQueue.rst
> +   int type = 1;
I added the following comment to the example: 

`   // Assuming that eventType has been stored in the Java world when you registered the listener.`

2023-08-01 18:51 UTC, rlouedec-microej commented on VEEPortingGuide/eventQueue.rst
> +It will call the default listener if no listener corresponds to the event type.
That does not explain that you should pass the type to your native stack for it to be able to send events of that type.

2023-08-01 20:37 UTC, rlouedec-microej requested changes

2023-08-01 20:37 UTC, rlouedec-microej commented on VEEPortingGuide/eventQueue.rst
> +To handle a non-extended event, you must implement your listener's ``handleEvent(int type, int data)`` method.
Typo:
```suggestion
To handle a short event, you must implement your listener ``handleEvent(int type, int data)`` method. 
```

2023-08-01 20:37 UTC, rlouedec-microej commented on VEEPortingGuide/eventQueue.rst
> +For example:
This is unclear: the example does not refer to what precedes (the listener registration).

2023-08-01 20:37 UTC, rlouedec-microej commented on VEEPortingGuide/eventQueue.rst
> +- The length of the data in bytes stored on 24 bits.
What does the length represents ? (number of bytes ? bits ? including the header ?)

2023-08-01 20:37 UTC, rlouedec-microej commented on VEEPortingGuide/eventQueue.rst
> +   - This is useful when the extended data you send through the Event Queue is a C structure with multiple fields.
I would not say "it is useful" but rather "it is designed for".
To user something else than a C struct may be difficult actually.

2023-08-01 20:37 UTC, rlouedec-microej commented on VEEPortingGuide/eventQueue.rst
> +There are two ways to send an extended event through the Event Queue: from the native API or the Java API.
```suggestion
There are two ways to send an extended event through the Event Queue: from the C API or the Java API. 
```

2023-08-01 20:37 UTC, rlouedec-microej commented on VEEPortingGuide/eventQueue.rst
> +   }
I would suggest to have a complete example:
```suggestion
EventQueue queue = EventQueue.getInstance();
int type = queue.getNewType();
initialize(type);
queue.registerListener(type, new EventQueueListener() {
	@Override
	public void handleEvent(int type, int data) {
		throw new RuntimeException();
	}
	@Override
	public void handleExtendedEvent(int type, EventDataReader eventDataReader) {
		int x = 0;
		int y = 0;
		int z = 0;

		try {
			x = eventDataReader.readInt();
			y = eventDataReader.readInt();
			z = eventDataReader.readInt();
		} catch (IOException e) {
			System.out.println("IOException while reading accelerometer values from the EventDataReader.");
		}

		System.out.println("Accelerometer values: X = " + x + ", Y = " + y + ", Z = " + z + ".");
	}
});
```

2023-08-01 20:37 UTC, rlouedec-microej commented on VEEPortingGuide/eventQueue.rst
> +
```suggestion
To simulate event that are normally sent through through the C API, use the Event Queue Mock API from your mock.
```

2023-08-01 20:37 UTC, rlouedec-microej commented on VEEPortingGuide/eventQueue.rst
> +The Event Queue Mock API must be added to the :ref:`module.ivy <mmm_module_description>` of the MicroEJ
```suggestion
The Event Queue Mock API dependency must be added to the :ref:`module.ivy <mmm_module_description>` of your MicroEJ 
```

2023-08-01 20:37 UTC, rlouedec-microej commented on VEEPortingGuide/eventQueue.rst
> +In the Platform configuration project, (``-configuration`` suffix), add
At this point of the VPDG, readers should be aware of the terminology used here.
```suggestion
In the VEE Port configuration project, add
```

2023-08-01 20:37 UTC, rlouedec-microej commented on VEEPortingGuide/eventQueue.rst
> +The Platform project must be rebuilt (:ref:`platform_build`).
At this point of the VPDG, readers should be aware of implications of modying the configuration project.
```suggestion
```

2023-08-01 20:37 UTC, rlouedec-microej commented on VEEPortingGuide/eventQueue.rst
> +.. _Event Queue API Module: https://repository.microej.com/modules/ej/api/
```suggestion
.. _Event Queue API Module: https://repository.microej.com/modules/ej/api/event-queue/
```

2023-08-01 20:37 UTC, rlouedec-microej commented on VEEPortingGuide/index.rst
> +   eventQueue
IMO, most parts of what is documented here should be in the ADG rather than VPDG. (although other sections have the same issue as of now)

2023-08-02 15:02 UTC, cblanchard-microej commented on VEEPortingGuide/eventQueue.rst
> +.. figure:: images/event-queue-overview.png
Done

2023-08-02 15:02 UTC, cblanchard-microej commented on VEEPortingGuide/images/event-queue-architecture.png
Done

2023-08-02 18:20 UTC, rlouedec-microej commented on VEEPortingGuide/images/event-queue-overview.png
Can you align the event queue thread representation with previous schema ? (rounded corners)

2023-08-02 18:20 UTC, rlouedec-microej commented on VEEPortingGuide/images/event-queue-architecture.png
Pushing data to FIFO from an interrupt handler may not be possible depending on the FIFO backend.
But I would suggest to add this use case and use a footnote to explain the limitation.

2023-08-02 18:20 UTC, rlouedec-microej commented on VEEPortingGuide/eventQueue.rst
> +   - This is designed for when the extended data you send through the Event Queue is a C structure with multiple fields.
Rephrase suggestion:
```suggestion
   - The reader is designed to parse C-struct data.
```

2023-08-02 18:20 UTC, rlouedec-microej commented on VEEPortingGuide/eventQueue.rst
> +To simulate event that are normally sent through through the C API, use the Event Queue Mock API from your mock.
Typo:
```suggestion
To simulate event that are normally sent through the C API, use the Event Queue Mock API from your mock.
```

2023-08-02 18:20 UTC, rlouedec-microej commented on VEEPortingGuide/eventQueue.rst
> +.. figure:: images/event-queue-overview.png
For the last bullet, there are still only 1-N numberings in the architecture schema.
I would suggest to use A-Z for event listeners and 1-N for threads & events.

2023-08-03 15:26 UTC, rlouedec-microej reviewed
Here are suggestion for the wording of sections links.

2023-08-03 15:26 UTC, rlouedec-microej commented on ApplicationDeveloperGuide/eventQueue.rst
> +To add it to your VEE Port, please follow :ref:`Event Queue <pack_event>` instructions.
```suggestion
To use this API, your VEE Port must implement a compatible version. Please refer to the :ref:`VEE Porting Guide <pack_event>` to port the Event Queue for your project.
```

2023-08-22 12:56 UTC, jerome-leroux commented on VEEPortingGuide/images/event-queue-architecture.png
Upon reflection, event should be able to be sent from an interrupt. This is an important feature that would limit the usability of the library if it is not available.
How can we ensure it is the case?

2023-08-22 18:20 UTC, rlouedec-microej commented on VEEPortingGuide/images/event-queue-architecture.png
I agree.

For that, we would need an interrupt-compatible FIFO.
This use case is not limited to the event queue pack (I know we discussed about that for the serial communication as well).
It may be a good opportunity to make a generic C module for an interrupt-compatible FIFO (lock-free & atomic, or based on interrupt locking, or restrict to 1 publisher / 1 consumer...).

> How can we ensure it is the case?

To test it, we would need to generate an interrupt that use this FIFO.
This is at the very least specific to the VEE Port (if it is even possible).
We could make a native for VEE port developers to implement for the test suite to generate the interrupt.

2023-08-23 21:18 UTC, jerome-leroux commented on VEEPortingGuide/images/event-queue-architecture.png
Let's just add a note in the documentation saying the event can be sent from an interrupt if the implementation in the VEE Port allows it.
Create a ticket to add full support for interrupt: update LLAPI documentation (`LLEVENT_IMPL_offer_event`, `LLEVENT_IMPL_offer_extended_event`, ...), add test, update documentation.

2023-08-29 12:48 UTC, rlouedec-microej requested changes

2023-08-29 12:48 UTC, rlouedec-microej commented on ApplicationDeveloperGuide/images/event-queue-architecture.png
Please remove the spelling error line below "interrupt".
BTW, how do you generate the PNG ? Screenshot or export ?

2023-08-29 12:48 UTC, rlouedec-microej commented on ApplicationDeveloperGuide/eventQueue.rst
> +   Events can not be sent from the Interrupt Handler unless the VEE Port implementation allows it.
Can we reword into a positive statement ?

```suggestion
   To support sending events from the Interrupt Handler, the VEE Port must provide a compatible implementation.
```

2023-08-29 15:16 UTC, rlouedec-microej approved these changes

2023-09-06 15:48 UTC, rlouedec-microej commented on VEEPortingGuide/images/event-queue-architecture.png
Note added and Internal ticket created (M0224FL-148)

2023-09-06 15:54 UTC, merged