Improve Shared Interface documentation
MicroEJ/docs pull request #671
Opened 2023-08-09 23:05 UTC by rlouedec-microej

2023-08-10 17:08 UTC, rlouedec-microej commented
Links to the Shared Interface examples repository will be added when it is published.

2023-08-17 08:38 UTC, frivieremicroej requested changes

2023-08-17 08:38 UTC, frivieremicroej commented on KernelDeveloperGuide/featuresCommunication.rst
> +
```suggestion
* an API for a first Application to register its Share Interface, and for a second Application to get a proxy on it
* a set of registered Kernel types converters
```

2023-08-17 14:36 UTC, rlouedec-microej commented on ApplicationDeveloperGuide/sandboxedAppSharedInterface.rst
> +Shared Interface Definition
Done in: 43ba03c7459c6088a618ae070fe5216a715ddf10

Should I apply this to more section titles ?

2023-08-17 14:36 UTC, rlouedec-microej commented on ApplicationDeveloperGuide/sandboxedAppSharedInterface.rst
> +Shared Interface Definition
Applied in: 43ba03c7459c6088a618ae070fe5216a715ddf10

2023-08-28 08:48 UTC, frivieremicroej commented
@rlouedec-microej updated & approved this MR.
The documentation is up-to-date with the current version of the GREEN Firmware. 
It will be need to be updated after the registry usage refactor (https://youtrack.cross/issue/J0095K-1404/Switch-from-Wadapps-shared-registry-to-ejservice)

2023-08-28 08:58 UTC, merged