M0269MD-233 Debug GUI Performances Issues
MicroEJ/docs pull request #674
Opened 2023-08-11 16:03 UTC by apineau-microej

2023-08-21 09:09 UTC, levMicroej commented on Tutorials/tutorialDebugGUIperformancesIssues.rst
> +- Drawing of the UI
Drawing of the UI:

2023-08-28 12:26 UTC, gjadi-mej requested changes
Please use a spellchecker and/or Grammarly to check the writing.

2023-08-28 12:26 UTC, gjadi-mej commented on Tutorials/tutorialDebugGUIperformancesIssues.rst
> +This document explains how to debug Graphical User Interface performances issues. It describes common pitfalls that can affect GUI performances, provides tools that allow to detect performances issue
```suggestion
This document explains how to debug Graphical User Interface performance issues. It describes common pitfalls that can affect GUI performances and provides tools to detect performance issues and how to solve them.

```

2023-08-28 12:26 UTC, gjadi-mej commented on Tutorials/tutorialDebugGUIperformancesIssues.rst
> +Before using more advanced UI debugging techniques, the global application code quality should be reviewed. An overall good code quality will help to get good UI performances. It will help getting mo
```suggestion
Before using more advanced UI debugging techniques, the global application code quality should be reviewed. Good code quality will help to get good UI performances. It will help to have more efficient code and allow easier debugging and maintenance.

```

2023-08-28 12:26 UTC, gjadi-mej commented on Tutorials/tutorialDebugGUIperformancesIssues.rst
> +Here is a list of documents or tools that help improving the quality of application code:
```suggestion
Here is a list of documents or tools that help improve the quality of application code:

```

2023-08-28 12:26 UTC, gjadi-mej commented on Tutorials/tutorialDebugGUIperformancesIssues.rst
> +- The :ref:`Get Started With GUI<tutorial_get_started_with_gui>` tutorial provides guidelines to start developping an efficient GUI.
```suggestion
- The :ref:`Get Started With GUI<tutorial_get_started_with_gui>` tutorial provides guidelines to develop efficient GUI.

```

2023-08-28 12:26 UTC, gjadi-mej commented on Tutorials/tutorialDebugGUIperformancesIssues.rst
> +- The `SonarQube™<https://github.com/MicroEJ/ExampleTool-Sonar>`_ source code quality analyzer allows to analyze an Application or Library code quality.
```suggestion
- The `SonarQube™<https://github.com/MicroEJ/ExampleTool-Sonar>`_ source code quality analyzer to analyze an Application or Library code quality.

```

2023-08-28 12:26 UTC, gjadi-mej commented on Tutorials/tutorialDebugGUIperformancesIssues.rst
> +Using the latest UI libraries (MicroUI, MWT, Widget, etc) available may solve some performances issues. The most recent UI libraries fix some bugs that may affect performance and they provide tools/l
```suggestion
The latest UI libraries (MicroUI, MWT, Widget, etc.) may solve some performance issues. The most recent UI libraries fix some bugs that may affect performance and provide tools/libraries to implement more performant UIs.

```

2023-08-28 12:36 UTC, levMicroej commented on Tutorials/tutorialDebugGUIperformancesIssues.rst
> +- Uses Memory debugging tools:
```suggestion
- Uses memory debugging tools:

```

2023-08-28 12:36 UTC, levMicroej commented on Tutorials/tutorialDebugGUIperformancesIssues.rst
> +- Drawing of the UI
```suggestion
- Drawing of the UI:

```

2023-08-30 09:10 UTC, apineau-microej commented on Tutorials/tutorialDebugGUIperformancesIssues.rst
> +  - MWT processing (layout of widgets and widget rendering process)
Fixed

2023-08-30 09:14 UTC, apineau-microej commented on Tutorials/tutorialDebugGUIperformancesIssues.rst
> +The format of UI resources should be chosen according to the usecase. Choosing the best resource format will reduce memory consumption and reduce drawing time.
Changed

2023-08-30 09:14 UTC, apineau-microej commented on Tutorials/tutorialDebugGUIperformancesIssues.rst
> +Keeping the widget hierarchy as simple as possible will help reducing the "MWT processing" part time. Improving the widgets hierarchy design may help reducing the number of widgets or the number of t
Fixed

2023-08-30 09:14 UTC, apineau-microej commented on Tutorials/tutorialDebugGUIperformancesIssues.rst
> +- Uses Memory debugging tools:
Fixed

2023-08-30 09:14 UTC, apineau-microej commented on Tutorials/tutorialDebugGUIperformancesIssues.rst
> +- Drawing of the UI
Fixed

2023-08-30 09:15 UTC, apineau-microej commented
> Please use a spellchecker and/or Grammarly to check the writing.

Writing checked and issue fixed

2023-09-04 09:31 UTC, apineau-microej commented on Tutorials/tutorialDebugGUIperformancesIssues.rst
> +MCUs and SoCs may have access to various hardware IPs to speedup the UI. Be sure your UI port exploit all of them.
```suggestion
MCUs and SoCs may have access to various hardware IPs to speedup the UI. Be sure your UI port exploits all of them.

```

2023-09-04 09:39 UTC, apineau-microej commented on Tutorials/tutorialDebugGUIperformancesIssues.rst
> +Check that the flush policy selected is the best according your hardware capabilities. Generally, the best flush policy is the switch mode.
```suggestion
Check that the flush policy selected is the best according to your hardware capabilities. Generally, the best flush policy is the switch mode.

```

2023-09-04 09:39 UTC, apineau-microej commented on Tutorials/tutorialDebugGUIperformancesIssues.rst
> +Please always prefer the fastest RAM whenever its size allow it.
```suggestion
Please always prefer the fastest RAM whenever its size allowd it.

```

2023-09-04 09:40 UTC, apineau-microej commented on Tutorials/tutorialDebugGUIperformancesIssues.rst
> +In a MCU, you may have the choice between different types of RAM that have different properties in terms of quantity and speed.
```suggestion
In an MCU, you may have the choice between different types of RAM that have different properties in terms of quantity and speed.

```

2023-09-04 09:41 UTC, apineau-microej commented on Tutorials/tutorialDebugGUIperformancesIssues.rst
> +For example, during the back copy if the flush policy is switch or during your flush if your display is driven through SPI (if there is a DMA dedicated to the SPI port).
```suggestion
For example, during the back copy if the flush policy is switched or during your flush if your display is driven through SPI (if there is a DMA dedicated to the SPI port).

```

2023-09-04 09:42 UTC, apineau-microej commented on Tutorials/tutorialDebugGUIperformancesIssues.rst
> +For more information about flush policy, please read our documentation about :ref:`section_display`.
```suggestion
For more information about the flush policy, please read our documentation about :ref:`section_display`.

```

2023-09-04 09:42 UTC, apineau-microej commented on Tutorials/tutorialDebugGUIperformancesIssues.rst
> +Another point to watch in this field is the amount of other tasks that are running in the same time than the UI task.
```suggestion
Another point to watch in this field is the amount of other tasks that are running at the same time than the UI task.

```

2023-09-04 09:43 UTC, apineau-microej commented on Tutorials/tutorialDebugGUIperformancesIssues.rst
> +Ensure that your project is configured to bring the best performances with compiling optimization options correctly setup.
```suggestion
Ensure that your project is configured to bring the best performances with compiling optimization options correctly set up.

```

2023-09-04 09:44 UTC, apineau-microej commented on Tutorials/tutorialDebugGUIperformancesIssues.rst
> +Regardless the GUI application in development, it may be possible that the rootcause of low performances of the GUI is located at the low-level of the system.
```suggestion
Regardless of the GUI application in development, it may be possible that the root cause of low performances of the GUI is located at the low-level of the system.

```

2023-09-11 11:39 UTC, apineau-microej commented on Tutorials/tutorialDebugGUIperformancesIssues.rst
> +This document explains how to debug Graphical User Interface performances issues. It describes common pitfalls that can affect GUI performances, provides tools that allow to detect performances issue
I removed the "s" from "performances" but did not applied the other suggestions as the writing is already correct.

2023-09-11 11:41 UTC, apineau-microej commented on Tutorials/tutorialDebugGUIperformancesIssues.rst
> +Before using more advanced UI debugging techniques, the global application code quality should be reviewed. An overall good code quality will help to get good UI performances. It will help getting mo
I replaced "help getting" by "help to get". I kept "An overall good..." as this is correct

2023-09-11 11:41 UTC, apineau-microej commented on Tutorials/tutorialDebugGUIperformancesIssues.rst
> +Here is a list of documents or tools that help improving the quality of application code:
Fixed

2023-09-11 11:43 UTC, apineau-microej commented on Tutorials/tutorialDebugGUIperformancesIssues.rst
> +- The :ref:`Get Started With GUI<tutorial_get_started_with_gui>` tutorial provides guidelines to start developping an efficient GUI.
Fixed

2023-09-11 11:44 UTC, apineau-microej commented on Tutorials/tutorialDebugGUIperformancesIssues.rst
> +- The `SonarQube™<https://github.com/MicroEJ/ExampleTool-Sonar>`_ source code quality analyzer allows to analyze an Application or Library code quality.
Not fixed, the current writing is correct

2023-09-11 11:45 UTC, apineau-microej commented on Tutorials/tutorialDebugGUIperformancesIssues.rst
> +Using the latest UI libraries (MicroUI, MWT, Widget, etc) available may solve some performances issues. The most recent UI libraries fix some bugs that may affect performance and they provide tools/l
Just removed the "s" from "performances" the rest is correct

2023-09-13 12:58 UTC, frivieremicroej requested changes

2023-09-13 12:58 UTC, frivieremicroej commented on Tutorials/tutorialDebugGUIperformancesIssues.rst
> +How to debug GUI performance issue
make a whole pass on capitalized titles => https://docs.cross/howto/conventions.html#corporate-guidelines
```suggestion
How to Debug GUI Performance Issue

```

2023-09-18 09:28 UTC, merged