Added a global list of build types per SDK version and added the list of latest buildtypes added per each SDK changelog entry
MicroEJ/docs pull request #676
Opened 2023-08-17 16:04 UTC by gjadi-mej

I didn't fill the build types for SDK 5.0.1 because the tag Easyant4Eclipse v2.1.1 is missing.

2023-08-17 16:20 UTC, tdelhomenie-microej requested changes

2023-08-17 16:20 UTC, tdelhomenie-microej commented on SDKUserGuide/sdkChangeLog.rst
>  - Added Gradle dependency line in the generated Javadoc of an artifact repository (``build-artifact-repository`` build type).
Shouldn't this line be under the line `Added build-artifact-repository#3.4.0` ?

2023-08-17 16:20 UTC, tdelhomenie-microej commented on SDKUserGuide/sdkChangeLog.rst
> +- Added build-std-javalib#3.2.0
It is weird to have new version of build types but without content, it seems like we did an upgrade for nothing. Shouldn't we instead have something like:
```
- Fixed ``build-std-javalib`` compilation with JDK 11.
- Fixed Artifact Checker's execution on ``build-std-javalib``.
- Fixed ``build-artifact-repository`` build type which couldn't find the previous release of the repository to merge it.
- Added new build types version:
  - build-addon-processor#2.2.0
  - build-application#9.2.0
  - ...
```
?

2023-08-17 16:20 UTC, tdelhomenie-microej commented on SDKUserGuide/sdkChangeLog.rst
> +------------------
Shouldn't we put this section in a dedicated page instead?

2023-08-18 15:24 UTC, gjadi-mej commented on SDKUserGuide/sdkChangeLog.rst
> +------------------
As said on another channel, this is in the same source file but in a different html chapter in the final rendering (same as SDK Dist and SDK changelogs).

2023-08-18 15:26 UTC, gjadi-mej commented on SDKUserGuide/sdkChangeLog.rst
> +- Added build-std-javalib#3.2.0
I was also thinking about that, but to use the same format for all build type version declaration. To have a dedicated section `Latest Build Type Available`.

WDYT?


(Especially because it may not be true that the change mentioned was done in the version mentioned (e.g. it may have been done in an earlier version and all of them are added but we're only showing the latest)).

2023-08-21 08:36 UTC, tdelhomenie-microej approved these changes

2023-08-21 08:44 UTC, merged