Feature/m0081 meja 154 introduce feature code chunks
MicroEJ/docs pull request #679
Opened 2023-08-18 15:34 UTC by frivieremicroej

2023-08-24 19:48 UTC, jerome-leroux requested changes

2023-08-24 19:48 UTC, jerome-leroux commented on VEEPortingGuide/architecture8Migration.rst
> +The code logic based on a ``malloc/free`` implementation does not need to be changed.
I would add something like this (I am not sure I totally understood the changes):
The Kernel Working Buffer no longer exists, and the Features can no longer be allocated in this buffer. Memory allocation for the Features will now use the function `LLKERNEL_IMPL_allocateFeature()`. The functions `LLKERNEL_IMPL_allocateWorkingBuffer()` and `LLKERNEL_IMPL_freeWorkingBuffer()` have been removed.

2023-08-24 19:48 UTC, jerome-leroux commented on VEEPortingGuide/multiSandbox.rst
>  - the address location where the Feature will be installed,
```suggestion
- the location where the Feature will be installed,
```

2023-08-28 08:02 UTC, frivieremicroej commented
https://docs.microej.com/en/feature-m0081meja-154_introduce_feature_code_chunks/

2023-08-29 13:27 UTC, frivieremicroej commented on VEEPortingGuide/architecture8Migration.rst
> +      return 0;
I rewrote theses LLAPI, here is the latest version.
```
/**
	 * Gets the number of Features that have been installed into memory from a prior execution of this Kernel.
	 * <p>
	 * This function is called once at the start of the Core Engine. Afterward, the Core Engine will retrieve Feature
	 * handles by calling {@link #getFeatureHandle(int)} for each index in the range <code>[0..allocated_features_count[</code>.
	 *
	 * @return the number of Features that have been installed into memory from a prior execution of this Kernel, <code>0</code> if none.
	 * @see #getFeatureHandle(int)
	 */
	public int getAllocatedFeaturesCount();
	
	/**
	 * Gets the handle of a Feature that has been installed into memory from a prior execution of this Kernel.
	 * <p>
	 * This function is called at the start of the Core Engine for each index from <code>0</code> to
	 * <code>{@link IDynamicFeaturesManager#getAllocatedFeaturesCount()}-1</code>.
	 *
	 * @param index
	 *            an index in the range <code>[0..{@link IDynamicFeaturesManager#getAllocatedFeaturesCount()}[</code>
	 * @return a handle that uniquely identifies the Feature located at the specified index, which has been installed into memory from a prior execution of this Kernel.  (<code>0</code> is no a valid handle).
	 * @see #getAllocatedFeaturesCount()
	 */
	public int getFeatureHandle(int index);
```

2023-08-29 13:53 UTC, frivieremicroej commented on VEEPortingGuide/architecture8Migration.rst
> +      f->RAM_area = KERNEL_MALLOC(size_RAM);
done

2023-08-29 13:53 UTC, frivieremicroej commented on VEEPortingGuide/architecture8Migration.rst
> +      struct installed_feature* f = (struct installed_feature*)KERNEL_MALLOC(sizeof(struct installed_feature));
done

2023-08-29 14:00 UTC, frivieremicroej commented on VEEPortingGuide/architecture8Migration.rst
> +The code logic based on a ``malloc/free`` implementation does not need to be changed.
OK, most of of you suggestion added to give more details

2023-09-08 22:28 UTC, jerome-leroux commented on VEEPortingGuide/architecture8Migration.rst
> +   #define KERNEL_AREA_GET_START_ADDRESS(addr, alignment) ((void*)((((int32_t)addr)+alignment-1)&~(alignment-1)))
```suggestion
   #define KERNEL_AREA_GET_MAX_SIZE(size, alignment) ((size)+((alignment)-1))
   #define KERNEL_AREA_GET_START_ADDRESS(addr, alignment) ((void*)((((int32_t)(addr))+(alignment)-1)&~((alignment)-1)))
```

2023-09-08 22:35 UTC, jerome-leroux commented on VEEPortingGuide/multiSandbox.rst
> +Feature installation flow allows to install Features in any byte-addressable memory (including ROM) with a minimum amount of required RAM.
I am not sure about the "byte-addressable" term. One can argue that an external serial flash is "byte-addressable" with a driver.

We should probably use the term "byte-addressable and mapped in the address space of the CPU"?

2023-09-08 22:39 UTC, jerome-leroux requested changes
See previous comments

2023-09-12 11:45 UTC, frivieremicroej commented on VEEPortingGuide/multiSandbox.rst
> +Feature installation flow allows to install Features in any byte-addressable memory (including ROM) with a minimum amount of required RAM.
ok, updated 9b84365aad789f2809770f649c267973e15811cf

2023-09-12 13:18 UTC, jerome-leroux commented on VEEPortingGuide/architectureChangelog.rst
> +- Redesigned Feature installation flow. A Feature can now be installed in any any byte-addressable memory mapped to the CPU's address space, including ROM.
```suggestion
- Redesigned Feature installation flow. A Feature can now be installed in any byte-addressable memory mapped to the CPU's address space, including ROM.
```

2023-09-12 13:19 UTC, jerome-leroux approved these changes

2023-09-12 15:21 UTC, merged