Feature/UI memory
MicroEJ/docs pull request #687
Opened 2023-08-28 11:27 UTC by gbalan-microej

2023-08-28 20:06 UTC, rlouedec-microej requested changes

2023-08-28 20:06 UTC, rlouedec-microej commented on VEEPortingGuide/vgImage.rst
>  The implementation is responsible for the image's lifecycle: allocation and release (already implemented in the :ref:`section_vg_cco`).
```suggestion
For an image loaded from an external memory which is not byte-addressable, its data must be copied into byte-addressable memory before the image can be used for drawings.
By default (see :ref:`section_vg_cco`), the image data is copied into MicroUI :ref:`images_heap`.
```

2023-09-04 05:02 UTC, gbalan-microej commented on VEEPortingGuide/uiFontCore.rst
> +* retrieves font in external memories (:ref:`section_font_loader_memory` loader).
The description has the same look as the image loader (I try to always use the same type of description between the font, image, vg font and vg image modules). For the moment, I'm leaving the commentary as it is, but it may be necessary to reword it for all the chapters.

2023-09-04 05:07 UTC, gbalan-microej commented on VEEPortingGuide/uiImageOverview.rst
> +   the characteristics of the Graphical Engine that are useful to configure the :ref:`section_image_generator`.
Originally, you could choose which modules to install in a VEE Port using the .platform file. In this way, each module described its deps to make sure you got a coherent VEE Port. All the internal modules of the Image module (same for the font module: generator, loader and renderer) had their own "dependencies" chapter like all the other modules (VM etc.).  I've simply moved these chapters into a single chapter.

2023-09-04 05:18 UTC, gbalan-microej commented on VEEPortingGuide/vgFont.rst
> +This option requires an implementation of the :ref:`section_externalresourceloader`.
Once again, this chapter exists to have a similarity between the chapters image, the font, the vg image and the vg font. I've reworded it.

2023-09-04 05:26 UTC, gbalan-microej commented on VEEPortingGuide/vgFont.rst
> +.. note:: The simulator (Front Panel) does not manage the external resources. All images listed in ``*.externresources.list`` files are copied in the external resources folder, and this folder is add
hmm you're right. I have moved this note a dedicated chapter "simulation" (idem for image, font, vg image, vg font)

2023-09-04 05:50 UTC, gbalan-microej commented on VEEPortingGuide/vgFont.rst
> +10. The application can use the font.
i have added a link to your new section "Principle" into the CCO Freetype chapter

2023-09-04 05:54 UTC, gbalan-microej commented on VEEPortingGuide/vgFont.rst
> +The following steps describe how to open an external resource from the application:
maybe, but it's always the same thing: the user wants to read something dedicated to his use case (how to load an external vg font) and making links to a generic section is sometimes disturbing. On the other hand, the microej guy wants generic chapters to simplify the documentation...

2023-09-04 07:03 UTC, gbalan-microej commented on VEEPortingGuide/vgImage.rst
> +The implementation is responsible for the image's lifecycle: allocation and release (already implemented in the :ref:`section_vg_cco`).
only available for MicroVG Over VGLite; doc updated

2023-09-04 07:15 UTC, gbalan-microej commented
@rlouedec-microej I've modified the doc according to your suggestions. Could you take a look at it? I've also corrected something in your new "Principle" chapter (same branch, last commit)

2023-09-05 19:54 UTC, rlouedec-microej commented on VEEPortingGuide/uiFontCore.rst
> +* retrieves font in external memories (:ref:`section_font_loader_memory` loader).
I noticed that, I did comment only for the font section but this should be applied to others as well 👍

2023-09-05 19:57 UTC, rlouedec-microej commented on VEEPortingGuide/uiImageOverview.rst
> +   the characteristics of the Graphical Engine that are useful to configure the :ref:`section_image_generator`.
I understand, I am just taking the opportunity to comment it 😃

2023-09-05 20:03 UTC, rlouedec-microej commented on VEEPortingGuide/vgFont.rst
> +The following steps describe how to open an external resource from the application:
Yeah, I know. There is no good answer..
In my personal opinion, it was generic enough to be moved to another section.
Maybe we could keep a dedicated guide that say:
* "follow the steps in the other section"
* <insert the 3 lasts bullets after>

WDYT?

2023-09-05 20:24 UTC, rlouedec-microej commented on VEEPortingGuide/uiFontCore.rst
> +* retrieves font in external memories (:ref:`section_font_loader_memory` loader).
Thanks for your clarification already.
I suggest further rewording: (clarification of the "and/or" + of the packaging of font data)
```diff
- The Font Loader is a module of the MicroUI runtime that:
- 
- * retrieves font data (precomputed bitmaps of glyphs generated by the :ref:`section_fontgen`) that is ready to be displayed without needing additional runtime memory, 
- * retrieves font data in external memories (:ref:`section_font_loader_memory` loader).
+ The Font Loader is a module of the MicroUI runtime that loads font data (precomputed bitmaps of glyphs) ready to be displayed.
+ The font data must be stored as a resource (in EJF raw format).
+ Typically, these resources are generated by the :ref:`section_fontgen` and embedded as internal resources or loaded from external memories (:ref:`section_font_loader_memory` loader).
```

2023-09-05 20:28 UTC, rlouedec-microej commented on VEEPortingGuide/uiImageOverview.rst
> +   the characteristics of the Graphical Engine that are useful to configure the :ref:`section_image_generator`.
With my understanding, I can suggest:
```diff
- -  Display module (see :ref:`section_display`): This module gives
-    the characteristics of the Graphical Engine that are useful to configure the :ref:`section_image_generator`.
+ -  Display module (see :ref:`section_display`): the characteristics of the target display are used to configure the :ref:`section_image_generator`.
```

2023-09-05 20:35 UTC, rlouedec-microej commented on ApplicationDeveloperGuide/UI/MicroUI/fonts.rst
> +The management of this kind of font may be different than the internal fonts and require a dedicated heap.
Follow up conversation: https://github.com/MicroEJ/docs/commit/b99ccd1182b51f4c7113a32e57aafcc86f1e4b90#r126534929

2023-09-05 20:41 UTC, rlouedec-microej commented on VEEPortingGuide/vgFont.rst
> +10. The application can use the font.
Thanks !

2023-09-05 20:42 UTC, rlouedec-microej commented on VEEPortingGuide/vgImage.rst
> +The implementation is responsible for the image's lifecycle: allocation and release (already implemented in the :ref:`section_vg_cco`).
Perfect !

2023-09-05 20:58 UTC, rlouedec-microej commented on ApplicationDeveloperGuide/UI/MicroUI/images.rst
> +For more detail about the images heap implementation, refers to :ref:`this chapter<section_image_loader_memory>` in the VEE Port Guide.
Typo:
```suggestion
For more details about the images heap implementation, refers to :ref:`this chapter<section_image_loader_memory>` in the VEE Port Guide. 
```

2023-09-05 20:58 UTC, rlouedec-microej commented on ApplicationDeveloperGuide/UI/MicroVG/vectorfont.rst
> +To declare them as :ref:`external resources<vectorfont_external>`, the font files must be declared too in a ``.externresources.list`` file.
This is wrong, right ?
```suggestion
The fonts are decoded at runtime.
They don't need to be pre-processed by some generator tool like MicroUI Fonts.
Vector Font files must be declared as resources in a ``.resources.list`` file available in the classpath (:ref:`chapter.microej.applicationResources`). 
To declare them as :ref:`external resources<vectorfont_external>`, the font files must be declared too in a ``.externresources.list`` file.
```

2023-09-05 20:58 UTC, rlouedec-microej commented on VEEPortingGuide/vgCco.rst
> +   * If the resource is internal, it is opened.
Why ?

AFAIK, if the resource is internal, there is nothing to do.
But it it is external (for example, a file from some FFS), it must be opened first.
Am I wrong ?

2023-09-06 05:23 UTC, gbalan-microej commented on VEEPortingGuide/vgCco.rst
> +   * If the resource is internal, it is opened.
I have the impression that there's something missing for internal fonts, which is why I thought there was a problem: the first line for internal, the second for external... actually not but according to me, it misses something

2023-09-06 05:30 UTC, gbalan-microej commented on VEEPortingGuide/uiFontCore.rst
> +* retrieves font in external memories (:ref:`section_font_loader_memory` loader).
ok (changes accepted) but the intro doesn't look the same as the image loader (https://docs.microej.com/en/latest/VEEPortingGuide/uiImageLoader.html). In fact, it's not a problem, but as I said before, the idea was to use the same convention.

2023-09-06 05:35 UTC, gbalan-microej commented on VEEPortingGuide/vgFont.rst
> +The following steps describe how to open an external resource from the application:
yes and no. Yes because a chapter in this page https://docs.microej.com/en/latest/VEEPortingGuide/externalResourceLoader.html must exist and no because there are some differences specific to the module (image, font, or generic resources): name of the external list file, format etc.

2023-09-06 05:40 UTC, gbalan-microej commented on ApplicationDeveloperGuide/UI/MicroVG/vectorfont.rst
> +To declare them as :ref:`external resources<vectorfont_external>`, the font files must be declared too in a ``.externresources.list`` file.
Sorry, I'd forgotten about this suggestion. Updated.

2023-09-06 15:07 UTC, rlouedec-microej commented on VEEPortingGuide/uiFontCore.rst
> +* retrieves font in external memories (:ref:`section_font_loader_memory` loader).
If you want, we can update it accordingly. Here is a suggestion:
```diff
+ The Image Loader is a module of the MicroUI runtime that loads image data (image size, pixel format & bitmap) ready to be displayed.
+ During the image drawing, the Image Renderer will, if needed, convert the bitmap to target pixel format.
+ The image data must be stored as a resource (in MEJ_IMG raw format, e.g. ``*.png_raw``).
+ For byte-addressable image resources, better performances can be achieved if it is memory aligned (according to the bpp).
+ Typically, these resources are generated by the :ref:`section_image_generator` and embedded as internal resources (in which case it is automatically memory aligned) or loaded from external memories (:ref:`section_image_external_memory` loader).
+ It can also dynamically convert image files (such as PNG) into supported format (see `Image Decoder<image_runtime_decoder>`_) and manage MicroUI :ref:`section_buffered_image` created by the Application.
```

2023-09-07 06:00 UTC, gbalan-microej commented on VEEPortingGuide/vgCco.rst
> +   * If the resource is internal, it is opened.
I understand the points & bullets. The current solution is okay for me. 

But it is not the "issue": when I read your suggestion, I have the impression that bullet # 1 only concerns external resources (even with the addition between brackets). Here's my proposal:

* If the resource is internal (or if it is an external resource located in byte-addressable memory), Freetype library simply retains the resource address (no loading step).
* If the external resource [...]

2023-09-07 06:08 UTC, gbalan-microej commented on VEEPortingGuide/uiFontCore.rst
> +* retrieves font in external memories (:ref:`section_font_loader_memory` loader).
I prefer the bulleted list (list of characteristics, there's a notion of sequence) even if it's not the same as the font loader (because there aren't many bullets actually). What's more, I only want to talk to the image loader, not the image renderer (and the renderer doesn't convert images, the loader does).

2023-09-08 04:46 UTC, gbalan-microej commented on VEEPortingGuide/uiFontCore.rst
> +* retrieves font in external memories (:ref:`section_font_loader_memory` loader).
sorry my mistake: there **no** notion of sequence ! 

this chapter is dedicated to the image loader which is a part of the image enigne. The functional description of the image engine (generator, loader, renderer) is described in the first chapter "overview" https://docs.microej.com/en/latest/VEEPortingGuide/uiImageOverview.html#functional-description

- the generator generates the images
- the loader loads them (manage external resources, call the runtime decoders if it is required, convert to another format on demande)
- the renderer renders

2023-09-08 17:18 UTC, rlouedec-microej commented on VEEPortingGuide/uiFontCore.rst
> +* retrieves font in external memories (:ref:`section_font_loader_memory` loader).
Oh... This diagram is really nice but I have so many questions now...

To keep it short, it presents a 5 steps process: "generator" (although, btw, I am not a fan of the terminology, I would prefer "pre-processor"), "loader", "decoder", "renderer", "drawing".
Whereas the documentation merge loader/decoder and renderer/drawing.

That may be fine but I have no clue what the "renderer" is doing now.
Probably this is because the diagram is about **resource** image format, not **pixel** format.

I suggest we keep this discussion open and address it later.

2023-09-08 17:47 UTC, rlouedec-microej commented on VEEPortingGuide/vgCco.rst
> +   * If the resource is internal, it is opened.
I see, it is not obvious it is is an optional step.
I pushed 3 commits, the last one clarifies that.

2023-09-08 17:47 UTC, rlouedec-microej approved these changes

2023-09-11 04:48 UTC, gbalan-microej commented on VEEPortingGuide/vgCco.rst
> +   * If the resource is internal, it is opened.
ok for me. Just one more thing: maybe you can add a link to the chapter "external resource loader"

>    * Else, if the resource is external from non-byte-addressable memory, the FreeType library is configured to use the  :ref:`external loader<section_externalresourceloader>` to read from that memory.

2023-09-11 04:59 UTC, gbalan-microej commented on VEEPortingGuide/uiFontCore.rst
> +* retrieves font in external memories (:ref:`section_font_loader_memory` loader).
done, see https://youtrack.cross/issue/M0092MEJAUI-2248/doc-UI3-ideas-of-chapters (+ a copy of the discussion in RC)

2023-09-11 12:26 UTC, rlouedec-microej commented on VEEPortingGuide/vgCco.rst
> +   * If the resource is internal, it is opened.
Done in: 5af7719

2023-09-11 14:28 UTC, merged