Add bytecode verifier presentation to application developer guide.
MicroEJ/docs pull request #702
Opened 2023-09-01 07:03 UTC by bguedas

2023-09-04 08:36 UTC, frivieremicroej requested changes

2023-09-04 08:36 UTC, frivieremicroej commented on ApplicationDeveloperGuide/soar.rst
> +   Bytecode Verifier is disabled by default.
@jleroux @bguedas I'm thinking that Bytecode Verifier shall be 
- disabled by default during Executable build (prefer execution speed first: expected trusted code)
- and enabled by default during Feature build (prefere security first , this will not drastically increase the Feature build time)

2023-09-04 08:36 UTC, frivieremicroej commented on ApplicationDeveloperGuide/soar.rst
> +.. _soar_bytecode_verifier:
Missing changelog line to 8.1

2023-09-04 08:36 UTC, frivieremicroej commented on ApplicationDeveloperGuide/soar.rst
> +
Please change the destination branch to architecture8.1

2023-09-04 08:36 UTC, frivieremicroej commented on ApplicationDeveloperGuide/soar.rst
> +.. figure:: images/bytecode_verifier.png
We should simplify this schematic with unsupported languages. TBD

2023-09-04 08:36 UTC, frivieremicroej commented on ApplicationDeveloperGuide/soar.rst
> +Bytecode Verifier is a piece of software that scrutinize the bytecode instructions for adherence to strict rules and constraints.
We may be able to improve the BV intro (using chatgpt ?)

2023-09-05 07:11 UTC, bguedas commented on ApplicationDeveloperGuide/soar.rst
> +   Bytecode Verifier is disabled by default.
I agree

2023-09-05 07:19 UTC, bguedas commented on ApplicationDeveloperGuide/soar.rst
> +
Done

2023-09-07 13:33 UTC, bguedas commented on ApplicationDeveloperGuide/soar.rst
> +.. figure:: images/bytecode_verifier.png
Done

2023-09-07 14:13 UTC, bguedas commented on ApplicationDeveloperGuide/soar.rst
> +.. _soar_bytecode_verifier:
Added

2023-09-07 14:14 UTC, bguedas commented on ApplicationDeveloperGuide/soar.rst
> +Bytecode Verifier is a piece of software that scrutinize the bytecode instructions for adherence to strict rules and constraints.
Any suggestion?

2023-09-14 15:25 UTC, frivieremicroej approved these changes

2023-09-14 16:11 UTC, jerome-leroux requested changes

2023-09-14 16:11 UTC, jerome-leroux commented on ApplicationDeveloperGuide/soar.rst
> +Bytecode Verifier is the tool that scrutinize the bytecode instructions for adherence to strict rules and constraints.
```suggestion
Bytecode Verifier is the tool that scrutinizes the bytecode instructions for adherence to strict rules and constraints.
```

2023-09-14 16:11 UTC, jerome-leroux commented on ApplicationDeveloperGuide/soar.rst
> +- Access Control: Verifying that class access and method invocations adhere to Java's access control rules, ensuring data encapsulation and security.
```suggestion
- Access Control: Verifying that class accesses and method invocations adhere to Java's access control rules, ensuring data encapsulation and security.
```

2023-09-14 16:11 UTC, jerome-leroux commented on ApplicationDeveloperGuide/soar.rst
> +If you wish to integrate an alternative (commercial) implementation, contact `our support team <https://www.microej.com/contact/#form_2>`_  for access to the SOAR interface API and integration instru
Has this message been validated by the governance?

2023-09-14 16:11 UTC, jerome-leroux commented on ApplicationDeveloperGuide/images/link_application_simple.png
Why don't we show the bytecode verifier here?

2023-09-14 16:11 UTC, jerome-leroux commented on ApplicationDeveloperGuide/images/link_executable.png
Why don't we show the bytecode verifier here?

2023-09-15 12:04 UTC, frivieremicroej commented on ApplicationDeveloperGuide/soar.rst
> +If you wish to integrate an alternative (commercial) implementation, contact `our support team <https://www.microej.com/contact/#form_2>`_  for access to the SOAR interface API and integration instru
ok we can remove commercial

2023-09-15 15:11 UTC, frivieremicroej commented on ApplicationDeveloperGuide/images/link_application_simple.png
I prefer not to increase the complexity of the build flow for the general purpose schematics.
Bytecode Verifier is an advance section of the SOAR chapter .

2023-09-15 18:26 UTC, jerome-leroux commented on ApplicationDeveloperGuide/images/link_application_simple.png
ok

2023-09-15 18:27 UTC, jerome-leroux commented on ApplicationDeveloperGuide/images/link_executable.png
ok

2023-09-20 18:02 UTC, jerome-leroux commented on ApplicationDeveloperGuide/soar.rst
> +Starting from :ref:`Architecture 8.1.0 <changelog-8.1.0>`, an implementation, derived from the `Apache BCEL Project <https://commons.apache.org/proper/commons-bcel/>`_, is now included.
It was already the case before 8.1.0.

```suggestion
A default implementation, derived from the `Apache BCEL Project <https://commons.apache.org/proper/commons-bcel/>`_, is included in the SOAR.
```

2023-09-21 14:28 UTC, jerome-leroux approved these changes

2023-09-22 07:20 UTC, merged