Add information on how to debug with IntelliJ and SDK 6.
MicroEJ/docs pull request #728
Opened 2023-09-20 09:01 UTC by bguedas

2023-09-20 09:39 UTC, tdelhomenie-microej requested changes

2023-09-20 09:39 UTC, tdelhomenie-microej commented on SDK6UserGuide/runOnSimulator.rst
> +   .. tab:: IntelliJ IDEA
We must add Android Studio now.

2023-09-20 14:27 UTC, bguedas commented on SDK6UserGuide/runOnSimulator.rst
> +   .. tab:: IntelliJ IDEA
I add "Android Studio /" in the tab's name. i don't have Android Studio installed to check if it's the same, but I guess it is.

2023-09-20 15:08 UTC, gjadi-mej commented on SDK6UserGuide/runOnSimulator.rst
> +   .. tab:: IntelliJ IDEA
Yup, it's the same.

2023-09-21 08:03 UTC, tdelhomenie-microej commented
@bguedas Archi 8.1 minimum for Android Studio / IntelliJ

2023-09-21 08:24 UTC, bguedas commented
> @bguedas Archi 8.1 minimum for Android Studio / IntelliJ

Done.

2023-09-21 10:23 UTC, tdelhomenie-microej approved these changes

2023-09-26 13:47 UTC, jcourcelmicroej approved these changes

2023-09-26 14:52 UTC, merged