SystemView: Fix Bus Hardfault when no JVM is running
MicroEJ/docs pull request #745
Opened 2023-09-29 08:23 UTC by emoreac-microej

Documentation update to provide a fixed implementation of `SYSVIEW_MICROEJ_X_OS_SendTaskList()`

YT: https://youtrack.cross/issue/M0119TD-27/SystemView-Bus-Hardfault-when-no-JVM-is-running

Fixed tested in STM32F7508-DK: https://youtrack.cross/issue/P0234STM32F7508DK-261/Fix-hardfault-when-the-System-View-analysis-is-started-when-the-JVM-is-not-running

2023-10-05 07:14 UTC, jcourcelmicroej requested changes

2023-10-05 07:14 UTC, jcourcelmicroej commented on VEEPortingGuide/systemView.rst
> +        and the include that declares the external variable ``pvMicrojvmCreatedTask``. ``pvMicrojvmCreatedTask`` must be the FreeRTOS task handle
```suggestion
        and the include that declares the external variable ``pvMEJCoreEngineTask``. ``pvMEJCoreEngineTask`` must be the FreeRTOS task handle
```

2023-10-05 07:14 UTC, jcourcelmicroej commented on VEEPortingGuide/systemView.rst
> +            * Consequently, we only allow to call LLMJVM_MONITOR_SYSTEMVIEW_send_task_list() when the current task is the Microjvm.
```suggestion
            * Consequently, we only allow to call LLMJVM_MONITOR_SYSTEMVIEW_send_task_list() when the current task is the MicroEJ Core Engine.
```

2023-10-05 07:14 UTC, jcourcelmicroej commented on VEEPortingGuide/systemView.rst
> +            // Check if the current task handle is the Microjvm task handle. pvMicrojvmCreatedTask is an external variable.
```suggestion
            // Check if the current task handle is the MicroEJ Core Engine task handle. pvMEJCoreEngineTask is an external variable.
```

2023-10-05 07:14 UTC, jcourcelmicroej commented on VEEPortingGuide/systemView.rst
> +            if( xHandle == pvMicrojvmCreatedTask){
```suggestion
            if( xHandle == pvMEJCoreEngineTask){
```

2023-10-05 07:14 UTC, jcourcelmicroej commented on VEEPortingGuide/systemView.rst
> +            * the function LLMJVM_MONITOR_SYSTEMVIEW_send_task_list(). However, if the Microjvm task is created,
```suggestion
            * the function LLMJVM_MONITOR_SYSTEMVIEW_send_task_list(). However, if the MicroEJ Core Engine task is created,
```

2023-10-05 07:14 UTC, jcourcelmicroej commented on VEEPortingGuide/systemView.rst
> +            // Check if the Microjvm task handle is not NULL. pvMicrojvmCreatedTask is an external variable.
```suggestion
            // Check if the MicroEJ Core Engine task handle is not NULL. pvMEJCoreEngineTask is an external variable.
```

2023-10-05 07:14 UTC, jcourcelmicroej commented on VEEPortingGuide/systemView.rst
> +               // The JVM task is running, we execute LLMJVM_MONITOR_SYSTEMVIEW_send_task_list()
```suggestion
               // The MicroEJ Core Engine task is running, we execute LLMJVM_MONITOR_SYSTEMVIEW_send_task_list()
```

2023-10-05 07:14 UTC, jcourcelmicroej commented on VEEPortingGuide/systemView.rst
> +            if( NULL != pvMicrojvmCreatedTask){
```suggestion
            if( NULL != pvMEJCoreEngineTask){
```

2023-10-05 07:14 UTC, jcourcelmicroej commented on VEEPortingGuide/systemView.rst
> +            * the SystemView Software through the J-Link probe. Consequently, the Microjvm task will never call
```suggestion
            * the SystemView Software through the J-Link probe. Consequently, the MicroEJ Core Engine task will never call
```

2023-10-05 07:14 UTC, jcourcelmicroej commented on VEEPortingGuide/systemView.rst
> +               // Launched by the JVM, we execute LLMJVM_MONITOR_SYSTEMVIEW_send_task_list()
```suggestion
               // Launched by the MicroEJ Core Engine, we execute LLMJVM_MONITOR_SYSTEMVIEW_send_task_list()
```

2023-10-05 07:14 UTC, jcourcelmicroej commented on VEEPortingGuide/systemView.rst
> -         void SEGGER_SYSVIEW_Conf(void) {
Why this function has been removed ?

2023-10-05 08:21 UTC, emoreac-microej commented on VEEPortingGuide/systemView.rst
> -         void SEGGER_SYSVIEW_Conf(void) {
It's a mistake during the update, I will put it back.
Thanks for your attention.

2023-10-05 08:24 UTC, emoreac-microej commented
Hi @jcourcelmicroej , thanks for the review.
I applied your feedback.

2023-10-10 08:56 UTC, jcourcelmicroej approved these changes

2023-10-10 08:57 UTC, merged