Feature/m0127 cc 568 tutorial build micro ej firmware
MicroEJ/docs pull request #75
Opened 2020-09-25 15:49 UTC by gjadi-mej

2020-09-25 15:59 UTC, gjadi-mej commented
@thomasponsmicroej You're right about the diagram and "Library repository", unfortunately I was able to find the original file for this image.

2020-09-25 21:24 UTC, jerome-leroux requested changes

2020-09-25 21:24 UTC, jerome-leroux commented on Tutorials/tutorialUnderstandMicroEJFirmwareBuild.rst
> +.. image:: images/build_microej_mono_sandbox_firmware_numbered.PNG
Use schema from https://documentation.cross/share/page/site/m0127customercare/document-details?nodeRef=workspace://SpacesStore/05857911-5344-4c8b-9d02-3b2a34562975

2020-09-25 21:24 UTC, jerome-leroux commented on Tutorials/tutorialUnderstandMicroEJFirmwareBuild.rst
> +    * The public API (``.java`` or ``.h``) change.
```suggestion
    * The public API (``.java`` or ``.h``) changes.
```

2020-09-25 21:24 UTC, jerome-leroux commented on Tutorials/tutorialUnderstandMicroEJFirmwareBuild.rst
> +.. image:: images/qa_resources-v3.png
"MEJ32 Architecture" -> "MicroEJ Architecture"
"MEJ32 Repository" -> "MicroEJ Repository"
"MEJ32 Arch/Compiler" -> "MicroEJ Architecture"

2020-09-25 21:24 UTC, jerome-leroux commented on Tutorials/tutorialUnderstandMicroEJFirmwareBuild.rst
> +A good knowledge of the :ref:`chapter-glossary` is required.
```suggestion
Good knowledge of the :ref:`chapter-glossary` is required.
```

2020-09-25 21:24 UTC, jerome-leroux commented on Tutorials/tutorialUnderstandMicroEJFirmwareBuild.rst
> +The MicroEJ Architectures are distributed into 2 formats:
```suggestion
The MicroEJ Architectures are distributed into two formats:
```

2020-09-25 21:24 UTC, jerome-leroux commented on Tutorials/tutorialUnderstandMicroEJFirmwareBuild.rst
> +The list of supported MicroEJ Architectures can be found here
```suggestion
The supported MicroEJ Architectures are listed here
```

2020-09-25 21:24 UTC, jerome-leroux commented on Tutorials/tutorialUnderstandMicroEJFirmwareBuild.rst
> +Depending on the requirements of the project, the MicroEJ Platform can
```suggestion
Depending on the project's requirements, the MicroEJ Platform can
```

2020-09-25 21:24 UTC, jerome-leroux commented on Tutorials/tutorialUnderstandMicroEJFirmwareBuild.rst
> +be connected in various ways to the BSP, see :ref:`bsp_connection` for
```suggestion
be connected in various ways to the BSP; see :ref:`bsp_connection` for
```

2020-09-25 21:24 UTC, jerome-leroux commented on Tutorials/tutorialUnderstandMicroEJFirmwareBuild.rst
> +  * etc…
```suggestion
  * etc.
```

2020-09-25 21:24 UTC, jerome-leroux commented on Tutorials/tutorialUnderstandMicroEJFirmwareBuild.rst
> +object code) that is linked with the
```suggestion
object code) linked with the
```

2020-09-25 21:24 UTC, jerome-leroux commented on Tutorials/tutorialUnderstandMicroEJFirmwareBuild.rst
> +To import an existing MicroEJ Application as zip project in the SDK:
```suggestion
To import an existing MicroEJ Application as a zipped project in the SDK:
```

2020-09-25 21:24 UTC, jerome-leroux commented on Tutorials/tutorialUnderstandMicroEJFirmwareBuild.rst
> +create, configure and develop a MicroEJ Application.
```suggestion
create, configure, and develop a MicroEJ Application.
```

2020-09-25 21:24 UTC, jerome-leroux commented on Tutorials/tutorialUnderstandMicroEJFirmwareBuild.rst
> +  artifacts (libraries, tools, …), see
```suggestion
  artifacts (libraries, tools, etc.), see
```

2020-09-25 21:24 UTC, jerome-leroux commented on Tutorials/tutorialUnderstandMicroEJFirmwareBuild.rst
> +  https://repository.microej.com/. This repository can also be used as an offline repository, see https://developer.microej.com/central-repository/.
```suggestion
  https://repository.microej.com/. One can also use this repository as an offline repository, see https://developer.microej.com/central-repository/.
```

2020-09-25 21:24 UTC, jerome-leroux commented on Tutorials/tutorialUnderstandMicroEJFirmwareBuild.rst
> +  that can be imported in the workspace (see
```suggestion
  and imported in the workspace (see
```

2020-09-25 21:24 UTC, jerome-leroux commented on Tutorials/tutorialUnderstandMicroEJFirmwareBuild.rst
> +produce the MicroEJ Firmware that will be deployed on the target
```suggestion
produce the MicroEJ Firmware deployed on the target
```

2020-09-28 07:51 UTC, gjadi-mej commented on Tutorials/tutorialUnderstandMicroEJFirmwareBuild.rst
> +  that can be imported in the workspace (see
Disagree. It's the offline repository that can be imported. Not the Central Repository to which the "It" refers to.

2020-09-28 07:55 UTC, gjadi-mej commented on Tutorials/tutorialUnderstandMicroEJFirmwareBuild.rst
> +  https://repository.microej.com/. This repository can also be used as an offline repository, see https://developer.microej.com/central-repository/.
Not in favor of this. We use the passive voice throughout the document, not the active one.

2020-09-28 08:01 UTC, gjadi-mej commented on Tutorials/tutorialUnderstandMicroEJFirmwareBuild.rst
> +.. image:: images/qa_resources-v3.png
Do you know where is located the source of this image? I couldn't find it.

2020-09-28 08:07 UTC, gjadi-mej commented on Tutorials/tutorialUnderstandMicroEJFirmwareBuild.rst
> +in order to build a firmware.
It emphasizes that one has to respect versions and dependencies between components. You can't make a firmware from incompatible components. I'll try to rephrase it.

2020-09-28 09:12 UTC, gjadi-mej commented on Tutorials/tutorialUnderstandMicroEJFirmwareBuild.rst
> +.. image:: images/build_microej_mono_sandbox_firmware_numbered.PNG
Done. Thanks.

2020-09-28 14:21 UTC, gjadi-mej commented on Tutorials/tutorialUnderstandMicroEJFirmwareBuild.rst
> +.. image:: images/qa_resources-v3.png
I redid it. WDYT?

2020-09-28 14:22 UTC, gjadi-mej commented on Tutorials/tutorialUnderstandMicroEJFirmwareBuild.rst
> +in order to build a firmware.
Done. Thoughts on the rephrasing?

2020-09-28 15:37 UTC, gjadi-mej commented
@thomasponsmicroej I redraw the diagram to integrate your suggestion. WDYT?

2020-09-28 16:02 UTC, jerome-leroux commented on Tutorials/tutorialUnderstandMicroEJFirmwareBuild.rst
> +in order to build a firmware.
Good

2020-09-28 16:06 UTC, jerome-leroux commented on Tutorials/tutorialUnderstandMicroEJFirmwareBuild.rst
> +  that can be imported in the workspace (see
Yes

2020-09-28 16:10 UTC, jerome-leroux commented on Tutorials/tutorialUnderstandMicroEJFirmwareBuild.rst
> +  https://repository.microej.com/. This repository can also be used as an offline repository, see https://developer.microej.com/central-repository/.
OK. I tried to remove as much as possible the passive voice from the document.
The active voice can provide more clarity and brevity. Grammarly advises against using the passive voice.

2020-09-28 16:13 UTC, jerome-leroux commented on Tutorials/tutorialUnderstandMicroEJFirmwareBuild.rst
> +.. image:: images/qa_resources-v3.png
Good

2020-09-28 16:22 UTC, jerome-leroux approved these changes

2020-09-29 07:14 UTC, thomasponsmicroej commented
> 
> 
> @thomasponsmicroej I redraw the diagram to integrate your suggestion. WDYT?

ok for me

2020-09-29 07:19 UTC, thomasponsmicroej commented
to continue with repositories naming, why mentionning ivy?  example: "Ivy Repository" in the last section or "Module (Ivy) Repository" in the repository section. I would use "Module repository" everywhere for simplicity and conformance with the glossary. I think we prefer to expose MMM rather than ivy or easyant when possible.

2020-09-29 07:30 UTC, gjadi-mej commented
@thomasponsmicroej I replaced Module Repository + Ivy with MMM in the latest version of the diagram.

2020-09-29 07:31 UTC, merged