document the GC stack size user option
MicroEJ/docs pull request #755
Opened 2023-10-03 10:02 UTC by frivieremicroej

2023-10-03 23:26 UTC, jerome-leroux requested changes

2023-10-03 23:26 UTC, jerome-leroux commented on ApplicationDeveloperGuide/sectionArchitectureOptions.rst
> +using . When the maximum of stack is reached,  depth-first search of alive object GC stack size
?
```suggestion

```

2023-10-03 23:26 UTC, jerome-leroux commented on ApplicationDeveloperGuide/sectionArchitectureOptions.rst
> +Indicates the quantity of items in the :ref:`Garbage Collector <runtime_gc>`'s internal stack.
Some idea to name the stack:
- frontier stack? see https://medium.com/tebs-lab/breadth-first-search-and-depth-first-search-4310f3bf8416
- LIFO buffer?

2023-10-04 11:35 UTC, frivieremicroej commented on ApplicationDeveloperGuide/sectionArchitectureOptions.rst
> +using . When the maximum of stack is reached,  depth-first search of alive object GC stack size
removed

2023-10-04 11:39 UTC, frivieremicroej commented on ApplicationDeveloperGuide/sectionArchitectureOptions.rst
> +Indicates the quantity of items in the :ref:`Garbage Collector <runtime_gc>`'s internal stack.
I understand the potential conflict between threads stack and GC stack (GC is not a thread), but I don't think these proposals are more appropriate.
What about "GC working buffer" ?

2023-10-04 20:28 UTC, jerome-leroux commented on ApplicationDeveloperGuide/sectionArchitectureOptions.rst
> +Indicates the quantity of items in the :ref:`Garbage Collector <runtime_gc>`'s internal stack.
Why not just calling it "GC Mark Stack"?

See the following documents that talk about the same issue:
- https://www.ibm.com/docs/en/ztpf/1.1.0.15?topic=collection-mark-phase
- https://www.ibm.com/docs/en/ztpf/1.1.0.15?topic=phase-mark-stack-overflow
- https://www.ibm.com/support/pages/preventing-mark-stack-overflows-during-garbage-collection-java-sdk

2023-10-11 12:07 UTC, jerome-leroux approved these changes

2023-10-11 12:23 UTC, merged