Feature/m0081 meja 2229 multiapp debug doc
MicroEJ/docs pull request #760
Opened 2023-10-04 11:41 UTC by agazardMicroeJ

2023-10-05 06:43 UTC, frivieremicroej commented
@agazardMicroeJ please rebase the branch

2023-10-05 08:44 UTC, agazardMicroeJ commented
> @agazardMicroeJ please rebase the branch

done

2023-10-05 11:56 UTC, jcourcelmicroej requested changes

2023-10-05 11:56 UTC, jcourcelmicroej commented on ApplicationDeveloperGuide/debuggerProxy.rst
> +The hex files are generated in the same directory as the ``vee-memory-dump.mac`` file.
```suggestion
The ``*.hex`` files are generated in the same directory as the ``vee-memory-dump.mac`` file.
```

2023-10-05 12:00 UTC, jcourcelmicroej commented on ApplicationDeveloperGuide/debuggerProxy.rst
> +    If you have multiple hex files generated in the previous step, you can if you want merge them into a single hex file.
```suggestion
    If you have multiple ``*.hex`` files generated in the previous step, you can if you want merge them into a single ``*.hex`` file.
```

2023-10-05 12:00 UTC, jcourcelmicroej commented on ApplicationDeveloperGuide/debuggerProxy.rst
> +    It will be easier to use a single hex file than multiple files in the Debugger Proxy command line.
```suggestion
    It will be easier to use a single ``*.hex`` file than multiple files in the Debugger Proxy command line.
```
For all mentions, prefer ``*.hex" or "Intel HEX"

2023-10-05 12:00 UTC, jcourcelmicroej commented on ApplicationDeveloperGuide/debuggerProxy.rst
> +    You can run the following shell script to merge all the hex files into a single file called ``all.hex`` for example.
```suggestion
    You can run the following shell script to merge all the ``*.hex`` files into a single file called ``all.hex`` for example.
```
Same as previous comments and proposals

2023-10-05 12:00 UTC, jcourcelmicroej commented on ApplicationDeveloperGuide/debuggerProxy.rst
> +    Make sure to move to the directory where hex files are generated before running the script.
```suggestion
    Make sure to move to the directory where ``*.hex`` files are generated before running the script.
```

2023-10-05 12:05 UTC, jcourcelmicroej commented on ApplicationDeveloperGuide/debuggerProxy.rst
> +    Now, use this single ``all.hex`` file as value to the Debugger Proxy option ``-Ddebugger.out.ihex.path``
Why option is always with ``ihex`` instead of ``hex`` (c.f: ``-Ddebugger.out.ihex.path``) ?

2023-10-06 10:20 UTC, agazardMicroeJ commented on ApplicationDeveloperGuide/debuggerProxy.rst
> +    Now, use this single ``all.hex`` file as value to the Debugger Proxy option ``-Ddebugger.out.ihex.path``
option name renamed to `debugger.out.hex.path`

2023-10-09 15:34 UTC, merged