Feature/UI pack 13.7.0
MicroEJ/docs pull request #761
Opened 2023-10-04 13:37 UTC by gbalan-microej

2023-10-04 13:37 UTC, gbalan-microej commented
it is a draft because the packs are not released / published yet

2023-10-10 07:14 UTC, seonmej requested changes

2023-10-10 07:14 UTC, seonmej commented on ApplicationDeveloperGuide/UI/MicroUI/images.rst
> +   +--------------+------------------------------------+-------------------------------------+
In the same order as the others:
```suggestion
   | ARGB8888_PRE | .. image:: images/transparent.png  | .. image:: images/argb8888.png      |
   +--------------+------------------------------------+-------------------------------------+
   | ARGB4444_PRE | .. image:: images/transparent.png  | .. image:: images/argb4444.png      |
   +--------------+------------------------------------+-------------------------------------+
   | ARGB1555_PRE | .. image:: images/transparent.png  | .. image:: images/argb1555.png      |
   +--------------+------------------------------------+-------------------------------------+
```

2023-10-10 07:14 UTC, seonmej commented on VEEPortingGuide/uiCco.rst
> +* ARGB8888, ARGB1555, and ARGB4444 transparent images may not compatible with some revisions of the VG-Lite GPU. Older GPU revisions do not render transparent images correctly because the pre-multipl
```suggestion
* ARGB8888, ARGB1555, and ARGB4444 transparent images may not be compatible with some revisions of the VG-Lite GPU. Older GPU revisions do not render transparent images correctly because the pre-multiplication of the pixel opacity is not propagated to the pixel color components. To force the hardware rendering for non-premultiplied transparent images when the VG-Lite GPU is not compatible, uncomment the definition of ``VGLITE_USE_GPU_FOR_TRANSPARENT_IMAGES``  in ``ui_vglite_configuration.h``. Note that this limitation does not concern the VG-Lite GPU compatible with non-premultiplied transparent images and the A8/A4 formats.
```

2023-10-10 07:14 UTC, seonmej commented on VEEPortingGuide/uiChangeLog.rst
> +XXX copy/paste from UI Pack
Don't forget this XXX

2023-10-10 07:14 UTC, seonmej commented on VEEPortingGuide/vgChangeLog.rst
> +XXX copy/paste from VG Pack
Don't forget this XXX

2023-10-18 08:46 UTC, gbalan-microej commented on VEEPortingGuide/uiChangeLog.rst
> +XXX copy/paste from UI Pack
yes of course. The changelog will be copied from ui pack to the doc after its publication

2023-10-18 08:47 UTC, gbalan-microej commented on VEEPortingGuide/vgChangeLog.rst
> +XXX copy/paste from VG Pack
I have moved the VG pack commit in another branch; the idea is to be able to perform the publication of the UI Pack without the VG pack (may be both pack will be released at the same time)

2023-10-20 15:27 UTC, microej-sh requested changes

2023-10-20 15:27 UTC, microej-sh commented on ApplicationDeveloperGuide/UI/MicroUI/images.rst
> +   - `ARGB` formats: choose between non-premultiplied formats and premultiplied formats (suffix `_PRE`),
```suggestion
   - `ARGB` formats: choose between non-premultiplied formats and premultiplied formats (suffixed with `_PRE`),
```

2023-10-20 15:27 UTC, microej-sh commented on ApplicationDeveloperGuide/UI/MicroUI/images.rst
> +   - `Ax` formats (pictogram): all bits-per-pixel may not be available.
```suggestion
   - `Ax` formats (pictogram): all bits-per-pixel values may not be available.
```

2023-10-20 15:27 UTC, microej-sh commented on ApplicationDeveloperGuide/UI/MicroUI/images.rst
> +   - avoid formats `Cx`, `ACxx` and `xxx_RLE`: not compatible with the GPU.
```suggestion
   - avoid formats `Cx`, `ACxx` and `xxx_RLE`, which are not compatible with a GPU.
```

2023-10-20 15:27 UTC, microej-sh commented on VEEPortingGuide/uiReleaseNotes.rst
> +The following table describes the compatibility versions between the  MicroEJ UI Packs and the C modules:
There is an extra space.
```suggestion
The following table describes the compatibility versions between the MicroEJ UI Packs and the C modules:
```

2023-11-02 10:57 UTC, microej-sh approved these changes

2023-11-02 11:06 UTC, seonmej approved these changes

2023-11-02 11:07 UTC, merged