Add Getting Started SDK 6 and RT595
MicroEJ/docs pull request #762
Opened 2023-10-04 16:05 UTC by cblanchard-microej

2023-10-05 06:48 UTC, denisbedin requested changes

2023-10-05 06:48 UTC, denisbedin commented on SDK6UserGuide/gettingStarted.rst
> +During this Getting Started, you will learn to run an application in the Virtual Device and on the Device using the MicroEJ SDK 6.
```suggestion
During this Getting Started, you will learn to run an application on the Virtual Device and on the Device using the MicroEJ SDK 6.
```

2023-10-05 06:48 UTC, denisbedin commented on SDK6UserGuide/gettingStarted.rst
> +   If you want to know more about the use of the Demo-Wearable-VG, please have a look at its `Readme <https://github.com/MicroEJ/Demo-Wearable-VG/blob/master/watch-vg/README.md>`__
```suggestion
   If you want to know more about the use of the Demo-Wearable-VG, please have a look at its `Readme <https://github.com/MicroEJ/Demo-Wearable-VG/blob/master/watch-vg/README.md>`__.
```

2023-10-05 06:48 UTC, denisbedin commented on SDK6UserGuide/gettingStarted.rst
> +For this Getting Started, the Demo-Wearable-VG MicroEJ Application will be use. You can download it using the following command::
```suggestion
For this Getting Started, the ``Demo-Wearable-VG`` MicroEJ Application will be use. You can download it using the following command::
```

2023-10-05 06:48 UTC, denisbedin commented on SDK6UserGuide/index.rst
> +   gettingStarted
The Getting started should be at the beginning of the SDK 6 User Guide IMO.

2023-10-09 07:13 UTC, tdelhomenie-microej requested changes

2023-10-09 07:13 UTC, tdelhomenie-microej commented on SDK6UserGuide/gettingStarted.rst
> +Once the firmware is flashed, you should see the Demo-Wearable-VG running on your board.
We should add a screenshot of the Watchface here IMO.
Also we may add a section to explain that the developer can update the code and flash again to start playing with the application code.

2023-10-09 07:13 UTC, tdelhomenie-microej commented on SDK6UserGuide/gettingStarted.rst
> +To follow this Getting Started, all you need is:
Requirements are generally things that should be installed before starting the tutorial. Here we mix requirements and elements that will be installed during the tutorial.

2023-10-09 07:13 UTC, tdelhomenie-microej commented on SDK6UserGuide/gettingStarted.rst
> +
Maybe add a text here to introduce the elements to install, something like "The C toolchain must be installed now, it is composed of the GNU ARM Embedded Toolchain, CMake and Make."?

2023-10-09 07:13 UTC, tdelhomenie-microej commented on SDK6UserGuide/gettingStarted.rst
> +`Make <https://gnuwin32.sourceforge.net/packages/make.htm>`__ is the tool that will generate the executable based on the files generated by CMake. It will also be used to flash the board.
It was not easy to understand how to install it, the Make site is quite confusing, maybe we should summarize what to do exactly here.

2023-10-09 07:13 UTC, tdelhomenie-microej commented on SDK6UserGuide/gettingStarted.rst
> +* MicroEJ SDK 6 installed (check the :ref:`System Requirements <sdk_6_system_requirements>` and your :ref:`JDK Version <sdk_6_java_version>`).
The installation documentation met the developer choose any IDE, we should probably say that IntelliJ IDEA will be used in this tutorial.

2023-10-09 15:24 UTC, cblanchard-microej commented on SDK6UserGuide/gettingStarted.rst
> +During this Getting Started, you will learn to run an application in the Virtual Device and on the Device using the MicroEJ SDK 6.
Done

2023-10-09 15:24 UTC, cblanchard-microej commented on SDK6UserGuide/gettingStarted.rst
> +
Done

2023-10-09 15:24 UTC, cblanchard-microej commented on SDK6UserGuide/gettingStarted.rst
> +`Cmake <https://cmake.org/>`__ is the application used by the build system to generate the firmware.
Done

2023-10-09 15:24 UTC, cblanchard-microej commented on SDK6UserGuide/gettingStarted.rst
> +`Cmake <https://cmake.org/>`__ is the application used by the build system to generate the firmware.
Ok, if it works on your side I can say that it has been tested with version 3.26.5 :wink:

2023-10-09 15:24 UTC, cblanchard-microej commented on SDK6UserGuide/gettingStarted.rst
> +For this Getting Started, the Demo-Wearable-VG MicroEJ Application will be use. You can download it using the following command::
Done in all the Getting Started

2023-10-09 15:24 UTC, cblanchard-microej commented on SDK6UserGuide/gettingStarted.rst
> +In order to execute the Demo-Wearable-VG Application on the Virtual Device, the SDK provides the Gradle ``runOnSimulator`` task.
Done

2023-10-09 15:24 UTC, cblanchard-microej commented on SDK6UserGuide/gettingStarted.rst
> +   If you want to know more about the use of the Demo-Wearable-VG, please have a look at its `Readme <https://github.com/MicroEJ/Demo-Wearable-VG/blob/master/watch-vg/README.md>`__
Done

2023-10-09 15:24 UTC, cblanchard-microej commented on SDK6UserGuide/gettingStarted.rst
> +Flash the application on i.MX RT595 EVK
Done

2023-10-09 15:24 UTC, cblanchard-microej commented on SDK6UserGuide/gettingStarted.rst
> +In order flash the Demo-Wearable-VG Application on i.MX RT595 EVK, the application provides the Gradle ``runOnDevice`` task.
done

2023-10-09 15:38 UTC, cblanchard-microej commented on SDK6UserGuide/index.rst
> +   gettingStarted
Done

2023-11-23 10:13 UTC, tdelhomenie-microej requested changes

2023-11-23 10:13 UTC, tdelhomenie-microej commented on SDK6UserGuide/gettingStartedIMXRT595.rst
> +Please contact `support@microej.com <support@microej.com>`__ to get the code for this demo.
You could add a subject and a body in the email link to make it easier for the user.

2023-11-23 10:13 UTC, tdelhomenie-microej commented on SDK6UserGuide/gettingStartedIMXRT595.rst
> +It will soon be release publicly.
```suggestion
It will soon be released publicly.
```

2023-11-23 10:13 UTC, tdelhomenie-microej commented on SDK6UserGuide/gettingStartedIMXRT595.rst
> +^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Shouldn't it be in the prerequisites instead?

2023-11-23 14:25 UTC, tdelhomenie-microej approved these changes

2023-11-24 09:12 UTC, merged