M0078DDG-546 Add documentation about shared services
MicroEJ/docs pull request #778
Opened 2023-10-13 13:55 UTC by stinlot-microej

2023-10-17 13:05 UTC, acolleux-microej submitted a review, later dismissed

2023-10-17 13:05 UTC, acolleux-microej commented on KernelDeveloperGuide/featuresCommunication.rst
>  proxy.
This section is not really understandable in my point of view.
![image](https://github.com/MicroEJ/docs/assets/75476371/8387505c-51c6-4cae-a350-3c6c893954cf)

Should it be rephrased, or should we add more context ?

2023-10-17 13:05 UTC, acolleux-microej commented on KernelDeveloperGuide/featuresCommunication.rst
> +    and will thrown an exception if used from a feature context.
Should we mention de Kernel API dependency line to add to use it in the kernel ?

2023-10-20 10:08 UTC, stinlot-microej commented on KernelDeveloperGuide/featuresCommunication.rst
> +sharing an instance between features whereas the Shared Services allows to actually register and get these instances once correctly set up.
Yes, I added few line to make it more explicit

2023-10-20 10:09 UTC, stinlot-microej commented on KernelDeveloperGuide/featuresCommunication.rst
> +      To ensure that every type is indeed embedded, make sure that the property ``soar.generate.classnames`` is set to ``true``
You are right, I added a line to explain the usage of type list and noted that using this property means footprint impact

2023-10-20 10:10 UTC, stinlot-microej commented on KernelDeveloperGuide/featuresCommunication.rst
>  retrieve instances of shared interface: a KF service registry.
It is indeed shared registry but I am wondering if at the beginning we should specify each notion:
- registry
- shared interface
- shared services
- service
...

We use a lot of different terms and their meaning may not be understood by everyone

2023-10-20 10:11 UTC, stinlot-microej commented on KernelDeveloperGuide/featuresCommunication.rst
>  proxy.
I actually moved that in a section which is more about implementing its own registry implementation, this is actually already done in our kf-impl

2023-10-20 10:12 UTC, stinlot-microej commented on KernelDeveloperGuide/featuresCommunication.rst
> +    and will thrown an exception if used from a feature context.
I don't quite get your question, what Kernel API line should we add to use it in the Kernel ?
ServiceRegistryKF is the implementation from kf-util, it is not supposed to be used outside the Kernel, we should not put it in Kernel api, unless I miss understood your question ?
Maybe theses lines are not clear enough

2023-10-20 13:40 UTC, acolleux-microej commented on KernelDeveloperGuide/featuresCommunication.rst
> +      To ensure that every type is indeed embedded, make sure that the property ``soar.generate.classnames`` is set to ``true``
The same thing is written in the next section: Communication between Kernel and Feature
Should it also be updated?

![image](https://github.com/MicroEJ/docs/assets/75476371/75feade5-4774-4c15-bcc1-f1285489d1a6)

2023-10-20 13:41 UTC, acolleux-microej commented on KernelDeveloperGuide/featuresCommunication.rst
>  retrieve instances of shared interface: a KF service registry.
Yes, I think it would be interesting to define those notions

2023-10-20 13:46 UTC, acolleux-microej commented on KernelDeveloperGuide/featuresCommunication.rst
> +    and will thrown an exception if used from a feature context.
Ok, I misread this part of the doc. it's clear for me.
However, should we mention somewhere that we need to add the Service Kernel API in the kernel to enable the user to use the services in the features?
https://github.com/MicroEJ/Kernel-GREEN/blob/922df4fbdc74553155270896ba7ed0307b647457/module.ivy#L93C13-L93C13

2023-10-25 12:33 UTC, stinlot-microej commented on KernelDeveloperGuide/featuresCommunication.rst
> +      To ensure that every type is indeed embedded, make sure that the property ``soar.generate.classnames`` is set to ``true``
Yes I updated this part as well noting the eventual impact on the footprint

2023-11-20 17:24 UTC, frivieremicroej requested changes

2023-11-20 17:24 UTC, frivieremicroej commented on KernelDeveloperGuide/featuresCommunication.rst
> +.. _Kernel.bind(): https://repository.microej.com/javadoc/microej_5.x/apis/ej/kf/Kernel.html#bind-T-java.lang.Class-ej.kf.Feature-
The Kernel.bind API is very powerful but quite difficult to understand from the javadoc.
I definitely believe that we must inline a full basic example in the documentation, as explained here: https://youtrack.cross/issue/M0078DDG-542/Document-the-binding-of-Shared-Interfaces-in-the-Kernel (20230630_example_sharedinterface_service.zip)

1. Declare the following class in your Kernel
```java
package com.microej.example;

import ej.kf.Feature;
import ej.kf.Feature.State;
import ej.kf.FeatureStateListener;
import ej.kf.Kernel;
import ej.kf.Module;

/**
 * Example of Kernel APIs for registering a generic Shared Interface service.
 */
public class GlobalService {

	private static Object GLOBAL_SERVICE;
	static {
		// automatically unregister the global service when the Feature is stopped.
		Kernel.addFeatureStateListener(new FeatureStateListener() {

			@Override
			public void stateChanged(Feature feature, State previousState) {
				synchronized (GlobalService.class) {
					if (GLOBAL_SERVICE != null && Kernel.getOwner(GLOBAL_SERVICE) == feature
							&& previousState == State.STARTED) {
						GLOBAL_SERVICE = null;
					}
				}
			}
		});
	}

	/**
	 * Basic API to register a Feature service. <br>
	 * The service is automatically unregistered when the Feature is stopped.
	 *
	 * @param service
	 *            the service being registered. It must implement a shared interface.
	 */
	public synchronized static void registerService(Object service) {
		Kernel.enter();
		GLOBAL_SERVICE = service;
	}

	/**
	 * Basic API to retrieve a Feature service. <br>
	 *
	 * @param <T>
	 *            the interface type
	 *
	 * @param serviceClass
	 *            the interface of the service being retrieved. It must implement a shared interface.
	 * @return the binded service or <code>null</code> if no registered service
	 */
	@SuppressWarnings("unchecked")
	public synchronized static <T> T getService(Class<T> serviceClass) {
		Module contextOwner = Kernel.getContextOwner();
		Kernel.enter();
		if (GLOBAL_SERVICE == null) {
			return null;
		}
		return Kernel.bind((T) GLOBAL_SERVICE, serviceClass, (Feature) contextOwner);
	}
}
```
2. Declare the following exposed APIs in your `kernel.api` file:
```xml
	<method name="com.microej.example.GlobalService.registerService(java.lang.Object)void"/>
	<method name="com.microej.example.GlobalService.getService(java.lang.Class)java.lang.Object"/>

```

3. Your App1 is ready to register a Shared Interface as a servoice
```java
MySharedInterface service = new MySharedInterface();
GlobalService.registerService(service);
```

4. Your App2 is ready to retrieve a Shared Interface as a servoice
```java
MySharedInterface service = GlobalService.getService(MySharedInterface.class))
service.use();
```

2023-11-23 15:05 UTC, fplardmicroej commented on KernelDeveloperGuide/featuresCommunication.rst
> +   Note that it can have an impact on the footprint of the Kernel as all Types will be embedded.
In my understanding, this is a duplicate of the following...

```rst
If no instance was found an attempt is made to create a new instance of the provided type, assuming it is embedded in the Kernel.
By default only directly referenced type names in the code are embedded in the Kernel, to explicitely tell the Kernel to embed a type name, a resources file ``types.list`` can be used.
Learn more about types `here <https://docs.microej.com/en/latest/ApplicationDeveloperGuide/classpath.html#types>`_.
```

... which I re-phrased into...

```rst
If no instance was found, an attempt is made to create a new one of the provided type, assuming the type is embedded in the Kernel.
By default only types referenced directly in the code are embedded in the Kernel. Non-referenced types may be declared as `Required Types <https://docs.microej.com/en/latest/ApplicationDeveloperGuide/classpath.html#types>`_ to be embedded in the Kernel.
```

... following one of your comments from this MR.

Moreover the property `soar.generate.classnames` is enabled by default, according to the documentation.

For these reasons I suggest to remove this section.

2023-11-27 11:03 UTC, fplardmicroej commented on KernelDeveloperGuide/featuresCommunication.rst
> +If no instance was found an attempt is made to create a new instance of the provided Type, assuming it is embedded in the Kernel.
The service loader uses a `SystemPropertiesServiceLoader` as a fallback service loader (https://gitlab.cross/J0095_Kernels/J0095_KF-Util/-/blob/develop/com.microej.kf.util/src/main/java/com/microej/kf/util/service/ServiceLoaderKF.java#L23).

2023-12-01 08:31 UTC, frivieremicroej commented on KernelDeveloperGuide/featuresCommunication.rst
> +If no instance was found an attempt is made to create a new instance of the provided Type, assuming it is embedded in the Kernel.
OK, this should be demonstrated in the GREEN Kernel to be able to instanciate a Service in this way.

2023-12-01 10:47 UTC, fplardmicroej commented on KernelDeveloperGuide/featuresCommunication.rst
> +If no instance was found an attempt is made to create a new instance of the provided Type, assuming it is embedded in the Kernel.
I've created a ticket for that: https://youtrack.cross/issue/J0095K-1441/GREEN-Demonstrate-instantiation-of-services-through-system-properties

2023-12-13 11:49 UTC, frivieremicroej approved these changes

2023-12-13 11:50 UTC, merged