Remove free access on SDK 5 portable archives
MicroEJ/docs pull request #780
Opened 2023-10-16 08:55 UTC by gjadi-mej

2023-10-17 06:36 UTC, tdelhomenie-microej requested changes

2023-10-17 06:36 UTC, tdelhomenie-microej commented on SDKUserGuide/installSDKDistribution21_11.rst
> +   - `macOS x86_64 - Intel chip (.zip) <mailto:support@microej.com?subject=MicroEJ-SDK-Installer-MacOS-21.11.zip&body=Hi%2C%0D%0ACould%20I%20get%20access%20to%20MicroEJ-SDK-Installer-MacOS-21.11.zip%
Installers are not concerned by this change, they can be downloaded freely since the installation process contains the EULA acceptation step.

2023-10-17 08:57 UTC, gjadi-mej commented on SDKUserGuide/installSDKDistribution21_11.rst
> +   - `macOS x86_64 - Intel chip (.zip) <mailto:support@microej.com?subject=MicroEJ-SDK-Installer-MacOS-21.11.zip&body=Hi%2C%0D%0ACould%20I%20get%20access%20to%20MicroEJ-SDK-Installer-MacOS-21.11.zip%
Maybe, a greedy regexp :)

2023-10-20 15:09 UTC, tdelhomenie-microej approved these changes

2023-10-20 15:23 UTC, merged