M0081MEJA-2311 Document how to select the Core Engine capability with…
MicroEJ/docs pull request #783
Opened 2023-10-17 18:50 UTC by jerome-leroux

… the Architecture 8.1.0.

2023-10-26 15:20 UTC, frivieremicroej commented on VEEPortingGuide/multiSandbox.rst
> +To enable the Multi-Sandbox capability of the MicroEJ Core Engine, set the property ``com.microej.runtime.capability`` to ``multi`` in ``mjvm/mjvm.properties`` file.
```suggestion
To enable the Multi-Sandbox capability of the Core Engine, set the property ``com.microej.runtime.capability`` to ``multi`` in ``mjvm/mjvm.properties`` file.
```

2023-10-26 15:21 UTC, frivieremicroej commented on VEEPortingGuide/tinySandbox.rst
> +To enable the Tiny-Sandbox capability of the MicroEJ Core Engine, set the property ``com.microej.runtime.capability`` to ``tiny`` in ``mjvm/mjvm.properties`` file.
```suggestion
To enable the Tiny-Sandbox capability of the Core Engine, set the property ``com.microej.runtime.capability`` to ``tiny`` in ``mjvm/mjvm.properties`` file.
```

2023-10-26 15:27 UTC, frivieremicroej requested changes
overall OK

2023-10-26 15:27 UTC, frivieremicroej commented on VEEPortingGuide/architecture8Migration.rst
> +If you use the `Platform Configuration Additions <https://github.com/MicroEJ/VEEPortQualificationTools/blob/master/framework/platform/>`_, update to the version ``2.1.0`` or higher.
Here we should recommend to migrate (what was previously in the XPF message) rather than requiring an update.

2023-10-26 15:27 UTC, frivieremicroej commented on VEEPortingGuide/architecture8Migration.rst
> +In your VEE Port, delete the property ``com.microej.platformbuilder.module.multi.enabled`` and use the property ``com.microej.runtime.capability``.
Same for the property: it is a recommendation, but PCAs still support the legacy property.
This property was not documented in the PCAs.
Moreover no one used it for building a tiny configuration.

2023-10-26 16:42 UTC, jerome-leroux commented on VEEPortingGuide/architecture8Migration.rst
> +In your VEE Port, delete the property ``com.microej.platformbuilder.module.multi.enabled`` and use the property ``com.microej.runtime.capability``.
I'd rather be assertive here to force people to update.

2023-10-27 10:07 UTC, jerome-leroux commented on VEEPortingGuide/architecture8Migration.rst
> +In your VEE Port, delete the property ``com.microej.platformbuilder.module.multi.enabled`` and use the property ``com.microej.runtime.capability``.
Say: if you defined the property `com.microej.platformbuilder.module.multi.enabled` then you need to update PCA. Recommend to use the new property.

2023-10-27 10:08 UTC, jerome-leroux commented on VEEPortingGuide/architecture8Migration.rst
> +If you use the `Platform Configuration Additions <https://github.com/MicroEJ/VEEPortQualificationTools/blob/master/framework/platform/>`_, update to the version ``2.1.0`` or higher.
OK

2023-10-30 20:28 UTC, merged