feature/M0081MEJA-2334_sentinel-usage
MicroEJ/docs pull request #792
Opened 2023-10-26 13:16 UTC by apielmicroej

2023-10-30 16:43 UTC, jcourcelmicroej commented on SDKUserGuide/licenses.rst
> +- Get Sentinel_RTE_Installation.zip installers here: xxxxx. It contains installer for Windows, Mac and Linux.
```suggestion
- Get ``Sentinel_RTE_Installation-1.0.0.zip`` installers here: xxxxx. It contains installer for Windows, Mac and Linux.
```

2023-10-30 16:45 UTC, jcourcelmicroej commented on SDKUserGuide/licenses.rst
> +- Get Sentinel_RTE_Installation.zip installers here: xxxxx. It contains installer for Windows, Mac and Linux.
This zip file require to be versionned with a changelog inside. It will allow to track change and backward compatibility between each changes.

2023-10-30 16:46 UTC, jcourcelmicroej commented on SDKUserGuide/licenses.rst
> +- To uninstall RTE type haspdinst_37102.exe -r in the command line. A message is displayed informing you that the Sentinel LDK Run-time Environment was successfully removed.
```suggestion
- To uninstall RTE type ``haspdinst_37102.exe -r`` in the command line. A message is displayed informing you that the Sentinel LDK Run-time Environment was successfully removed.
```

2023-10-30 16:46 UTC, jcourcelmicroej commented on SDKUserGuide/licenses.rst
> +Get aksusbd_37102-9.14.1.tar.gz file and as root, enter the following command:
```suggestion
Get ``aksusbd_37102-9.14.1.tar.gz`` file and as root, enter the following command:
```

2023-10-30 16:47 UTC, jcourcelmicroej commented on SDKUserGuide/licenses.rst
> +- Get Sentinel_Runtime_37102.tar file.
```suggestion
- Get ``Sentinel_Runtime_37102.tar`` file.
```

2023-10-30 16:48 UTC, jcourcelmicroej commented on SDKUserGuide/licenses.rst
> +- Follow the instructions of the installer wizard until the installation is complete. The first time that you run Admin Control Center and submit configuration changes, hasplmd creates configuration
```suggestion
- Follow the instructions of the installer wizard until the installation is complete. The first time that you run Admin Control Center and submit configuration changes, ``hasplmd`` creates configuration files in ``/private/etc/hasplm/``.
```

2023-10-30 16:48 UTC, jcourcelmicroej commented on SDKUserGuide/licenses.rst
> +Unzip MicroEJ_library.zip file in the following location:
```suggestion
Unzip ``MicroEJ_library.zip`` file in the following location:
```

2023-10-30 16:49 UTC, jcourcelmicroej commented on SDKUserGuide/licenses.rst
> +- For Mac: ``/var/hasplm`` (By default, the /var path is hidden. You may need to modify the operating system View option to display all files and folders in order to access this path.)
```suggestion
- For Mac: ``/var/hasplm`` (By default, the ``/var`` path is hidden. You may need to modify the operating system View option to display all files and folders in order to access this path.)
```

2023-10-30 16:51 UTC, jcourcelmicroej commented on SDKUserGuide/licenses.rst
> +- On the product computer open a web navigator and go to localhost port 1947 (Sentinel Admin Control Center)
```suggestion
- On the product computer open a web navigator and go to http://localhost:1947 (Sentinel Admin Control Center)
```

2023-10-30 16:52 UTC, jcourcelmicroej commented on SDKUserGuide/licenses.rst
> +- Go to `Sentinel key` and click on `fingerprint` for Local key to download the C2V file.
```suggestion
- Go to ``Sentinel key`` and click on ``fingerprint`` for Local key to download the C2V file.
```

2023-10-30 16:52 UTC, jcourcelmicroej commented on SDKUserGuide/licenses.rst
> +- Click on `Update/Attach` and upload the V2C file
```suggestion
- Click on ``Update/Attach`` and upload the V2C file
```

2023-10-31 07:31 UTC, apielmicroej commented on SDKUserGuide/licenses.rst
> +- On the product computer open a web navigator and go to localhost port 1947 (Sentinel Admin Control Center)
Je peux pas mettre l'adresse véritable, les checks de la PR contrôle toutes les URLs et le check sur localhost est en échec.

2023-11-02 08:45 UTC, jcourcelmicroej commented on SDKUserGuide/licenses.rst
> +- For Linux: ``/var/hasplm``
Please also document the fact that OS environment variable for dynamic library search must be updated:
- On Linux ``LD_LIBRARY_PATH`` with ``export LD_LIBRARY_PATH=/var/hasplm:$LD_LIBRARY_PATH``
- On Mac ``DYLD_LIBRARY_PATH`` with ``export DYLD_LIBRARY_PATH=/var/hasplm:$DYLD_LIBRARY_PATH``

We can mention here that this modification has to be setup at session startup (e.g: using ``.bashrc`` file) to ensure that OS is properly configured to run a MicroEJ SDK or MicroEJ Architecture using Sentinel license manager.

2023-11-02 09:25 UTC, jcourcelmicroej commented on SDKUserGuide/licenses.rst
> +- In ``SentinelRuntimeInstaller.framework/Versions/A/Resources/`` double-click on Sentinel_Runtime.dmg.
```suggestion
- In ``SentinelRuntimeInstaller.framework/Versions/A/Resources/`` double-click on ``Sentinel_Runtime.dmg``.
```

2023-11-07 17:15 UTC, jcourcelmicroej commented on SDKUserGuide/licenses.rst
> +- Finally set ``LD_LIBRARY_PATH`` variable with command ``export LD_LIBRARY_PATH=/var/hasplm:$LD_LIBRARY_PATH``. This modification has to be setup at session startup  (e.g: using .bashrc file) to ens
```suggestion
- Finally set ``LD_LIBRARY_PATH`` variable with command ``export LD_LIBRARY_PATH=/var/hasplm:$LD_LIBRARY_PATH``. This modification has to be setup at session startup  (e.g: using ``.bashrc`` file) to ensure that OS is properly configured to run a MicroEJ SDK or MicroEJ Architecture using Sentinel license manager.
```

2023-11-07 17:15 UTC, jcourcelmicroej commented on SDKUserGuide/licenses.rst
> +- Finally set ``DYLD_LIBRARY_PATH`` variable with command ``export DYLD_LIBRARY_PATH=/var/hasplm:$DYLD_LIBRARY_PATH``. This modification has to be setup at session startup  (e.g: using .bashrc file)
```suggestion
- Finally set ``DYLD_LIBRARY_PATH`` variable with command ``export DYLD_LIBRARY_PATH=/var/hasplm:$DYLD_LIBRARY_PATH``. This modification has to be setup at session startup  (e.g: using ``.bashrc`` file) to ensure that OS is properly configured to run a MicroEJ SDK or MicroEJ Architecture using Sentinel license manager.
```

2023-11-10 10:00 UTC, frivieremicroej requested changes

2023-11-13 09:54 UTC, jcourcelmicroej commented on SDKUserGuide/licenses.rst
> +- For RedHat, SUSE, or CentOS 64-bit ARM systems: ``rpm -i aksusbd-9.14-1.aarch64.rpm``
```suggestion
```

2023-11-13 10:10 UTC, jcourcelmicroej commented on SDKUserGuide/licenses.rst
> +- For Ubuntu or Debian 32-bit ARM systems: ``dpkg -i aksusbd_9.14-1_armhf.deb``
Done

2023-11-13 10:10 UTC, jcourcelmicroej commented on SDKUserGuide/licenses.rst
> +- For Ubuntu or Debian 64-bit ARM systems: ``dpkg -i aksusbd_9.14-1_arm64.deb``
Done

2023-11-13 10:16 UTC, jcourcelmicroej commented on SDKUserGuide/licenses.rst
> +	For Windows 64-bit, please put ``hasp_windows_x64_37102.dll`` file in the system folder (``%SystemRoot%\system32``) if you have administrator rights on your machine.
Done

2023-11-13 10:16 UTC, jcourcelmicroej commented on SDKUserGuide/licenses.rst
> +.. note:
Fixed, merged in the first list item.

2023-11-13 10:23 UTC, jcourcelmicroej commented on SDKUserGuide/licenses.rst
> +Sentinel LDK Run-time Environment is required on the end user's computer to enable your protected software to run by communicating with Sentinel protection keys.
Done

2023-11-13 10:23 UTC, jcourcelmicroej commented on SDKUserGuide/licenses.rst
> +- To uninstall RTE type ``haspdinst_37102.exe -r`` in the command line. A message is displayed informing you that the Sentinel LDK Run-time Environment was successfully removed.
Done

2023-11-13 12:03 UTC, jcourcelmicroej commented on SDKUserGuide/licenses.rst
> +
Done

2023-11-13 12:04 UTC, jcourcelmicroej commented on SDKUserGuide/licenses.rst
> +
Done

2023-11-16 10:15 UTC, jcourcelmicroej commented on SDKUserGuide/licenses.rst
> +- Copy ``aksusbd-9.14.1/haspvlib_37102.so`` and ``aksusbd-9.14.1/haspvlib_x86_64_37102.so`` to /var/hasplm directory
```suggestion
- Copy ``aksusbd-9.14.1/haspvlib_37102.so`` and ``aksusbd-9.14.1/haspvlib_x86_64_37102.so`` to ``/var/hasplm`` directory
```

2023-11-16 10:18 UTC, jcourcelmicroej commented on SDKUserGuide/licenses.rst
> +Set up environment
```suggestion
Setup Your Environment
```

2023-11-28 16:58 UTC, jcourcelmicroej commented on SDKUserGuide/licenses.rst
> +First, get ``Sentinel_RTE_Installation-1.0.0.zip`` file here: xxxxx. It contains installer for Windows, macOS and Linux.
Done

2023-12-13 08:33 UTC, frivieremicroej commented
Marked as draft as a preview documentation. Will not be merged until we decide to officially support Sentinel as COTS component.

2024-04-19 14:28 UTC, rlouedec-microej commented on SDKUserGuide/licenses.rst
> +   [DEBUG] ===== SUCCESS =====
Should we include the output for Architecture 8.1+ ?
```suggestion
   [DEBUG] ===== MicroEJ Sentinel Debug Tool =====
   [DEBUG] => login failed with feature 1, status=400
   [DEBUG] ===== MicroEJ Dongle Debug Tool =====
   [DEBUG] => Detected dongle UID: XXXXXXXX.
   [DEBUG] => Dongle UID has valid MicroEJ data: XXXXXXXX (only the first one is listed).
   [DEBUG] => Detected MicroEJ License XXXXX-XXXXX-XXXXX-XXXXX - valid until YYYY-MM-DD.
   [DEBUG] ===== SUCCESS =====
```

I just had a feedback from customer:
> Unsure what that result regarding the MicroEJ Sentinel Debug Tool login failure is indicative of as I have not run across it yet on the doc site

2024-04-24 20:56 UTC, rlouedec-microej commented
The default settings for RTE installation on a workstation seems weird.
I would expect we should configure `Configuration > Network > Network Visibility` to `None (Local Access Only)`.
The default `All Network Adapters` seems only adapted for the installation time of the floating license server.
Also, we should probably document how to restrict access to the administration interface on the floating license server.

2024-09-12 14:28 UTC, rlouedec-microej commented on SDKUserGuide/licenses_sentinel.rst
> +.. figure:: images/sentinel_architecture.png
Nice diagram.

Can we have different arrows for the step1 / step 2 to clarify that those are emails and not actual network connections like other arrows?

Also, I am not sure how relevant it is to document the MicroEJ part. This could be more confusing than helping.

2024-09-13 09:19 UTC, apielmicroej commented on SDKUserGuide/licenses_sentinel.rst
> +.. figure:: images/sentinel_architecture.png
I have updated the diagram.

2025-01-14 09:55 UTC, closed without merging