Feature/m0090 ide 4446 Add code coverage analyzer and how to enable code coverage cc generation
MicroEJ/docs pull request #793
Opened 2023-10-26 15:00 UTC by gjadi-mej

2023-10-31 08:19 UTC, bguedas requested changes

2023-10-31 08:19 UTC, bguedas commented on SDK6UserGuide/codeCoverageAnalyzer.rst
> +--------------------------
This Option section is not of the same kind as the others: `------` instead of `^^^^^^`

2023-10-31 08:19 UTC, bguedas commented on SDK6UserGuide/codeCoverageAnalyzer.rst
> +Options
Are they really options or arguments? I mean, an "option" is supposed to be optional. I guess that some of them are mandatory and other optional. Moreover, we do not describe `cc.src.folders` and `cc.html.dir`.

2023-10-31 08:19 UTC, bguedas commented on SDK6UserGuide/runOnSimulator.rst
> +   | Description 2008-2023, MicroEJ Corp. Content in this space is free
Really?

2023-11-02 10:02 UTC, gjadi-mej commented on SDK6UserGuide/runOnSimulator.rst
> +   | Description 2008-2023, MicroEJ Corp. Content in this space is free
Fixed. No idea how I did this :D

2023-11-02 10:02 UTC, gjadi-mej commented on SDK6UserGuide/codeCoverageAnalyzer.rst
> +--------------------------
Fixed.

2023-11-02 10:07 UTC, gjadi-mej commented on SDK6UserGuide/codeCoverageAnalyzer.rst
> +Options
I've added description for src.folders and html.dir.

I kept the name options because that's what is used in the SDK5 documentation.
Also, for now they are required but as soon as we will provide dedicated task, we will be able to provide the suitable default value (as it's done in SDK5).

Not sure it's worth changing the formulation.

2023-11-07 17:14 UTC, bguedas approved these changes

2023-11-10 13:03 UTC, merged