Added tutorial page
MicroEJ/docs pull request #80
Opened 2020-10-02 14:58 UTC by flardy

2020-10-20 08:51 UTC, seonmej requested changes

2020-10-20 08:51 UTC, seonmej commented on Tutorials/tutorialTracesInApplication.rst
> +   The default platform implementation of the Trace API prints the events in the console. MicroEJ provides an other implementation that redirects the events to `SystemView <https://www.segger.com/pro
`events sequence and duration`

2020-10-20 08:51 UTC, seonmej commented on Tutorials/tutorialTracesInApplication.rst
> +-  Each ``Logger`` created with this method is registered in the ``LoggerManager`` and can be retrieved using its String ``ID``.
`LogManager` instead of `LoggerManager`

2020-10-20 08:51 UTC, seonmej commented on Tutorials/tutorialTracesInApplication.rst
> +    -  ``log(...)`` methods, that send a ``LogRecord`` with the level argument to the registered ``Handler`` instances.
- remove `,`
- `with a level` or `with a specified level`

2020-10-20 08:51 UTC, seonmej commented on Tutorials/tutorialTracesInApplication.rst
> +    -  ``log(...)`` methods, that send a ``LogRecord`` with the level argument to the registered ``Handler`` instances.
- remove `,`
- `with a level` or `with a specified level`

2020-10-20 08:51 UTC, seonmej commented on Tutorials/tutorialTracesInApplication.rst
> +Library ``ej.library.eclasspath.logging`` is based over the ``java.util.logging`` library and follows the same principles:
Tell that this solution is entirely based on Strings (unlike the other solutions).

2020-10-20 08:51 UTC, seonmej commented on Tutorials/tutorialTracesInApplication.rst
> +- Log a message by using methods ``MessageLogger.log(...)``, specifying the log level, the message category and message integer identifer.
`identifier` (missing `i`)

2020-10-20 08:51 UTC, seonmej commented on Tutorials/tutorialTracesInApplication.rst
> +- As the ID of the message is an integer, making the output not very human-readable, it is wise to maintain a documentation that describes all message IDs.
`all IDs.`

2020-10-20 08:51 UTC, seonmej commented on Tutorials/tutorialTracesInApplication.rst
> +   ``<dependency org="ej.library.runtime" name="message" rev="x.y.z"/>``
I think that the version used for the tutorial can be put here. It is tedious to have to search for the right version.

2020-10-20 08:51 UTC, seonmej commented on Tutorials/tutorialTracesInApplication.rst
> +   ``<dependency org="ej.library.runtime" name="message" rev="x.y.z"/>``
(The same goes for the 3 solutions.)

2020-10-20 08:51 UTC, seonmej commented on Tutorials/tutorialTracesInApplication.rst
> +         BasicMessageLogger.INSTANCE.log(Level.INFO, "Application", 2, oldState, currentState);
Use constants for the category and the ID.

2020-10-20 08:51 UTC, seonmej commented on Tutorials/tutorialTracesInApplication.rst
> +* You can add logging to your MicroEJ applications while meeting the constraints of embedded applications
Add `.` at the end.

2020-10-22 22:16 UTC, jerome-leroux requested changes
Can you add a paragraph that summarizes the pro and con of each solution so that a reader can decide which one to use?

2020-10-22 22:16 UTC, jerome-leroux commented on Tutorials/tutorialTracesInApplication.rst
> +- As the ID of the message is an integer, making the output not very human-readable, it is wise to maintain a documentation that describes all IDs.
```suggestion
- As the ID of the message is an integer, making the output not very human-readable, it is wise to maintain documentation that describes all IDs.
```

2020-10-22 22:16 UTC, jerome-leroux commented on Tutorials/tutorialTracesInApplication.rst
> +A boolean constant declared in a ``if`` statement can be used to fully remove portions of code: when this boolean constant is evaluated as ``false``, the wrapped code becomes unreachable and, thus, i
```suggestion
A boolean constant declared in an ``if`` statement can be used to fully remove portions of code: when this boolean constant is evaluated as ``false``, the wrapped code becomes unreachable and, thus, is not embedded.
```

2020-10-22 22:16 UTC, jerome-leroux commented on Tutorials/tutorialTracesInApplication.rst
> +#. Let's consider a constant ``com.mycompany.logging`` that we declared as ``false`` in a resource file named ``example.constants.list``.
```suggestion
#. Let's consider a constant ``com.mycompany.logging`` declared as ``false`` in a resource file named ``example.constants.list``.
```

2020-10-22 22:16 UTC, jerome-leroux commented on Tutorials/tutorialTracesInApplication.rst
> +When using the Trace API (ej.api.trace), you can evaluate the value of constant ``Tracer.TRACE_ENABLED_CONSTANT_PROPERTY`` that represents property ``core.trace.enabled``.
```suggestion
When using the Trace API (``ej.api.trace``), you can evaluate the value of the static field ``Tracer.TRACE_ENABLED_CONSTANT_PROPERTY`` that represents the constant ``core.trace.enabled``.
```

2020-10-22 22:16 UTC, jerome-leroux commented on Tutorials/tutorialTracesInApplication.rst
> +The value of this property can be modified by going to :guilabel:`Launch` > :guilabel:`Launch configurations` then in the tab :guilabel:`Configuration` > :guilabel:`Runtime`, check/uncheck the option
```suggestion
The value of this constant can be modified by going to :guilabel:`Launch` > :guilabel:`Launch configurations` then in the tab :guilabel:`Configuration` > :guilabel:`Runtime`, check/uncheck the option :guilabel:`Enable execution traces` to respectively set the value to ``true``/``false``.
```

2020-10-22 22:16 UTC, jerome-leroux commented on Tutorials/tutorialTracesInApplication.rst
> +Follow same principle as before:
```suggestion
Follow the same principle as before:
```

2020-10-22 22:16 UTC, jerome-leroux commented on Tutorials/tutorialTracesInApplication.rst
> +`ProGuard <https://www.guardsquare.com/en/products/proguard>`_ is a command-line tool that shrinks, optimizes and obfuscates Java code.
```suggestion
`ProGuard <https://www.guardsquare.com/en/products/proguard>`_ is a command-line tool that shrinks, optimizes, and obfuscates Java code.
```

2020-10-22 22:16 UTC, jerome-leroux commented on Tutorials/tutorialTracesInApplication.rst
> +It optimizes bytecode as well as detect and remove unused instructions. Therefore it can be used to remove log messages in a production binary.
```suggestion
It optimizes bytecode as well as it detects and removes unused instructions. Therefore it can be used to remove log messages in a production binary.
```

2020-10-22 22:16 UTC, jerome-leroux commented on Tutorials/tutorialTracesInApplication.rst
> +At this point of the tutorial:
```suggestion
At this point in the tutorial:
```

2020-10-23 11:42 UTC, jerome-leroux commented on Tutorials/tutorialTracesInApplication.rst
> +This tutorial presents several solutions. The aim is to help developers to report precise execution context for further debugging and monitoring.
```suggestion
This document explains how to add logging and tracing to MicroEJ applications and libraries with three different solutions. The aim is to help developers to report precise execution context for further debugging and monitoring.
```
?

2020-10-27 21:28 UTC, jerome-leroux commented on Tutorials/tutorialTracesInApplication.rst
> +- Messages library
```suggestion
- Trace API: a real-time event recording library designed for performance and interaction analysis.
- Logging library: a complete and highly configurable standard logging library.
- Messages library: a lightweight and simple logging library. 
```

2020-11-25 16:48 UTC, apineau-microej commented on Tutorials/tutorialTracesInApplication.rst
> +Trace API (ej.api.trace)
By default the traces are disabled. It is already explained how to enable traces below but it could be mentioned here.

2020-11-30 09:15 UTC, gjadi-mej reviewed
Cool tutorial!

2020-11-30 09:15 UTC, gjadi-mej commented on Tutorials/tutorialInstrumentJavaCodeForLogging.rst
> +Combined with the category, the printed message identifier value allows the user to find the corresponding error/warning/info description.
`the category` is introduced here without context and it can't be understood without reading the rest of the section.
Here is a suggested formulation:
```suggestion
In addition to a message identifier, the category of the message allows the user to find the corresponding error/warning/info description.
An external documentation must be maintained to describe all message identifiers and their expected arguments for each category.
```

2020-11-30 09:15 UTC, gjadi-mej commented on Tutorials/tutorialInstrumentJavaCodeForLogging.rst
> +#. Add the following dependency to the ``module.ivy``:
Because of the nested list (the logger API provides....: - item 1 - item 2), the fonts of this list items are larger than the lists in the other sections.  I find it a bit confusing. 
I couldn't find a workaround except by reformulating the item to remove the sub-list.

2020-11-30 09:15 UTC, gjadi-mej commented on Tutorials/tutorialInstrumentJavaCodeForLogging.rst
> +   When possible, prefer using a logging solution that uses primitive types over Strings.
```suggestion
   Unlike the two other libraries discussed here, the ``Logging`` library is entirely based on Strings (log IDs and messages). 
   String operations can lead to performance issues and String objects use significant ROM space. 
   When possible, prefer using a logging solution that uses primitive types over Strings.
```

The ``Note that`` feels redundant as we are already inside a `.. note::` item.

2020-11-30 09:15 UTC, gjadi-mej commented on Tutorials/tutorialInstrumentJavaCodeForLogging.rst
> +        :align: center
This tip is useful but what's the best practice regarding how to do it in practice to produce both a production and a debug firmware?

- 2 projects? 1 for production and 1 for debug with various properties set in each project
- can it be set in the launcher? how?

2020-11-30 09:23 UTC, frivieremicroej commented on Tutorials/tutorialInstrumentJavaCodeForLogging.rst
> +        :align: center
2 projects or 1 project with a custom module.ant that generates prod/debug options properties files depending on a build option - OK I understand you point I will create a dedicated ticket how to build multiple firmware flavors from build options.

2020-11-30 09:34 UTC, frivieremicroej commented on Tutorials/tutorialInstrumentJavaCodeForLogging.rst
> +#. Add the following dependency to the ``module.ivy``:
fixed

2020-11-30 09:59 UTC, frivieremicroej commented on Tutorials/tutorialTracesInApplication.rst
> +Trace API (ej.api.trace)
pulled up the option activation into the trace section

2020-11-30 10:03 UTC, merged