document the creation of Configurations in all supported IDEs
MicroEJ/docs pull request #807
Opened 2023-11-20 15:20 UTC by denisbedin

2023-11-21 07:36 UTC, bguedas requested changes

2023-11-21 07:36 UTC, bguedas commented on SDK6UserGuide/howtos/createCustomConfigurationInIDE.rst
> +   | Copyright 2008-2023, MicroEJ Corp. Content in this space is free
```suggestion
   | Copyright 2023, MicroEJ Corp. Content in this space is free 
```

2023-11-21 09:08 UTC, denisbedin commented on SDK6UserGuide/howtos/createCustomConfigurationInIDE.rst
> +   | Copyright 2008-2023, MicroEJ Corp. Content in this space is free
The copyright is ok (see the copyright notice here : https://docs.cross/howto/contribute.html#id1)

2023-11-22 09:15 UTC, bguedas approved these changes

2023-11-22 09:26 UTC, merged