M0090IDE-4478 Add a tutorial on how to create a branded Eclipse
MicroEJ/docs pull request #816
Opened 2023-11-30 10:43 UTC by tdelhomenie-microej

2023-12-01 09:26 UTC, tdelhomenie-microej commented on SDK6UserGuide/tutorials/brandEclipse.rst
> +How To Brand an Eclipse IDE
Done.

2023-12-01 09:26 UTC, tdelhomenie-microej commented on SDK6UserGuide/tutorials/brandEclipse.rst
> +- Install the Microej plugin as described in the ``Eclipse`` tab of the :ref:`sdk_6_install_ide_plugin` chapter.
Done.

2023-12-01 09:27 UTC, tdelhomenie-microej commented on SDK6UserGuide/tutorials/brandEclipse.rst
> +Copy the branding resources
Done.

2023-12-01 14:26 UTC, bguedas requested changes
We should add recommended sizes for the images. The "Branding" tab says that the image should not exceed 500x330 and that the text is not shown if it exceeds 250x330.

2023-12-01 14:26 UTC, bguedas commented on SDK6UserGuide/tutorials/brandEclipse.rst
> +  The image format must be bmp, with one bmp file for each one of the following resolutions: 16x16, 32x32, 64x64, 128x128, 256x256.
```suggestion
  The image format must be png, with one png file for each one of the following resolutions: 16x16, 32x32, 48x48, 64x64, 128x128, 256x256.
```

2023-12-01 14:26 UTC, bguedas commented on SDK6UserGuide/tutorials/brandEclipse.rst
> +- Select :guilabel:`Plug-in Developement` > :guilabel:`Eclipse product`, then click on the guilabel:`Next` button.
```suggestion
- Select :guilabel:`Plug-in Developement` > :guilabel:`Eclipse product`, then click on the :guilabel:`Next` button.
```

2023-12-01 17:14 UTC, tdelhomenie-microej commented on SDK6UserGuide/tutorials/brandEclipse.rst
> +- Create a folder named ``images``.
Done.

2023-12-01 17:14 UTC, tdelhomenie-microej commented on SDK6UserGuide/tutorials/brandEclipse.rst
> +- Copy the ``About`` dialog (:guilabel:`Help` > :guilabel:`About...`) image in the ``images`` folder.
Done.

2023-12-01 17:14 UTC, tdelhomenie-microej commented on SDK6UserGuide/tutorials/brandEclipse.rst
> +  The image format must be bmp, with one bmp file for each one of the following resolutions: 16x16, 32x32, 64x64, 128x128, 256x256.
Done.

2023-12-01 17:15 UTC, tdelhomenie-microej commented on SDK6UserGuide/tutorials/brandEclipse.rst
> +- Select :guilabel:`Plug-in Developement` > :guilabel:`Eclipse product`, then click on the guilabel:`Next` button.
Done.

2023-12-01 17:15 UTC, tdelhomenie-microej commented
@bguedas I refactored the branding resources copy by dispatching in each section. Let me know what you think.

2023-12-05 08:17 UTC, bguedas approved these changes
LGTM, it should be reviewed by IoT team now.

2023-12-05 08:20 UTC, tdelhomenie-microej commented
@abaloche-microej do you confirm you did a review and a successful test?

2023-12-07 08:26 UTC, merged