Feature/m0078 ddg 553 mej32 block diagram
MicroEJ/docs pull request #827
Opened 2023-12-14 11:38 UTC by frivieremicroej

Add final Core Engine block diagram and refresh the whole Core Engine page with latest glossary terms.

2023-12-14 21:36 UTC, jerome-leroux commented
Changes to be merge with what have been done for Architecture 8.1. See https://github.com/MicroEJ/docs/compare/master...architecture_8_1#diff-52e36b4feaff961f710ef9ed6dccea00ac5cd9119f8ef16c6167cba9b1a8935d

2023-12-14 21:41 UTC, jerome-leroux requested changes

2023-12-14 21:41 UTC, jerome-leroux commented on VEEPortingGuide/coreEngine.rst
> +   :align: center
The image is not clickable to open it full screen.

2023-12-14 21:41 UTC, jerome-leroux commented on VEEPortingGuide/images/mjvm_block-diagram.png
32bits -> 32-bit
64bits -> 64-bit
16bits -> 16-bit

2023-12-14 21:41 UTC, jerome-leroux commented on VEEPortingGuide/images/mjvm_block-diagram.png
In "Advanced Profiling", add "Exceptions"

2023-12-14 21:41 UTC, jerome-leroux commented on VEEPortingGuide/coreEngine.rst
> +:ref:`The following diagram <fig_mjvm_flow2>` shows the overall process.
```suggestion
:ref:`The following diagram <fig_mjvm_flow2>` shows the overall build flow. 
```

2023-12-14 21:41 UTC, jerome-leroux commented on VEEPortingGuide/coreEngine.rst
>  .. _core_engine:
Changes to be merged with what have been done for Architecture 8.1: https://github.com/MicroEJ/docs/compare/master...architecture_8_1#diff-52e36b4feaff961f710ef9ed6dccea00ac5cd9119f8ef16c6167cba9b1a8935d

2023-12-14 21:41 UTC, jerome-leroux commented on VEEPortingGuide/coreEngine.rst
> +The Core Engine defines two times:
```suggestion
The Core Engine defines two different times:
```

2023-12-18 09:01 UTC, frivieremicroej commented on VEEPortingGuide/coreEngine.rst
>  .. _core_engine:
OK, I suggest to first merge this branch asap, then I will rebase the Architecture 8.1 branch on top of it

2023-12-18 16:46 UTC, jerome-leroux approved these changes

2023-12-18 16:46 UTC, merged