Add Create IAR Image tutorial
MicroEJ/docs pull request #839
Opened 2023-12-28 08:06 UTC by apielmicroej

2024-01-02 10:22 UTC, jerome-leroux requested changes
Review numbering of the bullets list. See https://microej-docs--839.com.readthedocs.build/en/839/Tutorials/tutorialCreateIARImage.html

2024-01-02 10:22 UTC, jerome-leroux commented on Tutorials/tutorialCreateIARImage.rst
> +This tutorial was tested with MicroEJ SDK ``5.8.1-jdk11``, IAR ``9.30.1`` and Docker ``24.0.6``.
```suggestion
This tutorial was tested with MicroEJ SDK ``5.8.1-jdk11``, IAR ``9.30.1``, and Docker ``24.0.6``.
```

2024-01-02 10:22 UTC, jerome-leroux commented on Tutorials/tutorialCreateIARImage.rst
> +#. In a new directory create a file name Dockerfile.
```suggestion
#. In a new directory create a file named ``Dockerfile``.
```

2024-01-02 10:22 UTC, jerome-leroux commented on Tutorials/tutorialCreateIARImage.rst
> +#. Install this package and any others required.
```suggestion
#. Install this package along with any others required packages.
```

2024-01-02 10:22 UTC, jerome-leroux commented on Tutorials/tutorialCreateIARImage.rst
> +#. Add package info to your Dockerfile (change to the version you want to use):
```suggestion
#. Add the package info to your Dockerfile (update the version with the one you want to use):
```

2024-01-02 10:22 UTC, jerome-leroux commented on Tutorials/tutorialCreateIARImage.rst
> +#. Set IAR path and licence server
```suggestion
#. Set IAR path and license server address:
```

2024-01-02 10:22 UTC, jerome-leroux commented on Tutorials/tutorialCreateIARImage.rst
> +#. Finally we need a run.sh script containing this code:
```suggestion
#. Finally create a ``run.sh`` script with the following content:
```

2024-01-10 06:18 UTC, fpinel-microej requested changes

2024-01-10 06:18 UTC, fpinel-microej commented on Tutorials/tutorialCreateIARImage.rst
> +      exec "$@"
```suggestion
      exec "$@"

..
   | Copyright 2023, MicroEJ Corp. Content in this space is free 
   for read and redistribute. Except if otherwise stated, modification 
   is subject to MicroEJ Corp prior approval.
   | MicroEJ is a trademark of MicroEJ Corp. All other trademarks and 
   copyrights are the property of their respective owners.
```

2024-01-10 10:12 UTC, fpinel-microej approved these changes

2024-01-15 13:26 UTC, jerome-leroux approved these changes

2024-01-16 08:51 UTC, merged