remove support of dropIns folder for MicroEJ VEE selection
MicroEJ/docs pull request #843
Opened 2024-01-03 15:41 UTC by denisbedin

https://docs.microej.com/en/feature-sdk6_remove_dropins_support/

2024-01-05 16:39 UTC, tdelhomenie-microej requested changes

2024-01-05 16:39 UTC, tdelhomenie-microej commented on SDK6UserGuide/limitations.rst
> +- Load the VEE Port from a dependency.
Why removing "its archive file path, its folder path"?

2024-01-05 16:39 UTC, tdelhomenie-microej commented on SDK6UserGuide/selectKernel.rst
>     | Copyright 2008-2023, MicroEJ Corp. Content in this space is free
```suggestion
   | Copyright 2008-2024, MicroEJ Corp. Content in this space is free 
```

2024-01-05 16:39 UTC, tdelhomenie-microej commented on SDK6UserGuide/selectVeePort.rst
>     | Copyright 2008-2023, MicroEJ Corp. Content in this space is free
```suggestion
   | Copyright 2008-2024, MicroEJ Corp. Content in this space is free 
```

2024-01-08 08:07 UTC, denisbedin commented on SDK6UserGuide/selectVeePort.rst
>     | Copyright 2008-2023, MicroEJ Corp. Content in this space is free
Done.

2024-01-08 08:07 UTC, denisbedin commented on SDK6UserGuide/selectKernel.rst
>     | Copyright 2008-2023, MicroEJ Corp. Content in this space is free
Done.

2024-01-08 08:09 UTC, denisbedin commented on SDK6UserGuide/limitations.rst
> +- Load the VEE Port from a dependency.
I removed it because we also use a dependency to load a local VEE Port. But I added it back because it is clearer that way.

2024-01-09 08:37 UTC, tdelhomenie-microej approved these changes

2024-01-09 08:44 UTC, merged