execTool: Document Local Deployment Socket
MicroEJ/docs pull request #848
Opened 2024-01-09 08:29 UTC by gjadi-mej

2024-01-09 08:41 UTC, bguedas requested changes

2024-01-09 08:41 UTC, bguedas commented on SDK6UserGuide/localDeployTool.rst
> +Dependencies
It looks like a section from a README. Is it the case? And is it relevant here, especially when there is no dependency?

2024-01-09 08:41 UTC, bguedas commented on SDK6UserGuide/localDeployTool.rst
> +This tool is a built-in Architecture tool bundled in the VDE when it is built.
I can't find any other VDE occurence in the doc, I thoink we should say Virtual Device instead.

2024-01-09 08:41 UTC, bguedas commented on SDK6UserGuide/localDeployTool.rst
> +Specify the FQDN of the Feature Application to deploy. It is the entry-point of the feature.
Maybe explain FQDN in full words

2024-01-09 09:36 UTC, gjadi-mej commented on SDK6UserGuide/localDeployTool.rst
> +Dependencies
Not from a README but I reused a similar format as the stack trace reader.
No strong opinion on this.

2024-01-09 09:38 UTC, gjadi-mej commented on SDK6UserGuide/localDeployTool.rst
> +This tool is a built-in Architecture tool bundled in the VDE when it is built.
updated.

2024-01-09 09:38 UTC, gjadi-mej commented on SDK6UserGuide/localDeployTool.rst
> +Specify the FQDN of the Feature Application to deploy. It is the entry-point of the feature.
updated.

2024-01-09 10:36 UTC, bguedas commented on SDK6UserGuide/localDeployTool.rst
> +Dependencies
Neither do I, I think the best thing is to be consistent for each tool. Let's see what the others say

2024-01-10 10:15 UTC, tdelhomenie-microej requested changes

2024-01-10 10:15 UTC, tdelhomenie-microej commented on SDK6UserGuide/localDeployTool.rst
> +Dependencies
I don't see the value to keep it, so I would remove it.

2024-01-10 10:15 UTC, tdelhomenie-microej commented on SDK6UserGuide/localDeployTool.rst
> +The Local Deployment Socket builds the Sandboxed Application ``.fo`` and upload it on the device identified by its IP address. On the device, it is the job of the Kernel Application that receives the
Technically, the tool does not build the `.fo` file, it only deploys it. Not a big issue, but we could replace this by something like "The Local Deployment Socket makes sure that the Sandboxed Application ``.fo`` is built and upload it ..." instead?

2024-01-10 10:15 UTC, tdelhomenie-microej commented on SDK6UserGuide/localDeployTool.rst
> +This tool is a built-in Architecture tool bundled in the Virtual Device when it is built.
This is an implementation detail IMO, and it is not totally true since the tool is also composed of the execTool Gradle task, which is part of the SDK. Shouldn't we say instead that this tool comes with the SDK, thanks to the `execTool` Gradle task?

2024-01-10 10:15 UTC, tdelhomenie-microej commented on SDK6UserGuide/tools.rst
> +   localDeployTool
I know it is designed as a MicroEJ Tool, but it seems strange to me that deploying a Standalone Application is done with a runOnDevice task, but not a Sandboxed Application. This brings confusion IMO. That's not the purpose here, but we should probably think of allowing to deploy a fo file with the runOnDevice task.

2024-01-10 10:15 UTC, tdelhomenie-microej commented on SDK6UserGuide/localDeployTool.rst
> +   | Copyright 2024, MicroEJ Corp. Content in this space is free
I think all the documentation pages should all have the same years, so "2008-2024".

2024-01-10 10:15 UTC, tdelhomenie-microej commented on SDK6UserGuide/tools.rst
>     | Copyright 2023, MicroEJ Corp. Content in this space is free
Wrong year.

2024-01-10 10:23 UTC, gjadi-mej commented on SDK6UserGuide/localDeployTool.rst
> +The Local Deployment Socket builds the Sandboxed Application ``.fo`` and upload it on the device identified by its IP address. On the device, it is the job of the Kernel Application that receives the
As far as I can see, yes the tool does the build of the .fo. There is no dependency from the `:execTool` task to the `:buildFeature` task. It's all done under the hood by `localDeploymentSocket.microejLaunch`.

2024-01-10 10:31 UTC, tdelhomenie-microej commented on SDK6UserGuide/localDeployTool.rst
> +The Local Deployment Socket builds the Sandboxed Application ``.fo`` and upload it on the device identified by its IP address. On the device, it is the job of the Kernel Application that receives the
Waouh ok, I did not know! So there are 2 ways to build a fo file... Are we sure it is built with the same options in both cases?

2024-01-10 17:37 UTC, gjadi-mej commented on SDK6UserGuide/localDeployTool.rst
> +The Local Deployment Socket builds the Sandboxed Application ``.fo`` and upload it on the device identified by its IP address. On the device, it is the job of the Kernel Application that receives the
Hmm I didn't think about that. I'll have to check it out.

2024-01-10 17:38 UTC, gjadi-mej commented on SDK6UserGuide/tools.rst
> +   localDeployTool
agreed. I think it could be done once we've documented the basics of the microejtool and we will work on improve the experience with dedicated tasks (or here, with well integrated task).

2024-01-10 17:42 UTC, gjadi-mej commented on SDK6UserGuide/localDeployTool.rst
> +This tool is a built-in Architecture tool bundled in the Virtual Device when it is built.
I don't know. Maybe we could just remove the section because it doesn't bring anything. I'm not sure.
I've reused the same structure as the stacktrace reader

For the stack trace reader we have:

> This tool is a built-in Architecture tool.

We can of course update the stack trace reader doc too.

2024-01-12 09:37 UTC, tdelhomenie-microej commented on SDK6UserGuide/localDeployTool.rst
> +This tool is a built-in Architecture tool bundled in the Virtual Device when it is built.
I agree, we should remove them in both cases.

2024-01-12 09:37 UTC, tdelhomenie-microej commented on SDK6UserGuide/tools.rst
> +   localDeployTool
Agreed.

2024-01-12 11:08 UTC, gjadi-mej commented on SDK6UserGuide/localDeployTool.rst
> +This tool is a built-in Architecture tool bundled in the Virtual Device when it is built.
fixed.

2024-01-12 11:08 UTC, gjadi-mej commented on SDK6UserGuide/localDeployTool.rst
> +   | Copyright 2024, MicroEJ Corp. Content in this space is free
fixed.

2024-01-12 14:17 UTC, gjadi-mej commented on SDK6UserGuide/localDeployTool.rst
> +The Local Deployment Socket builds the Sandboxed Application ``.fo`` and upload it on the device identified by its IP address. On the device, it is the job of the Kernel Application that receives the
I've aligned the behavior of the buildFeature task with that of the localDeploymentSocket tool in the gradle plugin (in review).

2024-01-16 10:51 UTC, tdelhomenie-microej approved these changes

2024-01-29 08:42 UTC, bguedas approved these changes

2024-01-29 08:52 UTC, merged