unify application entrypoint
MicroEJ/docs pull request #852
Opened 2024-01-18 13:55 UTC by denisbedin

https://docs.microej.com/en/feature-sdk6_unify_application_entrypoint/

2024-02-07 10:49 UTC, tdelhomenie-microej requested changes

2024-02-07 10:49 UTC, tdelhomenie-microej commented on SDK6UserGuide/createProject.rst
> +- If your Application requires advanced features, for example the `FeatureEntryPoint.stop()`_ method:
Shouldn't we move this chapter in a dedicated page or at least a dedicated section, less visible, to keep the default flow lighter?

2024-02-07 10:49 UTC, tdelhomenie-microej commented on SDK6UserGuide/moduleNatures.rst
> +**Description**: Wraps the Application.
Should be more detailed IMO: "Wraps the Application class to be able to run ..."

2024-02-07 10:49 UTC, tdelhomenie-microej commented on SDK6UserGuide/sdk6MigrationNotes.rst
> +~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
This chapter should go in another section "from 0.15.0 to 0.16.0".

2024-02-07 13:18 UTC, denisbedin commented on SDK6UserGuide/sdk6MigrationNotes.rst
> +~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Done.

2024-02-07 13:18 UTC, denisbedin commented on SDK6UserGuide/moduleNatures.rst
> +**Description**: Wraps the Application.
Done.

2024-02-07 13:45 UTC, denisbedin commented on SDK6UserGuide/createProject.rst
> +- If your Application requires advanced features, for example the `FeatureEntryPoint.stop()`_ method:
I created a new HowTo Guide : https://docs.microej.com/en/feature-sdk6_unify_application_entrypoint/SDK6UserGuide/howtos/createFeatureClass.html

2024-02-07 15:41 UTC, tdelhomenie-microej approved these changes

2024-02-08 07:31 UTC, denisbedin commented on SDK6UserGuide/createProject.rst
> +- If your Application requires advanced features, for example the `FeatureEntryPoint.stop()`_ method:
I changed the title

2024-02-08 07:32 UTC, merged