Feature/m0018 pqt 144 run test suite
MicroEJ/docs pull request #87
Opened 2020-10-07 16:14 UTC by gjadi-mej

2020-10-07 19:29 UTC, jerome-leroux requested changes

2020-10-07 19:29 UTC, jerome-leroux commented on Tutorials/tutorialRunATestSuite.rst
> +https://github.com/MicroEJ/PlatformQualificationTools/tree/master/tests/fs/java/java-testsuite-fs/validation/microej-testsuite-common.properties)
We should not reference a specific file in the master branch.
Prefer referencing a commit or a tag.

2020-10-07 19:29 UTC, jerome-leroux commented on Tutorials/tutorialRunATestSuite.rst
> +    ``microej.testsuite.properties.testsuite.trace.port``.
Rendering of this section is not good in github preview. I don't know if the problem comes from github or the RST.

2020-10-07 19:29 UTC, jerome-leroux commented on Tutorials/tutorialRunATestSuite.rst
> +``Build Module``.
```suggestion
To run the Test Suite, right click on the Test Suite module and select
``Build Module``.
```

2020-10-07 19:29 UTC, jerome-leroux commented on Tutorials/tutorialRunATestSuite.rst
> +Several reasons might explain why exclude some tests:
```suggestion
Several reasons might explain why to exclude some tests:
```

2020-10-07 19:29 UTC, jerome-leroux commented on Tutorials/tutorialRunATestSuite.rst
> +- Iterative development: Test only the ADLA that is currently being
```suggestion
- Iterative development: Test only the abstraction layer that is currently being
```

2020-10-07 19:29 UTC, jerome-leroux commented on Tutorials/tutorialRunATestSuite.rst
> +  use the latest Foundation Library, then it is necessary to exclude
```suggestion
  use the latest Foundation Library, then it can be necessary to exclude
```

2020-10-07 19:29 UTC, jerome-leroux commented on Tutorials/tutorialRunATestSuite.rst
> +  might have specific requirements that prevents a fully compliant
```suggestion
  might have specific requirements that prevent a fully compliant
```

2020-10-07 19:29 UTC, jerome-leroux commented on Tutorials/tutorialRunATestSuite.rst
> +If necessary, the binary produced and ran on the device by the Test
```suggestion
If necessary, the binaries produced and ran on the device by the Test
```

2020-10-07 19:29 UTC, jerome-leroux commented on Tutorials/tutorialRunATestSuite.rst
> +``target~/test/xml/TIMESTAMP/bin/FULLY-QUALIFIED-CLASSNAME/application.out``.
```suggestion
``target~/test/xml/<TIMESTAMP>/bin/<FULLY-QUALIFIED-CLASSNAME>/application.out``.
```

2020-10-07 19:29 UTC, jerome-leroux commented on Tutorials/tutorialRunATestSuite.rst
> +The following image shows a example of a Test Suite Report for the Test Suite FS.
```suggestion
The following image shows an example of a Test Suite Report for the Test Suite FS.
```

2020-10-08 08:13 UTC, gjadi-mej commented on Tutorials/tutorialRunATestSuite.rst
> +https://github.com/MicroEJ/PlatformQualificationTools/tree/master/tests/fs/java/java-testsuite-fs/validation/microej-testsuite-common.properties)
fixed.

2020-10-08 08:13 UTC, gjadi-mej commented on Tutorials/tutorialRunATestSuite.rst
> +    ``microej.testsuite.properties.testsuite.trace.port``.
fixed

2020-10-08 08:13 UTC, gjadi-mej commented on Tutorials/tutorialRunATestSuite.rst
> +https://github.com/MicroEJ/PlatformQualificationTools/tree/master/tests/fs/java/java-testsuite-fs/config.properties.
fixed

2020-10-08 11:58 UTC, stephanemainchain commented on Tutorials/tutorialRunATestSuite.rst
> +MicroEJ Foundation Library named FS.  It is the role of the MicroEJ
MicroEJ Platform Engineer: wtf is this and where is it defined?
Prefer: The Abstraction layer of each foundation API must be implemented in the BSP.

2020-10-08 11:58 UTC, stephanemainchain commented on Tutorials/tutorialRunATestSuite.rst
> +- A MicroEJ Platform with:
A MicroEJ Platform source imported in the MicroEJ SDK workspace:

2020-10-08 11:58 UTC, stephanemainchain commented on Tutorials/tutorialRunATestSuite.rst
> +Platform Engineer to implement the required functions, called
Avoid platform engineer (never defined before, too complex)

2020-10-08 11:58 UTC, stephanemainchain commented on Tutorials/tutorialRunATestSuite.rst
> +implementation.
to validate the C code implementation of the Abstraction Layer.

2020-10-08 11:58 UTC, stephanemainchain commented on Tutorials/tutorialRunATestSuite.rst
> +3. Flash MicroEJ Firmware onto the device.
the MicroEJ Firmware...

2020-10-08 11:58 UTC, stephanemainchain commented on Tutorials/tutorialRunATestSuite.rst
> +Abstraction Layer, in the BSP.  The Test Suite is used to validate the
First time BSP is mentionned. What is BSP?

2020-10-08 13:16 UTC, gjadi-mej commented on Tutorials/tutorialRunATestSuite.rst
> +3. Flash MicroEJ Firmware onto the device.
fixed

2020-10-08 13:17 UTC, gjadi-mej commented on Tutorials/tutorialRunATestSuite.rst
> +implementation.
fixed

2020-10-08 13:17 UTC, gjadi-mej commented on Tutorials/tutorialRunATestSuite.rst
> +Platform Engineer to implement the required functions, called
fixed

2020-10-08 13:17 UTC, gjadi-mej commented on Tutorials/tutorialRunATestSuite.rst
> +- A MicroEJ Platform with:
fixed

2020-10-08 13:17 UTC, gjadi-mej commented on Tutorials/tutorialRunATestSuite.rst
> +MicroEJ Foundation Library named FS.  It is the role of the MicroEJ
fixed

2020-10-08 13:18 UTC, gjadi-mej commented on Tutorials/tutorialRunATestSuite.rst
> +Abstraction Layer, in the BSP.  The Test Suite is used to validate the
The tutorial assumes the reader has read the tutorial on how to build a MicroEJ Firmware which explains what is the BSP. Do we need to repeat it?

2020-10-08 14:13 UTC, stephanemainchain commented on Tutorials/tutorialRunATestSuite.rst
> +Abstraction Layer, in the BSP.  The Test Suite is used to validate the
ok noted.

2020-10-09 15:25 UTC, gjadi-mej commented on Tutorials/tutorialRunATestSuite.rst
> +When the Test Suite is executed, the Test Suite Engine must read the
I checked with adiallo and he confirmed that the default behavior for the Test Suite Engine as configured in the PQT is to expect the `run.bat` to output on stdout the trace of execution. If the user sets the address and port then it uses it.

2020-10-12 16:20 UTC, gjadi-mej commented on Tutorials/tutorialRunATestSuite.rst
> +When the Test Suite is executed, the Test Suite Engine must read the
Removed the mention of redirection to stdout.

2020-10-13 13:41 UTC, frivieremicroej commented
Doc after my ref/tuto refactor is available here: https://docs.microej.com/en/feature-m0018pqt-144_run_test_suite/Tutorials/tutorialRunATestSuiteOnDevice.html

TODO @gjadi-mej to update the tuto steps based on Wrover + FS and fullfill the sections / XXX

2020-10-29 09:18 UTC, gjadi-mej commented
@frivieremicroej In `testsuiteEngine.rst`, what's the default value for `jvmargs`?

2020-11-17 15:28 UTC, jerome-leroux requested changes

2020-11-17 15:28 UTC, jerome-leroux commented on Tutorials/tutorialRunATestSuiteOnDevice.rst
> +into the workspace:
```suggestion
Follow these steps to import the Testsuite FS into the workspace from the `Platform Qualification Tools
<https://github.com/MicroEJ/PlatformQualificationTools/blob/2.3.0/tests/fs>`__:
```

2020-11-17 15:28 UTC, jerome-leroux commented on Tutorials/tutorialRunATestSuiteOnDevice.rst
> +UART port must be used.
```suggestion
The WROVER platform used in this tutorial is particular because
the UART port is already used to flash the device. Thus, a separate
UART port must be used for the trace output.
```

2020-11-17 20:08 UTC, jerome-leroux commented on ApplicationDeveloperGuide/testsuite.rst
> +  .. figure:: images/testuiteReportXMLExampleJUnitView.png
```suggestion
  .. figure:: images/testuiteReportXMLExampleJunitView.png
```

2020-11-17 20:09 UTC, jerome-leroux commented on ApplicationDeveloperGuide/testsuite.rst
> +Once a testsuite is completed, a testsuite report is generated:
```suggestion
Once a testsuite is completed, the following  testsuite reports are generated:
```

2020-11-17 20:09 UTC, jerome-leroux commented on ApplicationDeveloperGuide/testsuite.rst
> +- in HTML format in module project location ``target~/test/html/test/junit-noframes.html``.
```suggestion
- HTML report in module project location ``target~/test/html/test/junit-noframes.html``.
```

2020-11-17 20:10 UTC, jerome-leroux commented on ApplicationDeveloperGuide/testsuite.rst
> +- in JUnit XML format, in module project location ``target~/test/xml/TEST-test-report.xml``.
```suggestion
- JUnit XML report in module project location ``target~/test/xml/TEST-test-report.xml``.
```

2020-11-17 20:15 UTC, jerome-leroux commented on ApplicationDeveloperGuide/testsuite.rst
> +  execution traces for each test executed are available.
```suggestion
This report contains a summary and the execution trace of every executed test.
```

2020-11-17 20:16 UTC, jerome-leroux commented on ApplicationDeveloperGuide/testsuite.rst
> +  XML report file can also be open in the JUnit View. Right-click on the file > :guilabel:`Open With` >  :guilabel:`JUnit View`:
```suggestion
  XML report file can also be opened in the JUnit View. Right-click on the file > :guilabel:`Open With` >  :guilabel:`JUnit View`:
```

2020-11-17 20:23 UTC, jerome-leroux commented on ApplicationDeveloperGuide/testsuite.rst
> +is available in module project location ``target~/test/xml/<TIMESTAMP>/bin/<FULLY-QUALIFIED-CLASSNAME>/application.out``.
```suggestion
is available in the module project location ``target~/test/xml/<TIMESTAMP>/bin/<FULLY-QUALIFIED-CLASSNAME>/application.out``.
```

2020-12-14 16:02 UTC, gjadi-mej commented
https://docs.microej.com/en/feature-m0018pqt-144_run_test_suite/Tutorials/tutorialRunATestSuiteOnDevice.html

2020-12-14 19:14 UTC, jerome-leroux requested changes

2020-12-14 19:14 UTC, jerome-leroux commented on Tutorials/tutorialRunATestSuiteOnDevice.rst
> +  implementation of the Foundation Library.
```suggestion
- **Iterative development**. Test only the Abstraction Layer that is
  currently being developed.  The full Testsuite must still be executed to
  validate the complete implementation.

- **Known bugs in the Foundation Library**. The latest version of the Test
  Suite for a given Foundation Library might contain regression
  tests or tests for new features.  If the MicroEJ Platform doesn't
  use the latest Foundation Library, then it can be necessary to exclude
  the new tests.

- **Known bugs in the Foundation Library implementation**. The project
  might have specific requirements that prevent a fully compliant
  implementation of the Foundation Library.
```

2020-12-14 19:14 UTC, jerome-leroux commented on Tutorials/tutorialRunATestSuiteOnDevice.rst
> +Configure which Tests to Run
```suggestion
Configure the Tests to Run
```

2020-12-16 10:34 UTC, gjadi-mej commented on Tutorials/tutorialRunATestSuiteOnDevice.rst
> +:ref:`platform_testsuite` on a device using the `Platform
Fixed by rebasing on top of master.

2020-12-16 10:34 UTC, gjadi-mej commented on Tutorials/tutorialRunATestSuiteOnDevice.rst
> +  :ref:`application_testsuite` for this topic.
Fixed by rebasing on top of master.

2020-12-16 10:34 UTC, gjadi-mej commented on Tutorials/tutorialRunATestSuiteOnDevice.rst
> +use the :ref:`tool_serial_to_socket` tool to redirect the execution
Fixed by rebasing on top of master.

2020-12-16 10:34 UTC, gjadi-mej commented on Tutorials/tutorialRunATestSuiteOnDevice.rst
> +few set of tests.  In the following example, only the classes that
Removed "this tab".  New sentence is:

> To speed-up the execution, let's configure it to run only a small set of tests.

2020-12-16 10:34 UTC, gjadi-mej commented on Tutorials/tutorialRunATestSuiteOnDevice.rst
> +https://github.com/MicroEJ/PlatformQualificationTools/blob/2.3.0/tests/fs/java/java-testsuite-fs/config.properties.
Yes it's normal.  Here is the new sentence:

> For example, see this `config.properties <https://github.com/MicroEJ/PlatformQualificationTools/blob/2.3.0/tests/fs/java/java-testsuite-fs/config.properties>`__ file.

2021-01-07 09:56 UTC, gjadi-mej commented on ApplicationDeveloperGuide/testsuite.rst
> +  execution traces for each test executed are available.
fixed.

2021-01-07 09:58 UTC, gjadi-mej commented on ApplicationDeveloperGuide/testsuite.rst
> +- in JUnit XML format, in module project location ``target~/test/xml/TEST-test-report.xml``.
fixed.  I also reused the same wording above for JUnit HTML report.

2021-01-07 10:00 UTC, gjadi-mej commented on ApplicationDeveloperGuide/testsuite.rst
> +Once a testsuite is completed, a testsuite report is generated:
fixed.

2021-01-12 16:54 UTC, fpinel-microej commented
Troubleshooting additions suggestions :
- if TraceAnalyzer can't detect anything but STST is setup and running fine
```
[testsuite:javaTestsuite] [traceAnalyzer:socketTraceAnalyzer] 1 : TraceAnalyzer ERROR :
[testsuite:javaTestsuite] [traceAnalyzer:socketTraceAnalyzer] [M3] - No activity on input stream since 75 s.
[testsuite:javaTestsuite] [traceAnalyzer:socketTraceAnalyzer] 
[testsuite:javaTestsuite] [traceAnalyzer:socketTraceAnalyzer] 2 : TraceAnalyzer ERROR :
[testsuite:javaTestsuite] [traceAnalyzer:socketTraceAnalyzer] [M5] - No encountered success/failure tag.
[testsuite:javaTestsuite] [traceAnalyzer:socketTraceAnalyzer] 
[testsuite:javaTestsuite] BUILD FAILED
[testsuite:javaTestsuite] C:\Program Files\MicroEJ\MicroEJ-SDK-20.12\rcp\configuration\org.eclipse.osgi\11\data\repositories\microej-build-repository\com\is2t\easyant\plugins\microej-testsuite\3.4.0\microej-testsuite-harness-jpf-emb-3.4.0.xml:85: TraceAnalyzer ends with errors.
```
==> some trace redirection properties may not set, or set inappropriately
==> COM port may have changed, check for `serial.serialutil.SerialException: could not open port 'COM7': FileNotFoundError(2, 'The system cannot find the file specified.', None, 2)` error in trace
- `[testsuite:javaTestsuite] C:\Program Files\MicroEJ\MicroEJ-SDK-20.12\rcp\configuration\org.eclipse.osgi\11\data\repositories\microej-build-repository\com\is2t\easyant\plugins\microej-testsuite\3.4.0\microej-testsuite-harness-jpf-emb-3.4.0.xml:49: Binary file generation failed.`
==> BSP Connection properties may not be set, or set inappropriately
- 
```
No loaded Platform.
Possible options to load a platform are: 
- (1) Set the property `platform-loader.target.platform.file` to a Platform file absolute path.
- (2) Set the property `platform-loader.target.platform.dir` to a Platform directory absolute path.
- (3) Declare a dependency in `module.ivy`.
- (4) Copy/Paste a Platform file into the folder defined by the property `platform-loader.target.platform.dropins` (by default its value is `dropins`).
A Platform declared using (1) or (2) is loaded prior to (3) or (4).
```
==> property `target.platform.dir` may not be set

-
```
[testsuite:javaTestsuite] [traceAnalyzer:socketTraceAnalyzer] 1 : SocketTraceAnalyzerError ERROR :
[testsuite:javaTestsuite] [traceAnalyzer:socketTraceAnalyzer] [M1] - Could not connect to localhost:5555
[testsuite:javaTestsuite] [traceAnalyzer:socketTraceAnalyzer] 
[testsuite:javaTestsuite] BUILD FAILED
```
==> STST may not be running

Other additions suggestions :
- Remind in the tutorial that pre-configured config.properties and microej-testsuite-common.properties are available in the `...-configuration/testsuite/..` folder of the MicroEJ Platform, if necessay

2021-01-12 17:21 UTC, fpinel-microej commented
Do not forget to update Github links : 
- https://github.com/MicroEJ/PlatformQualificationTools/releases/tag/2.3.0 in *Import the Test Suite*
- https://github.com/MicroEJ/PlatformQualificationTools/blob/2.3.0/tests/fs/java/java-testsuite-fs/config.properties in *Configure the Platform BSP Connection*
- https://github.com/MicroEJ/PlatformQualificationTools/blob/2.3.0/tests/fs/java/java-testsuite-fs/validation/microej-testsuite-common.properties in *Configure the Test Suite Specific Options*

2021-01-13 14:28 UTC, gjadi-mej commented
> 
> 
> Troubleshooting additions suggestions :
> 
>     * if TraceAnalyzer can't detect anything but STST is setup and running fine
> 
> 
> ```
> [testsuite:javaTestsuite] [traceAnalyzer:socketTraceAnalyzer] 1 : TraceAnalyzer ERROR :
> [testsuite:javaTestsuite] [traceAnalyzer:socketTraceAnalyzer] [M3] - No activity on input stream since 75 s.
> [testsuite:javaTestsuite] [traceAnalyzer:socketTraceAnalyzer] 
> [testsuite:javaTestsuite] [traceAnalyzer:socketTraceAnalyzer] 2 : TraceAnalyzer ERROR :
> [testsuite:javaTestsuite] [traceAnalyzer:socketTraceAnalyzer] [M5] - No encountered success/failure tag.
> [testsuite:javaTestsuite] [traceAnalyzer:socketTraceAnalyzer] 
> [testsuite:javaTestsuite] BUILD FAILED
> [testsuite:javaTestsuite] C:\Program Files\MicroEJ\MicroEJ-SDK-20.12\rcp\configuration\org.eclipse.osgi\11\data\repositories\microej-build-repository\com\is2t\easyant\plugins\microej-testsuite\3.4.0\microej-testsuite-harness-jpf-emb-3.4.0.xml:85: TraceAnalyzer ends with errors.
> ```
> 
> ==> some trace redirection properties may not set, or set inappropriately
> ==> COM port may have changed, check for `serial.serialutil.SerialException: could not open port 'COM7': FileNotFoundError(2, 'The system cannot find the file specified.', None, 2)` error in trace
> 
>     * `[testsuite:javaTestsuite] C:\Program Files\MicroEJ\MicroEJ-SDK-20.12\rcp\configuration\org.eclipse.osgi\11\data\repositories\microej-build-repository\com\is2t\easyant\plugins\microej-testsuite\3.4.0\microej-testsuite-harness-jpf-emb-3.4.0.xml:49: Binary file generation failed.`
>       ==> BSP Connection properties may not be set, or set inappropriately
> 
> 
> ```
> No loaded Platform.
> Possible options to load a platform are: 
> - (1) Set the property `platform-loader.target.platform.file` to a Platform file absolute path.
> - (2) Set the property `platform-loader.target.platform.dir` to a Platform directory absolute path.
> - (3) Declare a dependency in `module.ivy`.
> - (4) Copy/Paste a Platform file into the folder defined by the property `platform-loader.target.platform.dropins` (by default its value is `dropins`).
> A Platform declared using (1) or (2) is loaded prior to (3) or (4).
> ```
> 
> ==> property `target.platform.dir` may not be set
> 
> 
> ```
> [testsuite:javaTestsuite] [traceAnalyzer:socketTraceAnalyzer] 1 : SocketTraceAnalyzerError ERROR :
> [testsuite:javaTestsuite] [traceAnalyzer:socketTraceAnalyzer] [M1] - Could not connect to localhost:5555
> [testsuite:javaTestsuite] [traceAnalyzer:socketTraceAnalyzer] 
> [testsuite:javaTestsuite] BUILD FAILED
> ```
> 
> ==> STST may not be running
> 
> Other additions suggestions :
> 
>     * Remind in the tutorial that pre-configured `config.properties` and `microej-testsuite-common.properties` files are available in the `...-configuration/testsuite/..` folder of the MicroEJ Platform, if necessay

Added to PQT.  Thanks.

2021-02-19 15:38 UTC, frivieremicroej commented
github links ok => let's go

2021-02-19 15:38 UTC, merged