fix SDK6 heap dumper documentation to reflect actual usage.
MicroEJ/docs pull request #884
Opened 2024-02-16 13:39 UTC by tboue

Documentation didn't reflect what we had to do with @dalgassimou to perform a heap dump on device with architecture 8.

There also is a duplicate of this page for SDK5, do I update it ?

2024-02-21 13:38 UTC, dalgassimou commented on SDK6UserGuide/heapAnalyzer.rst
> +The heap dump should be performed after a call to ``System.gc()`` to exclude discardable objects.
the dump can be generation in many cases not only after a `System.gc` see here https://github.com/MicroEJ/docs/blob/master/ApplicationDeveloperGuide/debuggerProxy.rst?plain=1#L23

2024-02-21 13:38 UTC, dalgassimou commented on SDK6UserGuide/heapAnalyzer.rst
> +- from .hex files that must be manually retrieved on device.
```suggestion
- from .hex files that must be manually retrieved from the device.
```

2024-02-21 13:38 UTC, dalgassimou commented on SDK6UserGuide/heapAnalyzer.rst
> +   void LLMJVM_on_OutOfMemoryError_thrown(){
this is the wrong example, you should define here the LLMJVM_on_Runtime_gc_done

2024-02-21 13:41 UTC, dalgassimou commented
We should add a section in the documentation, listing the memory sections to be emptied depending on whether we're in a multi or mono use case.

2024-02-22 12:51 UTC, tboue commented
> We should add a section in the documentation, listing the memory sections to be emptied depending on whether we're in a multi or mono use case.

I agree but is it possible ? We did dump the entire RAM at the end because finding the list of sections was too long ?

2024-02-26 09:34 UTC, tboue commented on SDK6UserGuide/heapAnalyzer.rst
> +- from .hex files that must be manually retrieved on device.
applied in https://github.com/MicroEJ/docs/pull/884/commits/437e9770e60d925051a25d490677e7d73069f934

2024-02-26 09:35 UTC, tboue commented on SDK6UserGuide/heapAnalyzer.rst
> +The heap dump should be performed after a call to ``System.gc()`` to exclude discardable objects.
Explanation added in https://github.com/MicroEJ/docs/pull/884/commits/9272f8c920fe424effb96bb4b13a4af7ae5bc4ec

2024-02-26 09:35 UTC, tboue commented on SDK6UserGuide/heapAnalyzer.rst
> +   void LLMJVM_on_OutOfMemoryError_thrown(){
fixed in https://github.com/MicroEJ/docs/pull/884/commits/9272f8c920fe424effb96bb4b13a4af7ae5bc4ec

2024-02-27 08:49 UTC, dalgassimou commented on SDK6UserGuide/heapAnalyzer.rst
> +   dump ihex memory java_features_dynamic_start java_features_dynamic_end
Is this correct? or
```suggestion
   dump ihex memory &java_features_dynamic_start &java_features_dynamic_end
```

2024-02-27 08:49 UTC, dalgassimou commented on SDK6UserGuide/heapAnalyzer.rst
> +- features related sections. These will change depending on the board, number of features and other parameters. It is possible to dump the entire memory and let the :ref:`heap extractor<_sdk6_heapdum
```suggestion
- features related sections. These will change depending on the board, number of features and other parameters. It is possible to dump the entire memory and let the :ref:`heap extractor<_sdk6_heapdumper_extract_heap>` extract the requiered sections instead.
```

2024-02-27 08:49 UTC, dalgassimou commented on SDK6UserGuide/heapAnalyzer.rst
> +If the symbol isn't embedded, add the following lines in any source file (ex:main.c):
I don't think this is right, I purpose something like this
```suggestion
If the symbol is inlined, add the following lines in any source file (ex:main.c):
```
What do you think @frivieremicroej?

2024-03-04 12:41 UTC, tboue commented on SDK6UserGuide/heapAnalyzer.rst
> +      }
Tested again, no need to implement the callback, just having a body header is enough

2024-03-04 15:24 UTC, tboue commented on SDK6UserGuide/heapAnalyzer.rst
> +If the symbol isn't embedded, add the following lines in any source file (ex:main.c):
Changed to https://github.com/MicroEJ/docs/pull/884/files#diff-d122d22cbbd8db54cff58c20f6831435524140fb2fafe25be7c8dcc084801a51R113-R114

2024-03-04 15:28 UTC, frivieremicroej requested changes

2024-03-04 15:30 UTC, frivieremicroej approved these changes

2024-03-04 15:30 UTC, frivieremicroej commented on SDK6UserGuide/heapAnalyzer.rst
> +      void LLMJVM_on_Runtime_gc_done(){
confirmed by @tboue

2024-03-04 15:30 UTC, merged