document how to skip the publication of a Virtual Device
MicroEJ/docs pull request #921
Opened 2024-03-15 11:20 UTC by denisbedin

https://docs.microej.com/en/feature-sdk6_document_producevirtualdeviceduringbuild/SDK6UserGuide/publishProject.html

2024-03-15 16:13 UTC, tdelhomenie-microej requested changes

2024-03-15 16:13 UTC, tdelhomenie-microej commented on SDK6UserGuide/publishProject.rst
> +    }
We should probably refactor the way the 3 "produce..." options are documented. First, shouldn't we move them out of the Publication documentation, since it is not directly related to publication (I may want to not build the VD when I just build an Application).
Second, I htink we should list then in a given section "Built and Published Artifacts Options" which could start by "The list of built and published artifacts can be configured thanks to the following options..."?

2024-03-18 10:06 UTC, denisbedin commented on SDK6UserGuide/publishProject.rst
> +    }
The "produce..."  methods have been documented in a dedicated section in the buildExecutable, buildFeature and buildVirtualDevice pages.

2024-03-18 11:12 UTC, tdelhomenie-microej requested changes

2024-03-18 11:12 UTC, tdelhomenie-microej commented on SDK6UserGuide/buildExecutable.rst
> +Publish an Executable
```suggestion
Trigger Executable Build by Default
```

2024-03-18 11:12 UTC, tdelhomenie-microej commented on SDK6UserGuide/buildFeature.rst
> +Publish a Feature
```suggestion
Trigger Feature Build by Default
```

2024-03-18 11:12 UTC, tdelhomenie-microej commented on SDK6UserGuide/buildVirtualDevice.rst
> +Publish a Virtual Device
```suggestion
Skip Virtual Device Build by Default
```

2024-03-18 11:18 UTC, denisbedin commented on SDK6UserGuide/buildExecutable.rst
> +Publish an Executable
Done.

2024-03-18 11:18 UTC, denisbedin commented on SDK6UserGuide/buildFeature.rst
> +Publish a Feature
Done.

2024-03-18 11:18 UTC, denisbedin commented on SDK6UserGuide/buildVirtualDevice.rst
> +Publish a Virtual Device
Done.

2024-03-18 11:19 UTC, tdelhomenie-microej approved these changes

2024-03-18 11:32 UTC, merged