Document Null Analysis in SDK 6
MicroEJ/docs pull request #938
Opened 2024-04-02 12:45 UTC by tdelhomenie-microej

2024-04-10 14:55 UTC, denisbedin requested changes

2024-04-11 13:19 UTC, tdelhomenie-microej commented on SDK6UserGuide/nullAnalysis.rst
> +    - Select the category :guilabel:`Java` > :guilabel:`Probable Bugs` > :guilabel:`Nullability problems` > :guilabel:`Nullability and data flow problems`.
Done

2024-04-11 13:19 UTC, tdelhomenie-microej commented on SDK6UserGuide/nullAnalysis.rst
> +    - Select the category :guilabel:`Java` > :guilabel:`Javadoc` > :guilabel:`Missing'package-info.java'`.
Done

2024-04-11 13:19 UTC, tdelhomenie-microej commented on SDK6UserGuide/nullAnalysis.rst
> +    - Select ``ej.annotation.Nullable`` in the :guilabel:`Nullable annotations` list.
Done

2024-04-11 13:42 UTC, denisbedin approved these changes

2024-04-11 13:48 UTC, merged