Clarify requirements for SDK 5 (MMM) on Ubuntu 22.04 (headless)
MicroEJ/docs pull request #946
Opened 2024-04-09 19:28 UTC by rlouedec-microej

2024-04-10 09:08 UTC, denisbedin requested changes

2024-04-10 22:31 UTC, rlouedec-microej commented on SDKUserGuide/systemRequirements.rst
> +     - To build a Platform with MicroUI, the OpenJDK distribution from Ubuntu is not supported. The Eclipse Temurin distribution is recommended.
IMO, the "system requirements" section is more about what you need on your system to **use** the MICROEJ SDK 5 than only about the SDK installation.

The VEE Port build is a valid use case for the MICROEJ SDK 5.
(It is even one of the last use cases for current MICROEJ SDK 6 projects)

Personally, I would avoid troubleshooting because you only go there after encountering the issue (and users may even not check this section / search for the error message in docs.microej.com).

WDYT ?

2024-04-11 08:15 UTC, denisbedin commented on SDKUserGuide/systemRequirements.rst
> +     - To build a Platform with MicroUI, the OpenJDK distribution from Ubuntu is not supported. The Eclipse Temurin distribution is recommended.
After discussing with Thomas and Benoit, we agreed that it should be documented in the System Requirements page, but without mentioning the build of a VEE Port or MicroUI, since at this stage an user can ignore what is a VEE Port.
```suggestion
     - For headless installations, the ``libwebkit2gtk-4.0-37`` package is required additionally.
     - The OpenJDK distribution from Ubuntu is not supported. The Eclipse Temurin distribution is recommended.
```
But we should also add a troubleshooting section in the https://docs.microej.com/en/latest/VEEPortingGuide/platformCreation.html# chapter to document the error with a link to the System Requirements page, in case the user didn't read them or skipped the installation of the package.

2024-04-11 22:39 UTC, rlouedec-microej commented on SDKUserGuide/systemRequirements.rst
> +     - To build a Platform with MicroUI, the OpenJDK distribution from Ubuntu is not supported. The Eclipse Temurin distribution is recommended.
Ok it makes sense.
I added the two issues to troubleshooting.

2024-04-17 11:48 UTC, denisbedin requested changes

2024-04-17 11:48 UTC, denisbedin commented on SDKUserGuide/systemRequirements.rst
> +     - For headless installations, to build a Platform, the ``libwebkit2gtk-4.0-37`` package is required additionally.
```suggestion
  
```

2024-04-17 11:48 UTC, denisbedin commented on SDKUserGuide/troubleshooting.rst
> +Could not load SWT library
The two troubleshootings should be moved to https://docs.microej.com/en/latest/SDKUserGuide/mmm.html#troubleshooting.

2024-04-22 19:49 UTC, rlouedec-microej commented on SDKUserGuide/systemRequirements.rst
> +     - For headless installations, to build a Platform, the ``libwebkit2gtk-4.0-37`` package is required additionally.
Applied here: 60778730ab9f6da7b9b0a5a87f28319cd48785e2

2024-04-22 19:49 UTC, rlouedec-microej commented on SDKUserGuide/troubleshooting.rst
> +Could not load SWT library
Done here: 6c0912d8bf7927cac3deb8e9eca673bf0e95abf0

2024-04-23 06:20 UTC, denisbedin approved these changes

2024-04-23 13:29 UTC, merged