Document Runtime API configuration
MicroEJ/docs pull request #954
Opened 2024-04-25 08:19 UTC by denisbedin

https://docs.microej.com/en/feature-sdk6_document_runtime_api_configuration/

2024-04-29 09:30 UTC, tdelhomenie-microej requested changes

2024-04-29 09:30 UTC, tdelhomenie-microej commented on SDK6UserGuide/buildVirtualDevice.rst
> +
We should describe a bit more the usage of the microejRuntimeApi configuration and what it does exactly IMO. In the case of the VD, it allows to embed all transitive dependencies in the VD.
And we should add a section somewhere to document how to use it in an Application, and what it does.

2024-04-29 14:56 UTC, denisbedin commented on SDK6UserGuide/buildVirtualDevice.rst
> +
Done.

2024-04-30 11:42 UTC, tdelhomenie-microej approved these changes

2024-04-30 11:42 UTC, tdelhomenie-microej commented on KernelDeveloperGuide/runtimeEnvironment.rst
> +      microejRuntimeApi("com.mycompany:myruntimeapi:1.0.0")
In order to be consistent with the Mock page (https://docs.microej.com/en/latest/VEEPortingGuide/mock.html) we should put SDK 6 first.

2024-04-30 12:55 UTC, merged