Add VS Code support for SDK 6.
MicroEJ/docs pull request #961
Opened 2024-05-14 12:20 UTC by bguedas

2024-05-14 12:48 UTC, tdelhomenie-microej requested changes

2024-05-14 12:48 UTC, tdelhomenie-microej commented on SDK6UserGuide/install.rst
> +      MicroEJ does not provide a dedicated plugin for VS Code, but Microsoft provides a plugin that brings a usefull collection of plugins for Java
```suggestion
      MicroEJ does not provide a dedicated plugin for VS Code, but Microsoft provides a plugin that brings an useful collection of plugins for Java
```

2024-05-14 12:48 UTC, tdelhomenie-microej commented on SDK6UserGuide/install.rst
> +         not present in Gradle dependencies.
```suggestion
         Unlike other supported IDEs (Android Studio/IntelliJ IDEA/Eclipse), there is no MicroEJ plugin which removes
         the JDK dependency. As a result, `IntelliSense <https://code.visualstudio.com/docs/editor/intellisense>`__ may propose classes and methods from the JDK which are
         not present in your project dependencies.
```

2024-05-14 15:20 UTC, tdelhomenie-microej approved these changes

2024-05-16 09:31 UTC, tdelhomenie-microej requested changes

2024-05-16 09:31 UTC, tdelhomenie-microej commented on SDK6UserGuide/runOnSimulator.rst
> +      - Set ``localhost`` as ``hostName`` and ``8000`` as ``port`` in the generated json
We should not "hardcode" `8000` in the doc, since it depends on the value set in the configuration (and it is `12000` by default).

2024-05-17 05:50 UTC, bguedas commented on SDK6UserGuide/runOnSimulator.rst
> +      - Click on ``create a launch.json file`` in the opened panel
Done

2024-05-17 05:50 UTC, bguedas commented on SDK6UserGuide/runOnSimulator.rst
> +      - Set ``localhost`` as ``hostName`` and ``8000`` as ``port`` in the generated json
Changed

2024-05-17 07:12 UTC, tdelhomenie-microej approved these changes

2024-05-17 07:54 UTC, merged