Document how update the state of the 'debugged' application
MicroEJ/docs pull request #979
Opened 2024-06-24 09:33 UTC by dalgassimou

2024-06-24 10:23 UTC, dalgassimou commented
link to download the latest vee debugger proxy: https://nextcloud.cross/index.php/s/4RH7NEG9Gp39x97

2024-09-23 10:19 UTC, agazardMicroeJ commented on ApplicationDeveloperGuide/debuggerProxy.rst
> +Refresh the state of the memory dump
move just before the `VEE Debugger Proxy Options Summary` section

2024-09-23 10:19 UTC, agazardMicroeJ commented on ApplicationDeveloperGuide/debuggerProxy.rst
> +While the VEE Debugger Proxy is running, you can continue to run the application and perform a new memory dump at a later time. With this new memory dump there's no need to stop and restart the VEE D
rewording proposal: If you want to debug your application using a new memory dump, you don't need to stop and restart the VEE Debugger Proxy. Simply overwrite the old memory dump files with the new ones, then restart the  :ref:`Remote Java Application Launch <debug_on_device>`.

2024-09-24 11:52 UTC, frivieremicroej requested changes
@agazardMicroeJ before merging this branche, the new proxy must first be published in next SDK 6 release, and download link updated to this new version

2024-11-07 21:19 UTC, rlouedec-microej commented
I've just noticed that the jdwp-server 1.0.3 was published: https://forge.microej.com/ui/repos/tree/General/microej-sdk6-repository-release/com/microej/tool/jdwp-server/1.0.3

_Note that it does not publish any CHANGELOG._

Can we finalize this PR?

2024-11-08 08:28 UTC, Jetbl commented
Download link updated, PR ready to be merged

2024-11-08 08:34 UTC, dalgassimou commented
lgtm

2024-11-08 13:50 UTC, rlouedec-microej approved these changes
LGTM, thank you!

2024-12-19 07:52 UTC, frivieremicroej approved these changes

2024-12-19 07:52 UTC, merged