Move UI tutorials to UI App Dev Guide
MicroEJ/docs pull request #984
Opened 2024-06-26 09:05 UTC by acolleux-microej

## Changes

![image](https://github.com/MicroEJ/docs/assets/75476371/c2fcead6-ec36-429c-a3e8-01d6f62037ab)

![image](https://github.com/MicroEJ/docs/assets/75476371/96b2415f-2bae-4f9b-8955-78d997f3d240)

![image](https://github.com/MicroEJ/docs/assets/75476371/74ded911-5eca-4c2d-9709-e48a36d80bb3)

2024-06-26 15:00 UTC, microej-sh requested changes

2024-06-26 15:00 UTC, microej-sh commented on ApplicationDeveloperGuide/guiSoftwareRobot.rst
> +We will now present the basic architecture and code required to create and to run a robot within a MicroEJ application on the simulator and on device.
```suggestion
We will now present the basic architecture and code required to create and to run a robot within a MicroEJ application on the simulator and on the device.
```

2024-06-26 15:06 UTC, microej-sh approved these changes

2024-06-27 08:21 UTC, seonmej approved these changes

2024-06-27 16:34 UTC, merged