Add Training section
MicroEJ/docs pull request #988
Opened 2024-06-26 10:17 UTC by acolleux-microej

2024-07-11 08:13 UTC, jerome-leroux commented on Tutorials/trainingVEEPortAppDev.rst
> +Training for MICROEJ SDK 6 coming soon!
```suggestion
Training for MICROEJ SDK 6 is coming soon!
In the mean time, you can follow the :ref:`SDK 6 Getting Started <sdk_6_getting_started>`.
```

2024-08-19 10:30 UTC, jerome-leroux requested changes

2024-08-19 10:30 UTC, jerome-leroux commented on Tutorials/trainingDebugTools.rst
> +- :ref:`tutorial_discover_embedded_debugging_techniques.use_case_1`
There is no link to the first section of "Discover Embedded Debugging Techniques". Why?

2024-08-19 10:30 UTC, jerome-leroux commented on Tutorials/trainingVEEPortDevFromScratch.rst
> +- Validate the resulting VEE Port with the Port Qualification Tools (PQT).
This is not part of this training

2024-08-21 12:01 UTC, acolleux-microej commented on Tutorials/trainingDebugTools.rst
> +- :ref:`tutorial_discover_embedded_debugging_techniques.use_case_1`
the first section of "Discover Embedded Debugging Techniques" addresses topics that are already addressed in other trainings or in [Debug Tools slides](https://repository.microej.com/packages/training/debugging_with_microej_sdk/DEV-M0127-PRE-MicroEJ-Debug-Tools-SDK5-STM32F7508-2.2-RC20240820.pdf):

- Events Tracing and Logging: addressed in Unit 1: Master logging within your Application of Debug Training + Slide 36-37 of debug tools slides
- Runtime State Dump: from slide 10 in debug tools slides
- Memory Inspection: from slide 20 in debug tools slides
- Platform Qualification: Dedicated PQT training on the training page
- Simulator Debugger: slide 16 in debug tools slides
- Static Analysis Tools: new training item to be added in the training page
- GUI Debugging Tools: covered from slide 30 in debug tools slides

2024-08-21 12:47 UTC, acolleux-microej commented on Tutorials/trainingVEEPortDevFromScratch.rst
> +- Validate the resulting VEE Port with the Port Qualification Tools (PQT).
Removed

2024-08-21 15:34 UTC, microej-sh requested changes

2024-08-21 15:34 UTC, microej-sh commented on Tutorials/trainingGuiRaster.rst
> +This training is raster oriented.
```suggestion
This training is raster-oriented.
```

2024-08-21 15:34 UTC, microej-sh commented on Tutorials/trainingGuiRaster.rst
> +- GUI Qualification:
```suggestion
- Qualify a GUI:
```

2024-08-21 15:34 UTC, microej-sh commented on Tutorials/trainingGuiRaster.rst
> +Evaluation kit is optional to complete this training, it can be fully done on MICROEJ SDK Simulator.
```suggestion
Using an evaluation kit is optional to complete this training, as it can be fully done on the MICROEJ SDK Simulator.
```

2024-08-21 15:34 UTC, microej-sh commented on Tutorials/trainingGuiRaster.rst
> +- Knowledge of Java programming language.
```suggestion
- Knowledge of the Java programming language.
```

2024-08-26 07:33 UTC, microej-sh approved these changes

2024-08-29 10:02 UTC, jerome-leroux commented on Tutorials/trainingDebugTools.rst
> +- :ref:`tutorial_discover_embedded_debugging_techniques.use_case_1`
OK, but the page https://microej-docs--988.com.readthedocs.build/en/988/Tutorials/tutorialDiscoverEmbeddedDebuggingTechniques.html is not accessible from the ToC. The only links to this page are in https://microej-docs--988.com.readthedocs.build/en/988/Tutorials/trainingDebugTools.html and they link only sub-sections of this page.

If it is redundant with what is explained in the slides or other trainings, should we remove the 1st section or move it somewhere else?
Furthermore, it would probably be beneficial to move the 2 use cases in their own pages?

2024-08-29 10:07 UTC, jerome-leroux commented
I think the "MICROEJ SDK Basics" training covers to much (advanced) topics.
- "Manage Multithreading with SNI": should be in the SNI training
- "Build your own Foundation Library": should be a specific training
- "Edit a Front Panel File": should be in a specific training under the UI section

2024-08-29 16:17 UTC, jerome-leroux requested changes

2024-08-30 07:32 UTC, jerome-leroux commented on Tutorials/trainingPQT.rst
> +- :download:`Slides: PQT Overview <https://repository.microej.com/packages/training/DEV-M0018PQT_0002-PRE-Platform_Qualification_Tools_Overview-1.0.pdf>`
Slides need to be reviewed. They are talking about "Platform Qualification Tools" instead of "Port Qualification Tools"

2024-08-30 07:39 UTC, jerome-leroux commented on Tutorials/trainingGuiRaster.rst
> +Unit 2: Coding Challenges
I feel that Unit 1 and 2 overlap. One is in SDK 5, the other one in SDK 6.
The flow needs to be discussed.

2024-08-30 07:40 UTC, jerome-leroux commented on Tutorials/trainingSdkBasics.rst
> +- :download:`Slides: MICROEJ SDK Basics for NXP i.MX RT1170 Evaluation Kit <https://repository.microej.com/packages/training/microej_sdk_basics/DEV-M0127-PRE-VEE_Port_and_Application_development-SDK6
Can we configure the links so that they trigger a download of the PDF file instead of displaying it in the same tab?

2024-08-30 08:18 UTC, jerome-leroux commented on Tutorials/tutorialSetupBuildUsingJenkinsAndArtifactory.rst
>      :align: center
Modify the diagram to add a reference to Gitea

2024-08-30 13:55 UTC, acolleux-microej commented on Tutorials/trainingDebugTools.rst
> +- :ref:`tutorial_discover_embedded_debugging_techniques.use_case_1`
Yes, you are right, let's remove the redundant sections and split the use cases in 2 different pages

2024-08-30 14:11 UTC, acolleux-microej commented on Tutorials/trainingSdkBasics.rst
Here is my proposal for those 2 topics:

- "Manage Multithreading with SNI": should be in the SNI training
  > OK, in that case let's refactor the project sources to remove the foundation library.
  > Provide only an application / mock project defining the LLGPIO native functions
- "Build your own Foundation Library": should be a specific training
  > In that case, I would rather create a new step by step training for creating & building your own foundation library under SDK6.
  > + Move it to the For Beginners / VEE Port section
  > Should we keep the same use case or a new one? (LLGPIO)
- "Edit a Front Panel File": should be in a specific training under the UI section => OK

2024-08-30 14:33 UTC, acolleux-microej commented on Tutorials/trainingPQT.rst
> +- :download:`Slides: PQT Overview <https://repository.microej.com/packages/training/DEV-M0018PQT_0002-PRE-Platform_Qualification_Tools_Overview-1.0.pdf>`
Yes, I've put those slides as an example, we need to rework them fully according to new SDK6 VEE Port template.

Maybe we can remove the link for now?

2024-08-30 14:36 UTC, acolleux-microej commented on Tutorials/trainingSdkBasics.rst
> +- :download:`Slides: MICROEJ SDK Basics for NXP i.MX RT1170 Evaluation Kit <https://repository.microej.com/packages/training/microej_sdk_basics/DEV-M0127-PRE-VEE_Port_and_Application_development-SDK6
I don't know, I will have to check this out.

What about opening the training slides in a new tab ?

2024-08-30 14:36 UTC, acolleux-microej commented on Tutorials/tutorialSetupBuildUsingJenkinsAndArtifactory.rst
>      :align: center
Should we maintain this training ? It will probably be deprecated with SDK6.

2024-08-30 14:42 UTC, acolleux-microej commented on Tutorials/trainingGuiRaster.rst
> +Unit 2: Coding Challenges
cc @microej-sh , @seonmej, @gbalan-microej 

Some topics are not presented in the SDK 6 training compared to the SDK5 one:
- Starting MicroUI
- Scroll / Contact list
- Internationalization

2024-09-20 06:59 UTC, acolleux-microej commented on Tutorials/trainingDebugTools.rst
> +- :ref:`tutorial_discover_embedded_debugging_techniques.use_case_1`
1. Move *Use Case 1: Debugging a GUI Application Freeze* in a dedicated training in the GUI section + in a dedicated .rst
2. Move *Use Case 2: Debugging a HardFault* in a dedicated training in the VEE Dev section + in a dedicated .rst
3. Remove Debugging Tools section + make sure that the content is present in the Debug PPT

2024-10-02 15:23 UTC, acolleux-microej commented on Tutorials/tutorialSetupBuildUsingJenkinsAndArtifactory.rst
>      :align: center
Fixed

2024-10-02 15:26 UTC, acolleux-microej commented on Tutorials/trainingPQT.rst
> +- :download:`Slides: PQT Overview <https://repository.microej.com/packages/training/DEV-M0018PQT_0002-PRE-Platform_Qualification_Tools_Overview-1.0.pdf>`
Link removed, redirect to Introduction page of PQT doc instead.

2024-10-02 15:26 UTC, acolleux-microej commented on Tutorials/trainingSdkBasics.rst
Fixed in version 2.1 of the slides.

2024-10-03 09:45 UTC, jerome-leroux commented on Tutorials/trainingSdkBasics.rst
Can you push this new version?

2024-10-03 09:46 UTC, jerome-leroux commented on Tutorials/trainingSdkBasics.rst
> +- :download:`Slides: MICROEJ SDK Basics for NXP i.MX RT1170 Evaluation Kit <https://repository.microej.com/packages/training/microej_sdk_basics/DEV-M0127-PRE-VEE_Port_and_Application_development-SDK6
It is OK too.

2024-10-15 13:05 UTC, acolleux-microej commented on Tutorials/trainingSdkBasics.rst
> +- :download:`Slides: MICROEJ SDK Basics for NXP i.MX RT1170 Evaluation Kit <https://repository.microej.com/packages/training/microej_sdk_basics/DEV-M0127-PRE-VEE_Port_and_Application_development-SDK6
PDFs are now opened in a new tab

2024-10-16 07:15 UTC, frivieremicroej approved these changes

2024-10-17 08:22 UTC, jerome-leroux approved these changes

2024-10-17 08:23 UTC, merged